#include "./common.hlsl"

Texture2D<uint2> SceneTexturesStruct_CustomStencilTexture : register(t0);

Texture2D<float4> Material_Texture2D_0 : register(t1);

Texture2D<float4> PostProcessInput_0_Texture : register(t2);

cbuffer $Globals : register(b0) {
  float2 PostProcessInput_0_UVViewportMin : packoffset(c000.x);
  float2 PostProcessInput_0_UVViewportSize : packoffset(c000.z);
  float2 PostProcessInput_0_UVViewportBilinearMin : packoffset(c001.x);
  float2 PostProcessInput_0_UVViewportBilinearMax : packoffset(c001.z);
  float2 PostProcessInput_1_UVViewportMin : packoffset(c002.x);
  float2 PostProcessInput_1_UVViewportSize : packoffset(c002.z);
  float2 PostProcessInput_1_UVViewportBilinearMin : packoffset(c003.x);
  float2 PostProcessInput_1_UVViewportBilinearMax : packoffset(c003.z);
  float2 PostProcessInput_2_UVViewportMin : packoffset(c004.x);
  float2 PostProcessInput_2_UVViewportSize : packoffset(c004.z);
  float2 PostProcessInput_2_UVViewportBilinearMin : packoffset(c005.x);
  float2 PostProcessInput_2_UVViewportBilinearMax : packoffset(c005.z);
  float2 PostProcessInput_3_UVViewportMin : packoffset(c006.x);
  float2 PostProcessInput_3_UVViewportSize : packoffset(c006.z);
  float2 PostProcessInput_3_UVViewportBilinearMin : packoffset(c007.x);
  float2 PostProcessInput_3_UVViewportBilinearMax : packoffset(c007.z);
  float2 PostProcessInput_4_UVViewportMin : packoffset(c008.x);
  float2 PostProcessInput_4_UVViewportSize : packoffset(c008.z);
  float2 PostProcessInput_4_UVViewportBilinearMin : packoffset(c009.x);
  float2 PostProcessInput_4_UVViewportBilinearMax : packoffset(c009.z);
  uint2 PostProcessOutput_ViewportMin : packoffset(c010.x);
  float2 PostProcessOutput_ViewportSizeInverse : packoffset(c010.z);
};

cbuffer UniformBufferConstants_View : register(b1) {
  float4 View_TranslatedWorldToClip[4] : packoffset(c000.x);
  float4 View_RelativeWorldToClip[4] : packoffset(c004.x);
  float4 View_ClipToRelativeWorld[4] : packoffset(c008.x);
  float4 View_TranslatedWorldToView[4] : packoffset(c012.x);
  float4 View_ViewToTranslatedWorld[4] : packoffset(c016.x);
  float4 View_TranslatedWorldToCameraView[4] : packoffset(c020.x);
  float4 View_CameraViewToTranslatedWorld[4] : packoffset(c024.x);
  float4 View_ViewToClip[4] : packoffset(c028.x);
  float4 View_ViewToClipNoAA[4] : packoffset(c032.x);
  float4 View_ClipToView[4] : packoffset(c036.x);
  float4 View_ClipToTranslatedWorld[4] : packoffset(c040.x);
  float4 View_SVPositionToTranslatedWorld[4] : packoffset(c044.x);
  float4 View_ScreenToRelativeWorld[4] : packoffset(c048.x);
  float4 View_ScreenToTranslatedWorld[4] : packoffset(c052.x);
  float4 View_MobileMultiviewShadowTransform[4] : packoffset(c056.x);
  float3 View_ViewTilePosition : packoffset(c060.x);
  float PrePadding_View_972 : packoffset(c060.w);
  float3 View_MatrixTilePosition : packoffset(c061.x);
  float PrePadding_View_988 : packoffset(c061.w);
  float3 View_ViewForward : packoffset(c062.x);
  float PrePadding_View_1004 : packoffset(c062.w);
  float3 View_ViewUp : packoffset(c063.x);
  float PrePadding_View_1020 : packoffset(c063.w);
  float3 View_ViewRight : packoffset(c064.x);
  float PrePadding_View_1036 : packoffset(c064.w);
  float3 View_HMDViewNoRollUp : packoffset(c065.x);
  float PrePadding_View_1052 : packoffset(c065.w);
  float3 View_HMDViewNoRollRight : packoffset(c066.x);
  float PrePadding_View_1068 : packoffset(c066.w);
  float4 View_InvDeviceZToWorldZTransform : packoffset(c067.x);
  float4 View_ScreenPositionScaleBias : packoffset(c068.x);
  float3 View_RelativeWorldCameraOrigin : packoffset(c069.x);
  float PrePadding_View_1116 : packoffset(c069.w);
  float3 View_TranslatedWorldCameraOrigin : packoffset(c070.x);
  float PrePadding_View_1132 : packoffset(c070.w);
  float3 View_RelativeWorldViewOrigin : packoffset(c071.x);
  float PrePadding_View_1148 : packoffset(c071.w);
  float3 View_RelativePreViewTranslation : packoffset(c072.x);
  float PrePadding_View_1164 : packoffset(c072.w);
  float4 View_PrevViewToClip[4] : packoffset(c073.x);
  float4 View_PrevClipToView[4] : packoffset(c077.x);
  float4 View_PrevTranslatedWorldToClip[4] : packoffset(c081.x);
  float4 View_PrevTranslatedWorldToView[4] : packoffset(c085.x);
  float4 View_PrevViewToTranslatedWorld[4] : packoffset(c089.x);
  float4 View_PrevTranslatedWorldToCameraView[4] : packoffset(c093.x);
  float4 View_PrevCameraViewToTranslatedWorld[4] : packoffset(c097.x);
  float3 View_PrevTranslatedWorldCameraOrigin : packoffset(c101.x);
  float PrePadding_View_1628 : packoffset(c101.w);
  float3 View_PrevRelativeWorldCameraOrigin : packoffset(c102.x);
  float PrePadding_View_1644 : packoffset(c102.w);
  float3 View_PrevRelativeWorldViewOrigin : packoffset(c103.x);
  float PrePadding_View_1660 : packoffset(c103.w);
  float3 View_RelativePrevPreViewTranslation : packoffset(c104.x);
  float PrePadding_View_1676 : packoffset(c104.w);
  float4 View_PrevClipToRelativeWorld[4] : packoffset(c105.x);
  float4 View_PrevScreenToTranslatedWorld[4] : packoffset(c109.x);
  float4 View_ClipToPrevClip[4] : packoffset(c113.x);
  float4 View_ClipToPrevClipWithAA[4] : packoffset(c117.x);
  float4 View_TemporalAAJitter : packoffset(c121.x);
  float4 View_GlobalClippingPlane : packoffset(c122.x);
  float2 View_FieldOfViewWideAngles : packoffset(c123.x);
  float2 View_PrevFieldOfViewWideAngles : packoffset(c123.z);
  float4 View_ViewRectMin : packoffset(c124.x);
  float4 View_ViewSizeAndInvSize : packoffset(c125.x);
  uint4 View_ViewRectMinAndSize : packoffset(c126.x);
  float4 View_LightProbeSizeRatioAndInvSizeRatio : packoffset(c127.x);
  float4 View_BufferSizeAndInvSize : packoffset(c128.x);
  float4 View_BufferBilinearUVMinMax : packoffset(c129.x);
  float4 View_ScreenToViewSpace : packoffset(c130.x);
  float2 View_BufferToSceneTextureScale : packoffset(c131.x);
  float2 View_ResolutionFractionAndInv : packoffset(c131.z);
  int View_NumSceneColorMSAASamples : packoffset(c132.x);
  float View_ProjectionDepthThicknessScale : packoffset(c132.y);
  float View_PreExposure : packoffset(c132.z);
  float View_OneOverPreExposure : packoffset(c132.w);
  float4 View_DiffuseOverrideParameter : packoffset(c133.x);
  float4 View_SpecularOverrideParameter : packoffset(c134.x);
  float4 View_NormalOverrideParameter : packoffset(c135.x);
  float2 View_RoughnessOverrideParameter : packoffset(c136.x);
  float View_PrevFrameGameTime : packoffset(c136.z);
  float View_PrevFrameRealTime : packoffset(c136.w);
  float View_OutOfBoundsMask : packoffset(c137.x);
  float PrePadding_View_2196 : packoffset(c137.y);
  float PrePadding_View_2200 : packoffset(c137.z);
  float PrePadding_View_2204 : packoffset(c137.w);
  float3 View_WorldCameraMovementSinceLastFrame : packoffset(c138.x);
  float View_CullingSign : packoffset(c138.w);
  float View_NearPlane : packoffset(c139.x);
  float View_GameTime : packoffset(c139.y);
  float View_RealTime : packoffset(c139.z);
  float View_DeltaTime : packoffset(c139.w);
  float View_MaterialTextureMipBias : packoffset(c140.x);
  float View_MaterialTextureDerivativeMultiply : packoffset(c140.y);
  uint View_Random : packoffset(c140.z);
  uint View_FrameNumber : packoffset(c140.w);
  uint View_FrameCounter : packoffset(c141.x);
  uint View_StateFrameIndexMod8 : packoffset(c141.y);
  uint View_StateFrameIndex : packoffset(c141.z);
  uint View_DebugViewModeMask : packoffset(c141.w);
  uint View_WorldIsPaused : packoffset(c142.x);
  float View_CameraCut : packoffset(c142.y);
  float View_UnlitViewmodeMask : packoffset(c142.z);
  float PrePadding_View_2284 : packoffset(c142.w);
  float4 View_DirectionalLightColor : packoffset(c143.x);
  float3 View_DirectionalLightDirection : packoffset(c144.x);
  float PrePadding_View_2316 : packoffset(c144.w);
  float4 View_TranslucencyLightingVolumeMin[2] : packoffset(c145.x);
  float4 View_TranslucencyLightingVolumeInvSize[2] : packoffset(c147.x);
  float4 View_TemporalAAParams : packoffset(c149.x);
  float4 View_CircleDOFParams : packoffset(c150.x);
  float View_DepthOfFieldSensorWidth : packoffset(c151.x);
  float View_DepthOfFieldFocalDistance : packoffset(c151.y);
  float View_DepthOfFieldScale : packoffset(c151.z);
  float View_DepthOfFieldFocalLength : packoffset(c151.w);
  float View_DepthOfFieldFocalRegion : packoffset(c152.x);
  float View_DepthOfFieldNearTransitionRegion : packoffset(c152.y);
  float View_DepthOfFieldFarTransitionRegion : packoffset(c152.z);
  float View_MotionBlurNormalizedToPixel : packoffset(c152.w);
  float View_GeneralPurposeTweak : packoffset(c153.x);
  float View_GeneralPurposeTweak2 : packoffset(c153.y);
  float View_DemosaicVposOffset : packoffset(c153.z);
  float View_DecalDepthBias : packoffset(c153.w);
  float3 View_IndirectLightingColorScale : packoffset(c154.x);
  float PrePadding_View_2476 : packoffset(c154.w);
  float3 View_PrecomputedIndirectLightingColorScale : packoffset(c155.x);
  float PrePadding_View_2492 : packoffset(c155.w);
  float3 View_PrecomputedIndirectSpecularColorScale : packoffset(c156.x);
  float PrePadding_View_2508 : packoffset(c156.w);
  float4 View_AtmosphereLightDirection[2] : packoffset(c157.x);
  float4 View_AtmosphereLightIlluminanceOnGroundPostTransmittance[2] : packoffset(c159.x);
  float4 View_AtmosphereLightIlluminanceOuterSpace[2] : packoffset(c161.x);
  float4 View_AtmosphereLightDiscLuminance[2] : packoffset(c163.x);
  float4 View_AtmosphereLightDiscCosHalfApexAngle_PPTrans[2] : packoffset(c165.x);
  float4 View_SkyViewLutSizeAndInvSize : packoffset(c167.x);
  float3 View_SkyCameraTranslatedWorldOrigin : packoffset(c168.x);
  float PrePadding_View_2700 : packoffset(c168.w);
  float4 View_SkyPlanetTranslatedWorldCenterAndViewHeight : packoffset(c169.x);
  float4 View_SkyViewLutReferential[4] : packoffset(c170.x);
  float4 View_SkyAtmosphereSkyLuminanceFactor : packoffset(c174.x);
  float View_SkyAtmospherePresentInScene : packoffset(c175.x);
  float View_SkyAtmosphereHeightFogContribution : packoffset(c175.y);
  float View_SkyAtmosphereBottomRadiusKm : packoffset(c175.z);
  float View_SkyAtmosphereTopRadiusKm : packoffset(c175.w);
  float4 View_SkyAtmosphereCameraAerialPerspectiveVolumeSizeAndInvSize : packoffset(c176.x);
  float View_SkyAtmosphereAerialPerspectiveStartDepthKm : packoffset(c177.x);
  float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolution : packoffset(c177.y);
  float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolutionInv : packoffset(c177.z);
  float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKm : packoffset(c177.w);
  float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKmInv : packoffset(c178.x);
  float View_SkyAtmosphereApplyCameraAerialPerspectiveVolume : packoffset(c178.y);
  float PrePadding_View_2856 : packoffset(c178.z);
  float PrePadding_View_2860 : packoffset(c178.w);
  float3 View_NormalCurvatureToRoughnessScaleBias : packoffset(c179.x);
  float View_RenderingReflectionCaptureMask : packoffset(c179.w);
  float View_RealTimeReflectionCapture : packoffset(c180.x);
  float View_RealTimeReflectionCapturePreExposure : packoffset(c180.y);
  float PrePadding_View_2888 : packoffset(c180.z);
  float PrePadding_View_2892 : packoffset(c180.w);
  float4 View_AmbientCubemapTint : packoffset(c181.x);
  float View_AmbientCubemapIntensity : packoffset(c182.x);
  float View_SkyLightApplyPrecomputedBentNormalShadowingFlag : packoffset(c182.y);
  float View_SkyLightAffectReflectionFlag : packoffset(c182.z);
  float View_SkyLightAffectGlobalIlluminationFlag : packoffset(c182.w);
  float4 View_SkyLightColor : packoffset(c183.x);
  float4 View_MobileSkyIrradianceEnvironmentMap[8] : packoffset(c184.x);
  float View_MobilePreviewMode : packoffset(c192.x);
  float View_HMDEyePaddingOffset : packoffset(c192.y);
  float View_ReflectionCubemapMaxMip : packoffset(c192.z);
  float View_ShowDecalsMask : packoffset(c192.w);
  uint View_DistanceFieldAOSpecularOcclusionMode : packoffset(c193.x);
  float View_IndirectCapsuleSelfShadowingIntensity : packoffset(c193.y);
  float PrePadding_View_3096 : packoffset(c193.z);
  float PrePadding_View_3100 : packoffset(c193.w);
  float3 View_ReflectionEnvironmentRoughnessMixingScaleBiasAndLargestWeight : packoffset(c194.x);
  int View_StereoPassIndex : packoffset(c194.w);
  float4 View_GlobalVolumeTranslatedCenterAndExtent[6] : packoffset(c195.x);
  float4 View_GlobalVolumeTranslatedWorldToUVAddAndMul[6] : packoffset(c201.x);
  float4 View_GlobalDistanceFieldMipTranslatedWorldToUVScale[6] : packoffset(c207.x);
  float4 View_GlobalDistanceFieldMipTranslatedWorldToUVBias[6] : packoffset(c213.x);
  float View_GlobalDistanceFieldMipFactor : packoffset(c219.x);
  float View_GlobalDistanceFieldMipTransition : packoffset(c219.y);
  int View_GlobalDistanceFieldClipmapSizeInPages : packoffset(c219.z);
  int PrePadding_View_3516 : packoffset(c219.w);
  float3 View_GlobalDistanceFieldInvPageAtlasSize : packoffset(c220.x);
  float PrePadding_View_3532 : packoffset(c220.w);
  float3 View_GlobalDistanceFieldInvCoverageAtlasSize : packoffset(c221.x);
  float View_GlobalVolumeDimension : packoffset(c221.w);
  float View_GlobalVolumeTexelSize : packoffset(c222.x);
  float View_MaxGlobalDFAOConeDistance : packoffset(c222.y);
  uint View_NumGlobalSDFClipmaps : packoffset(c222.z);
  float View_CoveredExpandSurfaceScale : packoffset(c222.w);
  float View_NotCoveredExpandSurfaceScale : packoffset(c223.x);
  float View_NotCoveredMinStepScale : packoffset(c223.y);
  float View_DitheredTransparencyStepThreshold : packoffset(c223.z);
  float View_DitheredTransparencyTraceThreshold : packoffset(c223.w);
  int2 View_CursorPosition : packoffset(c224.x);
  float View_bCheckerboardSubsurfaceProfileRendering : packoffset(c224.z);
  float PrePadding_View_3596 : packoffset(c224.w);
  float3 View_VolumetricFogInvGridSize : packoffset(c225.x);
  float PrePadding_View_3612 : packoffset(c225.w);
  float3 View_VolumetricFogGridZParams : packoffset(c226.x);
  float PrePadding_View_3628 : packoffset(c226.w);
  float2 View_VolumetricFogSVPosToVolumeUV : packoffset(c227.x);
  float2 View_VolumetricFogViewGridUVToPrevViewRectUV : packoffset(c227.z);
  float2 View_VolumetricFogPrevViewGridRectUVToResourceUV : packoffset(c228.x);
  float2 View_VolumetricFogPrevUVMax : packoffset(c228.z);
  float2 View_VolumetricFogScreenToResourceUV : packoffset(c229.x);
  float2 View_VolumetricFogUVMax : packoffset(c229.z);
  float View_VolumetricFogMaxDistance : packoffset(c230.x);
  float PrePadding_View_3684 : packoffset(c230.y);
  float PrePadding_View_3688 : packoffset(c230.z);
  float PrePadding_View_3692 : packoffset(c230.w);
  float3 View_VolumetricLightmapWorldToUVScale : packoffset(c231.x);
  float PrePadding_View_3708 : packoffset(c231.w);
  float3 View_VolumetricLightmapWorldToUVAdd : packoffset(c232.x);
  float PrePadding_View_3724 : packoffset(c232.w);
  float3 View_VolumetricLightmapIndirectionTextureSize : packoffset(c233.x);
  float View_VolumetricLightmapBrickSize : packoffset(c233.w);
  float3 View_VolumetricLightmapBrickTexelSize : packoffset(c234.x);
  float View_IndirectLightingCacheShowFlag : packoffset(c234.w);
  float View_EyeToPixelSpreadAngle : packoffset(c235.x);
  float PrePadding_View_3764 : packoffset(c235.y);
  float PrePadding_View_3768 : packoffset(c235.z);
  float PrePadding_View_3772 : packoffset(c235.w);
  float4 View_XRPassthroughCameraUVs[2] : packoffset(c236.x);
  float View_GlobalVirtualTextureMipBias : packoffset(c238.x);
  uint View_VirtualTextureFeedbackShift : packoffset(c238.y);
  uint View_VirtualTextureFeedbackMask : packoffset(c238.z);
  uint View_VirtualTextureFeedbackStride : packoffset(c238.w);
  uint View_VirtualTextureFeedbackJitterOffset : packoffset(c239.x);
  uint View_VirtualTextureFeedbackSampleOffset : packoffset(c239.y);
  uint PrePadding_View_3832 : packoffset(c239.z);
  uint PrePadding_View_3836 : packoffset(c239.w);
  float4 View_RuntimeVirtualTextureMipLevel : packoffset(c240.x);
  float2 View_RuntimeVirtualTexturePackHeight : packoffset(c241.x);
  float PrePadding_View_3864 : packoffset(c241.z);
  float PrePadding_View_3868 : packoffset(c241.w);
  float4 View_RuntimeVirtualTextureDebugParams : packoffset(c242.x);
  float View_OverrideLandscapeLOD : packoffset(c243.x);
  int View_FarShadowStaticMeshLODBias : packoffset(c243.y);
  float View_MinRoughness : packoffset(c243.z);
  float PrePadding_View_3900 : packoffset(c243.w);
  float4 View_HairRenderInfo : packoffset(c244.x);
  uint View_EnableSkyLight : packoffset(c245.x);
  uint View_HairRenderInfoBits : packoffset(c245.y);
  uint View_HairComponents : packoffset(c245.z);
  float View_bSubsurfacePostprocessEnabled : packoffset(c245.w);
  float4 View_SSProfilesTextureSizeAndInvSize : packoffset(c246.x);
  float4 View_SSProfilesPreIntegratedTextureSizeAndInvSize : packoffset(c247.x);
  float4 View_SpecularProfileTextureSizeAndInvSize : packoffset(c248.x);
  float3 View_PhysicsFieldClipmapCenter : packoffset(c249.x);
  float View_PhysicsFieldClipmapDistance : packoffset(c249.w);
  int View_PhysicsFieldClipmapResolution : packoffset(c250.x);
  int View_PhysicsFieldClipmapExponent : packoffset(c250.y);
  int View_PhysicsFieldClipmapCount : packoffset(c250.z);
  int View_PhysicsFieldTargetCount : packoffset(c250.w);
  int4 View_PhysicsFieldTargets[32] : packoffset(c251.x);
  uint View_GPUSceneViewId : packoffset(c283.x);
  float View_ViewResolutionFraction : packoffset(c283.y);
  float View_SubSurfaceColorAsTransmittanceAtDistanceInMeters : packoffset(c283.z);
  float PrePadding_View_4540 : packoffset(c283.w);
  float4 View_TanAndInvTanHalfFOV : packoffset(c284.x);
  float4 View_PrevTanAndInvTanHalfFOV : packoffset(c285.x);
  float4 View_GlintLUTParameters0 : packoffset(c286.x);
  float4 View_GlintLUTParameters1 : packoffset(c287.x);
  float4 View_GooNumCellsAndSize_RL : packoffset(c288.x);
  uint BindlessSampler_View_MaterialTextureBilinearWrapedSampler : packoffset(c289.x);
  uint PrePadding_View_4628 : packoffset(c289.y);
  uint BindlessSampler_View_MaterialTextureBilinearClampedSampler : packoffset(c289.z);
  uint PrePadding_View_4636 : packoffset(c289.w);
  uint BindlessResource_View_VolumetricLightmapIndirectionTexture : packoffset(c290.x);
  uint PrePadding_View_4644 : packoffset(c290.y);
  uint BindlessResource_View_VolumetricLightmapBrickAmbientVector : packoffset(c290.z);
  uint PrePadding_View_4652 : packoffset(c290.w);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients0 : packoffset(c291.x);
  uint PrePadding_View_4660 : packoffset(c291.y);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients1 : packoffset(c291.z);
  uint PrePadding_View_4668 : packoffset(c291.w);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients2 : packoffset(c292.x);
  uint PrePadding_View_4676 : packoffset(c292.y);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients3 : packoffset(c292.z);
  uint PrePadding_View_4684 : packoffset(c292.w);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients4 : packoffset(c293.x);
  uint PrePadding_View_4692 : packoffset(c293.y);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients5 : packoffset(c293.z);
  uint PrePadding_View_4700 : packoffset(c293.w);
  uint BindlessResource_View_SkyBentNormalBrickTexture : packoffset(c294.x);
  uint PrePadding_View_4708 : packoffset(c294.y);
  uint BindlessResource_View_DirectionalLightShadowingBrickTexture : packoffset(c294.z);
  uint PrePadding_View_4716 : packoffset(c294.w);
  uint BindlessSampler_View_VolumetricLightmapBrickAmbientVectorSampler : packoffset(c295.x);
  uint PrePadding_View_4724 : packoffset(c295.y);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler0 : packoffset(c295.z);
  uint PrePadding_View_4732 : packoffset(c295.w);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler1 : packoffset(c296.x);
  uint PrePadding_View_4740 : packoffset(c296.y);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler2 : packoffset(c296.z);
  uint PrePadding_View_4748 : packoffset(c296.w);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler3 : packoffset(c297.x);
  uint PrePadding_View_4756 : packoffset(c297.y);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler4 : packoffset(c297.z);
  uint PrePadding_View_4764 : packoffset(c297.w);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler5 : packoffset(c298.x);
  uint PrePadding_View_4772 : packoffset(c298.y);
  uint BindlessSampler_View_SkyBentNormalTextureSampler : packoffset(c298.z);
  uint PrePadding_View_4780 : packoffset(c298.w);
  uint BindlessSampler_View_DirectionalLightShadowingTextureSampler : packoffset(c299.x);
  uint PrePadding_View_4788 : packoffset(c299.y);
  uint BindlessResource_View_GlobalDistanceFieldPageAtlasTexture : packoffset(c299.z);
  uint PrePadding_View_4796 : packoffset(c299.w);
  uint BindlessResource_View_GlobalDistanceFieldCoverageAtlasTexture : packoffset(c300.x);
  uint PrePadding_View_4804 : packoffset(c300.y);
  uint BindlessResource_View_GlobalDistanceFieldPageTableTexture : packoffset(c300.z);
  uint PrePadding_View_4812 : packoffset(c300.w);
  uint BindlessResource_View_GlobalDistanceFieldMipTexture : packoffset(c301.x);
  uint PrePadding_View_4820 : packoffset(c301.y);
  uint BindlessSampler_View_GlobalDistanceFieldPageAtlasTextureSampler : packoffset(c301.z);
  uint PrePadding_View_4828 : packoffset(c301.w);
  uint BindlessSampler_View_GlobalDistanceFieldCoverageAtlasTextureSampler : packoffset(c302.x);
  uint PrePadding_View_4836 : packoffset(c302.y);
  uint BindlessSampler_View_GlobalDistanceFieldMipTextureSampler : packoffset(c302.z);
  uint PrePadding_View_4844 : packoffset(c302.w);
  uint BindlessResource_View_AtmosphereTransmittanceTexture : packoffset(c303.x);
  uint PrePadding_View_4852 : packoffset(c303.y);
  uint BindlessSampler_View_AtmosphereTransmittanceTextureSampler : packoffset(c303.z);
  uint PrePadding_View_4860 : packoffset(c303.w);
  uint BindlessResource_View_AtmosphereIrradianceTexture : packoffset(c304.x);
  uint PrePadding_View_4868 : packoffset(c304.y);
  uint BindlessSampler_View_AtmosphereIrradianceTextureSampler : packoffset(c304.z);
  uint PrePadding_View_4876 : packoffset(c304.w);
  uint BindlessResource_View_AtmosphereInscatterTexture : packoffset(c305.x);
  uint PrePadding_View_4884 : packoffset(c305.y);
  uint BindlessSampler_View_AtmosphereInscatterTextureSampler : packoffset(c305.z);
  uint PrePadding_View_4892 : packoffset(c305.w);
  uint BindlessResource_View_PerlinNoiseGradientTexture : packoffset(c306.x);
  uint PrePadding_View_4900 : packoffset(c306.y);
  uint BindlessSampler_View_PerlinNoiseGradientTextureSampler : packoffset(c306.z);
  uint PrePadding_View_4908 : packoffset(c306.w);
  uint BindlessResource_View_PerlinNoise3DTexture : packoffset(c307.x);
  uint PrePadding_View_4916 : packoffset(c307.y);
  uint BindlessSampler_View_PerlinNoise3DTextureSampler : packoffset(c307.z);
  uint PrePadding_View_4924 : packoffset(c307.w);
  uint BindlessResource_View_SobolSamplingTexture : packoffset(c308.x);
  uint PrePadding_View_4932 : packoffset(c308.y);
  uint BindlessSampler_View_SharedPointWrappedSampler : packoffset(c308.z);
  uint PrePadding_View_4940 : packoffset(c308.w);
  uint BindlessSampler_View_SharedPointClampedSampler : packoffset(c309.x);
  uint PrePadding_View_4948 : packoffset(c309.y);
  uint BindlessSampler_View_SharedBilinearWrappedSampler : packoffset(c309.z);
  uint PrePadding_View_4956 : packoffset(c309.w);
  uint BindlessSampler_View_SharedBilinearClampedSampler : packoffset(c310.x);
  uint PrePadding_View_4964 : packoffset(c310.y);
  uint BindlessSampler_View_SharedBilinearAnisoClampedSampler : packoffset(c310.z);
  uint PrePadding_View_4972 : packoffset(c310.w);
  uint BindlessSampler_View_SharedTrilinearWrappedSampler : packoffset(c311.x);
  uint PrePadding_View_4980 : packoffset(c311.y);
  uint BindlessSampler_View_SharedTrilinearClampedSampler : packoffset(c311.z);
  uint PrePadding_View_4988 : packoffset(c311.w);
  uint BindlessResource_View_PreIntegratedBRDF : packoffset(c312.x);
  uint PrePadding_View_4996 : packoffset(c312.y);
  uint BindlessSampler_View_PreIntegratedBRDFSampler : packoffset(c312.z);
  uint PrePadding_View_5004 : packoffset(c312.w);
  uint BindlessResource_View_SkyIrradianceEnvironmentMap : packoffset(c313.x);
  uint PrePadding_View_5012 : packoffset(c313.y);
  uint BindlessResource_View_TransmittanceLutTexture : packoffset(c313.z);
  uint PrePadding_View_5020 : packoffset(c313.w);
  uint BindlessSampler_View_TransmittanceLutTextureSampler : packoffset(c314.x);
  uint PrePadding_View_5028 : packoffset(c314.y);
  uint BindlessResource_View_SkyViewLutTexture : packoffset(c314.z);
  uint PrePadding_View_5036 : packoffset(c314.w);
  uint BindlessSampler_View_SkyViewLutTextureSampler : packoffset(c315.x);
  uint PrePadding_View_5044 : packoffset(c315.y);
  uint BindlessResource_View_DistantSkyLightLutTexture : packoffset(c315.z);
  uint PrePadding_View_5052 : packoffset(c315.w);
  uint BindlessSampler_View_DistantSkyLightLutTextureSampler : packoffset(c316.x);
  uint PrePadding_View_5060 : packoffset(c316.y);
  uint BindlessResource_View_CameraAerialPerspectiveVolume : packoffset(c316.z);
  uint PrePadding_View_5068 : packoffset(c316.w);
  uint BindlessSampler_View_CameraAerialPerspectiveVolumeSampler : packoffset(c317.x);
  uint PrePadding_View_5076 : packoffset(c317.y);
  uint BindlessResource_View_CameraAerialPerspectiveVolumeMieOnly : packoffset(c317.z);
  uint PrePadding_View_5084 : packoffset(c317.w);
  uint BindlessSampler_View_CameraAerialPerspectiveVolumeMieOnlySampler : packoffset(c318.x);
  uint PrePadding_View_5092 : packoffset(c318.y);
  uint BindlessResource_View_CameraAerialPerspectiveVolumeRayOnly : packoffset(c318.z);
  uint PrePadding_View_5100 : packoffset(c318.w);
  uint BindlessSampler_View_CameraAerialPerspectiveVolumeRayOnlySampler : packoffset(c319.x);
  uint PrePadding_View_5108 : packoffset(c319.y);
  uint BindlessResource_View_HairScatteringLUTTexture : packoffset(c319.z);
  uint PrePadding_View_5116 : packoffset(c319.w);
  uint BindlessSampler_View_HairScatteringLUTSampler : packoffset(c320.x);
  uint PrePadding_View_5124 : packoffset(c320.y);
  uint BindlessResource_View_GGXLTCMatTexture : packoffset(c320.z);
  uint PrePadding_View_5132 : packoffset(c320.w);
  uint BindlessSampler_View_GGXLTCMatSampler : packoffset(c321.x);
  uint PrePadding_View_5140 : packoffset(c321.y);
  uint BindlessResource_View_GGXLTCAmpTexture : packoffset(c321.z);
  uint PrePadding_View_5148 : packoffset(c321.w);
  uint BindlessSampler_View_GGXLTCAmpSampler : packoffset(c322.x);
  uint PrePadding_View_5156 : packoffset(c322.y);
  uint BindlessResource_View_SheenLTCTexture : packoffset(c322.z);
  uint PrePadding_View_5164 : packoffset(c322.w);
  uint BindlessSampler_View_SheenLTCSampler : packoffset(c323.x);
  uint PrePadding_View_5172 : packoffset(c323.y);
  uint View_bShadingEnergyConservation : packoffset(c323.z);
  uint View_bShadingEnergyPreservation : packoffset(c323.w);
  uint BindlessResource_View_ShadingEnergyGGXSpecTexture : packoffset(c324.x);
  uint PrePadding_View_5188 : packoffset(c324.y);
  uint BindlessResource_View_ShadingEnergyGGXGlassTexture : packoffset(c324.z);
  uint PrePadding_View_5196 : packoffset(c324.w);
  uint BindlessResource_View_ShadingEnergyClothSpecTexture : packoffset(c325.x);
  uint PrePadding_View_5204 : packoffset(c325.y);
  uint BindlessResource_View_ShadingEnergyDiffuseTexture : packoffset(c325.z);
  uint PrePadding_View_5212 : packoffset(c325.w);
  uint BindlessSampler_View_ShadingEnergySampler : packoffset(c326.x);
  uint PrePadding_View_5220 : packoffset(c326.y);
  uint BindlessResource_View_GlintTexture : packoffset(c326.z);
  uint PrePadding_View_5228 : packoffset(c326.w);
  uint BindlessSampler_View_GlintSampler : packoffset(c327.x);
  uint PrePadding_View_5236 : packoffset(c327.y);
  uint BindlessResource_View_SimpleVolumeTexture : packoffset(c327.z);
  uint PrePadding_View_5244 : packoffset(c327.w);
  uint BindlessSampler_View_SimpleVolumeTextureSampler : packoffset(c328.x);
  uint PrePadding_View_5252 : packoffset(c328.y);
  uint BindlessResource_View_SimpleVolumeEnvTexture : packoffset(c328.z);
  uint PrePadding_View_5260 : packoffset(c328.w);
  uint BindlessSampler_View_SimpleVolumeEnvTextureSampler : packoffset(c329.x);
  uint PrePadding_View_5268 : packoffset(c329.y);
  uint BindlessResource_View_SSProfilesTexture : packoffset(c329.z);
  uint PrePadding_View_5276 : packoffset(c329.w);
  uint BindlessSampler_View_SSProfilesSampler : packoffset(c330.x);
  uint PrePadding_View_5284 : packoffset(c330.y);
  uint BindlessSampler_View_SSProfilesTransmissionSampler : packoffset(c330.z);
  uint PrePadding_View_5292 : packoffset(c330.w);
  uint BindlessResource_View_SSProfilesPreIntegratedTexture : packoffset(c331.x);
  uint PrePadding_View_5300 : packoffset(c331.y);
  uint BindlessSampler_View_SSProfilesPreIntegratedSampler : packoffset(c331.z);
  uint PrePadding_View_5308 : packoffset(c331.w);
  uint BindlessResource_View_SpecularProfileTexture : packoffset(c332.x);
  uint PrePadding_View_5316 : packoffset(c332.y);
  uint BindlessSampler_View_SpecularProfileSampler : packoffset(c332.z);
  uint PrePadding_View_5324 : packoffset(c332.w);
  uint BindlessResource_View_WaterIndirection : packoffset(c333.x);
  uint PrePadding_View_5332 : packoffset(c333.y);
  uint BindlessResource_View_WaterData : packoffset(c333.z);
  uint PrePadding_View_5340 : packoffset(c333.w);
  float4 View_RectLightAtlasSizeAndInvSize : packoffset(c334.x);
  float View_RectLightAtlasMaxMipLevel : packoffset(c335.x);
  float PrePadding_View_5364 : packoffset(c335.y);
  uint BindlessResource_View_RectLightAtlasTexture : packoffset(c335.z);
  uint PrePadding_View_5372 : packoffset(c335.w);
  uint BindlessSampler_View_RectLightAtlasSampler : packoffset(c336.x);
  uint PrePadding_View_5380 : packoffset(c336.y);
  uint PrePadding_View_5384 : packoffset(c336.z);
  uint PrePadding_View_5388 : packoffset(c336.w);
  float4 View_IESAtlasSizeAndInvSize : packoffset(c337.x);
  uint BindlessResource_View_IESAtlasTexture : packoffset(c338.x);
  uint PrePadding_View_5412 : packoffset(c338.y);
  uint BindlessSampler_View_IESAtlasSampler : packoffset(c338.z);
  uint PrePadding_View_5420 : packoffset(c338.w);
  uint BindlessSampler_View_LandscapeWeightmapSampler : packoffset(c339.x);
  uint PrePadding_View_5428 : packoffset(c339.y);
  uint BindlessResource_View_LandscapeIndirection : packoffset(c339.z);
  uint PrePadding_View_5436 : packoffset(c339.w);
  uint BindlessResource_View_LandscapePerComponentData : packoffset(c340.x);
  uint PrePadding_View_5444 : packoffset(c340.y);
  uint BindlessResource_View_VTFeedbackBuffer : packoffset(c340.z);
  uint PrePadding_View_5452 : packoffset(c340.w);
  uint BindlessResource_View_PhysicsFieldClipmapBuffer : packoffset(c341.x);
  uint PrePadding_View_5460 : packoffset(c341.y);
  uint PrePadding_View_5464 : packoffset(c341.z);
  uint PrePadding_View_5468 : packoffset(c341.w);
  float3 View_TLASRelativePreViewTranslation : packoffset(c342.x);
  float PrePadding_View_5484 : packoffset(c342.w);
  float3 View_TLASViewTilePosition : packoffset(c343.x);
  float PrePadding_View_5500 : packoffset(c343.w);
  uint BindlessResource_View_GooCells_RL : packoffset(c344.x);
  uint PrePadding_View_5508 : packoffset(c344.y);
  uint BindlessResource_View_GooSpheresList_RL : packoffset(c344.z);
  uint PrePadding_View_5516 : packoffset(c344.w);
  uint BindlessResource_View_EchoLocatableList_RL : packoffset(c345.x);
};

cbuffer UniformBufferConstants_MaterialCollection0 : register(b2) {
  float4 MaterialCollection0_Vectors[5] : packoffset(c000.x);
};

cbuffer UniformBufferConstants_Material : register(b3) {
  float4 Material_PreshaderBuffer[3] : packoffset(c000.x);
  uint BindlessResource_Material_Texture2D_0 : packoffset(c003.x);
  uint PrePadding_Material_52 : packoffset(c003.y);
  uint BindlessSampler_Material_Texture2D_0Sampler : packoffset(c003.z);
  uint PrePadding_Material_60 : packoffset(c003.w);
  uint BindlessSampler_Material_Wrap_WorldGroupSettings : packoffset(c004.x);
  uint PrePadding_Material_68 : packoffset(c004.y);
  uint BindlessSampler_Material_Clamp_WorldGroupSettings : packoffset(c004.z);
};

SamplerState Material_Texture2D_0Sampler : register(s0);

SamplerState PostProcessInput_0_Sampler : register(s1);

// DXIL FirstbitHi: returns bit position counting from MSB (leading zeros count)
uint firstbithigh_msb(int value) { return (value == 0) ? 0xFFFFFFFF : (31u - firstbithigh(value)); }
uint firstbithigh_msb(uint value) { return (value == 0) ? 0xFFFFFFFF : (31u - firstbithigh(value)); }

float4 main(
  precise noperspective float4 SV_Position : SV_Position,
  linear float4 TEXCOORD : TEXCOORD
) : SV_Target {
  float4 SV_Target;
  float _43;
  float _44;
  float4 _56;
  float _67;
  bool _71;
  float _72;
  float _73;
  float _74;
  float _75;
  float _77;
  float _78;
  float _79;
  float _80;
  float _91;
  float _92;
  float _93;
  float _117;
  float _127;
  float _128;
  float _129;
  float _131;
  int _132;
  float _178;
  float _133;
  int _179;
  float _185;
  float4 _205;
  float _209;
  float _210;
  float _212;
  float _213;
  float _214;
  float _215;
  float _218;
  float _221;
  float _223;
  float _224;
  float _225;
  float _226;
  float _228;
  float _233;
  float _236;
  float _237;
  float _242;
  float _252;
  float _253;
  float _254;
  float _265;
  float _272;
  float _273;
  float _274;
  _43 = (SV_Position.x - float((uint)(int)(PostProcessOutput_ViewportMin.x))) * PostProcessOutput_ViewportSizeInverse.x;
  _44 = (SV_Position.y - float((uint)(int)(PostProcessOutput_ViewportMin.y))) * PostProcessOutput_ViewportSizeInverse.y;
  _56 = PostProcessInput_0_Texture.Sample(PostProcessInput_0_Sampler, float2(((_43 * PostProcessInput_0_UVViewportSize.x) + PostProcessInput_0_UVViewportMin.x), ((_44 * PostProcessInput_0_UVViewportSize.y) + PostProcessInput_0_UVViewportMin.y)));
  _67 = sqrt((((MaterialCollection0_Vectors[3].x) * (MaterialCollection0_Vectors[3].x)) + ((MaterialCollection0_Vectors[3].y) * (MaterialCollection0_Vectors[3].y))) + ((MaterialCollection0_Vectors[3].z) * (MaterialCollection0_Vectors[3].z)));
  _71 = (bool)(_67 >= 0.0f) && (bool)(abs(_67) > 9.999999747378752e-06f);
  _72 = select(_71, (MaterialCollection0_Vectors[3].x), 0.0010000000474974513f);
  _73 = select(_71, (MaterialCollection0_Vectors[3].y), 0.0010000000474974513f);
  _74 = select(_71, (MaterialCollection0_Vectors[3].z), 0.0010000000474974513f);
  _75 = -0.0f - _74;
  _77 = rsqrt(dot(float3(_72, _73, _75), float3(_72, _73, _75)));
  _78 = _72 * _77;
  _79 = _73 * _77;
  _80 = _77 * _75;
  _91 = (MaterialCollection0_Vectors[2].x) - View_RelativeWorldCameraOrigin.x;
  _92 = (MaterialCollection0_Vectors[2].y) - View_RelativeWorldCameraOrigin.y;
  _93 = (MaterialCollection0_Vectors[2].z) - View_RelativeWorldCameraOrigin.z;
  _117 = (Material_PreshaderBuffer[1].x) * (4.76837158203125e-07f / sqrt((((-0.0f - (((_91 * 9.5367431640625e-07f) - View_ViewTilePosition.x) * View_ViewTilePosition.x)) - (View_ViewTilePosition.y * ((_92 * 9.5367431640625e-07f) - View_ViewTilePosition.y))) - (((_93 * 9.5367431640625e-07f) - View_ViewTilePosition.z) * View_ViewTilePosition.z)) + ((((_91 * _91) + (_92 * _92)) + (_93 * _93)) * 2.2737367544323206e-13f)));
  _127 = saturate(sqrt(((_72 * _72) + (_73 * _73)) + (_74 * _74)) * 0.004000000189989805f);
  _128 = (_117 * mad(_80, (View_TranslatedWorldToCameraView[2].x), mad(_79, (View_TranslatedWorldToCameraView[1].x), (_78 * (View_TranslatedWorldToCameraView[0].x))))) * _127;
  _129 = (_117 * mad(_80, (View_TranslatedWorldToCameraView[2].y), mad(_79, (View_TranslatedWorldToCameraView[1].y), (_78 * (View_TranslatedWorldToCameraView[0].y))))) * _127;
  _131 = 0.0f;
  _132 = 0;
  while(true) {
    _133 = float((uint)_132);
    if (float((uint)((int)(((uint2)(SceneTexturesStruct_CustomStencilTexture.Load(int3((uint)(uint(View_BufferSizeAndInvSize.x * min(max((((((_133 * _128) + _43) * View_ViewSizeAndInvSize.x) + View_ViewRectMin.x) * View_BufferSizeAndInvSize.z), View_BufferBilinearUVMinMax.x), View_BufferBilinearUVMinMax.z))), (uint)(uint(View_BufferSizeAndInvSize.y * min(max((((((_133 * _129) + _44) * View_ViewSizeAndInvSize.y) + View_ViewRectMin.y) * View_BufferSizeAndInvSize.w), View_BufferBilinearUVMinMax.y), View_BufferBilinearUVMinMax.w))), 0)))).y))) == 12.0f) {
      _178 = max(_131, (1.0f - (_133 * 0.015625f)));
    } else {
      _178 = _131;
    }
    _179 = _132 + 1;
    if (!(_179 == 64)) {
      _131 = _178;
      _132 = _179;
      continue;
    }
    _185 = (1.0f - _178) * 64.0f;
    _205 = PostProcessInput_0_Texture.Sample(PostProcessInput_0_Sampler, float2(min(max(((PostProcessInput_0_UVViewportSize.x * ((_185 * _128) + _43)) + PostProcessInput_0_UVViewportMin.x), PostProcessInput_0_UVViewportBilinearMin.x), PostProcessInput_0_UVViewportBilinearMax.x), min(max(((PostProcessInput_0_UVViewportSize.y * ((_185 * _129) + _44)) + PostProcessInput_0_UVViewportMin.y), PostProcessInput_0_UVViewportBilinearMin.y), PostProcessInput_0_UVViewportBilinearMax.y)));
    _209 = _43 + -0.5f;
    _210 = _44 + -0.5f;
    _212 = rsqrt(dot(float3(_72, _73, _74), float3(_72, _73, _74)));
    _213 = _212 * _72;
    _214 = _212 * _73;
    _215 = _212 * _74;
    _218 = mad(_215, (View_TranslatedWorldToCameraView[2].x), mad(_214, (View_TranslatedWorldToCameraView[1].x), (_213 * (View_TranslatedWorldToCameraView[0].x))));
    _221 = mad(_215, (View_TranslatedWorldToCameraView[2].y), mad(_214, (View_TranslatedWorldToCameraView[1].y), (_213 * (View_TranslatedWorldToCameraView[0].y))));
    _223 = rsqrt(dot(float3(_218, _221, 0.0f), float3(_218, _221, 0.0f)));
    _224 = _223 * _218;
    _225 = _223 * _221;
    _226 = dot(float3(0.0f, 1.0f, 0.0f), float3(_224, _225, 0.0f));
    _228 = abs(-0.0f - _226);
    _233 = (1.5707963705062866f - (_228 * 0.1565829962491989f)) * sqrt(1.0f - _228);
    _236 = select((_226 <= -0.0f), _233, (3.1415927410125732f - _233));
    _237 = abs(_226);
    _242 = (1.5707963705062866f - (_237 * 0.1565829962491989f)) * sqrt(1.0f - _237);
    _252 = (((select((_226 >= 0.0f), _242, (3.1415927410125732f - _242)) - _236) * (floor(dot(float3(_224, _225, 0.0f), float3(-1.0f, 0.0f, 0.0f))) + 1.0f)) + _236) * 1.0000003576278687f;
    _253 = cos(_252);
    _254 = sin(_252);
    _265 = (((float4)(Material_Texture2D_0.Sample(Material_Texture2D_0Sampler, float2(((dot(float2(_209, _210), float2(_253, (-0.0f - _254))) + 0.5f) * 8.0f), (dot(float2(_209, _210), float2(_254, _253)) + 0.5f))))).x) * _178;
    _272 = (_265 * (_205.x - _56.x)) + _56.x;
    _273 = (_265 * (_205.y - _56.y)) + _56.y;
    _274 = (_265 * (_205.z - _56.z)) + _56.z;
    //SV_Target.x = max(((((Material_PreshaderBuffer[2].x) - _272) * (Material_PreshaderBuffer[1].y)) + _272), 0.0f);
    //SV_Target.y = max(((((Material_PreshaderBuffer[2].y) - _273) * (Material_PreshaderBuffer[1].y)) + _273), 0.0f);
    //SV_Target.z = max(((((Material_PreshaderBuffer[2].z) - _274) * (Material_PreshaderBuffer[1].y)) + _274), 0.0f);
    SV_Target.x = ((((Material_PreshaderBuffer[2].x) - _272) * (Material_PreshaderBuffer[1].y)) + _272);
    SV_Target.y = ((((Material_PreshaderBuffer[2].y) - _273) * (Material_PreshaderBuffer[1].y)) + _273);
    SV_Target.z = ((((Material_PreshaderBuffer[2].z) - _274) * (Material_PreshaderBuffer[1].y)) + _274);
    SV_Target.w = 0.0f;
    break;
  }
  return SV_Target;
}