#include "./postfx.hlsli"
Texture2D<float4> SceneTexturesStruct_SceneDepthTexture : register(t0);

Texture2D<float4> SceneTexturesStruct_CustomDepthTexture : register(t1);

Texture2D<uint2> SceneTexturesStruct_CustomStencilTexture : register(t2);

Texture2D<float4> Material_Texture2D_0 : register(t3);

Texture2D<float4> PostProcessInput_0_Texture : register(t4);  // Scene Texture

cbuffer $Globals : register(b0) {
  float2 PostProcessInput_0_Extent : packoffset(c000.x);
  float2 PostProcessInput_0_ExtentInverse : packoffset(c000.z);
  float2 PostProcessInput_0_ScreenPosToViewportScale : packoffset(c001.x);
  float2 PostProcessInput_0_ScreenPosToViewportBias : packoffset(c001.z);
  uint2 PostProcessInput_0_ViewportMin : packoffset(c002.x);
  uint2 PostProcessInput_0_ViewportMax : packoffset(c002.z);
  float2 PostProcessInput_0_ViewportSize : packoffset(c003.x);
  float2 PostProcessInput_0_ViewportSizeInverse : packoffset(c003.z);
  float2 PostProcessInput_0_UVViewportMin : packoffset(c004.x);
  float2 PostProcessInput_0_UVViewportMax : packoffset(c004.z);
  float2 PostProcessInput_0_UVViewportSize : packoffset(c005.x);
  float2 PostProcessInput_0_UVViewportSizeInverse : packoffset(c005.z);
  float2 PostProcessInput_0_UVViewportBilinearMin : packoffset(c006.x);
  float2 PostProcessInput_0_UVViewportBilinearMax : packoffset(c006.z);
  float2 PostProcessInput_1_Extent : packoffset(c007.x);
  float2 PostProcessInput_1_ExtentInverse : packoffset(c007.z);
  float2 PostProcessInput_1_ScreenPosToViewportScale : packoffset(c008.x);
  float2 PostProcessInput_1_ScreenPosToViewportBias : packoffset(c008.z);
  uint2 PostProcessInput_1_ViewportMin : packoffset(c009.x);
  uint2 PostProcessInput_1_ViewportMax : packoffset(c009.z);
  float2 PostProcessInput_1_ViewportSize : packoffset(c010.x);
  float2 PostProcessInput_1_ViewportSizeInverse : packoffset(c010.z);
  float2 PostProcessInput_1_UVViewportMin : packoffset(c011.x);
  float2 PostProcessInput_1_UVViewportMax : packoffset(c011.z);
  float2 PostProcessInput_1_UVViewportSize : packoffset(c012.x);
  float2 PostProcessInput_1_UVViewportSizeInverse : packoffset(c012.z);
  float2 PostProcessInput_1_UVViewportBilinearMin : packoffset(c013.x);
  float2 PostProcessInput_1_UVViewportBilinearMax : packoffset(c013.z);
  float2 PostProcessInput_2_Extent : packoffset(c014.x);
  float2 PostProcessInput_2_ExtentInverse : packoffset(c014.z);
  float2 PostProcessInput_2_ScreenPosToViewportScale : packoffset(c015.x);
  float2 PostProcessInput_2_ScreenPosToViewportBias : packoffset(c015.z);
  uint2 PostProcessInput_2_ViewportMin : packoffset(c016.x);
  uint2 PostProcessInput_2_ViewportMax : packoffset(c016.z);
  float2 PostProcessInput_2_ViewportSize : packoffset(c017.x);
  float2 PostProcessInput_2_ViewportSizeInverse : packoffset(c017.z);
  float2 PostProcessInput_2_UVViewportMin : packoffset(c018.x);
  float2 PostProcessInput_2_UVViewportMax : packoffset(c018.z);
  float2 PostProcessInput_2_UVViewportSize : packoffset(c019.x);
  float2 PostProcessInput_2_UVViewportSizeInverse : packoffset(c019.z);
  float2 PostProcessInput_2_UVViewportBilinearMin : packoffset(c020.x);
  float2 PostProcessInput_2_UVViewportBilinearMax : packoffset(c020.z);
  float2 PostProcessInput_3_Extent : packoffset(c021.x);
  float2 PostProcessInput_3_ExtentInverse : packoffset(c021.z);
  float2 PostProcessInput_3_ScreenPosToViewportScale : packoffset(c022.x);
  float2 PostProcessInput_3_ScreenPosToViewportBias : packoffset(c022.z);
  uint2 PostProcessInput_3_ViewportMin : packoffset(c023.x);
  uint2 PostProcessInput_3_ViewportMax : packoffset(c023.z);
  float2 PostProcessInput_3_ViewportSize : packoffset(c024.x);
  float2 PostProcessInput_3_ViewportSizeInverse : packoffset(c024.z);
  float2 PostProcessInput_3_UVViewportMin : packoffset(c025.x);
  float2 PostProcessInput_3_UVViewportMax : packoffset(c025.z);
  float2 PostProcessInput_3_UVViewportSize : packoffset(c026.x);
  float2 PostProcessInput_3_UVViewportSizeInverse : packoffset(c026.z);
  float2 PostProcessInput_3_UVViewportBilinearMin : packoffset(c027.x);
  float2 PostProcessInput_3_UVViewportBilinearMax : packoffset(c027.z);
  float2 PostProcessInput_4_Extent : packoffset(c028.x);
  float2 PostProcessInput_4_ExtentInverse : packoffset(c028.z);
  float2 PostProcessInput_4_ScreenPosToViewportScale : packoffset(c029.x);
  float2 PostProcessInput_4_ScreenPosToViewportBias : packoffset(c029.z);
  uint2 PostProcessInput_4_ViewportMin : packoffset(c030.x);
  uint2 PostProcessInput_4_ViewportMax : packoffset(c030.z);
  float2 PostProcessInput_4_ViewportSize : packoffset(c031.x);
  float2 PostProcessInput_4_ViewportSizeInverse : packoffset(c031.z);
  float2 PostProcessInput_4_UVViewportMin : packoffset(c032.x);
  float2 PostProcessInput_4_UVViewportMax : packoffset(c032.z);
  float2 PostProcessInput_4_UVViewportSize : packoffset(c033.x);
  float2 PostProcessInput_4_UVViewportSizeInverse : packoffset(c033.z);
  float2 PostProcessInput_4_UVViewportBilinearMin : packoffset(c034.x);
  float2 PostProcessInput_4_UVViewportBilinearMax : packoffset(c034.z);
  float2 PostProcessOutput_Extent : packoffset(c035.x);
  float2 PostProcessOutput_ExtentInverse : packoffset(c035.z);
  float2 PostProcessOutput_ScreenPosToViewportScale : packoffset(c036.x);
  float2 PostProcessOutput_ScreenPosToViewportBias : packoffset(c036.z);
  uint2 PostProcessOutput_ViewportMin : packoffset(c037.x);
  uint2 PostProcessOutput_ViewportMax : packoffset(c037.z);
  float2 PostProcessOutput_ViewportSize : packoffset(c038.x);
  float2 PostProcessOutput_ViewportSizeInverse : packoffset(c038.z);
  float2 PostProcessOutput_UVViewportMin : packoffset(c039.x);
  float2 PostProcessOutput_UVViewportMax : packoffset(c039.z);
  float2 PostProcessOutput_UVViewportSize : packoffset(c040.x);
  float2 PostProcessOutput_UVViewportSizeInverse : packoffset(c040.z);
  float2 PostProcessOutput_UVViewportBilinearMin : packoffset(c041.x);
  float2 PostProcessOutput_UVViewportBilinearMax : packoffset(c041.z);
  float4 DepthOfFieldParams : packoffset(c042.x);
  uint bSceneLightingChannelsValid : packoffset(c043.x);
  uint bSceneDepthWithoutWaterTextureAvailable : packoffset(c043.y);
  float4 SceneWithoutSingleLayerWaterMinMaxUV : packoffset(c044.x);
  float2 SceneWithoutSingleLayerWaterTextureSize : packoffset(c045.x);
  float2 SceneWithoutSingleLayerWaterInvTextureSize : packoffset(c045.z);
  uint ManualStencilReferenceValue : packoffset(c046.x);
  uint ManualStencilTestMask : packoffset(c046.y);
};

cbuffer UniformBufferConstants_View : register(b1) {
  float4 View_TranslatedWorldToClip[4] : packoffset(c000.x);
  float4 View_TranslatedWorldToSubpixelClip[4] : packoffset(c004.x);
  float4 View_RelativeWorldToClip[4] : packoffset(c008.x);
  float4 View_ClipToRelativeWorld[4] : packoffset(c012.x);
  float4 View_TranslatedWorldToView[4] : packoffset(c016.x);
  float4 View_ViewToTranslatedWorld[4] : packoffset(c020.x);
  float4 View_TranslatedWorldToCameraView[4] : packoffset(c024.x);
  float4 View_CameraViewToTranslatedWorld[4] : packoffset(c028.x);
  float4 View_ViewToClip[4] : packoffset(c032.x);
  float4 View_ViewToClipNoAA[4] : packoffset(c036.x);
  float4 View_ClipToView[4] : packoffset(c040.x);
  float4 View_ClipToTranslatedWorld[4] : packoffset(c044.x);
  float4 View_SVPositionToTranslatedWorld[4] : packoffset(c048.x);
  float4 View_ScreenToRelativeWorld[4] : packoffset(c052.x);
  float4 View_ScreenToTranslatedWorld[4] : packoffset(c056.x);
  float4 View_MobileMultiviewShadowTransform[4] : packoffset(c060.x);
  float3 View_ViewTilePosition : packoffset(c064.x);
  float PrePadding_View_1036 : packoffset(c064.w);
  float3 View_MatrixTilePosition : packoffset(c065.x);
  float PrePadding_View_1052 : packoffset(c065.w);
  float3 View_ViewForward : packoffset(c066.x);
  float PrePadding_View_1068 : packoffset(c066.w);
  float3 View_ViewUp : packoffset(c067.x);
  float PrePadding_View_1084 : packoffset(c067.w);
  float3 View_ViewRight : packoffset(c068.x);
  float PrePadding_View_1100 : packoffset(c068.w);
  float3 View_HMDViewNoRollUp : packoffset(c069.x);
  float PrePadding_View_1116 : packoffset(c069.w);
  float3 View_HMDViewNoRollRight : packoffset(c070.x);
  float PrePadding_View_1132 : packoffset(c070.w);
  float4 View_InvDeviceZToWorldZTransform : packoffset(c071.x);
  float4 View_ScreenPositionScaleBias : packoffset(c072.x);
  float3 View_RelativeWorldCameraOrigin : packoffset(c073.x);
  float PrePadding_View_1180 : packoffset(c073.w);
  float3 View_TranslatedWorldCameraOrigin : packoffset(c074.x);
  float PrePadding_View_1196 : packoffset(c074.w);
  float3 View_RelativeWorldViewOrigin : packoffset(c075.x);
  float PrePadding_View_1212 : packoffset(c075.w);
  float3 View_RelativePreViewTranslation : packoffset(c076.x);
  float PrePadding_View_1228 : packoffset(c076.w);
  float4 View_PrevViewToClip[4] : packoffset(c077.x);
  float4 View_PrevClipToView[4] : packoffset(c081.x);
  float4 View_PrevTranslatedWorldToClip[4] : packoffset(c085.x);
  float4 View_PrevTranslatedWorldToView[4] : packoffset(c089.x);
  float4 View_PrevViewToTranslatedWorld[4] : packoffset(c093.x);
  float4 View_PrevTranslatedWorldToCameraView[4] : packoffset(c097.x);
  float4 View_PrevCameraViewToTranslatedWorld[4] : packoffset(c101.x);
  float3 View_PrevTranslatedWorldCameraOrigin : packoffset(c105.x);
  float PrePadding_View_1692 : packoffset(c105.w);
  float3 View_PrevRelativeWorldCameraOrigin : packoffset(c106.x);
  float PrePadding_View_1708 : packoffset(c106.w);
  float3 View_PrevRelativeWorldViewOrigin : packoffset(c107.x);
  float PrePadding_View_1724 : packoffset(c107.w);
  float3 View_RelativePrevPreViewTranslation : packoffset(c108.x);
  float PrePadding_View_1740 : packoffset(c108.w);
  float4 View_PrevClipToRelativeWorld[4] : packoffset(c109.x);
  float4 View_PrevScreenToTranslatedWorld[4] : packoffset(c113.x);
  float4 View_ClipToPrevClip[4] : packoffset(c117.x);
  float4 View_ClipToPrevClipWithAA[4] : packoffset(c121.x);
  float4 View_TemporalAAJitter : packoffset(c125.x);
  float4 View_GlobalClippingPlane : packoffset(c126.x);
  float2 View_FieldOfViewWideAngles : packoffset(c127.x);
  float2 View_PrevFieldOfViewWideAngles : packoffset(c127.z);
  float4 View_ViewRectMin : packoffset(c128.x);
  float4 View_ViewSizeAndInvSize : packoffset(c129.x);
  uint4 View_ViewRectMinAndSize : packoffset(c130.x);
  float4 View_LightProbeSizeRatioAndInvSizeRatio : packoffset(c131.x);
  float4 View_BufferSizeAndInvSize : packoffset(c132.x);
  float4 View_BufferBilinearUVMinMax : packoffset(c133.x);
  float4 View_ScreenToViewSpace : packoffset(c134.x);
  float2 View_BufferToSceneTextureScale : packoffset(c135.x);
  float2 View_ResolutionFractionAndInv : packoffset(c135.z);
  int View_NumSceneColorMSAASamples : packoffset(c136.x);
  float View_PreExposure : packoffset(c136.y);
  float View_OneOverPreExposure : packoffset(c136.z);
  float PrePadding_View_2188 : packoffset(c136.w);
  float4 View_DiffuseOverrideParameter : packoffset(c137.x);
  float4 View_SpecularOverrideParameter : packoffset(c138.x);
  float4 View_NormalOverrideParameter : packoffset(c139.x);
  float2 View_RoughnessOverrideParameter : packoffset(c140.x);
  float View_PrevFrameGameTime : packoffset(c140.z);
  float View_PrevFrameRealTime : packoffset(c140.w);
  float View_OutOfBoundsMask : packoffset(c141.x);
  float PrePadding_View_2260 : packoffset(c141.y);
  float PrePadding_View_2264 : packoffset(c141.z);
  float PrePadding_View_2268 : packoffset(c141.w);
  float3 View_WorldCameraMovementSinceLastFrame : packoffset(c142.x);
  float View_CullingSign : packoffset(c142.w);
  float View_NearPlane : packoffset(c143.x);
  float View_GameTime : packoffset(c143.y);
  float View_RealTime : packoffset(c143.z);
  float View_DeltaTime : packoffset(c143.w);
  float View_MaterialTextureMipBias : packoffset(c144.x);
  float View_MaterialTextureDerivativeMultiply : packoffset(c144.y);
  uint View_Random : packoffset(c144.z);
  uint View_FrameNumber : packoffset(c144.w);
  uint View_StateFrameIndexMod8 : packoffset(c145.x);
  uint View_StateFrameIndex : packoffset(c145.y);
  uint View_DebugViewModeMask : packoffset(c145.z);
  uint View_WorldIsPaused : packoffset(c145.w);
  float View_CameraCut : packoffset(c146.x);
  float View_UnlitViewmodeMask : packoffset(c146.y);
  float PrePadding_View_2344 : packoffset(c146.z);
  float PrePadding_View_2348 : packoffset(c146.w);
  float4 View_DirectionalLightColor : packoffset(c147.x);
  float3 View_DirectionalLightDirection : packoffset(c148.x);
  float PrePadding_View_2380 : packoffset(c148.w);
  float4 View_TranslucencyLightingVolumeMin[2] : packoffset(c149.x);
  float4 View_TranslucencyLightingVolumeInvSize[2] : packoffset(c151.x);
  float4 View_TemporalAAParams : packoffset(c153.x);
  float4 View_CircleDOFParams : packoffset(c154.x);
  float View_DepthOfFieldSensorWidth : packoffset(c155.x);
  float View_DepthOfFieldFocalDistance : packoffset(c155.y);
  float View_DepthOfFieldScale : packoffset(c155.z);
  float View_DepthOfFieldFocalLength : packoffset(c155.w);
  float View_DepthOfFieldFocalRegion : packoffset(c156.x);
  float View_DepthOfFieldNearTransitionRegion : packoffset(c156.y);
  float View_DepthOfFieldFarTransitionRegion : packoffset(c156.z);
  float View_MotionBlurNormalizedToPixel : packoffset(c156.w);
  float View_GeneralPurposeTweak : packoffset(c157.x);
  float View_GeneralPurposeTweak2 : packoffset(c157.y);
  float View_DemosaicVposOffset : packoffset(c157.z);
  float View_DecalDepthBias : packoffset(c157.w);
  float3 View_IndirectLightingColorScale : packoffset(c158.x);
  float PrePadding_View_2540 : packoffset(c158.w);
  float3 View_PrecomputedIndirectLightingColorScale : packoffset(c159.x);
  float PrePadding_View_2556 : packoffset(c159.w);
  float3 View_PrecomputedIndirectSpecularColorScale : packoffset(c160.x);
  float PrePadding_View_2572 : packoffset(c160.w);
  float4 View_AtmosphereLightDirection[2] : packoffset(c161.x);
  float4 View_AtmosphereLightIlluminanceOnGroundPostTransmittance[2] : packoffset(c163.x);
  float4 View_AtmosphereLightIlluminanceOuterSpace[2] : packoffset(c165.x);
  float4 View_AtmosphereLightDiscLuminance[2] : packoffset(c167.x);
  float4 View_AtmosphereLightDiscCosHalfApexAngle_PPTrans[2] : packoffset(c169.x);
  float4 View_SkyViewLutSizeAndInvSize : packoffset(c171.x);
  float3 View_SkyCameraTranslatedWorldOrigin : packoffset(c172.x);
  float PrePadding_View_2764 : packoffset(c172.w);
  float4 View_SkyPlanetTranslatedWorldCenterAndViewHeight : packoffset(c173.x);
  float4 View_SkyViewLutReferential[4] : packoffset(c174.x);
  float4 View_SkyAtmosphereSkyLuminanceFactor : packoffset(c178.x);
  float View_SkyAtmospherePresentInScene : packoffset(c179.x);
  float View_SkyAtmosphereHeightFogContribution : packoffset(c179.y);
  float View_SkyAtmosphereBottomRadiusKm : packoffset(c179.z);
  float View_SkyAtmosphereTopRadiusKm : packoffset(c179.w);
  float4 View_SkyAtmosphereCameraAerialPerspectiveVolumeSizeAndInvSize : packoffset(c180.x);
  float View_SkyAtmosphereAerialPerspectiveStartDepthKm : packoffset(c181.x);
  float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolution : packoffset(c181.y);
  float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolutionInv : packoffset(c181.z);
  float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKm : packoffset(c181.w);
  float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKmInv : packoffset(c182.x);
  float View_SkyAtmosphereApplyCameraAerialPerspectiveVolume : packoffset(c182.y);
  float PrePadding_View_2920 : packoffset(c182.z);
  float PrePadding_View_2924 : packoffset(c182.w);
  float3 View_NormalCurvatureToRoughnessScaleBias : packoffset(c183.x);
  float View_RenderingReflectionCaptureMask : packoffset(c183.w);
  float View_RealTimeReflectionCapture : packoffset(c184.x);
  float View_RealTimeReflectionCapturePreExposure : packoffset(c184.y);
  float PrePadding_View_2952 : packoffset(c184.z);
  float PrePadding_View_2956 : packoffset(c184.w);
  float4 View_AmbientCubemapTint : packoffset(c185.x);
  float View_AmbientCubemapIntensity : packoffset(c186.x);
  float View_SkyLightApplyPrecomputedBentNormalShadowingFlag : packoffset(c186.y);
  float View_SkyLightAffectReflectionFlag : packoffset(c186.z);
  float View_SkyLightAffectGlobalIlluminationFlag : packoffset(c186.w);
  float4 View_SkyLightColor : packoffset(c187.x);
  float4 View_MobileSkyIrradianceEnvironmentMap[8] : packoffset(c188.x);
  float View_MobilePreviewMode : packoffset(c196.x);
  float View_HMDEyePaddingOffset : packoffset(c196.y);
  float View_ReflectionCubemapMaxMip : packoffset(c196.z);
  float View_ShowDecalsMask : packoffset(c196.w);
  uint View_DistanceFieldAOSpecularOcclusionMode : packoffset(c197.x);
  float View_IndirectCapsuleSelfShadowingIntensity : packoffset(c197.y);
  float PrePadding_View_3160 : packoffset(c197.z);
  float PrePadding_View_3164 : packoffset(c197.w);
  float3 View_ReflectionEnvironmentRoughnessMixingScaleBiasAndLargestWeight : packoffset(c198.x);
  int View_StereoPassIndex : packoffset(c198.w);
  float4 View_GlobalVolumeTranslatedCenterAndExtent[6] : packoffset(c199.x);
  float4 View_GlobalVolumeTranslatedWorldToUVAddAndMul[6] : packoffset(c205.x);
  float4 View_GlobalDistanceFieldMipTranslatedWorldToUVScale[6] : packoffset(c211.x);
  float4 View_GlobalDistanceFieldMipTranslatedWorldToUVBias[6] : packoffset(c217.x);
  float View_GlobalDistanceFieldMipFactor : packoffset(c223.x);
  float View_GlobalDistanceFieldMipTransition : packoffset(c223.y);
  int View_GlobalDistanceFieldClipmapSizeInPages : packoffset(c223.z);
  int PrePadding_View_3580 : packoffset(c223.w);
  float3 View_GlobalDistanceFieldInvPageAtlasSize : packoffset(c224.x);
  float PrePadding_View_3596 : packoffset(c224.w);
  float3 View_GlobalDistanceFieldInvCoverageAtlasSize : packoffset(c225.x);
  float View_GlobalVolumeDimension : packoffset(c225.w);
  float View_GlobalVolumeTexelSize : packoffset(c226.x);
  float View_MaxGlobalDFAOConeDistance : packoffset(c226.y);
  uint View_NumGlobalSDFClipmaps : packoffset(c226.z);
  float View_CoveredExpandSurfaceScale : packoffset(c226.w);
  float View_NotCoveredExpandSurfaceScale : packoffset(c227.x);
  float View_NotCoveredMinStepScale : packoffset(c227.y);
  float View_DitheredTransparencyStepThreshold : packoffset(c227.z);
  float View_DitheredTransparencyTraceThreshold : packoffset(c227.w);
  int2 View_CursorPosition : packoffset(c228.x);
  float View_bCheckerboardSubsurfaceProfileRendering : packoffset(c228.z);
  float PrePadding_View_3660 : packoffset(c228.w);
  float3 View_VolumetricFogInvGridSize : packoffset(c229.x);
  float PrePadding_View_3676 : packoffset(c229.w);
  float3 View_VolumetricFogGridZParams : packoffset(c230.x);
  float PrePadding_View_3692 : packoffset(c230.w);
  float2 View_VolumetricFogSVPosToVolumeUV : packoffset(c231.x);
  float2 View_VolumetricFogScreenUVToHistoryVolumeUV : packoffset(c231.z);
  float View_VolumetricFogMaxDistance : packoffset(c232.x);
  float PrePadding_View_3716 : packoffset(c232.y);
  float PrePadding_View_3720 : packoffset(c232.z);
  float PrePadding_View_3724 : packoffset(c232.w);
  float3 View_VolumetricLightmapWorldToUVScale : packoffset(c233.x);
  float PrePadding_View_3740 : packoffset(c233.w);
  float3 View_VolumetricLightmapWorldToUVAdd : packoffset(c234.x);
  float PrePadding_View_3756 : packoffset(c234.w);
  float3 View_VolumetricLightmapIndirectionTextureSize : packoffset(c235.x);
  float View_VolumetricLightmapBrickSize : packoffset(c235.w);
  float3 View_VolumetricLightmapBrickTexelSize : packoffset(c236.x);
  float View_IndirectLightingCacheShowFlag : packoffset(c236.w);
  float View_EyeToPixelSpreadAngle : packoffset(c237.x);
  float PrePadding_View_3796 : packoffset(c237.y);
  float PrePadding_View_3800 : packoffset(c237.z);
  float PrePadding_View_3804 : packoffset(c237.w);
  float4 View_XRPassthroughCameraUVs[2] : packoffset(c238.x);
  float View_GlobalVirtualTextureMipBias : packoffset(c240.x);
  uint View_VirtualTextureFeedbackShift : packoffset(c240.y);
  uint View_VirtualTextureFeedbackMask : packoffset(c240.z);
  uint View_VirtualTextureFeedbackStride : packoffset(c240.w);
  uint View_VirtualTextureFeedbackJitterOffset : packoffset(c241.x);
  uint View_VirtualTextureFeedbackSampleOffset : packoffset(c241.y);
  uint PrePadding_View_3864 : packoffset(c241.z);
  uint PrePadding_View_3868 : packoffset(c241.w);
  float4 View_RuntimeVirtualTextureMipLevel : packoffset(c242.x);
  float2 View_RuntimeVirtualTexturePackHeight : packoffset(c243.x);
  float PrePadding_View_3896 : packoffset(c243.z);
  float PrePadding_View_3900 : packoffset(c243.w);
  float4 View_RuntimeVirtualTextureDebugParams : packoffset(c244.x);
  float View_OverrideLandscapeLOD : packoffset(c245.x);
  int View_FarShadowStaticMeshLODBias : packoffset(c245.y);
  float View_MinRoughness : packoffset(c245.z);
  float PrePadding_View_3932 : packoffset(c245.w);
  float4 View_HairRenderInfo : packoffset(c246.x);
  uint View_EnableSkyLight : packoffset(c247.x);
  uint View_HairRenderInfoBits : packoffset(c247.y);
  uint View_HairComponents : packoffset(c247.z);
  float View_bSubsurfacePostprocessEnabled : packoffset(c247.w);
  float4 View_SSProfilesTextureSizeAndInvSize : packoffset(c248.x);
  float4 View_SSProfilesPreIntegratedTextureSizeAndInvSize : packoffset(c249.x);
  float3 View_PhysicsFieldClipmapCenter : packoffset(c250.x);
  float View_PhysicsFieldClipmapDistance : packoffset(c250.w);
  int View_PhysicsFieldClipmapResolution : packoffset(c251.x);
  int View_PhysicsFieldClipmapExponent : packoffset(c251.y);
  int View_PhysicsFieldClipmapCount : packoffset(c251.z);
  int View_PhysicsFieldTargetCount : packoffset(c251.w);
  int4 View_PhysicsFieldTargets[32] : packoffset(c252.x);
  uint View_InstanceSceneDataSOAStride : packoffset(c284.x);
  uint View_GPUSceneViewId : packoffset(c284.y);
  float View_ViewResolutionFraction : packoffset(c284.z);
  float View_SubSurfaceColorAsTransmittanceAtDistanceInMeters : packoffset(c284.w);
  uint BindlessSampler_View_MaterialTextureBilinearWrapedSampler : packoffset(c285.x);
  uint PrePadding_View_4564 : packoffset(c285.y);
  uint BindlessSampler_View_MaterialTextureBilinearClampedSampler : packoffset(c285.z);
  uint PrePadding_View_4572 : packoffset(c285.w);
  uint BindlessResource_View_VolumetricLightmapIndirectionTexture : packoffset(c286.x);
  uint PrePadding_View_4580 : packoffset(c286.y);
  uint BindlessResource_View_VolumetricLightmapBrickAmbientVector : packoffset(c286.z);
  uint PrePadding_View_4588 : packoffset(c286.w);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients0 : packoffset(c287.x);
  uint PrePadding_View_4596 : packoffset(c287.y);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients1 : packoffset(c287.z);
  uint PrePadding_View_4604 : packoffset(c287.w);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients2 : packoffset(c288.x);
  uint PrePadding_View_4612 : packoffset(c288.y);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients3 : packoffset(c288.z);
  uint PrePadding_View_4620 : packoffset(c288.w);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients4 : packoffset(c289.x);
  uint PrePadding_View_4628 : packoffset(c289.y);
  uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients5 : packoffset(c289.z);
  uint PrePadding_View_4636 : packoffset(c289.w);
  uint BindlessResource_View_SkyBentNormalBrickTexture : packoffset(c290.x);
  uint PrePadding_View_4644 : packoffset(c290.y);
  uint BindlessResource_View_DirectionalLightShadowingBrickTexture : packoffset(c290.z);
  uint PrePadding_View_4652 : packoffset(c290.w);
  uint BindlessSampler_View_VolumetricLightmapBrickAmbientVectorSampler : packoffset(c291.x);
  uint PrePadding_View_4660 : packoffset(c291.y);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler0 : packoffset(c291.z);
  uint PrePadding_View_4668 : packoffset(c291.w);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler1 : packoffset(c292.x);
  uint PrePadding_View_4676 : packoffset(c292.y);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler2 : packoffset(c292.z);
  uint PrePadding_View_4684 : packoffset(c292.w);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler3 : packoffset(c293.x);
  uint PrePadding_View_4692 : packoffset(c293.y);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler4 : packoffset(c293.z);
  uint PrePadding_View_4700 : packoffset(c293.w);
  uint BindlessSampler_View_VolumetricLightmapTextureSampler5 : packoffset(c294.x);
  uint PrePadding_View_4708 : packoffset(c294.y);
  uint BindlessSampler_View_SkyBentNormalTextureSampler : packoffset(c294.z);
  uint PrePadding_View_4716 : packoffset(c294.w);
  uint BindlessSampler_View_DirectionalLightShadowingTextureSampler : packoffset(c295.x);
  uint PrePadding_View_4724 : packoffset(c295.y);
  uint BindlessResource_View_GlobalDistanceFieldPageAtlasTexture : packoffset(c295.z);
  uint PrePadding_View_4732 : packoffset(c295.w);
  uint BindlessResource_View_GlobalDistanceFieldCoverageAtlasTexture : packoffset(c296.x);
  uint PrePadding_View_4740 : packoffset(c296.y);
  uint BindlessResource_View_GlobalDistanceFieldPageTableTexture : packoffset(c296.z);
  uint PrePadding_View_4748 : packoffset(c296.w);
  uint BindlessResource_View_GlobalDistanceFieldMipTexture : packoffset(c297.x);
  uint PrePadding_View_4756 : packoffset(c297.y);
  uint BindlessResource_View_AtmosphereTransmittanceTexture : packoffset(c297.z);
  uint PrePadding_View_4764 : packoffset(c297.w);
  uint BindlessSampler_View_AtmosphereTransmittanceTextureSampler : packoffset(c298.x);
  uint PrePadding_View_4772 : packoffset(c298.y);
  uint BindlessResource_View_AtmosphereIrradianceTexture : packoffset(c298.z);
  uint PrePadding_View_4780 : packoffset(c298.w);
  uint BindlessSampler_View_AtmosphereIrradianceTextureSampler : packoffset(c299.x);
  uint PrePadding_View_4788 : packoffset(c299.y);
  uint BindlessResource_View_AtmosphereInscatterTexture : packoffset(c299.z);
  uint PrePadding_View_4796 : packoffset(c299.w);
  uint BindlessSampler_View_AtmosphereInscatterTextureSampler : packoffset(c300.x);
  uint PrePadding_View_4804 : packoffset(c300.y);
  uint BindlessResource_View_PerlinNoiseGradientTexture : packoffset(c300.z);
  uint PrePadding_View_4812 : packoffset(c300.w);
  uint BindlessSampler_View_PerlinNoiseGradientTextureSampler : packoffset(c301.x);
  uint PrePadding_View_4820 : packoffset(c301.y);
  uint BindlessResource_View_PerlinNoise3DTexture : packoffset(c301.z);
  uint PrePadding_View_4828 : packoffset(c301.w);
  uint BindlessSampler_View_PerlinNoise3DTextureSampler : packoffset(c302.x);
  uint PrePadding_View_4836 : packoffset(c302.y);
  uint BindlessResource_View_SobolSamplingTexture : packoffset(c302.z);
  uint PrePadding_View_4844 : packoffset(c302.w);
  uint BindlessSampler_View_SharedPointWrappedSampler : packoffset(c303.x);
  uint PrePadding_View_4852 : packoffset(c303.y);
  uint BindlessSampler_View_SharedPointClampedSampler : packoffset(c303.z);
  uint PrePadding_View_4860 : packoffset(c303.w);
  uint BindlessSampler_View_SharedBilinearWrappedSampler : packoffset(c304.x);
  uint PrePadding_View_4868 : packoffset(c304.y);
  uint BindlessSampler_View_SharedBilinearClampedSampler : packoffset(c304.z);
  uint PrePadding_View_4876 : packoffset(c304.w);
  uint BindlessSampler_View_SharedBilinearAnisoClampedSampler : packoffset(c305.x);
  uint PrePadding_View_4884 : packoffset(c305.y);
  uint BindlessSampler_View_SharedTrilinearWrappedSampler : packoffset(c305.z);
  uint PrePadding_View_4892 : packoffset(c305.w);
  uint BindlessSampler_View_SharedTrilinearClampedSampler : packoffset(c306.x);
  uint PrePadding_View_4900 : packoffset(c306.y);
  uint BindlessResource_View_PreIntegratedBRDF : packoffset(c306.z);
  uint PrePadding_View_4908 : packoffset(c306.w);
  uint BindlessSampler_View_PreIntegratedBRDFSampler : packoffset(c307.x);
  uint PrePadding_View_4916 : packoffset(c307.y);
  uint BindlessResource_View_PrimitiveSceneData : packoffset(c307.z);
  uint PrePadding_View_4924 : packoffset(c307.w);
  uint BindlessResource_View_InstanceSceneData : packoffset(c308.x);
  uint PrePadding_View_4932 : packoffset(c308.y);
  uint BindlessResource_View_InstancePayloadData : packoffset(c308.z);
  uint PrePadding_View_4940 : packoffset(c308.w);
  uint BindlessResource_View_LightmapSceneData : packoffset(c309.x);
  uint PrePadding_View_4948 : packoffset(c309.y);
  uint BindlessResource_View_SkyIrradianceEnvironmentMap : packoffset(c309.z);
  uint PrePadding_View_4956 : packoffset(c309.w);
  uint BindlessResource_View_TransmittanceLutTexture : packoffset(c310.x);
  uint PrePadding_View_4964 : packoffset(c310.y);
  uint BindlessSampler_View_TransmittanceLutTextureSampler : packoffset(c310.z);
  uint PrePadding_View_4972 : packoffset(c310.w);
  uint BindlessResource_View_SkyViewLutTexture : packoffset(c311.x);
  uint PrePadding_View_4980 : packoffset(c311.y);
  uint BindlessSampler_View_SkyViewLutTextureSampler : packoffset(c311.z);
  uint PrePadding_View_4988 : packoffset(c311.w);
  uint BindlessResource_View_DistantSkyLightLutTexture : packoffset(c312.x);
  uint PrePadding_View_4996 : packoffset(c312.y);
  uint BindlessSampler_View_DistantSkyLightLutTextureSampler : packoffset(c312.z);
  uint PrePadding_View_5004 : packoffset(c312.w);
  uint BindlessResource_View_CameraAerialPerspectiveVolume : packoffset(c313.x);
  uint PrePadding_View_5012 : packoffset(c313.y);
  uint BindlessSampler_View_CameraAerialPerspectiveVolumeSampler : packoffset(c313.z);
  uint PrePadding_View_5020 : packoffset(c313.w);
  uint BindlessResource_View_CameraAerialPerspectiveVolumeMieOnly : packoffset(c314.x);
  uint PrePadding_View_5028 : packoffset(c314.y);
  uint BindlessSampler_View_CameraAerialPerspectiveVolumeMieOnlySampler : packoffset(c314.z);
  uint PrePadding_View_5036 : packoffset(c314.w);
  uint BindlessResource_View_CameraAerialPerspectiveVolumeRayOnly : packoffset(c315.x);
  uint PrePadding_View_5044 : packoffset(c315.y);
  uint BindlessSampler_View_CameraAerialPerspectiveVolumeRayOnlySampler : packoffset(c315.z);
  uint PrePadding_View_5052 : packoffset(c315.w);
  uint BindlessResource_View_HairScatteringLUTTexture : packoffset(c316.x);
  uint PrePadding_View_5060 : packoffset(c316.y);
  uint BindlessSampler_View_HairScatteringLUTSampler : packoffset(c316.z);
  uint PrePadding_View_5068 : packoffset(c316.w);
  uint BindlessResource_View_LTCMatTexture : packoffset(c317.x);
  uint PrePadding_View_5076 : packoffset(c317.y);
  uint BindlessSampler_View_LTCMatSampler : packoffset(c317.z);
  uint PrePadding_View_5084 : packoffset(c317.w);
  uint BindlessResource_View_LTCAmpTexture : packoffset(c318.x);
  uint PrePadding_View_5092 : packoffset(c318.y);
  uint BindlessSampler_View_LTCAmpSampler : packoffset(c318.z);
  uint PrePadding_View_5100 : packoffset(c318.w);
  uint View_bShadingEnergyConservation : packoffset(c319.x);
  uint View_bShadingEnergyPreservation : packoffset(c319.y);
  uint BindlessResource_View_ShadingEnergyGGXSpecTexture : packoffset(c319.z);
  uint PrePadding_View_5116 : packoffset(c319.w);
  uint BindlessResource_View_ShadingEnergyGGXGlassTexture : packoffset(c320.x);
  uint PrePadding_View_5124 : packoffset(c320.y);
  uint BindlessResource_View_ShadingEnergyClothSpecTexture : packoffset(c320.z);
  uint PrePadding_View_5132 : packoffset(c320.w);
  uint BindlessResource_View_ShadingEnergyDiffuseTexture : packoffset(c321.x);
  uint PrePadding_View_5140 : packoffset(c321.y);
  uint BindlessSampler_View_ShadingEnergySampler : packoffset(c321.z);
  uint PrePadding_View_5148 : packoffset(c321.w);
  uint BindlessResource_View_SSProfilesTexture : packoffset(c322.x);
  uint PrePadding_View_5156 : packoffset(c322.y);
  uint BindlessSampler_View_SSProfilesSampler : packoffset(c322.z);
  uint PrePadding_View_5164 : packoffset(c322.w);
  uint BindlessSampler_View_SSProfilesTransmissionSampler : packoffset(c323.x);
  uint PrePadding_View_5172 : packoffset(c323.y);
  uint BindlessResource_View_SSProfilesPreIntegratedTexture : packoffset(c323.z);
  uint PrePadding_View_5180 : packoffset(c323.w);
  uint BindlessSampler_View_SSProfilesPreIntegratedSampler : packoffset(c324.x);
  uint PrePadding_View_5188 : packoffset(c324.y);
  uint BindlessResource_View_WaterIndirection : packoffset(c324.z);
  uint PrePadding_View_5196 : packoffset(c324.w);
  uint BindlessResource_View_WaterData : packoffset(c325.x);
  uint PrePadding_View_5204 : packoffset(c325.y);
  uint PrePadding_View_5208 : packoffset(c325.z);
  uint PrePadding_View_5212 : packoffset(c325.w);
  float4 View_RectLightAtlasSizeAndInvSize : packoffset(c326.x);
  float View_RectLightAtlasMaxMipLevel : packoffset(c327.x);
  float PrePadding_View_5236 : packoffset(c327.y);
  uint BindlessResource_View_RectLightAtlasTexture : packoffset(c327.z);
  uint PrePadding_View_5244 : packoffset(c327.w);
  uint BindlessSampler_View_RectLightAtlasSampler : packoffset(c328.x);
  uint PrePadding_View_5252 : packoffset(c328.y);
  uint PrePadding_View_5256 : packoffset(c328.z);
  uint PrePadding_View_5260 : packoffset(c328.w);
  float4 View_IESAtlasSizeAndInvSize : packoffset(c329.x);
  uint BindlessResource_View_IESAtlasTexture : packoffset(c330.x);
  uint PrePadding_View_5284 : packoffset(c330.y);
  uint BindlessSampler_View_IESAtlasSampler : packoffset(c330.z);
  uint PrePadding_View_5292 : packoffset(c330.w);
  uint BindlessSampler_View_LandscapeWeightmapSampler : packoffset(c331.x);
  uint PrePadding_View_5300 : packoffset(c331.y);
  uint BindlessResource_View_LandscapeIndirection : packoffset(c331.z);
  uint PrePadding_View_5308 : packoffset(c331.w);
  uint BindlessResource_View_LandscapePerComponentData : packoffset(c332.x);
  uint PrePadding_View_5316 : packoffset(c332.y);
  uint BindlessResource_View_VTFeedbackBuffer : packoffset(c332.z);
  uint PrePadding_View_5324 : packoffset(c332.w);
  uint BindlessResource_View_EditorVisualizeLevelInstanceIds : packoffset(c333.x);
  uint PrePadding_View_5332 : packoffset(c333.y);
  uint BindlessResource_View_EditorSelectedHitProxyIds : packoffset(c333.z);
  uint PrePadding_View_5340 : packoffset(c333.w);
  uint BindlessResource_View_PhysicsFieldClipmapBuffer : packoffset(c334.x);
  uint PrePadding_View_5348 : packoffset(c334.y);
  uint PrePadding_View_5352 : packoffset(c334.z);
  uint PrePadding_View_5356 : packoffset(c334.w);
  float3 View_TLASRelativePreViewTranslation : packoffset(c335.x);
  float PrePadding_View_5372 : packoffset(c335.w);
  float3 View_TLASViewTilePosition : packoffset(c336.x);
};

cbuffer UniformBufferConstants_Material : register(b2) {
  float4 Material_PreshaderBuffer[9] : packoffset(c000.x);
  uint BindlessResource_Material_Texture2D_0 : packoffset(c009.x);
  uint PrePadding_Material_148 : packoffset(c009.y);
  uint BindlessSampler_Material_Texture2D_0Sampler : packoffset(c009.z);
  uint PrePadding_Material_156 : packoffset(c009.w);
  uint BindlessSampler_Material_Wrap_WorldGroupSettings : packoffset(c010.x);
  uint PrePadding_Material_164 : packoffset(c010.y);
  uint BindlessSampler_Material_Clamp_WorldGroupSettings : packoffset(c010.z);
};

SamplerState SceneTexturesStruct_PointClampSampler : register(s0);

SamplerState Material_Texture2D_0Sampler : register(s1);

SamplerState PostProcessInput_0_Sampler : register(s2);

SamplerState PostProcessInput_BilinearSampler : register(s3);

float4 main(
    noperspective float4 SV_Position: SV_Position)
    : SV_Target {
  float4 SV_Target;
  float3 unclamped_linear_sample1 = float3(0, 0, 0);
  float3 unclamped_linear_sample2 = float3(0, 0, 0);
  float3 tonemapped_linear_sample1 = float3(0, 0, 0);
  float3 tonemapped_linear_sample2 = float3(0, 0, 0);

  float _28 = (SV_Position.x - float((uint)(int)(PostProcessOutput_ViewportMin.x))) * PostProcessOutput_ViewportSizeInverse.x;
  float _29 = (SV_Position.y - float((uint)(int)(PostProcessOutput_ViewportMin.y))) * PostProcessOutput_ViewportSizeInverse.y;

  float4 _42 = SampleAndConvertToSRGBWithToneMap(unclamped_linear_sample1, tonemapped_linear_sample1, PostProcessInput_0_Texture, PostProcessInput_0_Sampler, float2(((_28 * PostProcessInput_0_UVViewportSize.x) + PostProcessInput_0_UVViewportMin.x), ((_29 * PostProcessInput_0_UVViewportSize.y) + PostProcessInput_0_UVViewportMin.y)));

  float _46 = _28 + -0.5f;
  float _47 = _29 + -0.5f;
  float _50 = (_46 * _46) + (_47 * _47);
  float _60 = ((_50 * ((Material_PreshaderBuffer[1].y) + ((Material_PreshaderBuffer[1].x) * sqrt(_50)))) + 1.0f) * (Material_PreshaderBuffer[1].z);
  float _63 = (_60 * _46) + 0.5f;
  float _64 = (_60 * _47) + 0.5f;
  bool _70 = ((Material_PreshaderBuffer[1].w) >= 1.0f);
  float _71 = select(_70, frac(_63), saturate(_63));
  float _72 = select(_70, frac(_64), saturate(_64));

  float4 _88 = SampleAndConvertToSRGBWithToneMap(unclamped_linear_sample2, tonemapped_linear_sample2, PostProcessInput_0_Texture, PostProcessInput_BilinearSampler, float2(min(max(((_71 * PostProcessInput_0_UVViewportSize.x) + PostProcessInput_0_UVViewportMin.x), PostProcessInput_0_UVViewportBilinearMin.x), PostProcessInput_0_UVViewportBilinearMax.x), min(max(((_72 * PostProcessInput_0_UVViewportSize.y) + PostProcessInput_0_UVViewportMin.y), PostProcessInput_0_UVViewportBilinearMin.y), PostProcessInput_0_UVViewportBilinearMax.y)));

  float _95 = (_71 * _72) * View_GameTime;
  float _96 = _95 * 76.92308044433594f;
  float _100 = frac(abs(_96));
  float _103 = _95 * 8.130081176757812f;
  float _107 = frac(abs(_103));
  float _111 = (select((_103 >= (-0.0f - _103)), _107, (-0.0f - _107)) * 159900.0f) * select((_96 >= (-0.0f - _96)), _100, (-0.0f - _100));
  float _115 = frac(abs(_111));
  float _119 = saturate(select((_111 >= (-0.0f - _111)), _115, (-0.0f - _115)) + 0.10000000149011612f);
  float _123 = (_72 * 6.2831854820251465f) * (Material_PreshaderBuffer[2].x);
  float _130 = ((Material_PreshaderBuffer[2].y) * sin(_123)) + _119;
  float _138 = ((_88.x * (Material_PreshaderBuffer[2].w)) * _130) + _88.x;
  float _139 = ((_88.y * (Material_PreshaderBuffer[2].w)) * (((Material_PreshaderBuffer[2].y) * cos(_123)) + _119)) + _88.y;
  float _140 = ((_88.z * (Material_PreshaderBuffer[2].w)) * _130) + _88.z;
  float _166 = ((((SV_Position.x - float((uint)(int)(PostProcessOutput_ViewportMin.x))) * PostProcessOutput_ViewportSizeInverse.x) * View_ViewSizeAndInvSize.x) + View_ViewRectMin.x) * View_BufferSizeAndInvSize.z;
  float _167 = ((((SV_Position.y - float((uint)(int)(PostProcessOutput_ViewportMin.y))) * PostProcessOutput_ViewportSizeInverse.y) * View_ViewSizeAndInvSize.y) + View_ViewRectMin.y) * View_BufferSizeAndInvSize.w;
  float4 _170 = SceneTexturesStruct_CustomDepthTexture.SampleLevel(SceneTexturesStruct_PointClampSampler, float2(_166, _167), 0.0f);
  uint2 _190 = SceneTexturesStruct_CustomStencilTexture.Load(int3((uint)(uint(_166 * View_BufferSizeAndInvSize.x)), (uint)(uint(_167 * View_BufferSizeAndInvSize.y)), 0));
  float4 _194 = SceneTexturesStruct_SceneDepthTexture.SampleLevel(SceneTexturesStruct_PointClampSampler, float2(_166, _167), 0.0f);
  float _217 = 1.0f - saturate(ceil((((View_InvDeviceZToWorldZTransform.x * _170.x) + View_InvDeviceZToWorldZTransform.y) + (1.0f / ((View_InvDeviceZToWorldZTransform.z * _170.x) - View_InvDeviceZToWorldZTransform.w))) - select(((bool)(abs(float((uint)(int)(_190.y)) - (Material_PreshaderBuffer[3].y)) > 9.999999747378752e-06f) && ((bool)((bool)((Material_PreshaderBuffer[3].z) >= 0.0f) && (bool)(abs(Material_PreshaderBuffer[3].z) > 9.999999747378752e-06f)))), 0.0f, (((View_InvDeviceZToWorldZTransform.x * _194.x) + View_InvDeviceZToWorldZTransform.y) + (1.0f / ((View_InvDeviceZToWorldZTransform.z * _194.x) - View_InvDeviceZToWorldZTransform.w))))));
  bool _231 = (bool)((Material_PreshaderBuffer[3].w) >= 0.0f) && (bool)(abs(Material_PreshaderBuffer[3].w) > 9.999999747378752e-06f);
  float _232 = select(_231, ((_217 * (_138 - _42.x)) + _42.x), _138);
  float _233 = select(_231, ((_217 * (_139 - _42.y)) + _42.y), _139);
  float _234 = select(_231, ((_217 * (_140 - _42.z)) + _42.z), _140);
  float _235 = 1.0f - _42.x;
  float _236 = 1.0f - _42.y;
  float _237 = 1.0f - _42.z;
  float _244 = 1.0f - _232;
  float _245 = 1.0f - _233;
  float _246 = 1.0f - _234;
  float _256 = _232 + -0.5f;
  float _257 = _233 + -0.5f;
  float _258 = _234 + -0.5f;
  float _268 = _256 * 2.0f;
  float _269 = _257 * 2.0f;
  float _270 = _258 * 2.0f;
  float _280 = _232 * 2.0f;
  float _281 = _233 * 2.0f;
  float _282 = _234 * 2.0f;
  float _283 = _280 * _42.x;
  float _284 = _281 * _42.y;
  float _285 = _282 * _42.z;
  bool _286 = (_232 >= 0.5f);
  bool _288 = (_233 >= 0.5f);
  bool _290 = (_234 >= 0.5f);
  float _295 = _232 + _42.x;
  float _296 = _233 + _42.y;
  float _297 = _234 + _42.z;
  float _436;
  float _437;
  float _438;
  if (!((Material_PreshaderBuffer[4].x) == 1.0f)) {
    if (!((Material_PreshaderBuffer[4].x) == 2.0f)) {
      if (!((Material_PreshaderBuffer[4].x) == 3.0f)) {
        if (!((Material_PreshaderBuffer[4].x) == 4.0f)) {
          if (!((Material_PreshaderBuffer[4].x) == 5.0f)) {
            if (!((Material_PreshaderBuffer[4].x) == 6.0f)) {
              if (!((Material_PreshaderBuffer[4].x) == 7.0f)) {
                if (!((Material_PreshaderBuffer[4].x) == 8.0f)) {
                  if (!((Material_PreshaderBuffer[4].x) == 9.0f)) {
                    if (!((Material_PreshaderBuffer[4].x) == 10.0f)) {
                      if (!((Material_PreshaderBuffer[4].x) == 11.0f)) {
                        if (!((Material_PreshaderBuffer[4].x) == 12.0f)) {
                          if (!((Material_PreshaderBuffer[4].x) == 13.0f)) {
                            if (!((Material_PreshaderBuffer[4].x) == 14.0f)) {
                              if (!((Material_PreshaderBuffer[4].x) == 15.0f)) {
                                bool _431 = (bool)((Material_PreshaderBuffer[4].x) == 20.0f) || ((bool)((bool)((Material_PreshaderBuffer[4].x) == 19.0f) || ((bool)((bool)((Material_PreshaderBuffer[4].x) == 18.0f) || ((bool)((bool)((Material_PreshaderBuffer[4].x) == 16.0f) || (bool)((Material_PreshaderBuffer[4].x) == 17.0f)))))));
                                _436 = select(_431, 0.0f, _232);
                                _437 = select(_431, 0.0f, _233);
                                _438 = select(_431, 0.0f, _234);
                              } else {
                                _436 = (_232 * _42.x);
                                _437 = (_233 * _42.y);
                                _438 = (_234 * _42.z);
                              }
                            } else {
                              _436 = select((_42.x < 0.5f), ((_42.x * 2.0f) * _232), (1.0f - ((_235 * 2.0f) * _244)));
                              _437 = select((_42.y < 0.5f), ((_42.y * 2.0f) * _233), (1.0f - ((_236 * 2.0f) * _245)));
                              _438 = select((_42.z < 0.5f), ((_42.z * 2.0f) * _234), (1.0f - ((_237 * 2.0f) * _246)));
                            }
                          } else {
                            _436 = min(_42.x, _232);
                            _437 = min(_42.y, _233);
                            _438 = min(_42.z, _234);
                          }
                        } else {
                          _436 = max(_42.x, _232);
                          _437 = max(_42.y, _233);
                          _438 = max(_42.z, _234);
                        }
                      } else {
                        _436 = (1.0f - (_244 * _235));
                        _437 = (1.0f - (_245 * _236));
                        _438 = (1.0f - (_246 * _237));
                      }
                    } else {
                      _436 = select(_286, ((1.0f - ((1.0f - _280) * _235)) * _42.x), (1.0f - ((1.0f - _283) * _235)));
                      _437 = select(_288, ((1.0f - ((1.0f - _281) * _236)) * _42.y), (1.0f - ((1.0f - _284) * _236)));
                      _438 = select(_290, ((1.0f - ((1.0f - _282) * _237)) * _42.z), (1.0f - ((1.0f - _285) * _237)));
                    }
                  } else {
                    _436 = select(_286, max(_42.x, _268), min(_42.x, _280));
                    _437 = select(_288, max(_42.y, _269), min(_42.y, _281));
                    _438 = select(_290, max(_42.z, _270), min(_42.z, _282));
                  }
                } else {
                  _436 = (_42.x + select(_286, ((_232 + -0.125f) * 1.25f), ((_232 + -0.25f) * 2.0f)));
                  _437 = (_42.y + select(_288, ((_233 + -0.125f) * 1.25f), ((_233 + -0.25f) * 2.0f)));
                  _438 = (_42.z + select(_290, ((_234 + -0.125f) * 1.25f), ((_234 + -0.25f) * 2.0f)));
                }
              } else {
                _436 = _295;
                _437 = _296;
                _438 = _297;
              }
            } else {
              _436 = (_295 + -1.0f);
              _437 = (_296 + -1.0f);
              _438 = (_297 + -1.0f);
            }
          } else {
            _436 = abs(select(_286, (1.0f - ((1.0f - _268) * _235)), _283));
            _437 = abs(select(_288, (1.0f - ((1.0f - _269) * _236)), _284));
            _438 = abs(select(_290, (1.0f - ((1.0f - _270) * _237)), _285));
          }
        } else {
          _436 = (0.5f - (((_42.x + -0.5f) * 2.0f) * _256));
          _437 = (0.5f - (((_42.y + -0.5f) * 2.0f) * _257));
          _438 = (0.5f - (((_42.z + -0.5f) * 2.0f) * _258));
        }
      } else {
        _436 = abs(_42.x - _232);
        _437 = abs(_42.y - _233);
        _438 = abs(_42.z - _234);
      }
    } else {
      _436 = (_42.x / _244);
      _437 = (_42.y / _245);
      _438 = (_42.z / _246);
    }
  } else {
    _436 = (1.0f - (_235 / _232));
    _437 = (1.0f - (_236 / _233));
    _438 = (1.0f - (_237 / _234));
  }
  float4 _460 = Material_Texture2D_0.Sample(Material_Texture2D_0Sampler, float2(((((Material_PreshaderBuffer[5].z) * _28) + 0.5f) - (Material_PreshaderBuffer[6].x)), ((((Material_PreshaderBuffer[5].w) * _29) + 0.5f) - (Material_PreshaderBuffer[6].y))));
  _460 = ConditionalConvertSRGBToBT2020(_460);

  float4 _494 = SceneTexturesStruct_SceneDepthTexture.SampleLevel(SceneTexturesStruct_PointClampSampler, float2((((((SV_Position.x - float((uint)(int)(PostProcessOutput_ViewportMin.x))) * PostProcessOutput_ViewportSizeInverse.x) * View_ViewSizeAndInvSize.x) + View_ViewRectMin.x) * View_BufferSizeAndInvSize.z), (((((SV_Position.y - float((uint)(int)(PostProcessOutput_ViewportMin.y))) * PostProcessOutput_ViewportSizeInverse.y) * View_ViewSizeAndInvSize.y) + View_ViewRectMin.y) * View_BufferSizeAndInvSize.w)), 0.0f);
  float _509 = (Material_PreshaderBuffer[7].x) * (((View_InvDeviceZToWorldZTransform.x * _494.x) + View_InvDeviceZToWorldZTransform.y) + (1.0f / ((View_InvDeviceZToWorldZTransform.z * _494.x) - View_InvDeviceZToWorldZTransform.w)));
  float _516 = saturate(select((_509 <= 0.0f), 0.0f, exp2(log2(_509) * (Material_PreshaderBuffer[7].y))));
  float _523 = select(((bool)((Material_PreshaderBuffer[7].z) >= 0.0f) && (bool)(abs(Material_PreshaderBuffer[7].z) > 9.999999747378752e-06f)), (1.0f - _516), _516);
  float _527 = ((((Material_PreshaderBuffer[4].y) * (_436 - _42.x)) * _460.x) * _523) + _42.x;
  float _528 = ((((Material_PreshaderBuffer[4].y) * (_437 - _42.y)) * _460.x) * _523) + _42.y;
  float _529 = ((((Material_PreshaderBuffer[4].y) * (_438 - _42.z)) * _460.x) * _523) + _42.z;
  SV_Target.x = ((((Material_PreshaderBuffer[8].x) - _527) * (Material_PreshaderBuffer[7].w)) + _527);
  SV_Target.y = ((((Material_PreshaderBuffer[8].y) - _528) * (Material_PreshaderBuffer[7].w)) + _528);
  SV_Target.z = ((((Material_PreshaderBuffer[8].z) - _529) * (Material_PreshaderBuffer[7].w)) + _529);
  SV_Target.w = 0.0f;

  // SV_Target.rgb = max(0, SV_Target.rgb);
  float3 unclamped_linear_sample = unclamped_linear_sample1;
  float3 tonemapped_linear_sample = tonemapped_linear_sample1;
  SV_Target.rgb = ConvertSRGBtoPQAndUpgradeToneMap(SV_Target.rgb, unclamped_linear_sample, tonemapped_linear_sample);

  return SV_Target;
}
