//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.4.1 on Wed Feb  4 07:24:28 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyz
// TEXCOORD                 0   xy          1     NONE   float   xy
// TEXCOORD                 1     zw        1     NONE   float     zw
// TEXCOORD                 2   xyz         2     NONE   float   xyz
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// TEXCOORD                 4   xyzw        4     NONE   float   x
// TEXCOORD                 5   xyz         5     NONE   float   xyz
// TEXCOORD                 6   xyz         6     NONE   float   xyz
// TEXCOORD                 7   x           7     NONE    uint   x
// SV_IsFrontFace           0   x           8    FFACE    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                              { 0, 1.000000, 0, 0},
                              { 0, 0, 1.000000, 0},
                              { 0, 0, 0, 1.000000},
                              { 2, 1, -1.000000, 1.000000},
                              { 2, 1, 1.000000, 1.000000},
                              { 0, 2, 1.000000, -1.000000},
                              { 0, 2, 1.000000, 1.000000},
                              { 0, 1, 1.000000, 1.000000},
                              { 0, 1, -1.000000, 1.000000} }
dcl_constantbuffer CB0[244], immediateIndexed
dcl_constantbuffer CB1[4085], dynamicIndexed
dcl_constantbuffer CB2[24], immediateIndexed
dcl_constantbuffer CB3[259], dynamicIndexed
dcl_constantbuffer CB4[3], immediateIndexed
dcl_constantbuffer CB5[2054], dynamicIndexed
dcl_constantbuffer CB6[715], dynamicIndexed
dcl_constantbuffer CB7[160], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_comparison
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s7, mode_default
dcl_sampler s8, mode_default
dcl_sampler s9, mode_default
dcl_resource_structured t0, 4
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2darray (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t14
dcl_resource_texture2d (float,float,float,float) t15
dcl_resource_texture3d (float,float,float,float) t16
dcl_resource_texture3d (float,float,float,float) t17
dcl_resource_texture3d (float,float,float,float) t18
dcl_resource_texture3d (float,float,float,float) t19
dcl_resource_texture3d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_resource_texture3d (float,float,float,float) t22
dcl_resource_texture2d (float,float,float,float) t23
dcl_input_ps_siv linear noperspective v0.xyz, position
dcl_input_ps linear v1.xy
dcl_input_ps linear v1.zw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyzw
dcl_input_ps linear v4.x
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.xyz
dcl_input_ps constant v7.x
dcl_input_ps_sgv constant v8.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 37
mul r0.xy, v0.xyxx, cb0[82].zwzz
mad r0.zw, r0.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
mul r1.xyzw, -r0.wwww, cb0[25].xyzw
mad r1.xyzw, cb0[24].xyzw, r0.zzzz, r1.xyzw
mad r1.xyzw, cb0[26].xyzw, v0.zzzz, r1.xyzw
add r1.xyzw, r1.xyzw, cb0[27].xyzw
div r1.xyz, r1.xyzx, r1.wwww
mul r0.z, r1.y, cb0[1].z
mad r0.z, cb0[0].z, r1.x, r0.z
mad r0.z, cb0[2].z, r1.z, r0.z
add r0.z, r0.z, cb0[3].z
mov r2.z, |r0.z|
lt r0.z, l(0.000000), v3.w
movc r0.z, r0.z, l(1.000000), l(-1.000000)
eq r0.w, l(0.000000), cb0[86].w
add r3.xyz, -r1.xyzx, cb0[44].xyzx
mov r4.x, cb0[0].z
mov r4.y, cb0[1].z
mov r4.z, cb0[2].z
movc r3.xyz, r0.wwww, r3.xyzx, r4.xyzx
dp3 r0.w, r3.xyzx, r3.xyzx
max r2.w, r0.w, l(9.999999939E-09)
rsq r2.w, r2.w
mul r5.xyz, r2.wwww, r3.xyzx
mul r0.w, r0.w, r2.w
add r6.xy, -v1.xyxx, v1.zwzz
mad r6.zw, cb2[3].xxxx, r6.xxxy, v1.xxxy
mad r6.zw, r6.zzzw, cb2[12].xxxy, cb2[12].zzzw
mad r6.xy, cb2[2].wwww, r6.xyxx, v1.xyxx
mad r6.xy, r6.xyxx, cb2[11].xyxx, cb2[11].zwzz
sample_b_indexable(texture2d)(float,float,float,float) r7.xyzw, r6.xyxx, t5.xyzw, s5, cb0[108].x
add r3.w, cb0[108].x, cb2[3].y
sample_b_indexable(texture2d)(float,float,float,float) r8.xyz, r6.zwzz, t6.xywz, s6, r3.w
mul r8.x, r8.x, r8.z
mad r6.xy, r8.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r8.xy, r6.xyxx, cb2[0].xxxx
sample_b_indexable(texture2d)(float,float,float,float) r9.xyz, r6.zwzz, t7.xyzw, s7, cb0[108].x
mul r7.xyzw, r7.xyzw, cb2[8].xyzw
mul_sat r7.xyz, r7.xyzx, cb2[4].zzzz
add r10.xyz, -r7.xyzx, cb2[8].xyzx
mad r7.xyz, cb2[4].xxxx, r10.xyzx, r7.xyzx
mad r3.w, r7.w, v4.x, -r7.w
mad r10.w, cb2[23].x, r3.w, r7.w
add r3.w, -cb2[0].z, cb2[0].w
mad r11.w, r9.y, r3.w, cb2[0].z
add_sat r3.w, l(-1.000000), cb2[3].w
add r4.w, -r9.x, cb2[4].y
mad r3.w, r3.w, r4.w, r9.x
mul r9.xyw, v2.zxzy, v3.yzyx
mad r9.xyw, v2.yzyx, v3.zxzy, -r9.xyxw
mul r9.xyw, r0.zzzz, r9.xyxw
mul r8.yzw, r8.yyyy, r9.xxyw
mad r8.xyz, v3.xyzx, r8.xxxx, r8.yzwy
dp2 r0.z, r6.xyxx, r6.xyxx
min r0.z, r0.z, l(1.000000)
add r0.z, -r0.z, l(1.000000)
sqrt r0.z, r0.z
max r0.z, r0.z, l(1.000000017E-16)
lt r4.w, l(0.000000), cb2[1].w
movc r4.w, r4.w, l(-1.000000), l(1.000000)
movc r4.w, v8.x, l(1.000000), r4.w
mul r0.z, r0.z, r4.w
mad r6.xyz, v2.xyzx, r0.zzzz, r8.xyzx
dp3 r0.z, r6.xyzx, r6.xyzx
rsq r0.z, r0.z
mul r6.xyz, r0.zzzz, r6.xyzx
dp3 r0.z, r6.xyzx, r5.xyzx
dp3 r4.w, -r5.xyzx, r6.xyzx
mul r5.w, cb2[19].z, cb2[19].z
mad r7.w, -r4.w, r4.w, l(1.000000)
mad r5.w, -r5.w, r7.w, l(1.000000)
sqrt r7.w, r5.w
mad r7.w, cb2[19].z, r4.w, r7.w
ge r5.w, r5.w, l(0.000000)
mul r8.xyz, r6.xyzx, r7.wwww
mad r8.xyz, cb2[19].zzzz, -r5.xyzx, -r8.xyzx
and r8.xyz, r5.wwww, r8.xyzx
mul r5.w, r0.z, v0.z
max r5.w, r5.w, l(0.500000)
div r5.w, cb2[19].w, r5.w
add r5.w, r5.w, -cb2[19].w
mad r5.w, cb2[20].x, r5.w, cb2[19].w
mul r8.xyz, r5.wwww, r8.xyzx
mul r8.yw, r8.yyyy, cb0[1].xxxy
mad r8.xy, cb0[0].xyxx, r8.xxxx, r8.ywyy
mad r8.xy, cb0[2].xyxx, r8.zzzz, r8.xyxx
mad r8.zw, v1.xxxy, cb2[22].xxxy, cb2[22].zzzw
sample_b_indexable(texture2d)(float,float,float,float) r8.zw, r8.zwzz, t9.zwxy, s8, cb0[108].x
mad r8.zw, r8.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
mad r8.zw, r8.zzzw, cb2[19].yyyy, -r8.xxxy
mad r8.xy, cb2[19].xxxx, r8.zwzz, r8.xyxx
mad r8.zw, v0.xxxy, cb0[82].zzzw, r8.xxxy
mul r8.xy, r8.xyxx, l(0.250000, 0.250000, 0.000000, 0.000000)
mad r9.xy, v0.xyxx, cb0[82].zwzz, r8.xyxx
sample_b_indexable(texture2d)(float,float,float,float) r5.w, r8.zwzz, t1.yzwx, s0, cb0[108].x
sample_b_indexable(texture2d)(float,float,float,float) r7.w, r9.xyxx, t1.yzwx, s0, cb0[108].x
mad r7.w, cb0[84].z, r7.w, cb0[84].w
div r7.w, l(1.000000, 1.000000, 1.000000, 1.000000), r7.w
ge r7.w, r7.w, r2.z
and r7.w, r7.w, l(0x3f800000)
mad r8.xy, r7.wwww, r8.xyxx, r0.xyxx
mad r5.w, cb0[84].z, r5.w, cb0[84].w
div r5.w, l(1.000000, 1.000000, 1.000000, 1.000000), r5.w
ge r5.w, r5.w, r2.z
and r5.w, r5.w, l(0x3f800000)
add r8.zw, -r8.xxxy, r8.zzzw
mad r8.xy, r5.wwww, r8.zwzz, r8.xyxx
sample_b_indexable(texture2d)(float,float,float,float) r8.xyz, r8.xyxx, t8.xyzw, s9, cb0[108].x
max r5.w, v5.z, l(9.999999939E-09)
div r9.xy, v5.xyxx, r5.wwww
max r5.w, v6.z, l(9.999999939E-09)
div r12.xy, v6.xyxx, r5.wwww
add r12.xy, r9.xyxx, -r12.xyxx
mul r5.w, l(0.080000), cb2[0].y
mad r9.xyw, -r7.xyxz, r3.wwww, r7.xyxz
mad r5.w, -r5.w, r3.w, r5.w
mad r7.xyz, r7.xyzx, r3.wwww, r5.wwww
mad r13.xyzw, r11.wwww, l(-1.000000, -0.027500, -0.572000, 0.022000), l(1.000000, 0.042500, 1.040000, -0.040000)
mul r3.w, r13.x, r13.x
max r0.z, r0.z, l(0.000000)
mul r5.w, r0.z, l(-9.280000)
exp r5.w, r5.w
min r3.w, r3.w, r5.w
mad r3.w, r3.w, r13.x, r13.y
mad r13.xy, r3.wwww, l(-1.040000, 1.040000, 0.000000, 0.000000), r13.zwzz
eq r3.w, l(1.000000), cb0[113].y
mul r14.xyzw, r1.yyyy, cb0[241].xyzw
mad r14.xyzw, cb0[240].xyzw, r1.xxxx, r14.xyzw
mad r14.xyzw, cb0[242].xyzw, r1.zzzz, r14.xyzw
add r14.xyzw, r14.xyzw, cb0[243].xyzw
div r5.w, l(1.000000, 1.000000, 1.000000, 1.000000), r14.w
mul r14.xyz, r14.xyzx, l(1.000000, -1.000000, 1.000000, 0.000000)
mul r14.xyz, r5.wwww, r14.xyzx
mad_sat r13.zw, r14.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
mul r13.zw, r13.zzzw, cb0[82].xxxy
ftou r15.xy, r13.zwzz
mad r5.w, cb0[84].z, r14.z, cb0[84].w
div r15.z, l(1.000000, 1.000000, 1.000000, 1.000000), r5.w
ftou r2.xy, v0.xyxx
movc r14.xyz, r3.wwww, r15.xyzx, r2.xyzx
mad r2.xyz, r6.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000), r1.xyzx
mad r15.xyz, cb0[6].xzyx, -cb0[212].wwww, cb0[210].xzyx
add r15.xyz, r2.xzyx, -r15.xyzx
max r3.w, |r15.y|, |r15.x|
add r3.w, r3.w, l(-464.000000)
mul_sat r3.w, r3.w, l(0.031250)
add r5.w, |r15.z|, l(-208.000000)
mul_sat r5.w, r5.w, l(0.031250)
max r3.w, r3.w, r5.w
ne r5.w, l(0.000000), cb0[210].w
lt r7.w, r3.w, l(1.000000)
and r5.w, r5.w, r7.w
if_nz r5.w
  mad r15.xyz, cb0[6].xzyx, -cb0[212].yyyy, cb0[210].xzyx
  add r15.xyz, r2.xzyx, -r15.xyzx
  max r5.w, |r15.y|, |r15.x|
  add r5.w, r5.w, l(-29.000000)
  mul_sat r5.w, r5.w, l(0.500000)
  add r7.w, |r15.z|, l(-13.000000)
  mul_sat r7.w, r7.w, l(0.500000)
  max r5.w, r5.w, r7.w
  lt r7.w, r5.w, l(1.000000)
  if_nz r7.w
    mad r15.xyz, r2.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r16.xyz, r15.xyzx, cb0[211].xyzx
    round_ni r16.xyz, r16.xyzx
    mad r15.xyz, r15.xyzx, cb0[211].xyzx, -r16.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r16.xyz, r15.xyzx, t16.xyzw, s2, l(0.000000)
    add r7.w, -r5.w, l(1.000000)
    mul r8.w, l(0.500000), cb0[211].y
    mad r12.w, -cb0[211].y, l(0.500000), l(1.000000)
    max r8.w, r8.w, r15.y
    min r8.w, r12.w, r8.w
    mul r15.w, r8.w, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r17.xyzw, r15.xwzx, t17.xyzw, s1, l(0.000000)
    mad r17.xyz, r17.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r18.xyz, r16.xxxx, r17.xyzx
    add r17.xyz, r15.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r17.xyz, r17.xyzx, t17.xyzw, s1, l(0.000000)
    mad r17.xyz, r17.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r19.xyz, r16.yyyy, r17.xyzx
    add r15.xyz, r15.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r15.xyz, r15.xyzx, t17.xyzw, s1, l(0.000000)
    mad r15.xyz, r15.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r15.xyz, r16.zzzz, r15.xyzx
    mad r8.w, r17.w, r7.w, r3.w
    mov r15.w, r16.z
    mul r15.xyzw, r7.wwww, r15.xyzw
    mov r19.w, r16.y
    mul r17.xyzw, r7.wwww, r19.xyzw
    mov r18.w, r16.x
    mul r16.xyzw, r7.wwww, r18.xyzw
  else
    mov r15.xyzw, l(0,0,0,0)
    mov r17.xyzw, l(0,0,0,0)
    mov r16.xyzw, l(0,0,0,0)
    mov r8.w, r3.w
  endif
  mad r18.xyz, cb0[6].xzyx, -cb0[212].zzzz, cb0[210].xzyx
  add r18.xyz, r2.xzyx, -r18.xyzx
  max r7.w, |r18.y|, |r18.x|
  add r7.w, r7.w, l(-116.000000)
  mul_sat r7.w, r7.w, l(0.125000)
  add r12.w, |r18.z|, l(-52.000000)
  mul_sat r12.w, r12.w, l(0.125000)
  max r7.w, r7.w, r12.w
  lt r12.w, r7.w, l(1.000000)
  if_nz r12.w
    mad r18.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r19.xyz, r18.xyzx, cb0[211].xyzx
    round_ni r19.xyz, r19.xyzx
    mad r18.xyz, r18.xyzx, cb0[211].xyzx, -r19.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r19.xyz, r18.xyzx, t18.xyzw, s2, l(0.000000)
    add r12.w, -r7.w, l(1.000000)
    mul r5.w, r5.w, r12.w
    mul r12.w, l(0.500000), cb0[211].y
    mad r13.z, -cb0[211].y, l(0.500000), l(1.000000)
    max r12.w, r12.w, r18.y
    min r12.w, r13.z, r12.w
    mul r18.w, r12.w, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r20.xyzw, r18.xwzx, t19.xyzw, s1, l(0.000000)
    mad r20.xyz, r20.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r21.xyz, r19.xxxx, r20.xyzx
    add r20.xyz, r18.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r20.xyz, r20.xyzx, t19.xyzw, s1, l(0.000000)
    mad r20.xyz, r20.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r22.xyz, r19.yyyy, r20.xyzx
    add r18.xyz, r18.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r18.xyz, r18.xyzx, t19.xyzw, s1, l(0.000000)
    mad r18.xyz, r18.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r18.xyz, r19.zzzz, r18.xyzx
    mad r8.w, r20.w, r5.w, r8.w
    mov r18.w, r19.z
    mad r15.xyzw, r18.xyzw, r5.wwww, r15.xyzw
    mov r22.w, r19.y
    mad r17.xyzw, r22.xyzw, r5.wwww, r17.xyzw
    mov r21.w, r19.x
    mad r16.xyzw, r21.xyzw, r5.wwww, r16.xyzw
  endif
  lt r5.w, l(0.000000), r7.w
  if_nz r5.w
    mad r2.xyz, r2.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r18.xyz, r2.xyzx, cb0[211].xyzx
    mul r19.xyz, l(0.500000, 0.500000, 0.500000, 0.000000), cb0[211].xyzx
    round_ni r18.xyz, r18.xyzx
    mad r2.xyz, r2.xyzx, cb0[211].xyzx, -r18.xyzx
    mad r18.xyz, -cb0[211].xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(1.000000, 1.000000, 1.000000, 0.000000)
    max r2.xyz, r19.xyzx, r2.xyzx
    min r20.xyz, r18.xyzx, r2.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r21.xyw, r20.xyzx, t20.yzwx, s2, l(0.000000)
    add r2.x, -r3.w, l(1.000000)
    mul r2.x, r2.x, r7.w
    max r2.y, r19.y, r20.y
    min r2.y, r18.y, r2.y
    mul r20.w, r2.y, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r18.xyzw, r20.xwzx, t21.xyzw, s1, l(0.000000)
    add r19.xyz, r20.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r19.xyz, r19.xyzx, t21.xyzw, s1, l(0.000000)
    mad r19.xyz, r19.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r19.xyz, r21.yyyy, r19.xyzx
    mov r19.w, r21.y
    mad r15.xyzw, r19.xyzw, r2.xxxx, r15.xyzw
    add r19.xyz, r20.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r19.xyz, r19.xyzx, t21.xyzw, s1, l(0.000000)
    mad r19.xyz, r19.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r19.xyz, r21.xxxx, r19.xyzx
    mov r19.w, r21.x
    mad r17.xyzw, r19.xyzw, r2.xxxx, r17.xyzw
    mad r18.xyz, r18.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r21.xyz, r21.wwww, r18.xyzx
    mad r16.xyzw, r21.xyzw, r2.xxxx, r16.xyzw
    mad r8.w, r18.w, r2.x, r8.w
  endif
  mad_sat r2.x, r8.w, l(2.000000), l(-1.000000)
  add r18.x, -r3.w, r2.x
  add r2.x, r3.w, r2.x
  mul r18.y, r2.x, l(0.500000)
else
  mov r15.xyzw, l(0,0,0,0)
  mov r17.xyzw, l(0,0,0,0)
  mov r16.xyzw, l(0,0,0,0)
  mov r18.xy, l(0,1.000000,0,0)
endif
mul r19.xyzw, r18.yyyx, cb0[213].xyzw
mad r19.y, r19.w, l(0.500000), r19.y
mul r2.xy, r18.yxyy, cb0[213].wyww
mad r19.w, r2.y, l(0.375000), r2.x
add r16.xyzw, r16.xyzw, r19.xyzw
mul r19.xyzw, r18.yyyx, cb0[214].xyzw
mad r19.y, r19.w, l(0.500000), r19.y
mul r2.xy, r18.yxyy, cb0[214].wyww
mad r19.w, r2.y, l(0.375000), r2.x
add r17.xyzw, r17.xyzw, r19.xyzw
mul r19.xyzw, r18.yyyx, cb0[215].xyzw
mad r19.y, r19.w, l(0.500000), r19.y
mul r2.xy, r18.yxyy, cb0[215].wyww
mad r19.w, r2.y, l(0.375000), r2.x
add r15.xyzw, r15.xyzw, r19.xyzw
dp3 r2.x, r16.xyzx, r6.xyzx
add r2.x, r16.w, r2.x
max r2.x, r2.x, l(0.000000)
dp3 r3.w, r17.xyzx, r6.xyzx
add r3.w, r17.w, r3.w
max r2.y, r3.w, l(0.000000)
dp3 r3.w, r15.xyzx, r6.xyzx
add r3.w, r15.w, r3.w
max r2.z, r3.w, l(0.000000)
add r3.w, r4.w, r4.w
mad r15.xyz, r6.xyzx, -r3.wwww, -r5.xyzx
add r3.w, l(-1.000000), cb0[113].x
max r4.w, r11.w, l(0.001000)
log r4.w, r4.w
mad r4.w, -r4.w, l(1.200000), l(1.000000)
add r3.w, r3.w, -r4.w
utof r13.zw, r14.xxxy
mul r16.xy, r13.zwzz, cb3[0].wwww
round_ni r16.xy, r16.xyxx
add r4.w, r14.z, -cb3[2].y
round_ni r4.w, r4.w
add r5.w, l(-1.000000), cb3[1].x
max r7.w, r4.w, l(0.000000)
min r5.w, r5.w, r7.w
ge r4.w, r5.w, r4.w
mad r7.w, r16.y, cb3[0].x, r16.x
ftoi r7.w, r7.w
iadd r7.w, r7.w, cb0[110].z
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r7.w, r7.w, l(0), t0.xxxx
ftoi r5.w, r5.w
iadd r5.w, r5.w, cb0[110].w
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.w, r5.w, l(0), t0.xxxx
and r5.w, r5.w, r7.w
and r4.w, r4.w, r5.w
mul r16.xyz, r2.xyzx, cb0[111].xxxx
dp3 r5.w, r16.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
mov r1.w, l(1.000000)
mov r6.w, l(1.000000)
mov r16.xyz, l(0,0,0,0)
mov r7.w, l(1.000000)
mov r8.w, r4.w
mov r12.w, l(0)
loop
  lt r15.w, l(0.010000), r7.w
  ine r16.w, r8.w, l(0)
  and r16.w, r15.w, r16.w
  if_nz r16.w
    firstbit_lo r16.w, r8.w
    ishl r17.x, l(1), r16.w
    xor r8.w, r8.w, r17.x
    ishl r16.w, r16.w, l(3)
    dp4 r17.x, cb3[r16.w + 6].xyzw, r1.xyzw
    dp4 r17.y, cb3[r16.w + 7].xyzw, r1.xyzw
    dp4 r17.z, cb3[r16.w + 8].xyzw, r1.xyzw
    ge r18.xyz, cb3[r16.w + 5].xyzx, |r17.xyzx|
    and r17.w, r18.y, r18.x
    and r17.w, r18.z, r17.w
    if_nz r17.w
      mul r17.w, l(0.100000), cb3[r16.w + 5].x
      mul r18.xyz, |r17.xyzx|, l(0.100000, 0.100000, 0.100000, 0.000000)
      mul r18.xy, r18.xyxx, r18.xyxx
      add r19.xyz, -|r17.xyzx|, cb3[r16.w + 5].xyzx
      mul r19.xyz, r19.xyzx, cb3[r16.w + 9].xyzx
      eq r18.w, l(1.000000), cb3[r16.w + 10].x
      if_nz r18.w
        dp3 r20.x, cb3[r16.w + 6].xyzx, r15.xyzx
        dp3 r20.y, cb3[r16.w + 7].xyzx, r15.xyzx
        dp3 r20.z, cb3[r16.w + 8].xyzx, r15.xyzx
        add r21.xyz, -r17.xyzx, cb3[r16.w + 5].xyzx
        div r21.xyz, r21.xyzx, r20.xyzx
        add r22.xyz, -r17.xyzx, -cb3[r16.w + 5].xyzx
        div r22.xyz, r22.xyzx, r20.xyzx
        lt r23.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r20.xyzx
        movc r21.xyz, r23.xyzx, r21.xyzx, r22.xyzx
        min r18.w, r21.y, r21.x
        min r18.w, r21.z, r18.w
        mad r17.xyz, r20.xyzx, r18.wwww, r17.xyzx
      else
        mov r17.xyz, r15.xyzx
      endif
      dp3 r18.w, r17.xyzx, r17.xyzx
      rsq r18.w, r18.w
      mul r17.xyz, r17.xyzx, r18.wwww
      lt r20.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r17.xyzx
      lt r21.xyz, r17.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
      iadd r20.xyz, -r20.xyzx, r21.xyzx
      itof r20.xyz, r20.xyzx
      dp3 r18.w, r17.xyzx, r20.xyzx
      div r17.xyz, r17.xyzx, r18.wwww
      lt r17.z, r17.z, l(0.000000)
      add r20.zw, -|r17.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
      mul r20.xy, r20.zwzz, r20.xyxx
      movc r17.xy, r17.zzzz, r20.xyxx, r17.xyxx
      dp4 r17.z, cb3[r16.w + 4].xyzw, r6.xyzw
      max r17.z, r17.z, l(0.000000)
      max r17.z, r17.z, l(0.000100)
      min r18.w, r19.z, r19.y
      min r18.w, r18.w, r19.x
      add r18.x, r18.y, r18.x
      mad r18.x, r18.z, r18.z, r18.x
      mad r17.w, r17.w, r17.w, -r18.x
      mul r17.w, r17.w, cb3[r16.w + 9].x
      mul r17.w, r17.w, cb3[r16.w + 9].x
      add r18.x, l(1.000000), -cb3[r16.w + 10].y
      mul r17.w, r17.w, r18.x
      mul r17.w, r17.w, l(100.000000)
      mad_sat r17.w, r18.w, cb3[r16.w + 10].y, r17.w
      mul r18.x, r17.w, cb3[r16.w + 10].w
      mad r17.xy, r17.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
      mad r19.xy, r17.xyxx, cb3[1].wwww, cb3[2].wwww
      mov r19.z, cb3[r16.w + 5].w
      sample_l_indexable(texture2darray)(float,float,float,float) r18.yzw, r19.xyzx, t4.wxyz, s3, r3.w
      mul r18.yzw, r18.yyzw, cb3[r16.w + 9].wwww
      div r17.x, r5.w, r17.z
      min r17.x, |r17.x|, l(1.000000)
      mad r17.x, r17.x, l(2.000000), r5.w
      add r17.y, r17.z, l(2.000000)
      div r17.x, r17.x, r17.y
      add r17.x, r17.x, l(-1.000000)
      mad r17.x, r17.x, cb0[112].w, l(1.000000)
      mul r17.xyz, r17.xxxx, r18.yzwy
      mul r17.xyz, r18.xxxx, r17.xyzx
      mad r16.xyz, r17.xyzx, r7.wwww, r16.xyzx
      mad r16.w, -r17.w, cb3[r16.w + 10].w, l(1.000000)
      mul r7.w, r7.w, r16.w
    endif
    mov r12.w, l(-1)
    continue
  else
    mov r12.w, r15.w
    break
  endif
  mov r12.w, r15.w
endloop
if_nz r12.w
  dp3 r1.w, r15.xyzx, r15.xyzx
  rsq r1.w, r1.w
  mul r17.xyz, r1.wwww, r15.xyzx
  lt r18.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r17.xyzx
  lt r19.xyz, r17.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  iadd r18.xyz, -r18.xyzx, r19.xyzx
  itof r18.xyz, r18.xyzx
  dp3 r1.w, r17.xyzx, r18.xyzx
  div r17.xyz, r17.xyzx, r1.wwww
  lt r1.w, r17.z, l(0.000000)
  add r17.zw, -|r17.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
  mul r17.zw, r17.zzzw, r18.xxxy
  movc r17.xy, r1.wwww, r17.zwzz, r17.xyxx
  mov r6.w, l(1.000000)
  dp4 r1.w, cb3[3].xyzw, r6.xyzw
  max r1.w, r1.w, l(0.000000)
  max r1.w, r1.w, l(0.000100)
  mad r17.xy, r17.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
  mad r17.xy, r17.xyxx, cb3[1].wwww, cb3[2].wwww
  mov r17.z, l(0)
  sample_l_indexable(texture2darray)(float,float,float,float) r17.xyz, r17.xyzx, t4.xyzw, s3, r3.w
  div r3.w, r5.w, r1.w
  min r3.w, |r3.w|, l(1.000000)
  mad r3.w, r3.w, l(2.000000), r5.w
  add r1.w, r1.w, l(2.000000)
  div r1.w, r3.w, r1.w
  add r1.w, r1.w, l(-1.000000)
  mad r1.w, r1.w, cb0[112].w, l(1.000000)
  mul r17.xyz, r1.wwww, r17.xyzx
  mad r16.xyz, r17.xyzx, r7.wwww, r16.xyzx
endif
mul r16.xyz, r16.xyzx, cb0[112].zzzz
mul r16.xyz, r16.xyzx, cb0[111].yyyy
ne r1.w, l(0.000000), cb0[112].y
if_nz r1.w
  sample_b_indexable(texture2d)(float,float,float,float) r1.w, r0.xyxx, t3.yzwx, s1, cb0[108].x
  sample_b_indexable(texture2d)(float,float,float,float) r17.xyz, r0.xyxx, t2.xyzw, s1, cb0[108].x
  add r0.x, -r1.w, l(1.000000)
  mul r18.xyz, r0.xxxx, r16.xyzx
  mad r16.xyz, r17.xyzx, r1.wwww, r18.xyzx
endif
mul r2.xyz, r9.xywx, r2.xyzx
add r0.x, r9.z, l(-1.000000)
mad r0.x, cb2[1].x, r0.x, l(1.000000)
mul r2.xyz, r0.xxxx, r2.xyzx
mul_sat r0.x, r7.y, l(50.000000)
mul r0.x, r13.y, r0.x
mad r17.xyz, r7.xyzx, r13.xxxx, r0.xxxx
mul r16.xyz, r16.xyzx, r17.xyzx
mad r2.xyz, r2.xyzx, cb0[111].xxxx, r16.xyzx
lt r0.x, cb6[35].w, l(0.990000)
if_nz r0.x
  ftoi r0.x, cb6[35].x
  ieq r0.y, r0.x, l(2)
  movc r16.xyz, r0.yyyy, cb6[20].xyzx, cb0[44].xyzx
  add r16.xyz, r1.xyzx, -r16.xyzx
  dp3 r0.y, r16.xyzx, r16.xyzx
  add r0.y, -r0.y, cb6[34].w
  mul_sat r0.y, r0.y, cb6[34].z
  lt r1.w, l(0.000000), r0.y
  if_nz r1.w
    ilt r0.x, l(0), r0.x
    if_nz r0.x
      add r16.xyz, r1.xyzx, -cb6[20].xyzx
      add r17.xyz, r1.xyzx, -cb6[21].xyzx
      add r18.xyz, r1.xyzx, -cb6[22].xyzx
      add r19.xyz, r1.xyzx, -cb6[23].xyzx
      dp3 r16.x, r16.xyzx, r16.xyzx
      dp3 r16.y, r17.xyzx, r17.xyzx
      dp3 r16.z, r18.xyzx, r18.xyzx
      dp3 r16.w, r19.xyzx, r19.xyzx
      lt r17.x, r16.x, cb6[20].w
      lt r17.y, r16.y, cb6[21].w
      lt r17.z, r16.z, cb6[22].w
      lt r17.w, r16.w, cb6[23].w
      and r18.xyzw, r17.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
      movc r17.xyz, r17.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)
      add r17.xyz, r17.xyzx, r18.yzwy
      max r18.yzw, r17.xxyz, l(0.000000, 0.000000, 0.000000, 0.000000)
      dp4 r0.x, r18.xyzw, l(4.000000, 3.000000, 2.000000, 1.000000)
      add r0.x, -r0.x, l(4.000000)
      max r0.x, r0.x, l(0.000000)
      min r0.x, r0.x, l(3.000000)
      add r1.w, r0.x, l(1.000000)
      min r1.w, r1.w, l(3.000000)
      ftou r1.w, r1.w
      dp3 r3.w, r16.yzwy, icb[r1.w + 0].yzwy
      div r1.w, r3.w, cb6[r1.w + 20].w
      ge r3.w, r1.w, l(0.000000)
      ge r1.w, l(1.000000), r1.w
      and r1.w, r1.w, r3.w
      if_nz r1.w
        ftou r1.w, r0.x
        add r13.xy, r13.zwzz, l(2.083000, 4.867000, 0.000000, 0.000000)
        dp2 r3.w, r13.xyxx, l(0.0671105608, 0.00583714992, 0.000000, 0.000000)
        frc r3.w, r3.w
        mul r3.w, r3.w, l(52.982918)
        frc r3.w, r3.w
        dp4 r4.w, r16.xyzw, icb[r1.w + 0].xyzw
        div r1.w, r4.w, cb6[r1.w + 20].w
        sqrt r1.w, r1.w
        add r1.w, r1.w, l(-0.900000)
        mul r1.w, r1.w, l(12.000000)
        ge r1.w, r1.w, r3.w
        and r1.w, r1.w, l(0x3f800000)
        add r0.x, r0.x, r1.w
      endif
      dp3 r1.w, r6.xyzx, cb5[0].xyzx
      max r1.w, r1.w, l(0.000000)
      min r1.w, r1.w, l(0.900000)
      add r1.w, -r1.w, l(1.000000)
      ftou r3.w, r0.x
      ishl r4.w, r3.w, l(2)
      mul r13.xy, r1.wwww, cb6[r3.w + 24].xyxx
      max r1.w, r13.x, l(0.000000)
      mad r16.xyz, -cb5[0].xyzx, r1.wwww, r1.xyzx
      mad r16.xyz, r6.xyzx, r13.yyyy, r16.xyzx
      mul r17.xyz, r16.yyyy, cb6[r4.w + 1].xyzx
      mad r16.xyw, cb6[r4.w + 0].xyxz, r16.xxxx, r17.xyxz
      mad r16.xyz, cb6[r4.w + 2].xyzx, r16.zzzz, r16.xywx
      add r16.xyz, r16.xyzx, cb6[r4.w + 3].xyzx
      ge r17.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r16.xyzx
      ge r18.xyz, r16.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
      or r17.xyz, r17.xyzx, r18.xyzx
      or r1.w, r17.y, r17.x
      or r1.w, r17.z, r1.w
      and r3.w, r16.z, l(0x7fffffff)
      ult r3.w, l(0x7f800000), r3.w
      or r17.z, r1.w, r3.w
      ftoi r0.x, r0.x
      mad r13.xy, r16.xyxx, cb6[r0.x + 28].zwzz, cb6[r0.x + 28].xyxx
      mad r16.xy, r13.xyxx, cb6[32].zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
      round_ni r16.xy, r16.xyxx
      mad r13.xy, r13.xyxx, cb6[32].zwzz, -r16.xyxx
      add r18.xyzw, r13.xxyy, l(0.500000, 1.000000, 0.500000, 1.000000)
      mul r19.xw, r18.xxxz, r18.xxxz
      min r18.xz, r13.xxyx, l(0.000000, 0.000000, 0.000000, 0.000000)
      max r20.xy, r13.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
      mad r20.zw, r19.xxxw, l(0.000000, 0.000000, 0.500000, 0.500000), -r13.xxxy
      add r13.xy, -r13.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
      mad r13.xy, -r18.xzxx, r18.xzxx, r13.xyxx
      mad r18.xy, -r20.xyxx, r20.xyxx, r18.ywyy
      mov r21.x, r20.z
      mov r21.y, r13.x
      mov r21.z, r18.x
      mov r21.w, r19.x
      mul r21.xyzw, r21.xyzw, l(0.444440, 0.444440, 0.444440, 0.222220)
      mov r19.x, r20.w
      mov r19.y, r13.y
      mov r19.z, r18.y
      mul r18.xyzw, r19.xyzw, l(0.444440, 0.444440, 0.444440, 0.222220)
      add r19.xyzw, r21.ywyw, r21.xzxz
      add r20.xyzw, r18.yyww, r18.xxzz
      div r13.xy, r21.ywyy, r19.zwzz
      add r13.xy, r13.xyxx, l(-1.500000, 0.500000, 0.000000, 0.000000)
      mul r21.xy, r13.xyxx, cb6[32].xxxx
      div r13.xy, r18.ywyy, r20.ywyy
      add r13.xy, r13.xyxx, l(-1.500000, 0.500000, 0.000000, 0.000000)
      mul r21.zw, r13.xxxy, cb6[32].yyyy
      mul r18.xyzw, r19.xyzw, r20.xyzw
      mad r19.xyzw, r16.xyxy, cb6[32].xyxy, r21.xzyz
      sample_c_lz_indexable(texture2d)(float,float,float,float) r0.x, r19.xyxx, t10.xxxx, s4, r16.z
      sample_c_lz_indexable(texture2d)(float,float,float,float) r1.w, r19.zwzz, t10.xxxx, s4, r16.z
      mul r1.w, r1.w, r18.y
      mad r0.x, r18.x, r0.x, r1.w
      mad r19.xyzw, r16.xyxy, cb6[32].xyxy, r21.xwyw
      sample_c_lz_indexable(texture2d)(float,float,float,float) r1.w, r19.xyxx, t10.xxxx, s4, r16.z
      mad r0.x, r18.z, r1.w, r0.x
      sample_c_lz_indexable(texture2d)(float,float,float,float) r1.w, r19.zwzz, t10.xxxx, s4, r16.z
      mad r0.x, r18.w, r1.w, r0.x
      movc r17.x, r17.z, l(1.000000), r0.x
    else
      mov r17.xz, l(1.000000,0,0,0)
    endif
  else
    mov r17.xz, l(1.000000,0,0,0)
  endif
  lt r0.x, r0.y, l(1.000000)
  if_nz r0.x
    dp3 r0.x, r6.xyzx, cb5[0].xyzx
    max r0.x, r0.x, l(0.000000)
    min r0.x, r0.x, l(0.900000)
    add r0.x, -r0.x, l(1.000000)
    mul r13.xy, r0.xxxx, cb6[584].xyxx
    mad r16.xyz, -cb5[0].xyzx, r13.xxxx, r1.xyzx
    mad r16.xyz, r6.xyzx, r13.yyyy, r16.xyzx
    mul r13.xy, r16.yyyy, cb6[581].xyxx
    mad r13.xy, cb6[580].xyxx, r16.xxxx, r13.xyxx
    mad r13.xy, cb6[582].xyxx, r16.zzzz, r13.xyxx
    add r13.xy, r13.xyxx, cb6[583].xyxx
    lt r18.xy, l(0.000000, 0.000000, 0.000000, 0.000000), r13.xyxx
    and r0.x, r18.y, r18.x
    lt r18.xy, r13.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
    and r1.w, r18.y, r18.x
    and r0.x, r0.x, r1.w
    if_nz r0.x
      mul r0.x, r13.y, cb6[585].z
      round_ni r0.x, r0.x
      add r0.x, r13.x, r0.x
      mul r0.x, r0.x, cb6[585].y
      ftou r0.x, r0.x
      umin r0.x, r0.x, l(127)
      and r1.w, l(0x0000ffff), cb6[r0.x + 587].x
      f16tof32 r13.x, r1.w
      ge r1.w, r13.x, l(0.000000)
      if_nz r1.w
        mov r18.x, cb6[576].x
        mov r18.y, cb6[577].x
        mov r18.z, cb6[578].x
        mov r18.w, cb6[r0.x + 587].y
        mov r16.w, l(1.000000)
        dp4 r18.x, r18.xyzw, r16.xyzw
        mov r19.x, cb6[576].y
        mov r19.y, cb6[577].y
        mov r19.z, cb6[578].y
        mov r19.w, cb6[r0.x + 587].z
        dp4 r18.y, r19.xyzw, r16.xyzw
        mov r19.x, cb6[576].z
        mov r19.y, cb6[577].z
        mov r19.z, cb6[578].z
        mov r19.w, cb6[r0.x + 587].w
        dp4 r1.w, r19.xyzw, r16.xyzw
        lt r16.xy, l(0.000000, 0.000000, 0.000000, 0.000000), r18.xyxx
        lt r3.w, l(0.000000), r1.w
        and r4.w, r16.y, r16.x
        and r3.w, r3.w, r4.w
        lt r16.xy, r18.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
        lt r4.w, r1.w, l(1.000000)
        and r5.w, r16.y, r16.x
        and r4.w, r4.w, r5.w
        and r3.w, r3.w, r4.w
        if_nz r3.w
          ushr r0.x, cb6[r0.x + 587].x, l(16)
          f16tof32 r13.y, r0.x
          mad r13.xy, r18.xyxx, cb6[584].zwzz, r13.xyxx
          mad r16.xy, r13.xyxx, cb6[586].zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
          round_ni r16.xy, r16.xyxx
          mad r13.xy, r13.xyxx, cb6[586].zwzz, -r16.xyxx
          add r18.xyzw, r13.xxyy, l(0.500000, 1.000000, 0.500000, 1.000000)
          mul r19.xw, r18.xxxz, r18.xxxz
          min r16.zw, r13.xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
          max r18.xz, r13.xxyx, l(0.000000, 0.000000, 0.000000, 0.000000)
          mad r20.xy, r19.xwxx, l(0.500000, 0.500000, 0.000000, 0.000000), -r13.xyxx
          add r13.xy, -r13.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
          mad r13.xy, -r16.zwzz, r16.zwzz, r13.xyxx
          mad r16.zw, -r18.xxxz, r18.xxxz, r18.yyyw
          mov r18.x, r20.x
          mov r18.y, r13.x
          mov r18.z, r16.z
          mov r18.w, r19.x
          mul r18.xyzw, r18.xyzw, l(0.444440, 0.444440, 0.444440, 0.222220)
          mov r19.x, r20.y
          mov r19.y, r13.y
          mov r19.z, r16.w
          mul r19.xyzw, r19.xyzw, l(0.444440, 0.444440, 0.444440, 0.222220)
          add r20.xyzw, r18.ywyw, r18.xzxz
          add r21.xyzw, r19.yyww, r19.xxzz
          div r13.xy, r18.ywyy, r20.zwzz
          add r13.xy, r13.xyxx, l(-1.500000, 0.500000, 0.000000, 0.000000)
          mul r18.xy, r13.xyxx, cb6[586].xxxx
          div r13.xy, r19.ywyy, r21.ywyy
          add r13.xy, r13.xyxx, l(-1.500000, 0.500000, 0.000000, 0.000000)
          mul r18.zw, r13.xxxy, cb6[586].yyyy
          mul r19.xyzw, r20.xyzw, r21.xyzw
          mad r20.xyzw, r16.xyxy, cb6[586].xyxy, r18.xzyz
          sample_c_lz_indexable(texture2d)(float,float,float,float) r0.x, r20.xyxx, t13.xxxx, s4, r1.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r3.w, r20.zwzz, t13.xxxx, s4, r1.w
          mul r3.w, r3.w, r19.y
          mad r0.x, r19.x, r0.x, r3.w
          mad r16.xyzw, r16.xyxy, cb6[586].xyxy, r18.xwyw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r3.w, r16.xyxx, t13.xxxx, s4, r1.w
          mad r0.x, r19.z, r3.w, r0.x
          sample_c_lz_indexable(texture2d)(float,float,float,float) r1.w, r16.zwzz, t13.xxxx, s4, r1.w
          mad r17.y, r19.w, r1.w, r0.x
        else
          mov r17.y, l(1.000000)
        endif
      else
        mov r17.y, l(1.000000)
      endif
    else
      mov r17.y, l(1.000000)
    endif
    movc r17.x, r17.z, r17.y, r17.x
  else
    mov r17.y, l(1.000000)
  endif
  add r0.x, -r17.y, r17.x
  mad r0.x, r0.y, r0.x, r17.y
  lt r0.y, l(0.001000), r0.x
  if_nz r0.y
    add r16.xyz, r1.xyzx, -cb0[173].xyzx
    mad r13.xy, cb0[176].xzxx, r16.yyyy, r16.xzxx
    mul r16.yw, r13.xxxy, cb0[174].zzzz
    mul r17.xy, cb0[175].xyxx, cb0[183].wwww
    mad r13.xy, r13.xyxx, cb0[174].zzzz, r17.xyxx
    sample_l_indexable(texture2d)(float,float,float,float) r0.y, r13.xyxx, t12.yxzw, s2, l(0.000000)
    mad r13.xy, r16.ywyy, cb0[175].wwww, r17.xyxx
    sample_l_indexable(texture2d)(float,float,float,float) r1.w, r13.xyxx, t12.yzwx, s2, l(0.000000)
    dp2 r3.w, r16.xzxx, r16.xzxx
    sqrt r3.w, r3.w
    add r4.w, -cb0[174].x, cb0[174].y
    add r3.w, r3.w, -cb0[174].x
    div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
    mul_sat r3.w, r3.w, r4.w
    mad r4.w, r3.w, l(-2.000000), l(3.000000)
    mul r3.w, r3.w, r3.w
    mul r3.w, r3.w, r4.w
    add r1.w, -r0.y, r1.w
    mad r0.y, r3.w, r1.w, r0.y
    add r0.y, r0.y, l(-1.000000)
    mad r0.y, cb0[175].z, r0.y, l(1.000000)
    mul r0.x, r0.y, r0.x
  endif
  add r0.y, -r0.x, cb6[35].z
  mad r0.x, cb6[35].w, r0.y, r0.x
else
  mov r0.x, cb6[35].z
endif
min r0.x, r0.x, l(1.000000)
add r0.x, r0.x, l(-1.000000)
mad r0.x, cb6[34].x, r0.x, l(1.000000)
lt r1.w, l(0.001000), r0.x
if_nz r1.w
  dp3 r1.w, -cb5[0].xyzx, r15.xyzx
  mad r16.xyz, cb5[0].xyzx, r1.wwww, r15.xyzx
  lt r1.w, r1.w, cb5[4].z
  dp3 r3.w, r16.xyzx, r16.xyzx
  max r3.w, r3.w, l(0.0000610351562)
  rsq r3.w, r3.w
  mul r16.xyz, r3.wwww, r16.xyzx
  mul r16.xyz, r16.xyzx, cb5[4].yyyy
  mad r16.xyz, -cb5[0].xyzx, cb5[4].zzzz, r16.xyzx
  dp3 r3.w, r16.xyzx, r16.xyzx
  rsq r3.w, r3.w
  mul r16.xyz, r3.wwww, r16.xyzx
  movc r16.xyz, r1.wwww, r16.xyzx, r15.xyzx
  mad r17.xyz, r3.xyzx, r2.wwww, r16.xyzx
  dp3 r1.w, r17.xyzx, r17.xyzx
  max r1.w, r1.w, l(0.0000610351562)
  rsq r1.w, r1.w
  mul r17.xyz, r1.wwww, r17.xyzx
  dp3_sat r11.y, r16.xyzx, r6.xyzx
  dp3_sat r1.w, r6.xyzx, r17.xyzx
  min r11.z, r0.z, l(1.000000)
  mul r3.w, r11.w, r11.w
  mul r3.w, r3.w, r3.w
  mad r4.w, r1.w, r3.w, -r1.w
  mad r1.w, r4.w, r1.w, l(1.000000)
  dp3_sat r4.w, r5.xyzx, r17.xyzx
  add r4.w, -r4.w, l(1.000000)
  mul r5.w, r4.w, r4.w
  mul r5.w, r5.w, r5.w
  mul r6.w, r4.w, r5.w
  add r7.w, -r11.w, l(1.000000)
  mad r8.w, -r7.w, l(0.383026), l(-0.0761947036)
  mad r8.w, r7.w, r8.w, l(1.049970)
  mad r7.w, r7.w, r8.w, l(0.409255)
  min r7.w, r7.w, l(0.999000)
  add r8.w, -r7.w, l(1.000000)
  add r16.xyz, -r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mad r16.xyz, r16.xyzx, l(0.0476190485, 0.0476190485, 0.0476190485, 0.000000), r7.xyzx
  mad r4.w, -r5.w, r4.w, l(1.000000)
  mad r17.xyz, r7.xyzx, r4.wwww, r6.wwww
  mul r1.w, r1.w, r1.w
  div r1.w, r3.w, r1.w
  mad r13.xy, -r11.zyzz, r3.wwww, r11.zyzz
  mad r13.xy, r13.xyxx, r11.zyzz, r3.wwww
  sqrt r13.xy, r13.xyxx
  mul r13.xy, r11.yzyy, r13.xyxx
  add r3.w, r13.y, r13.x
  add r3.w, r3.w, l(0.000100)
  div r3.w, l(0.500000), r3.w
  mul r1.w, r1.w, r3.w
  mul r17.xyz, r1.wwww, r17.xyzx
  min r17.xyz, r17.xyzx, l(2048.000000, 2048.000000, 2048.000000, 0.000000)
  mad r18.xyzw, r11.zwyw, l(0.968750, 0.968750, 0.968750, 0.968750), l(0.015625, 0.015625, 0.015625, 0.015625)
  sample_l_indexable(texture2d)(float,float,float,float) r1.w, r18.xyxx, t15.yzwx, s1, l(0.000000)
  sample_l_indexable(texture2d)(float,float,float,float) r3.w, r18.zwzz, t15.yzwx, s1, l(0.000000)
  mul r1.w, r1.w, r3.w
  mul r1.w, r7.w, r1.w
  div r1.w, r1.w, r8.w
  mul r18.xyz, r16.xyzx, r16.xyzx
  mul r18.xyz, r1.wwww, r18.xyzx
  mad r16.xyz, -r16.xyzx, r8.wwww, l(1.000000, 1.000000, 1.000000, 0.000000)
  div r16.xyz, r18.xyzx, r16.xyzx
  add r16.xyz, r16.xyzx, r17.xyzx
  mul r16.xyz, r16.xyzx, cb5[4].xxxx
  max r16.xyz, r16.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  min r16.xyz, r16.xyzx, l(1000.000000, 1000.000000, 1000.000000, 0.000000)
  max r1.w, r10.w, l(0.010000)
  div r16.xyz, r16.xyzx, r1.wwww
  min r16.xyz, r16.xyzx, l(1000.000000, 1000.000000, 1000.000000, 0.000000)
  mul r17.xyz, r9.xywx, r11.yyyy
  mad r16.xyz, r16.xyzx, r11.yyyy, r17.xyzx
  mul r16.xyz, r16.xyzx, cb5[1].xyzx
  mov r0.y, l(0.500000)
  sample_b_indexable(texture2d)(float,float,float,float) r17.xyz, r0.xyxx, t14.xyzw, s1, cb0[108].x
  add r0.x, -r0.x, l(1.000000)
  mad r17.xyz, r16.xyzx, r17.xyzx, -r16.xyzx
  mad r16.xyz, r0.xxxx, r17.xyzx, r16.xyzx
else
  mov r16.xyz, l(0,0,0,0)
endif
mul r0.xy, r13.zwzz, l(0.031250, 0.031250, 0.000000, 0.000000)
round_ni r0.xy, r0.xyxx
mad r0.x, r0.y, cb4[1].y, r0.x
mul r0.x, r0.x, l(8.000000)
ftoi r0.x, r0.x
mad r0.y, -cb0[85].y, cb4[2].w, r14.z
round_ni r0.y, r0.y
add r1.w, l(-1.000000), cb4[1].w
max r3.w, r0.y, l(0.000000)
min r1.w, r1.w, r3.w
mul r3.w, r1.w, l(8.000000)
ftoi r3.w, r3.w
ge r0.y, r1.w, r0.y
iadd r1.w, r3.w, cb0[110].y
mul r3.w, r11.w, r11.w
min r11.x, r0.z, l(1.000000)
add r0.z, -r11.w, l(1.000000)
mad r4.w, -r0.z, l(0.383026), l(-0.0761947036)
mad r4.w, r0.z, r4.w, l(1.049970)
mad r0.z, r0.z, r4.w, l(0.409255)
min r0.z, r0.z, l(0.999000)
add r4.w, -r0.z, l(1.000000)
add r17.xyz, -r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mad r17.xyz, r17.xyzx, l(0.0476190485, 0.0476190485, 0.0476190485, 0.000000), r7.xyzx
mad r11.yz, r11.xxwx, l(0.000000, 0.968750, 0.968750, 0.000000), l(0.000000, 0.015625, 0.015625, 0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r5.w, r11.yzyy, t15.yzwx, s1, l(0.000000)
mad r18.xyz, -r17.xyzx, r4.wwww, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r17.xyz, r17.xyzx, r17.xyzx
mov r19.w, l(1.000000)
mov r13.y, l(1.000000)
mov r20.z, r11.w
mov r21.xyz, l(0,0,0,0)
mov r6.w, l(1.000000)
mov r7.w, l(0)
loop
  ilt r8.w, l(7), r7.w
  breakc_nz r8.w
  iadd r8.w, r0.x, r7.w
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r8.w, r8.w, l(0), t0.xxxx
  iadd r9.z, r1.w, r7.w
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r9.z, r9.z, l(0), t0.xxxx
  and r8.w, r8.w, r9.z
  and r8.w, r0.y, r8.w
  ishl r9.z, r7.w, l(5)
  mov r22.xyz, l(0,0,0,0)
  mov r11.y, r6.w
  mov r11.z, r8.w
  loop
    breakc_z r11.z
    firstbit_lo r12.w, r11.z
    ishl r15.w, l(1), r12.w
    xor r15.w, r11.z, r15.w
    iadd r12.w, r9.z, r12.w
    bfi r23.xyzw, l(29, 29, 29, 29), l(3, 3, 3, 3), r12.wwww, l(1, 3, 5, 6)
    bfi r16.w, l(29), l(3), r12.w, l(7)
    ftou r17.w, cb5[r23.z + 6].w
    ieq r17.w, r17.w, l(1)
    if_nz r17.w
      add r19.xyz, r1.xyzx, -cb5[r23.x + 6].xyzx
      and r24.xyz, l(0x0000ffff, 0x0000ffff, 0x0000ffff, 0), cb5[r23.z + 6].xzyx
      and r25.xyz, l(0x0000ffff, 0x0000ffff, 0x0000ffff, 0), cb5[r23.w + 6].yxzy
      ushr r26.xyz, cb5[r23.z + 6].xzyx, l(16, 16, 16, 0)
      ushr r27.xyz, cb5[r23.w + 6].yxzy, l(16, 16, 16, 0)
      f16tof32 r24.xyz, r24.xyzx
      f16tof32 r25.xyz, r25.xyzx
      f16tof32 r26.xyz, r26.xyzx
      f16tof32 r27.xyw, r27.yxyz
      mov r28.xz, r24.xxzx
      mov r28.yw, r26.xxxz
      dp4 r17.w, r19.xyzw, r28.xyzw
      mov r26.x, r24.y
      mov r26.z, r25.y
      mov r26.w, r27.x
      dp4 r18.w, r19.xyzw, r26.xyzw
      mov r27.xz, r25.xxzx
      dp4 r19.x, r19.xyzw, r27.xyzw
      max r17.w, |r17.w|, |r18.w|
      max r17.w, |r19.x|, r17.w
      mad r18.w, cb5[r16.w + 6].x, l(0.500000), l(0.500000)
      add r17.w, r17.w, -r18.w
      mad r18.w, -cb5[r16.w + 6].x, l(0.500000), l(0.500000)
      div_sat r17.w, r17.w, r18.w
      add r17.w, -r17.w, l(1.000000)
      mul r17.w, r17.w, r17.w
    else
      mov r17.w, l(1.000000)
    endif
    lt r18.w, l(0.500000), cb5[r23.y + 6].z
    lt r19.x, r17.w, l(0.001000)
    or r19.x, r18.w, r19.x
    if_nz r19.x
      mov r11.z, r15.w
      continue
    endif
    ishl r19.x, r12.w, l(3)
    bfi r12.w, l(29), l(3), r12.w, l(2)
    lt r19.y, cb5[r19.x + 6].w, l(1.500000)
    if_nz r19.y
      mad r19.y, cb5[r12.w + 6].y, l(0.500000), l(0.500000)
      add r24.x, r19.y, -|cb5[r12.w + 6].x|
      add r24.y, -r24.x, cb5[r12.w + 6].y
      add r19.y, -|r24.x|, l(1.000000)
      add r19.y, -|r24.y|, r19.y
      max r19.y, r19.y, l(0.000488281250)
      ge r19.z, cb5[r12.w + 6].x, l(0.000000)
      movc r24.z, r19.z, r19.y, -r19.y
      dp3 r19.y, r24.xyzx, r24.xyzx
      rsq r19.y, r19.y
      mul r24.xyz, r19.yyyy, r24.xyzx
      add r25.xyz, -r1.xyzx, cb5[r23.x + 6].xyzx
      dp3 r19.y, r25.xyzx, r25.xyzx
      rsq r19.z, r19.y
      mul r26.xyz, r19.zzzz, r25.xyzx
      ftoi r20.w, cb5[r16.w + 6].w
      mul r27.xyz, r24.xyzx, cb5[r12.w + 6].zzzz
      mad r28.xyz, -r27.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r25.xyzx
      mad r29.xyz, r27.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r25.xyzx
      ftou r21.w, cb5[r19.x + 6].w
      and r21.w, r21.w, l(1)
      ieq r22.w, r21.w, l(0)
      not r22.w, r22.w
      lt r23.z, l(0.000000), cb5[r12.w + 6].z
      and r22.w, r22.w, r23.z
      dp3 r23.z, r28.xyzx, r28.xyzx
      sqrt r23.z, r23.z
      dp3 r24.w, r29.xyzx, r29.xyzx
      sqrt r24.w, r24.w
      dp3 r25.w, r6.xyzx, r28.xyzx
      div r25.w, r25.w, r23.z
      dp3 r26.w, r6.xyzx, r29.xyzx
      div r26.w, r26.w, r24.w
      add r25.w, r25.w, r26.w
      mul_sat r30.x, r25.w, l(0.500000)
      dp3 r25.w, r28.xyzx, r29.xyzx
      mad r23.z, r23.z, r24.w, r25.w
      mad r23.z, r23.z, l(0.500000), l(1.000000)
      div r30.y, l(1.000000, 1.000000, 1.000000, 1.000000), r23.z
      dp3_sat r13.x, r6.xyzx, r26.xyzx
      movc r20.xy, r22.wwww, r30.xyxx, r13.xyxx
      lt r13.x, cb5[r23.w + 6].w, l(0.000000)
      if_nz r13.x
        mul r13.x, cb5[r23.x + 6].w, cb5[r23.x + 6].w
        mul r13.x, r13.x, r19.y
        mad r13.x, -r13.x, r13.x, l(1.000000)
        max r13.x, r13.x, l(0.000000)
        add r19.y, r19.y, l(1.000000)
        div r19.y, l(1.000000, 1.000000, 1.000000, 1.000000), r19.y
        and r23.z, r22.w, l(0x3f800000)
        add r24.w, -r19.y, r20.y
        mad r19.y, r23.z, r24.w, r19.y
        mul r13.x, r13.x, r13.x
        mul r13.x, r13.x, r19.y
      else
        mul r29.xyz, r25.xyzx, cb5[r23.x + 6].wwww
        dp3 r19.y, r29.xyzx, r29.xyzx
        min r19.y, r19.y, l(1.000000)
        add r19.y, -r19.y, l(1.000000)
        log r19.y, r19.y
        mul r19.y, r19.y, cb5[r23.w + 6].w
        exp r19.y, r19.y
        mul r13.x, r19.y, r20.y
      endif
      dp3 r19.y, r26.xyzx, -r24.xyzx
      add r19.y, r19.y, -cb5[r12.w + 6].z
      mul_sat r19.y, r19.y, cb5[r12.w + 6].w
      mul r19.y, r19.y, r19.y
      movc r19.y, r21.w, l(1.000000), r19.y
      mul r13.x, r13.x, r19.y
      not r19.y, r22.w
      ige r20.y, r20.w, l(0)
      and r19.y, r19.y, r20.y
      if_nz r19.y
        if_z r21.w
          ishl r19.y, r20.w, l(2)
          mul r24.xyz, r1.yyyy, cb7[r19.y + 33].xywx
          mad r24.xyz, cb7[r19.y + 32].xywx, r1.xxxx, r24.xyzx
          mad r24.xyz, cb7[r19.y + 34].xywx, r1.zzzz, r24.xyzx
          add r24.xyz, r24.xyzx, cb7[r19.y + 35].xywx
          div_sat r24.xy, r24.xyxx, r24.zzzz
          mad r24.xy, r24.xyxx, cb7[r20.w + 0].zwzz, cb7[r20.w + 0].xyxx
        else
          ishl r19.y, r20.w, l(2)
          dp3 r29.x, -r25.xyzx, cb7[r19.y + 32].xyzx
          dp3 r29.y, -r25.xyzx, cb7[r19.y + 33].xyzx
          dp3 r29.z, -r25.xyzx, cb7[r19.y + 34].xyzx
          lt r19.y, |r29.x|, |r29.y|
          and r19.y, r19.y, l(1)
          dp2 r20.y, |r29.xyxx|, icb[r19.y + 0].xyxx
          lt r20.y, r20.y, |r29.z|
          movc r19.y, r20.y, l(2), r19.y
          dp3 r20.y, r29.xyzx, icb[r19.y + 0].xyzx
          lt r20.y, r20.y, l(0.000000)
          bfi r19.y, l(31), l(1), r19.y, r20.y
          ushr r20.y, r19.y, l(1)
          dp3 r20.y, r29.xyzx, icb[r20.y + 0].xyzx
          div r23.z, l(0.000244140625), cb7[r20.w + 0].w
          add r23.z, -r23.z, l(0.500000)
          utof r24.z, r19.y
          ult r24.w, r19.y, l(2)
          and r24.w, r24.w, l(2)
          dp2 r24.w, r29.xzxx, icb[r24.w + 0].xzxx
          mul r24.w, r24.w, icb[r19.y + 4].z
          div r24.w, r24.w, |r20.y|
          mad r24.z, r24.w, r23.z, r24.z
          add r24.z, r24.z, l(0.500000)
          mul_sat r25.x, r24.z, l(0.166666672)
          iadd r24.z, l(-1), icb[r19.y + 4].y
          dp2 r24.z, r29.yzyy, icb[r24.z + 0].xyxx
          mul r19.y, r24.z, icb[r19.y + 4].w
          div r19.y, r19.y, |r20.y|
          mad_sat r25.y, -r19.y, r23.z, l(0.500000)
          mad r24.xy, r25.xyxx, cb7[r20.w + 0].zwzz, cb7[r20.w + 0].xyxx
        endif
        sample_l_indexable(texture2d)(float,float,float,float) r19.y, r24.xyxx, t23.yxzw, s1, l(0.000000)
        mul r13.x, r13.x, r19.y
      endif
      lt r19.y, l(0.000000), r13.x
      if_nz r19.y
        if_z r21.w
          ftoi r20.y, cb5[r23.y + 6].x
        else
          add r24.xyz, r1.xyzx, -cb5[r23.x + 6].xyzx
          lt r25.xyz, |r24.yzzy|, |r24.xxyx|
          and r20.w, r25.y, r25.x
          lt r24.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r24.xyzx
          ushr r21.w, cb5[r12.w + 6].w, l(24)
          ubfe r25.xy, l(8, 8, 0, 0), l(16, 8, 0, 0), cb5[r12.w + 6].wwww
          movc r21.w, r24.x, r21.w, r25.x
          and r23.z, l(255), cb5[r12.w + 6].w
          movc r23.z, r24.y, r25.y, r23.z
          ubfe r24.x, l(8), l(8), cb5[r23.y + 6].x
          and r24.y, l(255), cb5[r23.y + 6].x
          movc r24.x, r24.z, r24.x, r24.y
          movc r23.z, r25.z, r23.z, r24.x
          movc r20.w, r20.w, r21.w, r23.z
          ilt r21.w, r20.w, l(80)
          movc r20.y, r21.w, r20.w, l(-1)
        endif
        mad r24.xyz, r26.xyzx, cb6[r20.y + 288].xxxx, r1.xyzx
        mul r20.w, l(5.000000), cb6[r20.y + 288].y
        mad r24.xyz, r6.xyzx, r20.wwww, r24.xyzx
        ishl r20.w, r20.y, l(2)
        mul r25.xyzw, r24.yyyy, cb6[r20.w + 65].xyzw
        mad r25.xyzw, cb6[r20.w + 64].xyzw, r24.xxxx, r25.xyzw
        mad r24.xyzw, cb6[r20.w + 66].xyzw, r24.zzzz, r25.xyzw
        add r24.xyzw, r24.xyzw, cb6[r20.w + 67].xyzw
        div r24.xyz, r24.xyzx, r24.wwww
        ge r25.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r24.xyzx
        ge r29.xyz, r24.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
        add r30.xy, -cb6[r20.y + 344].xyxx, cb6[r20.y + 344].zwzz
        mad r24.xy, r24.xyxx, r30.xyxx, cb6[r20.y + 344].xyxx
        mad r30.xy, r24.xyxx, cb6[400].zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
        round_ni r30.xy, r30.xyxx
        mad r24.xy, r24.xyxx, cb6[400].zwzz, -r30.xyxx
        add r31.xyzw, r24.xxyy, l(0.500000, 1.000000, 0.500000, 1.000000)
        mul r32.xyzw, r31.xxzz, r31.xxzz
        add r30.zw, -r24.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
        min r31.xz, r24.xxyx, l(0.000000, 0.000000, 0.000000, 0.000000)
        max r33.xy, r24.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
        mul r34.xy, r30.zwzz, l(0.160000, 0.160000, 0.000000, 0.000000)
        mad r33.xy, -r33.xyxx, r33.xyxx, r31.ywyy
        add r33.xy, r33.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
        mul r33.xy, r33.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
        mul r32.xz, r32.xxzx, l(0.080000, 0.000000, 0.080000, 0.000000)
        mad r24.xy, r32.ywyy, l(0.500000, 0.500000, 0.000000, 0.000000), -r24.xyxx
        mul r35.xy, r24.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
        mad r24.xy, -r31.xzxx, r31.xzxx, r30.zwzz
        add r24.xy, r24.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
        mul r36.xy, r24.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
        mul r24.xy, r31.ywyy, l(0.160000, 0.160000, 0.000000, 0.000000)
        mov r35.z, r36.x
        mov r35.w, r24.x
        mov r34.z, r33.x
        mov r34.w, r32.x
        add r31.xyzw, r34.zwxz, r35.zwxz
        mov r36.z, r35.y
        mov r36.w, r24.y
        mov r33.z, r34.y
        mov r33.w, r32.z
        add r24.xyw, r33.zyzw, r36.zyzw
        div r32.xyz, r34.xzwx, r31.zwyz
        add r32.xyz, r32.xyzx, l(-2.500000, -0.500000, 1.500000, 0.000000)
        mul r32.xyz, r32.xyzx, cb6[400].xxxx
        div r33.xyz, r33.zywz, r24.xywx
        add r33.xyz, r33.xyzx, l(-2.500000, -0.500000, 1.500000, 0.000000)
        mul r33.xyw, r33.xyxz, cb6[400].yyyy
        mul r34.xyzw, r24.xxxy, r31.zwyz
        mov r32.w, r33.x
        mad r35.xyzw, r30.xyxy, cb6[400].xyxy, r32.xwyw
        sample_c_lz_indexable(texture2d)(float,float,float,float) r20.w, r35.xyxx, t11.xxxx, s4, r24.z
        sample_c_lz_indexable(texture2d)(float,float,float,float) r21.w, r35.zwzz, t11.xxxx, s4, r24.z
        mul r21.w, r21.w, r34.y
        mad r20.w, r34.x, r20.w, r21.w
        mad r30.zw, r30.xxxy, cb6[400].xxxy, r32.zzzw
        sample_c_lz_indexable(texture2d)(float,float,float,float) r21.w, r30.zwzz, t11.xxxx, s4, r24.z
        mad r20.w, r34.z, r21.w, r20.w
        mov r33.z, r32.x
        mad r35.xyzw, r30.xyxy, cb6[400].xyxy, r33.zyzw
        sample_c_lz_indexable(texture2d)(float,float,float,float) r21.w, r35.xyxx, t11.xxxx, s4, r24.z
        mad r20.w, r34.w, r21.w, r20.w
        mul r34.xyzw, r24.yyww, r31.xyzw
        mov r33.xz, r32.yyzy
        mad r32.xyzw, r30.xyxy, cb6[400].xyxy, r33.xyzy
        sample_c_lz_indexable(texture2d)(float,float,float,float) r21.w, r32.xyxx, t11.xxxx, s4, r24.z
        mad r20.w, r34.x, r21.w, r20.w
        sample_c_lz_indexable(texture2d)(float,float,float,float) r21.w, r32.zwzz, t11.xxxx, s4, r24.z
        mad r20.w, r34.y, r21.w, r20.w
        sample_c_lz_indexable(texture2d)(float,float,float,float) r21.w, r35.zwzz, t11.xxxx, s4, r24.z
        mad r20.w, r34.z, r21.w, r20.w
        ige r21.w, r20.y, l(0)
        or r25.xyz, r25.xyzx, r29.xyzx
        or r23.z, r25.y, r25.x
        or r23.z, r25.z, r23.z
        and r24.x, r24.z, l(0x7fffffff)
        ult r24.x, l(0x7f800000), r24.x
        or r23.z, r23.z, r24.x
        mad r25.xyzw, r30.xyxy, cb6[400].xyxy, r33.xwzw
        sample_c_lz_indexable(texture2d)(float,float,float,float) r24.x, r25.xyxx, t11.xxxx, s4, r24.z
        mad r20.w, r34.w, r24.x, r20.w
        mul r24.x, r24.w, r31.y
        sample_c_lz_indexable(texture2d)(float,float,float,float) r24.y, r25.zwzz, t11.xxxx, s4, r24.z
        mad r20.w, r24.x, r24.y, r20.w
        add r20.w, r20.w, l(-1.000000)
        mad r20.y, cb6[r20.y + 288].w, r20.w, l(1.000000)
        movc r20.y, r23.z, l(1.000000), r20.y
        movc r20.y, r21.w, r20.y, l(1.000000)
      else
        mov r20.y, l(1.000000)
      endif
      if_nz r22.w
        dp3 r20.w, r15.xyzx, r27.xyzx
        mul_sat r21.w, r19.z, cb5[r12.w + 6].z
        mad r21.w, r21.w, l(0.500000), r3.w
        min r21.w, r21.w, l(1.000000)
        div r21.w, r3.w, r21.w
        mad r24.xyz, r15.xyzx, r20.wwww, -r27.xyzx
        dp3 r22.w, r28.xyzx, r24.xyzx
        mul r20.w, r20.w, r20.w
        mad r20.w, cb5[r12.w + 6].z, cb5[r12.w + 6].z, -r20.w
        div_sat r20.w, r22.w, r20.w
        mad r24.xyz, r27.xyzx, r20.wwww, r28.xyzx
        dp3 r20.w, r24.xyzx, r24.xyzx
        rsq r20.w, r20.w
        mul r26.xyz, r20.wwww, r24.xyzx
      else
        mov r21.w, l(1.000000)
      endif
      if_nz r19.y
        mul_sat r19.y, r19.z, cb5[r16.w + 6].y
        mad r24.xyz, r3.xyzx, r2.wwww, r26.xyzx
        dp3 r19.z, r24.xyzx, r24.xyzx
        max r19.z, r19.z, l(0.0000610351562)
        rsq r19.z, r19.z
        mul r24.xyz, r19.zzzz, r24.xyzx
        dp3_sat r19.z, r6.xyzx, r24.xyzx
        dp3_sat r20.w, r5.xyzx, r24.xyzx
        lt r22.w, l(0.000000), r19.y
        mul r19.y, r19.y, r19.y
        mad r23.z, r20.w, l(3.600000), l(0.400000)
        div r19.y, r19.y, r23.z
        mad r19.y, r11.w, r11.w, r19.y
        min r19.y, r19.y, l(1.000000)
        movc r19.y, r22.w, r19.y, r3.w
        mul r19.y, r19.y, r19.y
        mad r22.w, r19.z, r19.y, -r19.z
        mad r19.z, r22.w, r19.z, l(1.000000)
        add r20.w, -r20.w, l(1.000000)
        mul r22.w, r20.w, r20.w
        mul r22.w, r22.w, r22.w
        mul r23.z, r20.w, r22.w
        mad r20.w, -r22.w, r20.w, l(1.000000)
        mad r24.xyz, r7.xyzx, r20.wwww, r23.zzzz
        mul r19.z, r19.z, r19.z
        div r19.z, r19.y, r19.z
        mul r19.z, r21.w, r19.z
        mad r20.w, -r11.x, r19.y, r11.x
        mad r20.w, r20.w, r11.x, r19.y
        sqrt r20.w, r20.w
        mad r21.w, -r20.x, r19.y, r20.x
        mad r19.y, r21.w, r20.x, r19.y
        sqrt r19.y, r19.y
        mul r19.y, r11.x, r19.y
        mad r19.y, r20.x, r20.w, r19.y
        add r19.y, r19.y, l(0.000100)
        div r19.y, l(0.500000), r19.y
        mul r19.y, r19.y, r19.z
        mul r24.xyz, r19.yyyy, r24.xyzx
        min r24.xyz, r24.xyzx, l(2048.000000, 2048.000000, 2048.000000, 0.000000)
        mad r19.yz, r20.xxzx, l(0.000000, 0.968750, 0.968750, 0.000000), l(0.000000, 0.015625, 0.015625, 0.000000)
        sample_l_indexable(texture2d)(float,float,float,float) r19.y, r19.yzyy, t15.yxzw, s1, l(0.000000)
        mul r19.y, r5.w, r19.y
        mul r19.y, r0.z, r19.y
        div r19.y, r19.y, r4.w
        mul r25.xyz, r17.xyzx, r19.yyyy
        div r25.xyz, r25.xyzx, r18.xyzx
        add r24.xyz, r24.xyzx, r25.xyzx
        mul r24.xyz, r24.xyzx, cb5[r16.w + 6].zzzz
        max r24.xyz, r24.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
        min r24.xyz, r24.xyzx, l(1000.000000, 1000.000000, 1000.000000, 0.000000)
        mul r25.xyz, r9.xywx, r20.xxxx
        mad r24.xyz, r24.xyzx, r20.xxxx, r25.xyzx
        mul r25.xyz, r13.xxxx, cb5[r19.x + 6].xyzx
        mul r20.xyw, r20.yyyy, r25.xyxz
        mul r20.xyw, r17.wwww, r20.xyxw
        mul r20.xyw, r20.xyxw, r24.xyxz
      else
        mov r20.xyw, l(0,0,0,0)
      endif
    else
      if_z r18.w
        mad r13.x, cb5[r12.w + 6].y, l(0.500000), l(0.500000)
        add r24.x, r13.x, -|cb5[r12.w + 6].x|
        add r24.y, -r24.x, cb5[r12.w + 6].y
        add r13.x, -|r24.x|, l(1.000000)
        add r13.x, -|r24.y|, r13.x
        max r13.x, r13.x, l(0.000488281250)
        ge r17.w, cb5[r12.w + 6].x, l(0.000000)
        movc r24.z, r17.w, r13.x, -r13.x
        dp3 r13.x, r24.xyzx, r24.xyzx
        rsq r13.x, r13.x
        mul r24.xyz, r13.xxxx, r24.xyzx
        add r25.xyz, -r1.xyzx, cb5[r23.x + 6].xyzx
        dp3 r13.x, r25.xyzx, r25.xyzx
        rsq r17.w, r13.x
        mul r26.xyz, r17.wwww, r25.xyzx
        ftoi r16.w, cb5[r16.w + 6].w
        mul r27.xyz, r24.xyzx, cb5[r12.w + 6].zzzz
        mad r28.xyz, -r27.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r25.xyzx
        mad r27.xyz, r27.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r25.xyzx
        ftou r17.w, cb5[r19.x + 6].w
        and r17.w, r17.w, l(1)
        ieq r18.w, r17.w, l(0)
        not r18.w, r18.w
        lt r19.x, l(0.000000), cb5[r12.w + 6].z
        and r18.w, r18.w, r19.x
        dp3 r19.x, r28.xyzx, r28.xyzx
        dp3 r19.y, r27.xyzx, r27.xyzx
        sqrt r19.xy, r19.xyxx
        dp3 r19.z, r28.xyzx, r27.xyzx
        mad r19.x, r19.x, r19.y, r19.z
        mad r19.x, r19.x, l(0.500000), l(1.000000)
        div r19.x, l(1.000000, 1.000000, 1.000000, 1.000000), r19.x
        movc r19.x, r18.w, r19.x, l(1.000000)
        lt r19.y, cb5[r23.w + 6].w, l(0.000000)
        if_nz r19.y
          mul r19.y, cb5[r23.x + 6].w, cb5[r23.x + 6].w
          mul r19.y, r13.x, r19.y
          mad r19.y, -r19.y, r19.y, l(1.000000)
          max r19.y, r19.y, l(0.000000)
          add r13.x, r13.x, l(1.000000)
          div r13.x, l(1.000000, 1.000000, 1.000000, 1.000000), r13.x
          and r19.z, r18.w, l(0x3f800000)
          add r21.w, -r13.x, r19.x
          mad r13.x, r19.z, r21.w, r13.x
          mul r19.y, r19.y, r19.y
          mul r13.x, r13.x, r19.y
        else
          mul r27.xyz, r25.xyzx, cb5[r23.x + 6].wwww
          dp3 r19.y, r27.xyzx, r27.xyzx
          min r19.y, r19.y, l(1.000000)
          add r19.y, -r19.y, l(1.000000)
          log r19.y, r19.y
          mul r19.y, r19.y, cb5[r23.w + 6].w
          exp r19.y, r19.y
          mul r13.x, r19.y, r19.x
        endif
        dp3 r19.x, r26.xyzx, -r24.xyzx
        add r19.x, r19.x, -cb5[r12.w + 6].z
        mul_sat r19.x, r19.x, cb5[r12.w + 6].w
        mul r19.x, r19.x, r19.x
        movc r19.x, r17.w, l(1.000000), r19.x
        mul r13.x, r13.x, r19.x
        not r18.w, r18.w
        ige r19.x, r16.w, l(0)
        and r18.w, r18.w, r19.x
        if_nz r18.w
          if_z r17.w
            ishl r18.w, r16.w, l(2)
            mul r19.xyz, r1.yyyy, cb7[r18.w + 33].xywx
            mad r19.xyz, cb7[r18.w + 32].xywx, r1.xxxx, r19.xyzx
            mad r19.xyz, cb7[r18.w + 34].xywx, r1.zzzz, r19.xyzx
            add r19.xyz, r19.xyzx, cb7[r18.w + 35].xywx
            div_sat r19.xy, r19.xyxx, r19.zzzz
            mad r19.xy, r19.xyxx, cb7[r16.w + 0].zwzz, cb7[r16.w + 0].xyxx
          else
            ishl r18.w, r16.w, l(2)
            dp3 r24.x, -r25.xyzx, cb7[r18.w + 32].xyzx
            dp3 r24.y, -r25.xyzx, cb7[r18.w + 33].xyzx
            dp3 r24.z, -r25.xyzx, cb7[r18.w + 34].xyzx
            lt r18.w, |r24.x|, |r24.y|
            and r18.w, r18.w, l(1)
            dp2 r19.z, |r24.xyxx|, icb[r18.w + 0].xyxx
            lt r19.z, r19.z, |r24.z|
            movc r18.w, r19.z, l(2), r18.w
            dp3 r19.z, r24.xyzx, icb[r18.w + 0].xyzx
            lt r19.z, r19.z, l(0.000000)
            bfi r18.w, l(31), l(1), r18.w, r19.z
            ushr r19.z, r18.w, l(1)
            dp3 r19.z, r24.xyzx, icb[r19.z + 0].xyzx
            div r21.w, l(0.000244140625), cb7[r16.w + 0].w
            add r21.w, -r21.w, l(0.500000)
            utof r22.w, r18.w
            ult r23.z, r18.w, l(2)
            and r23.z, r23.z, l(2)
            dp2 r23.z, r24.xzxx, icb[r23.z + 0].xzxx
            mul r23.z, r23.z, icb[r18.w + 4].z
            div r23.z, r23.z, |r19.z|
            mad r22.w, r23.z, r21.w, r22.w
            add r22.w, r22.w, l(0.500000)
            mul_sat r25.x, r22.w, l(0.166666672)
            iadd r22.w, l(-1), icb[r18.w + 4].y
            dp2 r22.w, r24.yzyy, icb[r22.w + 0].xyxx
            mul r18.w, r22.w, icb[r18.w + 4].w
            div r18.w, r18.w, |r19.z|
            mad_sat r25.y, -r18.w, r21.w, l(0.500000)
            mad r19.xy, r25.xyxx, cb7[r16.w + 0].zwzz, cb7[r16.w + 0].xyxx
          endif
          sample_l_indexable(texture2d)(float,float,float,float) r16.w, r19.xyxx, t23.yzwx, s1, l(0.000000)
          mul r13.x, r13.x, r16.w
        endif
        lt r13.x, l(0.000000), r13.x
        if_nz r13.x
          if_z r17.w
            ftoi r13.x, cb5[r23.y + 6].x
          else
            add r19.xyz, r1.xyzx, -cb5[r23.x + 6].xyzx
            lt r23.xzw, |r19.yyzz|, |r19.xxxy|
            and r16.w, r23.z, r23.x
            lt r19.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r19.xyzx
            ushr r17.w, cb5[r12.w + 6].w, l(24)
            ubfe r23.xz, l(8, 0, 8, 0), l(16, 0, 8, 0), cb5[r12.w + 6].wwww
            movc r17.w, r19.x, r17.w, r23.x
            and r12.w, l(255), cb5[r12.w + 6].w
            movc r12.w, r19.y, r23.z, r12.w
            ubfe r18.w, l(8), l(8), cb5[r23.y + 6].x
            and r19.x, l(255), cb5[r23.y + 6].x
            movc r18.w, r19.z, r18.w, r19.x
            movc r12.w, r23.w, r12.w, r18.w
            movc r12.w, r16.w, r17.w, r12.w
            ilt r16.w, r12.w, l(80)
            movc r13.x, r16.w, r12.w, l(-1)
          endif
          mad r19.xyz, r26.xyzx, cb6[r13.x + 288].xxxx, r1.xyzx
          mul r12.w, l(5.000000), cb6[r13.x + 288].y
          mad r19.xyz, r6.xyzx, r12.wwww, r19.xyzx
          ishl r12.w, r13.x, l(2)
          mul r23.xyzw, r19.yyyy, cb6[r12.w + 65].xyzw
          mad r23.xyzw, cb6[r12.w + 64].xyzw, r19.xxxx, r23.xyzw
          mad r23.xyzw, cb6[r12.w + 66].xyzw, r19.zzzz, r23.xyzw
          add r23.xyzw, r23.xyzw, cb6[r12.w + 67].xyzw
          div r19.xyz, r23.xyzx, r23.wwww
          ge r23.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r19.xyzx
          ge r24.xyz, r19.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
          add r25.xy, -cb6[r13.x + 344].xyxx, cb6[r13.x + 344].zwzz
          mad r19.xy, r19.xyxx, r25.xyxx, cb6[r13.x + 344].xyxx
          mad r25.xy, r19.xyxx, cb6[400].zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
          round_ni r25.xy, r25.xyxx
          mad r19.xy, r19.xyxx, cb6[400].zwzz, -r25.xyxx
          add r26.xyzw, r19.xxyy, l(0.500000, 1.000000, 0.500000, 1.000000)
          mul r27.xyzw, r26.xxzz, r26.xxzz
          add r25.zw, -r19.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
          min r26.xz, r19.xxyx, l(0.000000, 0.000000, 0.000000, 0.000000)
          max r28.xy, r19.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
          mul r29.xy, r25.zwzz, l(0.160000, 0.160000, 0.000000, 0.000000)
          mad r28.xy, -r28.xyxx, r28.xyxx, r26.ywyy
          add r28.xy, r28.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
          mul r28.xy, r28.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
          mul r27.xz, r27.xxzx, l(0.080000, 0.000000, 0.080000, 0.000000)
          mad r19.xy, r27.ywyy, l(0.500000, 0.500000, 0.000000, 0.000000), -r19.xyxx
          mul r30.xy, r19.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
          mad r19.xy, -r26.xzxx, r26.xzxx, r25.zwzz
          add r19.xy, r19.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
          mul r31.xy, r19.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
          mul r19.xy, r26.ywyy, l(0.160000, 0.160000, 0.000000, 0.000000)
          mov r30.z, r31.x
          mov r30.w, r19.x
          mov r29.z, r28.x
          mov r29.w, r27.x
          add r26.xyzw, r29.zwxz, r30.zwxz
          mov r31.z, r30.y
          mov r31.w, r19.y
          mov r28.z, r29.y
          mov r28.w, r27.z
          add r27.xyz, r28.zywz, r31.zywz
          div r29.xyz, r29.xzwx, r26.zwyz
          add r29.xyz, r29.xyzx, l(-2.500000, -0.500000, 1.500000, 0.000000)
          mul r29.xyz, r29.xyzx, cb6[400].xxxx
          div r28.xyz, r28.zywz, r27.xyzx
          add r28.xyz, r28.xyzx, l(-2.500000, -0.500000, 1.500000, 0.000000)
          mul r28.xyw, r28.xyxz, cb6[400].yyyy
          mul r30.xyzw, r26.zwyz, r27.xxxy
          mov r29.w, r28.x
          mad r31.xyzw, r25.xyxy, cb6[400].xyxy, r29.xwyw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r12.w, r31.xyxx, t11.xxxx, s4, r19.z
          sample_c_lz_indexable(texture2d)(float,float,float,float) r16.w, r31.zwzz, t11.xxxx, s4, r19.z
          mul r16.w, r16.w, r30.y
          mad r12.w, r30.x, r12.w, r16.w
          mad r19.xy, r25.xyxx, cb6[400].xyxx, r29.zwzz
          sample_c_lz_indexable(texture2d)(float,float,float,float) r16.w, r19.xyxx, t11.xxxx, s4, r19.z
          mad r12.w, r30.z, r16.w, r12.w
          mov r28.z, r29.x
          mad r31.xyzw, r25.xyxy, cb6[400].xyxy, r28.zyzw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r16.w, r31.xyxx, t11.xxxx, s4, r19.z
          mad r12.w, r30.w, r16.w, r12.w
          mul r30.xyzw, r26.xyzw, r27.yyzz
          mov r28.xz, r29.yyzy
          mad r29.xyzw, r25.xyxy, cb6[400].xyxy, r28.xyzy
          sample_c_lz_indexable(texture2d)(float,float,float,float) r16.w, r29.xyxx, t11.xxxx, s4, r19.z
          mad r12.w, r30.x, r16.w, r12.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r16.w, r29.zwzz, t11.xxxx, s4, r19.z
          mad r12.w, r30.y, r16.w, r12.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r16.w, r31.zwzz, t11.xxxx, s4, r19.z
          mad r12.w, r30.z, r16.w, r12.w
          ige r16.w, r13.x, l(0)
          or r23.xyz, r23.xyzx, r24.xyzx
          or r17.w, r23.y, r23.x
          or r17.w, r23.z, r17.w
          and r18.w, r19.z, l(0x7fffffff)
          ult r18.w, l(0x7f800000), r18.w
          or r17.w, r17.w, r18.w
          mad r23.xyzw, r25.xyxy, cb6[400].xyxy, r28.xwzw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r18.w, r23.xyxx, t11.xxxx, s4, r19.z
          mad r12.w, r30.w, r18.w, r12.w
          mul r18.w, r26.y, r27.z
          sample_c_lz_indexable(texture2d)(float,float,float,float) r19.x, r23.zwzz, t11.xxxx, s4, r19.z
          mad r12.w, r18.w, r19.x, r12.w
          add r12.w, r12.w, l(-1.000000)
          mad r12.w, cb6[r13.x + 288].w, r12.w, l(1.000000)
          movc r12.w, r17.w, l(1.000000), r12.w
          movc r12.w, r16.w, r12.w, l(1.000000)
        else
          mov r12.w, l(1.000000)
        endif
      else
        mov r12.w, l(1.000000)
      endif
      mul r11.y, r11.y, r12.w
      mov r20.xyw, l(0,0,0,0)
    endif
    add r22.xyz, r20.xywx, r22.xyzx
    mov r11.z, r15.w
  endloop
  mov r6.w, r11.y
  add r21.xyz, r21.xyzx, r22.xyzx
  iadd r7.w, r7.w, l(1)
endloop
dp3 r0.x, r2.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
add r1.xzw, -r0.xxxx, r2.xxyz
mad r0.xyz, cb0[184].wwww, r1.xzwx, r0.xxxx
mad r1.xzw, r21.xxyz, r6.wwww, r16.xxyz
mul r2.xyz, cb2[20].zzzz, cb2[21].xyzx
add r2.w, -r10.w, l(1.000000)
add r3.x, l(1.000000), -cb2[20].y
max r3.x, r3.x, l(0.010000)
div_sat r2.w, r2.w, r3.x
mad r2.xyz, r8.xyzx, r2.xyzx, -r1.xzwx
mad r1.xzw, r2.wwww, r2.xxyz, r1.xxzw
mad r0.xyz, r0.xyzx, cb0[184].xyzx, r1.xzwx
mad r1.x, r1.y, cb0[156].w, cb0[157].w
mad r1.z, r0.w, cb0[154].w, -cb0[153].w
max r1.xz, r1.xxzx, l(0.010000, 0.000000, 0.000000, 0.000000)
mul r1.w, r1.x, l(-1.442695)
exp r1.w, r1.w
add r1.w, -r1.w, l(1.000000)
div r1.x, r1.w, r1.x
mad r1.w, r1.y, cb0[156].w, cb0[158].w
mul r1.w, r1.w, l(1.442695)
exp r1.w, r1.w
mul r1.x, r1.w, r1.x
mul r1.x, r1.x, -r1.z
mul r1.xzw, r1.xxxx, cb0[155].xxyz
mul r1.xzw, r1.xxzw, l(1.442695, 0.000000, 1.442695, 1.442695)
exp r1.xzw, r1.xxzw
dp3 r2.x, -r5.xyzx, cb0[154].xyzx
mad r2.y, cb0[155].w, cb0[155].w, l(1.000000)
dp2 r2.z, r2.xxxx, cb0[155].wwww
add r2.y, -r2.z, r2.y
lt r2.z, l(0.000000), cb0[163].z
if_nz r2.z
  and r14.w, l(7), cb0[108].w
  imad r3.xyz, r14.xywx, l(0x0019660d, 0x0019660d, 0x0019660d, 0), l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)
  imad r2.z, r3.y, r3.z, r3.x
  imad r2.w, r3.z, r2.z, r3.y
  imad r3.x, r2.z, r2.w, r3.z
  imad r6.x, r2.w, r3.x, r2.z
  dp3 r2.z, -r5.xyzx, -r4.xyzx
  add r3.y, r1.y, -cb0[44].y
  lt r3.z, l(5.960464478E-08), r2.z
  div r2.z, l(1.000000, 1.000000, 1.000000, 1.000000), r2.z
  and r2.z, r2.z, r3.z
  mul r2.z, r2.z, cb0[163].w
  div r3.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
  mul r3.w, r2.z, r3.z
  mad r4.x, r3.w, r3.y, cb0[44].y
  mad r3.y, -r3.w, r3.y, r3.y
  mul r3.w, r3.y, cb0[159].z
  mul r3.y, r3.y, cb0[162].x
  max r3.yw, r3.yyyw, l(0.000000, -127.000000, 0.000000, -127.000000)
  add r4.y, r4.x, -cb0[159].x
  mul r4.y, r4.y, cb0[159].z
  max r4.y, r4.y, l(-127.000000)
  exp r4.y, -r4.y
  mul r4.y, r4.y, cb0[159].y
  lt r4.z, l(5.960464478E-08), |r3.w|
  exp r4.w, -r3.w
  add r4.w, -r4.w, l(1.000000)
  div r4.w, r4.w, r3.w
  mad r3.w, -r3.w, l(0.240226507), l(0.693147182)
  movc r3.w, r4.z, r4.w, r3.w
  add r4.x, r4.x, -cb0[162].z
  mul r4.x, r4.x, cb0[162].x
  max r4.x, r4.x, l(-127.000000)
  exp r4.x, -r4.x
  mul r4.x, r4.x, cb0[162].y
  lt r4.z, l(5.960464478E-08), |r3.y|
  exp r4.w, -r3.y
  add r4.w, -r4.w, l(1.000000)
  div r4.w, r4.w, r3.y
  mad r3.y, -r3.y, l(0.240226507), l(0.693147182)
  movc r3.y, r4.z, r4.w, r3.y
  mul r3.y, r3.y, r4.x
  mad r3.y, r4.y, r3.w, r3.y
  mad r2.z, -r2.z, r3.z, l(1.000000)
  mul r2.z, r0.w, r2.z
  mul r2.z, r2.z, r3.y
  exp r2.z, -r2.z
  min r2.z, r2.z, l(1.000000)
  max r2.z, r2.z, cb0[161].w
  mad_sat r3.yz, r0.wwww, cb0[160].yywy, cb0[160].xxzx
  add r2.z, r2.z, r3.y
  add r2.z, r3.z, r2.z
  min r2.z, r2.z, l(1.000000)
  imad r6.y, r3.x, r6.x, r2.w
  ushr r3.xy, r6.xyxx, l(16, 16, 0, 0)
  utof r3.xy, r3.xyxx
  mad r3.xy, r3.xyxx, l(0.0000305180438, 0.0000305180438, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  mad r3.xy, r3.xyxx, cb0[167].wwww, r13.zwzz
  mul r3.xy, r3.xyxx, cb0[165].xyxx
  mad r2.w, r14.z, cb0[164].x, cb0[164].y
  log r2.w, r2.w
  mul r2.w, r2.w, cb0[164].z
  div r3.z, r2.w, cb0[163].z
  sample_l_indexable(texture3d)(float,float,float,float) r3.xyzw, r3.xyzx, t22.xyzw, s1, l(0.000000)
  add r2.w, r14.z, -cb0[166].z
  mul_sat r2.w, r2.w, l(1000000.000000)
  add r3.xyzw, r3.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
  mad r3.xyzw, r2.wwww, r3.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
  add r2.w, -r2.z, l(1.000000)
  mul r4.xyz, r2.wwww, cb0[161].xyzx
  mad r3.xyz, r4.xyzx, r3.wwww, r3.xyzx
  mul r2.z, r2.z, r3.w
else
  add r1.y, r1.y, -cb0[44].y
  mul r2.w, r1.y, cb0[159].z
  max r2.w, r2.w, l(-127.000000)
  mul r1.y, r1.y, cb0[162].x
  max r1.y, r1.y, l(-127.000000)
  add r3.w, cb0[44].y, -cb0[159].x
  mul r3.w, r3.w, cb0[159].z
  max r3.w, r3.w, l(-127.000000)
  exp r3.w, -r3.w
  mul r3.w, r3.w, cb0[159].y
  lt r4.x, l(5.960464478E-08), |r2.w|
  exp r4.y, -r2.w
  add r4.y, -r4.y, l(1.000000)
  div r4.y, r4.y, r2.w
  mad r2.w, -r2.w, l(0.240226507), l(0.693147182)
  movc r2.w, r4.x, r4.y, r2.w
  add r4.x, cb0[44].y, -cb0[162].z
  mul r4.x, r4.x, cb0[162].x
  max r4.x, r4.x, l(-127.000000)
  exp r4.x, -r4.x
  mul r4.x, r4.x, cb0[162].y
  lt r4.y, l(5.960464478E-08), |r1.y|
  exp r4.z, -r1.y
  add r4.z, -r4.z, l(1.000000)
  div r4.z, r4.z, r1.y
  mad r1.y, -r1.y, l(0.240226507), l(0.693147182)
  movc r1.y, r4.y, r4.z, r1.y
  mul r1.y, r1.y, r4.x
  mad r1.y, r3.w, r2.w, r1.y
  mul r1.y, r0.w, r1.y
  exp r1.y, -r1.y
  min r1.y, r1.y, l(1.000000)
  max r1.y, r1.y, cb0[161].w
  mad_sat r4.xy, r0.wwww, cb0[160].ywyy, cb0[160].xzxx
  add r0.w, r1.y, r4.x
  add r0.w, r4.y, r0.w
  min r2.z, r0.w, l(1.000000)
  add r0.w, -r2.z, l(1.000000)
  mul r3.xyz, r0.wwww, cb0[161].xyzx
endif
mul r4.xyz, r1.xzwx, r2.zzzz
mad r0.w, r2.x, r2.x, l(1.000000)
mul r0.w, r0.w, l(0.0596831031)
mad r5.xyz, cb0[156].xyzx, r0.wwww, cb0[158].xyzx
mad r0.w, -cb0[155].w, cb0[155].w, l(1.000000)
mul r1.y, r2.y, l(12.566371)
sqrt r2.x, r2.y
mul r1.y, r1.y, r2.x
max r1.y, r1.y, l(0.001000)
div r0.w, r0.w, r1.y
mad_sat r2.xyw, cb0[157].xyxz, r0.wwww, r5.xyxz
mul r2.xyw, r2.xyxw, l(255.000000, 255.000000, 0.000000, 255.000000)
add r1.xyz, -r1.xzwx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r1.xyz, r1.xyzx, r2.xywx
mad r1.xyz, r1.xyzx, r2.zzzz, r3.xyzx
mad r10.xyz, r0.xyzx, r4.xyzx, r1.xyzx
mul r0.xy, r12.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000)
sqrt r0.xy, |r0.xyxx|
sqrt r0.xy, r0.xyxx
mov r12.z, -r12.y
lt r0.zw, l(0.000000, 0.000000, 0.000000, 0.000000), r12.xxxz
lt r1.xy, r12.xzxx, l(0.000000, 0.000000, 0.000000, 0.000000)
iadd r0.zw, -r0.zzzw, r1.xxxy
itof r0.zw, r0.zzzw
mul r0.xy, r0.zwzz, r0.xyxx
mad r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
ishl r0.z, v7.x, l(4)
max r0.z, cb1[r0.z + 4].z, cb1[r0.z + 4].y
add r0.z, r0.z, l(-0.100000024)
lt r0.w, l(0.000000), r0.z
lt r0.z, r0.z, l(0.000000)
iadd r0.z, -r0.w, r0.z
itof r0.z, r0.z
mov_sat r0.z, r0.z
add r1.xy, -r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mad r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
min o1.xy, r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
dp3 r0.x, r10.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
mul r0.x, r10.w, r0.x
max r0.x, r10.w, r0.x
mul_sat r0.x, r0.x, l(10.000000)
lt r0.x, l(0.500000), r0.x
and o1.z, r0.x, l(0x3f800000)
mov o0.xyzw, r10.xyzw
mov o1.w, l(0)
ret
// Approximately 0 instruction slots used
