//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.4.1 on Thu Jan 29 18:08:39 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy
// TEXCOORD                 0   xy          1     NONE   float   xy
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[235], immediateIndexed
dcl_constantbuffer CB1[259], dynamicIndexed
dcl_constantbuffer CB2[5], immediateIndexed
dcl_constantbuffer CB3[4], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_resource_structured t0, 4
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2darray (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture3d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture3d (float,float,float,float) t13
dcl_resource_texture3d (float,float,float,float) t14
dcl_resource_texture3d (float,float,float,float) t15
dcl_resource_texture3d (float,float,float,float) t16
dcl_resource_texture3d (float,float,float,float) t17
dcl_resource_texture3d (float,float,float,float) t18
dcl_resource_texture2d (float,float,float,float) t19
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture2d (float,float,float,float) t21
dcl_resource_texture2d (float,float,float,float) t22
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 25
ftou r0.xy, v0.xyxx
mov r0.z, l(0)
ld_indexable(texture2d)(float,float,float,float) r1.xyzw, r0.xyzz, t20.xyzw
ld_indexable(texture2d)(float,float,float,float) r2.xyzw, r0.xyzz, t21.xyzw
ld_indexable(texture2d)(float,float,float,float) r3.xyzw, r0.xyzz, t22.xyzw
mul r1.xyz, r1.xyzx, l(1023.000000, 1023.000000, 1023.000000, 0.000000)
ftou r1.xz, r1.xxzx
ubfe r4.x, l(7), l(3), r1.x
utof r4.x, r4.x
round_ne r1.y, r1.y
ftou r1.y, r1.y
mad r2.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r4.y, l(1.000000, 1.000000, 0.000000, 0.000000), |r2.xyxx|
add r5.y, -r4.y, l(1.000000)
lt r4.y, r5.y, l(0.000000)
ge r4.zw, r2.xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
add r6.xy, -|r2.yxyy|, l(1.000000, 1.000000, 0.000000, 0.000000)
movc r4.zw, r4.zzzw, l(0,0,1.000000,1.000000), l(0,0,-1.000000,-1.000000)
mul r4.zw, r4.zzzw, r6.xxxy
movc r5.xz, r4.yyyy, r4.zzwz, r2.xxyx
dp3 r2.x, r5.xyzx, r5.xyzx
rsq r2.x, r2.x
mul r5.xyz, r2.xxxx, r5.xyzx
and r2.x, r1.y, l(7)
utof r2.x, r2.x
mad r2.x, r2.x, l(0.107142866), l(0.500000)
utof r4.yz, r0.xxyx
mul r6.xy, v0.xyxx, cb0[82].zwzz
mad r6.zw, r6.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
add r7.xy, r4.yzyy, l(0.500000, 0.500000, 0.000000, 0.000000)
mul r7.xy, r7.xyxx, cb0[82].zwzz
sample_l_indexable(texture2d)(float,float,float,float) r2.y, r7.xyxx, t1.yxzw, s0, l(0.000000)
mul r7.xyzw, -r6.wwww, cb0[25].xyzw
mad r7.xyzw, cb0[24].xyzw, r6.zzzz, r7.xyzw
mad r7.xyzw, cb0[26].xyzw, r2.yyyy, r7.xyzw
add r7.xyzw, r7.xyzw, cb0[27].xyzw
div r7.xyz, r7.xyzx, r7.wwww
mul r2.y, r7.y, cb0[1].z
mad r2.y, cb0[0].z, r7.x, r2.y
mad r2.y, cb0[2].z, r7.z, r2.y
add r2.y, r2.y, cb0[3].z
eq r4.w, l(0.000000), cb0[86].w
add r8.xyz, -r7.xyzx, cb0[44].xyzx
mov r9.x, cb0[0].z
mov r9.y, cb0[1].z
mov r9.z, cb0[2].z
movc r8.xyz, r4.wwww, r8.xyzx, r9.xyzx
dp3 r4.w, r8.xyzx, r8.xyzx
max r6.z, r4.w, l(9.999999939E-09)
rsq r6.z, r6.z
mul r10.xyz, r6.zzzz, r8.xyzx
mul r4.w, r4.w, r6.z
lt r6.w, l(0.000488281250), cb0[234].x
if_nz r6.w
  sample_b_indexable(texture2d)(float,float,float,float) r6.w, v1.xyxx, t19.yzwx, s1, cb0[108].x
else
  mov r6.w, l(1.000000)
endif
add r6.w, -r6.w, l(1.000000)
mad_sat r8.w, r2.z, l(0.300000), l(0.250000)
mul r8.w, r8.w, cb0[222].x
mul r8.w, r6.w, r8.w
mad r8.w, r8.w, l(-0.750000), l(1.000000)
mul r3.xyz, r3.xyzx, r8.wwww
min r8.w, r2.z, l(0.300000)
mul r6.w, r6.w, cb0[222].x
mul r6.w, r6.w, l(0.500000)
add r8.w, -r2.z, r8.w
mad r11.z, r6.w, r8.w, r2.z
mul r2.zw, r2.xxxw, l(0.000000, 0.000000, 0.080000, 3.000000)
dp3 r6.w, r5.xyzx, r10.xyzx
max r8.w, r6.w, l(0.000000)
mad r12.xyzw, r11.zzzz, l(-1.000000, -0.027500, -0.572000, 0.022000), l(1.000000, 0.042500, 1.040000, -0.040000)
mul r9.w, r12.x, r12.x
mul r10.w, r8.w, l(-9.280000)
exp r10.w, r10.w
min r9.w, r9.w, r10.w
mad r9.w, r9.w, r12.x, r12.y
mad r12.xy, r9.wwww, l(-1.040000, 1.040000, 0.000000, 0.000000), r12.zwzz
ld_indexable(texture2d)(float,float,float,float) r12.z, r0.xyzz, t6.zwxy
lt r0.z, l(0.001000), r12.z
if_nz r0.z
  bfi r0.z, l(3), l(2), r1.x, l(0)
  mul r1.x, r1.w, l(3.000000)
  ftou r1.x, r1.x
  bfi r0.z, l(2), l(0), r1.x, r0.z
  utof r0.z, r0.z
  mul r1.x, r0.z, l(0.0322580636)
  ubfe r1.y, l(7), l(3), r1.y
  utof r1.y, r1.y
  mul r1.y, r1.y, l(0.00787401572)
  sample_l_indexable(texture2d)(float,float,float,float) r1.w, r6.xyxx, t9.yzwx, s1, l(0.000000)
  dp3 r9.w, -r10.xyzx, r5.xyzx
  add r9.w, r9.w, r9.w
  mad r13.xyz, r5.xyzx, -r9.wwww, -r10.xyzx
  dp3 r9.w, -cb2[0].xyzx, r13.xyzx
  mad r14.xyz, cb2[0].xyzx, r9.wwww, r13.xyzx
  lt r9.w, r9.w, cb2[4].z
  dp3 r10.w, r14.xyzx, r14.xyzx
  max r10.w, r10.w, l(0.0000610351562)
  rsq r10.w, r10.w
  mul r14.xyz, r10.wwww, r14.xyzx
  mul r14.xyz, r14.xyzx, cb2[4].yyyy
  mad r14.xyz, -cb2[0].xyzx, cb2[4].zzzz, r14.xyzx
  dp3 r10.w, r14.xyzx, r14.xyzx
  rsq r10.w, r10.w
  mul r14.xyz, r10.wwww, r14.xyzx
  movc r13.xyz, r9.wwww, r14.xyzx, r13.xyzx
  mad r8.xyz, r8.xyzx, r6.zzzz, r13.xyzx
  dp3 r6.z, r8.xyzx, r8.xyzx
  max r6.z, r6.z, l(0.0000610351562)
  rsq r6.z, r6.z
  mul r8.xyz, r6.zzzz, r8.xyzx
  dp3 r6.z, r5.xyzx, r13.xyzx
  mov_sat r11.x, r6.z
  dp3_sat r9.w, r5.xyzx, r8.xyzx
  dp3 r10.w, r10.xyzx, r13.xyzx
  min r11.y, r8.w, l(1.000000)
  mul r11.w, r11.z, r11.z
  mul r11.w, r11.w, r11.w
  mad r13.x, r9.w, r11.w, -r9.w
  mad r9.w, r13.x, r9.w, l(1.000000)
  dp3_sat r8.x, r10.xyzx, r8.xyzx
  add r8.x, -r8.x, l(1.000000)
  mul r8.y, r8.x, r8.x
  mul r8.y, r8.y, r8.y
  mul r8.z, r8.x, r8.y
  add r13.x, -r11.z, l(1.000000)
  mad r13.y, -r13.x, l(0.383026), l(-0.0761947036)
  mad r13.y, r13.x, r13.y, l(1.049970)
  mad r13.x, r13.x, r13.y, l(0.409255)
  min r13.x, r13.x, l(0.999000)
  add r13.y, -r13.x, l(1.000000)
  mad r2.x, -r2.x, l(0.080000), l(1.000000)
  mad r2.x, r2.x, l(0.0476190485), r2.z
  mov_sat r13.z, -r10.w
  mul r13.z, r13.z, r13.z
  mad r13.z, r13.z, l(-0.640000), l(1.000000)
  mul r13.z, r13.z, r13.z
  mad r8.x, -r8.y, r8.x, l(1.000000)
  mad r8.x, r2.z, r8.x, r8.z
  mul r8.y, r9.w, r9.w
  div r8.y, r11.w, r8.y
  mad r14.xy, -r11.yxyy, r11.wwww, r11.yxyy
  mad r14.xy, r14.xyxx, r11.yxyy, r11.wwww
  sqrt r14.xy, r14.xyxx
  mul r14.xy, r11.xyxx, r14.xyxx
  add r8.z, r14.y, r14.x
  add r8.z, r8.z, l(0.000100)
  div r8.z, l(0.500000), r8.z
  mul r8.y, r8.z, r8.y
  mul r8.x, r8.y, r8.x
  min r8.x, r8.x, l(2048.000000)
  mad r14.xyzw, r11.yzxz, l(0.968750, 0.968750, 0.968750, 0.968750), l(0.015625, 0.015625, 0.015625, 0.015625)
  sample_l_indexable(texture2d)(float,float,float,float) r8.y, r14.xyxx, t8.yxzw, s1, l(0.000000)
  sample_l_indexable(texture2d)(float,float,float,float) r8.z, r14.zwzz, t8.yzxw, s1, l(0.000000)
  mul r8.y, r8.z, r8.y
  mul r8.y, r13.x, r8.y
  div r8.y, r8.y, r13.y
  mul r8.z, r2.x, r2.x
  mul r8.y, r8.y, r8.z
  mad r2.x, -r2.x, r13.y, l(1.000000)
  div r2.x, r8.y, r2.x
  add r2.x, r2.x, r8.x
  add_sat r6.w, r6.w, l(0.200000)
  mov_sat r8.x, r10.w
  add r8.x, r8.x, l(0.500000)
  min r8.x, r8.x, l(1.000000)
  mul r8.y, r6.w, r8.x
  add_sat r8.z, r10.w, l(1.000000)
  mad r6.w, -r6.w, r8.x, l(1.000000)
  mad r6.w, r8.z, r6.w, r8.y
  mul r2.x, r2.x, r6.w
  mul r2.x, r1.y, r2.x
  mul r8.xyz, r1.yyyy, r3.xyzx
  ubfe r6.w, l(7), l(3), r1.z
  utof r6.w, r6.w
  mul r6.w, r6.w, l(0.00787401572)
  mul r2.x, r2.x, cb2[4].x
  max r2.x, r2.x, l(0.000000)
  min r2.x, r2.x, l(1000.000000)
  mul r2.x, r11.x, r2.x
  mad r8.xyz, r8.xyzx, r6.wwww, r2.xxxx
  max r2.x, r3.y, r3.x
  max r2.x, r3.z, r2.x
  max r2.x, r2.x, l(0.010000)
  div r13.xyw, r3.xyxz, r2.xxxx
  mul r2.x, r4.x, l(0.00393700786)
  mul r13.xyw, r2.xxxx, r13.xyxw
  add_sat r2.x, -r6.z, l(0.500000)
  ne r6.w, r13.z, l(0.360000)
  div r9.w, l(0.360000), r13.z
  movc r6.w, r6.w, r9.w, l(1.000000)
  mul r2.x, r2.x, r6.w
  mad_sat r0.z, r0.z, l(0.0322580636), r6.z
  add r0.z, -r11.x, r0.z
  mul r11.xyw, r0.zzzz, r3.xyxz
  mad r11.xyw, r13.xyxw, r2.xxxx, r11.xyxw
  mad r8.xyz, r11.xywx, r1.yyyy, r8.xyzx
  mul r8.xyz, r8.xyzx, cb2[1].xyzx
  mov r12.w, l(0.500000)
  sample_b_indexable(texture2d)(float,float,float,float) r11.xyw, r12.zwzz, t7.xywz, s1, cb0[108].x
  add r0.z, -r12.z, l(1.000000)
  mad r11.xyw, r8.xyxz, r11.xyxw, -r8.xyxz
  mad r8.xyz, r0.zzzz, r11.xywx, r8.xyzx
  max r0.z, r1.y, r1.w
  add r0.z, -r1.w, r0.z
  mad r0.z, r1.x, r0.z, r1.w
  mul r1.xyw, r0.zzzz, r8.xyxz
else
  mov r1.xyw, l(0,0,0,0)
endif
ne r6.zw, l(0.000000, 0.000000, 0.000000, 0.000000), cb0[112].xxxy
if_nz r6.z
  sample_b_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t4.yzxw, s0, cb0[108].x
  mad r0.z, r0.z, l(0.750000), l(0.250000)
  min r0.z, r3.w, r0.z
  add r2.x, r0.z, r8.w
  mad r6.z, r11.z, l(-16.000000), l(-1.000000)
  exp r6.z, r6.z
  log r2.x, |r2.x|
  mul r2.x, r2.x, r6.z
  exp r2.x, r2.x
  add r2.x, r0.z, r2.x
  add r2.x, r2.x, l(-1.000000)
  mov_sat r8.xyz, r2.xxxx
  mad r11.xyw, r3.xyxz, l(2.040400, 2.040400, 0.000000, 2.040400), l(-0.332400, -0.332400, 0.000000, -0.332400)
  mul r11.xyw, r0.zzzz, r11.xyxw
  mad r11.xyw, r3.xyxz, l(-4.795100, -4.795100, 0.000000, -4.795100), r11.xyxw
  add r11.xyw, r11.xyxw, l(0.641700, 0.641700, 0.000000, 0.641700)
  mul r11.xyw, r0.zzzz, r11.xyxw
  mad r11.xyw, r3.xyxz, l(2.755200, 2.755200, 0.000000, 2.755200), r11.xyxw
  add r11.xyw, r11.xyxw, l(0.690300, 0.690300, 0.000000, 0.690300)
  mul r11.xyw, r0.zzzz, r11.xyxw
  max r11.xyw, r0.zzzz, r11.xyxw
else
  mov r8.xyz, r3.wwww
  mov r11.xyw, r3.wwww
endif
mad r13.xyz, cb0[6].xzyx, -cb0[212].wwww, cb0[210].xzyx
add r13.xyz, r7.xzyx, -r13.xyzx
max r0.z, |r13.y|, |r13.x|
add r0.z, r0.z, l(-464.000000)
mul_sat r0.z, r0.z, l(0.031250)
add r2.x, |r13.z|, l(-208.000000)
mul_sat r2.x, r2.x, l(0.031250)
max r0.z, r0.z, r2.x
ne r2.x, l(0.000000), cb0[210].w
lt r3.w, r0.z, l(1.000000)
and r2.x, r2.x, r3.w
if_nz r2.x
  mad r13.xyz, cb0[6].xzyx, -cb0[212].yyyy, cb0[210].xzyx
  add r13.xyz, r7.xzyx, -r13.xyzx
  max r2.x, |r13.y|, |r13.x|
  add r2.x, r2.x, l(-29.000000)
  mul_sat r2.x, r2.x, l(0.500000)
  add r3.w, |r13.z|, l(-13.000000)
  mul_sat r3.w, r3.w, l(0.500000)
  max r2.x, r2.x, r3.w
  lt r3.w, r2.x, l(1.000000)
  if_nz r3.w
    mad r13.xyz, r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r14.xyz, r13.xyzx, cb0[211].xyzx
    round_ni r14.xyz, r14.xyzx
    mad r13.xyz, r13.xyzx, cb0[211].xyzx, -r14.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r14.xyw, r13.xyzx, t13.yzwx, s2, l(0.000000)
    add r3.w, -r2.x, l(1.000000)
    mul r6.z, l(0.500000), cb0[211].y
    mad r9.w, -cb0[211].y, l(0.500000), l(1.000000)
    max r6.z, r6.z, r13.y
    min r6.z, r9.w, r6.z
    mul r13.w, r6.z, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r15.xyzw, r13.xwzx, t14.xyzw, s1, l(0.000000)
    mad r6.z, r15.w, r3.w, r0.z
    add r16.xyz, r13.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r16.xyz, r16.xyzx, t14.xyzw, s1, l(0.000000)
    mad r16.xyz, r16.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r16.xyz, r14.yyyy, r16.xyzx
    mov r16.w, r14.y
    mul r16.xyzw, r3.wwww, r16.xyzw
    add r13.xyz, r13.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r13.xyz, r13.xyzx, t14.xyzw, s1, l(0.000000)
    mad r13.xyz, r13.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r13.xyz, r14.xxxx, r13.xyzx
    mov r13.w, r14.x
    mul r13.xyzw, r3.wwww, r13.xyzw
    mad r15.xyz, r15.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r14.xyz, r14.wwww, r15.xyzx
    mul r14.xyzw, r3.wwww, r14.xyzw
  else
    mov r16.xyzw, l(0,0,0,0)
    mov r13.xyzw, l(0,0,0,0)
    mov r14.xyzw, l(0,0,0,0)
    mov r6.z, r0.z
  endif
  mad r15.xyz, cb0[6].xzyx, -cb0[212].zzzz, cb0[210].xzyx
  add r15.xyz, r7.xzyx, -r15.xyzx
  max r3.w, |r15.y|, |r15.x|
  add r3.w, r3.w, l(-116.000000)
  mul_sat r3.w, r3.w, l(0.125000)
  add r9.w, |r15.z|, l(-52.000000)
  mul_sat r9.w, r9.w, l(0.125000)
  max r3.w, r3.w, r9.w
  lt r9.w, r3.w, l(1.000000)
  if_nz r9.w
    mad r15.xyz, r7.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r17.xyz, r15.xyzx, cb0[211].xyzx
    round_ni r17.xyz, r17.xyzx
    mad r15.xyz, r15.xyzx, cb0[211].xyzx, -r17.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r17.xyw, r15.xyzx, t15.yzwx, s2, l(0.000000)
    add r9.w, -r3.w, l(1.000000)
    mul r2.x, r2.x, r9.w
    mul r9.w, l(0.500000), cb0[211].y
    mad r10.w, -cb0[211].y, l(0.500000), l(1.000000)
    max r9.w, r9.w, r15.y
    min r9.w, r10.w, r9.w
    mul r15.w, r9.w, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r18.xyzw, r15.xwzx, t16.xyzw, s1, l(0.000000)
    mad r6.z, r18.w, r2.x, r6.z
    add r19.xyz, r15.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r19.xyz, r19.xyzx, t16.xyzw, s1, l(0.000000)
    mad r19.xyz, r19.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r19.xyz, r17.yyyy, r19.xyzx
    mov r19.w, r17.y
    mad r16.xyzw, r19.xyzw, r2.xxxx, r16.xyzw
    add r15.xyz, r15.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r15.xyz, r15.xyzx, t16.xyzw, s1, l(0.000000)
    mad r15.xyz, r15.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r15.xyz, r17.xxxx, r15.xyzx
    mov r15.w, r17.x
    mad r13.xyzw, r15.xyzw, r2.xxxx, r13.xyzw
    mad r15.xyz, r18.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r17.xyz, r17.wwww, r15.xyzx
    mad r14.xyzw, r17.xyzw, r2.xxxx, r14.xyzw
  endif
  lt r2.x, l(0.000000), r3.w
  if_nz r2.x
    mad r15.xyz, r7.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r17.xyz, r15.xyzx, cb0[211].xyzx
    mul r18.xyz, l(0.500000, 0.500000, 0.500000, 0.000000), cb0[211].xyzx
    round_ni r17.xyz, r17.xyzx
    mad r15.xyz, r15.xyzx, cb0[211].xyzx, -r17.xyzx
    mad r17.xyz, -cb0[211].xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(1.000000, 1.000000, 1.000000, 0.000000)
    max r15.xyz, r18.xyzx, r15.xyzx
    min r15.xyz, r17.xyzx, r15.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r19.xyw, r15.xyzx, t17.yzwx, s2, l(0.000000)
    add r2.x, -r0.z, l(1.000000)
    mul r2.x, r2.x, r3.w
    max r3.w, r18.y, r15.y
    min r3.w, r17.y, r3.w
    mul r15.w, r3.w, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r17.xyzw, r15.xwzx, t18.xyzw, s1, l(0.000000)
    add r18.xyz, r15.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r18.xyz, r18.xyzx, t18.xyzw, s1, l(0.000000)
    mad r18.xyz, r18.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r18.xyz, r19.yyyy, r18.xyzx
    mov r18.w, r19.y
    mad r16.xyzw, r18.xyzw, r2.xxxx, r16.xyzw
    add r15.xyz, r15.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r15.xyz, r15.xyzx, t18.xyzw, s1, l(0.000000)
    mad r15.xyz, r15.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r15.xyz, r19.xxxx, r15.xyzx
    mov r15.w, r19.x
    mad r13.xyzw, r15.xyzw, r2.xxxx, r13.xyzw
    mad r15.xyz, r17.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r19.xyz, r19.wwww, r15.xyzx
    mad r14.xyzw, r19.xyzw, r2.xxxx, r14.xyzw
    mad r6.z, r17.w, r2.x, r6.z
  endif
  mad_sat r2.x, r6.z, l(2.000000), l(-1.000000)
  add r15.x, -r0.z, r2.x
  add r0.z, r0.z, r2.x
  mul r15.y, r0.z, l(0.500000)
else
  mov r16.xyzw, l(0,0,0,0)
  mov r13.xyzw, l(0,0,0,0)
  mov r14.xyzw, l(0,0,0,0)
  mov r15.xy, l(0,1.000000,0,0)
endif
mul r17.xyzw, r15.yyyx, cb0[213].xyzw
mad r17.y, r17.w, l(0.500000), r17.y
mul r12.zw, r15.yyyx, cb0[213].wwwy
mad r17.w, r12.w, l(0.375000), r12.z
add r14.xyzw, r14.xyzw, r17.xyzw
mul r17.xyzw, r15.yyyx, cb0[214].xyzw
mad r17.y, r17.w, l(0.500000), r17.y
mul r12.zw, r15.yyyx, cb0[214].wwwy
mad r17.w, r12.w, l(0.375000), r12.z
add r13.xyzw, r13.xyzw, r17.xyzw
mul r17.xyzw, r15.yyyx, cb0[215].xyzw
mad r17.y, r17.w, l(0.500000), r17.y
mul r12.zw, r15.yyyx, cb0[215].wwwy
mad r17.w, r12.w, l(0.375000), r12.z
add r15.xyzw, r16.xyzw, r17.xyzw
ge r12.zw, r6.xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.z, r12.w, r12.z
if_nz r0.z
  sample_l_indexable(texture2d)(float,float,float,float) r16.xyzw, r6.xyxx, t12.xyzw, s1, l(0.000000)
  lt r17.xyzw, l(0.000100, 0.000100, 0.000100, 0.000100), |r16.xyzw|
  or r6.xy, r17.zwzz, r17.xyxx
  or r0.z, r6.y, r6.x
  if_nz r0.z
    dp3 r0.z, r16.yzwy, r16.yzwy
    sqrt r0.z, r0.z
    mov r6.x, l(1.000000)
    mov r6.y, r0.z
    mov r2.x, l(0)
    loop
      ge r3.w, l(4.600000), r6.y
      breakc_nz r3.w
      iadd r3.w, r2.x, l(1)
      mul r12.zw, r6.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
      mov r6.xy, r12.zwzz
      mov r2.x, r3.w
      continue
    endloop
    mul r16.xyzw, r6.xxxx, r16.xyzw
    dp3 r0.z, r16.yzwy, r16.yzwy
    sqrt r0.z, r0.z
    mad r0.z, r0.z, cb3[3].x, cb3[3].y
    mad r0.z, r0.z, l(255.000000), l(0.500000)
    mul r6.x, r0.z, l(0.00390625000)
    mov r6.y, l(0.500000)
    sample_l_indexable(texture2d)(float,float,float,float) r6.xy, r6.xyxx, t11.xyzw, s1, l(0.000000)
    mad r6.xy, r6.xyxx, cb3[2].xyxx, cb3[2].zwzz
    mul r17.x, r6.x, l(3.54490781)
    mul r17.yzw, r6.yyyy, r16.yyzw
    mul r0.z, r16.x, l(0.406976730)
    exp r0.z, r0.z
    mul r16.xyzw, r0.zzzz, r17.xyzw
    mov r17.xyzw, r16.xyzw
    mov r0.z, l(0)
    loop
      uge r3.w, r0.z, r2.x
      breakc_nz r3.w
      mul r18.xyzw, r17.xyzw, l(0.282094777, 0.282094777, 0.282094777, 0.282094777)
      dp4 r3.w, r18.xyzw, r17.xyzw
      dp2 r6.x, r18.yxyy, r17.xyxx
      dp2 r6.y, r18.zxzz, r17.xzxx
      dp2 r6.z, r18.wxww, r17.xwxx
      iadd r9.w, r0.z, l(1)
      mov r17.x, r3.w
      mov r17.yzw, r6.xxyz
      mov r0.z, r9.w
      continue
    endloop
    mul r16.xyzw, r17.xyzw, l(0.282094777, 0.282094777, 0.282094777, 0.282094777)
    mul r17.xyzw, r14.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r0.z, r16.xyzw, r17.xyzw
    dp2 r2.x, r16.yxyy, r17.xyxx
    dp2 r3.w, r16.zxzz, r17.xzxx
    dp2 r6.x, r16.wxww, r17.xwxx
    mul r17.xyzw, r13.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r6.y, r16.xyzw, r17.xyzw
    dp2 r6.z, r16.yxyy, r17.xyxx
    dp2 r9.w, r16.zxzz, r17.xzxx
    dp2 r10.w, r16.wxww, r17.xwxx
    mul r17.xyzw, r15.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r12.z, r16.xyzw, r17.xyzw
    dp2 r12.w, r16.yxyy, r17.xyxx
    dp2 r16.y, r16.zxzz, r17.xzxx
    dp2 r16.x, r16.wxww, r17.xwxx
    mul r14.w, r0.z, l(0.886226952)
    mul r14.x, r6.x, l(-1.02332675)
    mul r14.y, r2.x, l(-1.02332675)
    mul r14.z, r3.w, l(1.02332675)
    mul r13.x, r10.w, l(-1.02332675)
    mul r13.yw, r6.zzzy, l(0.000000, -1.02332675, 0.000000, 0.886226952)
    mul r13.z, r9.w, l(1.02332675)
    mul r15.yw, r12.wwwz, l(0.000000, -1.02332675, 0.000000, 0.886226952)
    mul r15.xz, r16.xxyx, l(-1.02332675, 0.000000, 1.02332675, 0.000000)
  endif
endif
mov r5.w, l(1.000000)
dp4 r6.x, r14.xyzw, r5.xyzw
dp4 r6.y, r13.xyzw, r5.xyzw
dp4 r6.z, r15.xyzw, r5.xyzw
max r6.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
dp3 r0.z, -r10.xyzx, r5.xyzx
add r0.z, r0.z, r0.z
mad r16.xyz, r5.xyzx, -r0.zzzz, -r10.xyzx
add r0.z, l(-1.000000), cb0[113].x
max r2.x, r11.z, l(0.001000)
log r2.x, r2.x
mad r2.x, -r2.x, l(1.200000), l(1.000000)
add r0.z, r0.z, -r2.x
mul r12.zw, r4.yyyz, cb1[0].wwww
round_ni r12.zw, r12.zzzw
add r2.x, |r2.y|, -cb1[2].y
round_ni r2.x, r2.x
add r3.w, l(-1.000000), cb1[1].x
max r9.w, r2.x, l(0.000000)
min r3.w, r3.w, r9.w
ge r2.x, r3.w, r2.x
mad r9.w, r12.w, cb1[0].x, r12.z
ftoi r9.w, r9.w
iadd r9.w, r9.w, cb0[110].z
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r9.w, r9.w, l(0), t0.xxxx
ftoi r3.w, r3.w
iadd r3.w, r3.w, cb0[110].w
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r3.w, l(0), t0.xxxx
and r3.w, r3.w, r9.w
and r2.x, r2.x, r3.w
mul r17.xyz, r6.xyzx, cb0[111].xxxx
dp3 r3.w, r17.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
mov r7.w, l(1.000000)
mov r17.xyz, l(0,0,0,0)
mov r9.w, l(1.000000)
mov r10.w, r2.x
mov r11.z, l(0)
loop
  lt r12.z, l(0.010000), r9.w
  ine r12.w, r10.w, l(0)
  and r12.w, r12.z, r12.w
  if_nz r12.w
    firstbit_lo r12.w, r10.w
    ishl r16.w, l(1), r12.w
    xor r10.w, r10.w, r16.w
    ishl r12.w, r12.w, l(3)
    dp4 r18.x, cb1[r12.w + 6].xyzw, r7.xyzw
    dp4 r18.y, cb1[r12.w + 7].xyzw, r7.xyzw
    dp4 r18.z, cb1[r12.w + 8].xyzw, r7.xyzw
    ge r19.xyz, cb1[r12.w + 5].xyzx, |r18.xyzx|
    and r16.w, r19.y, r19.x
    and r16.w, r19.z, r16.w
    if_nz r16.w
      mul r16.w, l(0.100000), cb1[r12.w + 5].x
      mul r19.xyz, |r18.xyzx|, l(0.100000, 0.100000, 0.100000, 0.000000)
      mul r19.xy, r19.xyxx, r19.xyxx
      add r20.xyz, -|r18.xyzx|, cb1[r12.w + 5].xyzx
      mul r20.xyz, r20.xyzx, cb1[r12.w + 9].xyzx
      eq r17.w, l(1.000000), cb1[r12.w + 10].x
      if_nz r17.w
        dp3 r21.x, cb1[r12.w + 6].xyzx, r16.xyzx
        dp3 r21.y, cb1[r12.w + 7].xyzx, r16.xyzx
        dp3 r21.z, cb1[r12.w + 8].xyzx, r16.xyzx
        add r22.xyz, -r18.xyzx, cb1[r12.w + 5].xyzx
        div r22.xyz, r22.xyzx, r21.xyzx
        add r23.xyz, -r18.xyzx, -cb1[r12.w + 5].xyzx
        div r23.xyz, r23.xyzx, r21.xyzx
        lt r24.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r21.xyzx
        movc r22.xyz, r24.xyzx, r22.xyzx, r23.xyzx
        min r17.w, r22.y, r22.x
        min r17.w, r22.z, r17.w
        mad r18.xyz, r21.xyzx, r17.wwww, r18.xyzx
      else
        mov r18.xyz, r16.xyzx
      endif
      dp3 r17.w, r18.xyzx, r18.xyzx
      rsq r17.w, r17.w
      mul r18.xyz, r17.wwww, r18.xyzx
      lt r21.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r18.xyzx
      lt r22.xyz, r18.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
      iadd r21.xyz, -r21.xyzx, r22.xyzx
      itof r21.xyz, r21.xyzx
      dp3 r17.w, r18.xyzx, r21.xyzx
      div r18.xyz, r18.xyzx, r17.wwww
      lt r17.w, r18.z, l(0.000000)
      add r18.zw, -|r18.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
      mul r18.zw, r18.zzzw, r21.xxxy
      movc r18.xy, r17.wwww, r18.zwzz, r18.xyxx
      dp4 r17.w, cb1[r12.w + 4].xyzw, r5.xyzw
      max r17.w, r17.w, l(0.000000)
      max r17.w, r17.w, l(0.000100)
      min r18.z, r20.z, r20.y
      min r18.z, r18.z, r20.x
      add r18.w, r19.y, r19.x
      mad r18.w, r19.z, r19.z, r18.w
      mad r16.w, r16.w, r16.w, -r18.w
      mul r16.w, r16.w, cb1[r12.w + 9].x
      mul r16.w, r16.w, cb1[r12.w + 9].x
      add r18.w, l(1.000000), -cb1[r12.w + 10].y
      mul r16.w, r16.w, r18.w
      mul r16.w, r16.w, l(100.000000)
      mad_sat r16.w, r18.z, cb1[r12.w + 10].y, r16.w
      mul r18.z, r16.w, cb1[r12.w + 10].w
      mad r18.xy, r18.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
      mad r19.xy, r18.xyxx, cb1[1].wwww, cb1[2].wwww
      mov r19.z, cb1[r12.w + 5].w
      sample_l_indexable(texture2darray)(float,float,float,float) r18.xyw, r19.xyzx, t5.xywz, s3, r0.z
      mul r18.xyw, r18.xyxw, cb1[r12.w + 9].wwww
      div r19.x, r3.w, r17.w
      min r19.x, |r19.x|, l(1.000000)
      mad r19.x, r19.x, l(2.000000), r3.w
      add r17.w, r17.w, l(2.000000)
      div r17.w, r19.x, r17.w
      add r17.w, r17.w, l(-1.000000)
      mad r17.w, r17.w, cb0[112].w, l(1.000000)
      mul r18.xyw, r17.wwww, r18.xyxw
      mul r18.xyz, r18.zzzz, r18.xywx
      mad r17.xyz, r18.xyzx, r9.wwww, r17.xyzx
      mad r12.w, -r16.w, cb1[r12.w + 10].w, l(1.000000)
      mul r9.w, r9.w, r12.w
    endif
    mov r11.z, l(-1)
    continue
  else
    mov r11.z, r12.z
    break
  endif
  mov r11.z, r12.z
endloop
if_nz r11.z
  dp3 r2.x, r16.xyzx, r16.xyzx
  rsq r2.x, r2.x
  mul r7.xzw, r2.xxxx, r16.xxyz
  lt r16.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r7.xzwx
  lt r18.xyz, r7.xzwx, l(0.000000, 0.000000, 0.000000, 0.000000)
  iadd r16.xyz, -r16.xyzx, r18.xyzx
  itof r16.xyz, r16.xyzx
  dp3 r2.x, r7.xzwx, r16.xyzx
  div r7.xzw, r7.xxzw, r2.xxxx
  lt r2.x, r7.w, l(0.000000)
  add r12.zw, -|r7.zzzx|, l(0.000000, 0.000000, 1.000000, 1.000000)
  mul r12.zw, r12.zzzw, r16.xxxy
  movc r7.xz, r2.xxxx, r12.zzwz, r7.xxzx
  dp4 r2.x, cb1[3].xyzw, r5.xyzw
  max r2.x, r2.x, l(0.000000)
  max r2.x, r2.x, l(0.000100)
  mad r7.xz, r7.xxzx, l(0.500000, 0.000000, 0.500000, 0.000000), l(0.500000, 0.000000, 0.500000, 0.000000)
  mad r16.xy, r7.xzxx, cb1[1].wwww, cb1[2].wwww
  mov r16.z, l(0)
  sample_l_indexable(texture2darray)(float,float,float,float) r7.xzw, r16.xyzx, t5.xwyz, s3, r0.z
  div r0.z, r3.w, r2.x
  min r0.z, |r0.z|, l(1.000000)
  mad r0.z, r0.z, l(2.000000), r3.w
  add r2.x, r2.x, l(2.000000)
  div r0.z, r0.z, r2.x
  add r0.z, r0.z, l(-1.000000)
  mad r0.z, r0.z, cb0[112].w, l(1.000000)
  mul r7.xzw, r0.zzzz, r7.xxzw
  mad r17.xyz, r7.xzwx, r9.wwww, r17.xyzx
endif
mul r7.xzw, r17.xxyz, cb0[112].zzzz
mul r7.xzw, r7.xxzw, cb0[111].yyyy
if_nz r6.w
  sample_b_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t3.yzxw, s1, cb0[108].x
  sample_b_indexable(texture2d)(float,float,float,float) r16.xyz, v1.xyxx, t2.xyzw, s1, cb0[108].x
  add r2.x, -r0.z, l(1.000000)
  mul r17.xyz, r2.xxxx, r7.xzwx
  mad r7.xzw, r16.xxyz, r0.zzzz, r17.xxyz
endif
mul r6.xyz, r3.xyzx, r6.xyzx
mul r6.xyz, r6.xyzx, cb0[111].xxxx
mad r0.z, r2.z, r12.x, r12.y
mul r7.xzw, r0.zzzz, r7.xxzw
mul r7.xzw, r8.xxyz, r7.xxzw
mad r6.xyz, r6.xyzx, r11.xywx, r7.xzwx
mul r5.xyzw, r5.xyzw, l(-1.000000, -1.000000, -1.000000, 1.000000)
dp4 r8.x, r14.xyzw, r5.xyzw
dp4 r8.y, r13.xyzw, r5.xyzw
dp4 r8.z, r15.xyzw, r5.xyzw
max r5.xyz, r8.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mul r5.xyz, r5.xyzx, cb0[111].xxxx
mul r5.xyz, r11.xywx, r5.xyzx
max r0.z, r3.y, r3.x
max r0.z, r3.z, r0.z
max r0.z, r0.z, l(0.010000)
div r3.xyz, r3.xyzx, r0.zzzz
mul r3.xyz, r3.xyzx, r5.xyzx
mul r0.z, r4.x, l(0.00787401572)
min r2.x, r8.w, l(1.000000)
bfi r1.z, l(3), l(2), r1.z, l(0)
ftou r2.z, r2.w
bfi r1.z, l(2), l(0), r2.z, r1.z
utof r1.z, r1.z
mul r1.z, r1.z, l(0.0322580636)
mad r0.z, r0.z, r2.x, r1.z
mul r2.xzw, r0.zzzz, r3.xxyz
mad r2.xzw, r2.xxzw, l(0.318309873, 0.000000, 0.318309873, 0.318309873), r6.xxyz
add r1.xyz, r1.xywx, r2.xzwx
mad r0.z, r7.y, cb0[156].w, cb0[157].w
max r0.z, r0.z, l(0.010000)
mad r1.w, r4.w, cb0[154].w, -cb0[153].w
max r1.w, r1.w, l(0.000000)
mul r2.x, r0.z, l(-1.442695)
exp r2.x, r2.x
add r2.x, -r2.x, l(1.000000)
div r0.z, r2.x, r0.z
mad r2.x, r7.y, cb0[156].w, cb0[158].w
mul r2.x, r2.x, l(1.442695)
exp r2.x, r2.x
mul r0.z, r0.z, r2.x
mul r0.z, r0.z, -r1.w
mul r2.xzw, r0.zzzz, cb0[155].xxyz
mul r2.xzw, r2.xxzw, l(1.442695, 0.000000, 1.442695, 1.442695)
exp r2.xzw, r2.xxzw
dp3 r0.z, -r10.xyzx, cb0[154].xyzx
mad r1.w, cb0[155].w, cb0[155].w, l(1.000000)
dp2 r3.x, r0.zzzz, cb0[155].wwww
add r1.w, r1.w, -r3.x
lt r3.x, l(0.000000), cb0[163].z
if_nz r3.x
  and r0.w, l(7), cb0[108].w
  imad r0.xyw, r0.xyxw, l(0x0019660d, 0x0019660d, 0, 0x0019660d), l(0x3c6ef35f, 0x3c6ef35f, 0, 0x3c6ef35f)
  imad r0.x, r0.y, r0.w, r0.x
  imad r0.y, r0.w, r0.x, r0.y
  imad r0.w, r0.x, r0.y, r0.w
  imad r3.x, r0.y, r0.w, r0.x
  dp3 r0.x, -r10.xyzx, -r9.xyzx
  add r3.z, r7.y, -cb0[44].y
  lt r3.w, l(5.960464478E-08), r0.x
  div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
  and r0.x, r0.x, r3.w
  mul r0.x, r0.x, cb0[163].w
  div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
  mul r4.x, r0.x, r3.w
  mad r5.x, r4.x, r3.z, cb0[44].y
  mad r3.z, -r4.x, r3.z, r3.z
  mul r4.x, r3.z, cb0[159].z
  max r4.x, r4.x, l(-127.000000)
  mul r3.z, r3.z, cb0[162].x
  max r3.z, r3.z, l(-127.000000)
  add r5.y, r5.x, -cb0[159].x
  mul r5.y, r5.y, cb0[159].z
  max r5.y, r5.y, l(-127.000000)
  exp r5.y, -r5.y
  mul r5.y, r5.y, cb0[159].y
  lt r5.z, l(5.960464478E-08), |r4.x|
  exp r5.w, -r4.x
  add r5.w, -r5.w, l(1.000000)
  div r5.w, r5.w, r4.x
  mad r4.x, -r4.x, l(0.240226507), l(0.693147182)
  movc r4.x, r5.z, r5.w, r4.x
  add r5.x, r5.x, -cb0[162].z
  mul r5.x, r5.x, cb0[162].x
  max r5.x, r5.x, l(-127.000000)
  exp r5.x, -r5.x
  mul r5.x, r5.x, cb0[162].y
  lt r5.z, l(5.960464478E-08), |r3.z|
  exp r5.w, -r3.z
  add r5.w, -r5.w, l(1.000000)
  div r5.w, r5.w, r3.z
  mad r3.z, -r3.z, l(0.240226507), l(0.693147182)
  movc r3.z, r5.z, r5.w, r3.z
  mul r3.z, r3.z, r5.x
  mad r3.z, r5.y, r4.x, r3.z
  mad r0.x, -r0.x, r3.w, l(1.000000)
  mul r0.x, r4.w, r0.x
  mul r0.x, r0.x, r3.z
  exp r0.x, -r0.x
  min r0.x, r0.x, l(1.000000)
  max r0.x, r0.x, cb0[161].w
  mad_sat r3.zw, r4.wwww, cb0[160].yyyw, cb0[160].xxxz
  add r0.x, r0.x, r3.z
  add r0.x, r3.w, r0.x
  min r0.x, r0.x, l(1.000000)
  imad r3.y, r0.w, r3.x, r0.y
  ushr r0.yw, r3.xxxy, l(0, 16, 0, 16)
  utof r0.yw, r0.yyyw
  mad r0.yw, r0.yyyw, l(0.000000, 0.0000305180438, 0.000000, 0.0000305180438), l(0.000000, -1.000000, 0.000000, -1.000000)
  mad r0.yw, r0.yyyw, cb0[167].wwww, r4.yyyz
  mul r3.xy, r0.ywyy, cb0[165].xyxx
  mad r0.y, |r2.y|, cb0[164].x, cb0[164].y
  log r0.y, r0.y
  mul r0.y, r0.y, cb0[164].z
  div r3.z, r0.y, cb0[163].z
  sample_l_indexable(texture3d)(float,float,float,float) r3.xyzw, r3.xyzx, t10.xyzw, s1, l(0.000000)
  add r0.y, |r2.y|, -cb0[166].z
  mul_sat r0.y, r0.y, l(1000000.000000)
  add r3.xyzw, r3.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
  mad r3.xyzw, r0.yyyy, r3.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
  add r0.y, -r0.x, l(1.000000)
  mul r4.xyz, r0.yyyy, cb0[161].xyzx
  mad r3.xyz, r4.xyzx, r3.wwww, r3.xyzx
  mul r0.x, r0.x, r3.w
else
  add r0.y, r7.y, -cb0[44].y
  mul r0.w, r0.y, cb0[159].z
  mul r0.y, r0.y, cb0[162].x
  max r0.yw, r0.yyyw, l(0.000000, -127.000000, 0.000000, -127.000000)
  add r2.y, cb0[44].y, -cb0[159].x
  mul r2.y, r2.y, cb0[159].z
  max r2.y, r2.y, l(-127.000000)
  exp r2.y, -r2.y
  mul r2.y, r2.y, cb0[159].y
  lt r3.w, l(5.960464478E-08), |r0.w|
  exp r4.x, -r0.w
  add r4.x, -r4.x, l(1.000000)
  div r4.x, r4.x, r0.w
  mad r0.w, -r0.w, l(0.240226507), l(0.693147182)
  movc r0.w, r3.w, r4.x, r0.w
  add r3.w, cb0[44].y, -cb0[162].z
  mul r3.w, r3.w, cb0[162].x
  max r3.w, r3.w, l(-127.000000)
  exp r3.w, -r3.w
  mul r3.w, r3.w, cb0[162].y
  lt r4.x, l(5.960464478E-08), |r0.y|
  exp r4.y, -r0.y
  add r4.y, -r4.y, l(1.000000)
  div r4.y, r4.y, r0.y
  mad r0.y, -r0.y, l(0.240226507), l(0.693147182)
  movc r0.y, r4.x, r4.y, r0.y
  mul r0.y, r0.y, r3.w
  mad r0.y, r2.y, r0.w, r0.y
  mul r0.y, r4.w, r0.y
  exp r0.y, -r0.y
  min r0.y, r0.y, l(1.000000)
  max r0.y, r0.y, cb0[161].w
  mad_sat r4.xy, r4.wwww, cb0[160].ywyy, cb0[160].xzxx
  add r0.y, r0.y, r4.x
  add r0.y, r4.y, r0.y
  min r0.x, r0.y, l(1.000000)
  add r0.y, -r0.x, l(1.000000)
  mul r3.xyz, r0.yyyy, cb0[161].xyzx
endif
mul r4.xyz, r0.xxxx, r2.xzwx
max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r1.xyz, r1.xyzx, l(255.000000, 255.000000, 255.000000, 0.000000)
mad r0.y, r0.z, r0.z, l(1.000000)
mul r0.y, r0.y, l(0.0596831031)
mad r0.yzw, cb0[156].xxyz, r0.yyyy, cb0[158].xxyz
mad r2.y, -cb0[155].w, cb0[155].w, l(1.000000)
mul r3.w, r1.w, l(12.566371)
sqrt r1.w, r1.w
mul r1.w, r1.w, r3.w
max r1.w, r1.w, l(0.001000)
div r1.w, r2.y, r1.w
mad_sat r0.yzw, cb0[157].xxyz, r1.wwww, r0.yyzw
mul r0.yzw, r0.yyzw, l(0.000000, 255.000000, 255.000000, 255.000000)
add r2.xyz, -r2.xzwx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r0.yzw, r0.yyzw, r2.xxyz
mad r0.xyz, r0.yzwy, r0.xxxx, r3.xyzx
mad o0.xyz, r1.xyzx, r4.xyzx, r0.xyzx
dp3 o0.w, r4.xyzx, l(0.333333343, 0.333333343, 0.333333343, 0.000000)
ret
// Approximately 0 instruction slots used
