//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.4.1 on Sun Feb  1 03:43:52 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy
// TEXCOORD                 0   xy          1     NONE   float   xy
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[235], immediateIndexed
dcl_constantbuffer CB1[259], dynamicIndexed
dcl_constantbuffer CB2[5], immediateIndexed
dcl_constantbuffer CB3[5], immediateIndexed
dcl_constantbuffer CB4[4], immediateIndexed
dcl_constantbuffer CB13[13], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_comparison
dcl_resource_structured t0, 4
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2darray (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture3d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture3d (float,float,float,float) t14
dcl_resource_texture2d (float,float,float,float) t15
dcl_resource_texture2d (float,float,float,float) t16
dcl_resource_texture3d (float,float,float,float) t17
dcl_resource_texture3d (float,float,float,float) t18
dcl_resource_texture3d (float,float,float,float) t19
dcl_resource_texture3d (float,float,float,float) t20
dcl_resource_texture3d (float,float,float,float) t21
dcl_resource_texture3d (float,float,float,float) t22
dcl_resource_texture2d (float,float,float,float) t23
dcl_resource_texture2d (float,float,float,float) t24
dcl_resource_texture2d (float,float,float,float) t25
dcl_resource_texture2d (float,float,float,float) t26
dcl_resource_texture3d (float,float,float,float) t27
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 24
ftou r0.xy, v0.xyxx
mov r0.z, l(0)
ld_indexable(texture2d)(float,float,float,float) r1.xyz, r0.xyzz, t24.xyzw
ld_indexable(texture2d)(float,float,float,float) r2.xyz, r0.xyzz, t25.xyzw
mad r2.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r1.w, l(1.000000, 1.000000, 0.000000, 0.000000), |r2.xyxx|
add r3.y, -r1.w, l(1.000000)
lt r1.w, r3.y, l(0.000000)
ge r4.xy, r2.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
add r4.zw, -|r2.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
movc r4.xy, r4.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
mul r4.xy, r4.xyxx, r4.zwzz
movc r3.xz, r1.wwww, r4.xxyx, r2.xxyx
dp3 r1.w, r3.xyzx, r3.xyzx
rsq r1.w, r1.w
mul r2.xyw, r1.wwww, r3.xyxz
utof r4.xy, r0.xyxx
mul r4.zw, v0.xxxy, cb0[82].zzzw
mad r5.xy, r4.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
add r5.zw, r4.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
mul r5.zw, r5.zzzw, cb0[82].zzzw
sample_l_indexable(texture2d)(float,float,float,float) r3.w, r5.zwzz, t1.yzwx, s0, l(0.000000)
mul r6.xyzw, -r5.yyyy, cb0[25].xyzw
mad r5.xyzw, cb0[24].xyzw, r5.xxxx, r6.xyzw
mad r5.xyzw, cb0[26].xyzw, r3.wwww, r5.xyzw
add r5.xyzw, r5.xyzw, cb0[27].xyzw
div r5.xyz, r5.xyzx, r5.wwww
mul r3.w, r5.y, cb0[1].z
mad r3.w, cb0[0].z, r5.x, r3.w
mad r3.w, cb0[2].z, r5.z, r3.w
add r3.w, r3.w, cb0[3].z
eq r6.x, l(0.000000), cb0[86].w
add r6.yzw, -r5.xxyz, cb0[44].xxyz
mov r7.x, cb0[0].z
mov r7.y, cb0[1].z
mov r7.z, cb0[2].z
movc r8.xyz, r6.xxxx, r6.yzwy, r7.xyzx
dp3 r6.x, r8.xyzx, r8.xyzx
max r7.w, r6.x, l(9.999999939E-09)
rsq r7.w, r7.w
mul r9.xyz, r7.wwww, r8.xyzx
mul r6.x, r6.x, r7.w
lt r8.w, l(0.000488281250), cb0[234].x
if_nz r8.w
  sample_b_indexable(texture2d)(float,float,float,float) r10.xy, v1.xyxx, t23.xyzw, s1, cb0[108].x
else
  mov r10.xy, l(1.000000,1.000000,0,0)
endif
lt r10.zw, l(0.000000, 0.000000, 0.500000, 0.500000), cb0[226].xxxy
if_nz r10.z
  add r9.w, |r2.y|, |r2.x|
  add r9.w, |r2.w|, r9.w
  div r9.w, l(1.000000, 1.000000, 1.000000, 1.000000), r9.w
  mul r11.xyz, |r2.xywx|, r9.wwww
  mul r12.xyz, r5.xyzx, cb0[229].xxxx
  sample_l_indexable(texture3d)(float,float,float,float) r9.w, r12.xyzx, t9.yzwx, s2, l(0.000000)
  mul r12.xyzw, r11.xxyy, l(0.000000, 1.000000, 0.707106, 0.000000)
  add r11.xyw, r12.zwzz, r12.xxxy
  mad r11.xyz, r11.zzzz, l(1.000000, 0.000000, 0.000000, 0.000000), r11.xywx
  mad r10.z, r9.w, l(2.000000), l(-1.000000)
  mul r11.xyz, r10.zzzz, r11.xyzx
  mov r10.z, |r2.y|
  add r10.z, r10.z, l(-0.700000)
  mul_sat r10.z, r10.z, l(4.000000)
  mad r11.w, r10.z, l(-2.000000), l(3.000000)
  mul r10.z, r10.z, r10.z
  mul r10.z, r10.z, r11.w
  add r11.w, -cb0[229].z, cb0[229].y
  mad r10.z, r10.z, r11.w, cb0[229].z
  mul r11.xyz, r10.zzzz, r11.xyzx
else
  mov r11.xyz, l(0,0,0,0)
  mov r9.w, l(0)
endif
mad r10.z, -r3.y, r1.w, l(-0.200000)
if_nz r10.w
  mul r12.xyz, r2.xywx, cb0[233].zzzz
  mul r13.xyz, l(0.000000, 1.000000, 0.000000, 0.000000), cb0[225].yyyy
  mad r12.xyz, r12.xyzx, cb0[225].xxxx, r13.xyzx
  max r10.w, -r2.y, l(0.000000)
  min r10.w, r10.w, l(0.900000)
  add r10.w, -r10.w, l(1.000000)
  mul_sat r11.w, r10.z, l(-10.000000)
  mad r12.w, r11.w, l(-2.000000), l(3.000000)
  mul r11.w, r11.w, r11.w
  mul r11.w, r11.w, r12.w
  max r11.w, r11.w, l(0.100000)
  min r11.w, r11.w, l(1.000000)
  mul r10.w, r10.w, r11.w
  mad r12.xyz, r12.xyzx, r10.wwww, r5.xyzx
  add r11.xyz, r11.xyzx, r12.xyzx
  mul r12.xyz, r11.yyyy, cb3[1].xyzx
  mad r11.xyw, cb3[0].xyxz, r11.xxxx, r12.xyxz
  mad r11.xyz, cb3[2].xyzx, r11.zzzz, r11.xywx
  add r11.xyz, r11.xyzx, cb3[3].xyzx
  mad r12.x, r11.x, l(0.500000), cb3[4].x
  mad r10.w, r11.y, l(0.500000), l(0.500000)
  add r12.z, -r10.w, cb3[4].y
  add r11.xy, r12.xzxx, l(0.500000, 1.000000, 0.000000, 0.000000)
  max r10.w, r11.z, l(0.000488281250)
  sample_c_lz_indexable(texture2d)(float,float,float,float) r10.w, r11.xyxx, t8.xxxx, s4, r10.w
else
  mov r10.w, l(1.000000)
endif
mov_sat r11.x, r2.y
add r11.y, l(1.000000), -cb0[230].w
mad r11.x, r11.x, r11.y, cb0[230].w
add r11.yz, r5.xxzx, -cb0[44].xxzx
max r11.y, |r11.z|, |r11.y|
mul r11.z, r10.w, r11.x
mul r11.w, l(0.0500000119), cb0[222].w
mad r12.x, -cb0[222].w, l(0.700000), r11.y
div r11.w, l(1.000000, 1.000000, 1.000000, 1.000000), r11.w
mul_sat r11.w, r11.w, r12.x
mad r12.x, r11.w, l(-2.000000), l(3.000000)
mul r11.w, r11.w, r11.w
mul r11.w, r11.w, r12.x
mad r10.w, -r11.x, r10.w, l(1.000000)
mad r10.w, r11.w, r10.w, r11.z
ge r11.z, r1.z, l(0.045000)
and r11.z, r11.z, l(0x3f800000)
mul r11.z, r10.w, r11.z
deriv_rty_coarse r12.xyz, r5.xyzx
deriv_rtx_coarse r13.xyz, r5.zxyz
mul r14.xyz, r12.xyzx, r13.xyzx
mad r12.xyz, r12.zxyz, r13.yzxy, -r14.xyzx
dp3 r11.w, r12.xyzx, r12.xyzx
max r11.w, r11.w, l(1.175494351E-38)
rsq r11.w, r11.w
mul r12.yzw, r11.wwww, r12.xxzy
mov_sat r13.x, r12.y
add r13.y, r13.x, l(-0.988000)
mul_sat r13.y, r13.y, l(1000.012878)
mad r13.z, r13.y, l(-2.000000), l(3.000000)
mul r13.y, r13.y, r13.y
mul r13.y, r13.y, r13.z
add r13.z, |r3.w|, l(-15.000000)
mul_sat r13.z, r13.z, l(0.015000)
add r13.z, -r13.z, l(1.000000)
lt r13.w, l(0.000488281250), cb0[223].y
mad r14.x, cb0[223].z, l(0.300000), l(0.687000)
add r13.x, r13.x, -r14.x
mul_sat r13.x, r13.x, l(-1000.012878)
mad r14.x, r13.x, l(-2.000000), l(3.000000)
mul r13.x, r13.x, r13.x
mul r13.x, r13.x, r14.x
mad r11.w, r12.x, r11.w, l(0.500000)
mul_sat r11.w, r11.w, l(2.500000)
mad r12.x, r11.w, l(-2.000000), l(3.000000)
mul r11.w, r11.w, r11.w
mul r11.w, r11.w, r12.x
mul r11.w, r11.w, r13.x
lt r11.w, l(0.000488281250), r11.w
and r11.w, r11.w, r13.w
if_nz r11.w
  mul r13.xw, |r12.zzzw|, |r12.zzzw|
  add r11.w, r13.w, r13.x
  div r11.w, l(1.000000, 1.000000, 1.000000, 1.000000), r11.w
  mul r13.xw, r11.wwww, r13.xxxw
  mul r14.xyz, r12.ywzy, l(0.000000, 1.000000, 0.000000, 0.000000)
  mad r14.xyz, r12.zywz, l(1.000000, 0.000000, 0.000000, 0.000000), -r14.xyzx
  dp2 r11.w, r14.xyxx, r14.xyxx
  rsq r11.w, r11.w
  mul r14.xyz, r11.wwww, r14.xyzx
  mul r15.xyz, r12.ywzy, r14.xyzx
  mad r15.xyz, r14.zxyz, r12.wzyw, -r15.xyzx
  dp3 r11.w, r15.xyzx, r15.xyzx
  rsq r11.w, r11.w
  mul r15.xyz, r11.wwww, r15.xyzx
  add r16.xyz, r5.xyzx, r5.xyzx
  round_ni r16.xyz, r16.xyzx
  add r16.xyz, r16.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  add r14.zw, r16.yyyy, r16.xxxz
  dp2 r11.w, r14.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
  sincos r11.w, null, r11.w
  mul r11.w, r11.w, l(43758.546875)
  frc r11.w, r11.w
  lt r14.zw, l(0.000000, 0.000000, 0.000000, 0.000000), r12.wwwz
  lt r16.xy, r12.wzww, l(0.000000, 0.000000, 0.000000, 0.000000)
  iadd r14.zw, r14.zzzw, -r16.xxxy
  itof r14.zw, r14.zzzw
  mul r16.xy, r5.xzxx, r14.zwzz
  mul r12.x, r9.w, r11.w
  add r14.z, -r11.w, l(1.000000)
  mad r14.z, r14.z, l(0.700000), l(0.300000)
  mul r17.xy, r12.xxxx, l(3.000000, 6.000000, 0.000000, 0.000000)
  mad r12.x, -cb0[223].x, r14.z, r17.x
  frc r18.x, r12.x
  mad r12.x, cb0[223].x, l(-0.300000), r17.y
  frc r18.y, r12.x
  mul r11.w, r11.w, l(5.000000)
  round_ni r11.w, r11.w
  add r17.x, r11.w, l(1.000000)
  mul r17.y, r5.y, r17.x
  mov r5.w, l(0.100000)
  mul r14.zw, r5.yyyw, r17.xxxy
  frc r14.zw, r14.zzzw
  add r17.xy, r18.xyxx, l(-1.000000, -1.000000, 0.000000, 0.000000)
  add r17.xy, r14.zwzz, -r17.xyxx
  add r17.xy, r17.xyxx, l(-0.800000, -0.800000, 0.000000, 0.000000)
  mul_sat r17.xy, r17.xyxx, l(5.00000048, 5.00000048, 0.000000, 0.000000)
  mad r17.zw, r17.xxxy, l(0.000000, 0.000000, -2.000000, -2.000000), l(0.000000, 0.000000, 3.000000, 3.000000)
  mul r17.xy, r17.xyxx, r17.xyxx
  mul r17.xy, r17.xyxx, r17.zwzz
  add r17.zw, -r14.zzzw, r18.xxxy
  max r17.xy, r17.zwzz, r17.xyxx
  add r18.zw, -r18.xxxy, r14.zzzw
  add r18.zw, r18.zzzw, l(0.000000, 0.000000, -0.800000, -0.800000)
  mul r18.zw, r18.zzzw, l(0.000000, 0.000000, 5.00000048, 5.00000048)
  max r18.zw, r18.zzzw, l(0.000000, 0.000000, 0.000000, 0.000000)
  mad r19.xy, r18.zwzz, l(-2.000000, -2.000000, 0.000000, 0.000000), l(3.000000, 3.000000, 0.000000, 0.000000)
  mul r18.zw, r18.zzzw, r18.zzzw
  mul r18.zw, r18.zzzw, r19.xxxy
  add r17.zw, r17.zzzw, l(0.000000, 0.000000, 1.000000, 1.000000)
  max r17.zw, r17.zzzw, r18.zzzw
  ge r14.zw, r14.zzzw, r18.xxxy
  and r14.zw, r14.zzzw, l(0, 0, 0x3f800000, 0x3f800000)
  add r17.zw, -r17.xxxy, r17.zzzw
  mad r14.zw, r14.zzzw, r17.zzzw, r17.xxxy
  mad r11.w, r14.z, r14.z, l(-0.400000)
  mul_sat r11.w, r11.w, l(1.66666663)
  mad r12.x, r11.w, l(-2.000000), l(3.000000)
  mul r11.w, r11.w, r11.w
  mul r11.w, r11.w, r12.x
  mad r12.x, r14.w, l(2.000000), l(-1.000000)
  mul r14.z, r11.w, l(0.010000)
  mul r17.x, r12.x, r14.z
  mad r17.x, r9.w, l(0.100000), r17.x
  mul r14.z, r11.w, r14.z
  mad r14.z, r14.z, r12.x, r9.w
  mul r17.y, r9.w, r14.z
  mov r16.z, r5.y
  mad r17.zw, r16.yyyz, cb0[224].xxxy, r17.xxxy
  sample_b_indexable(texture2d)(float,float,float,float) r18.xyzw, r17.zwzz, t10.xyzw, s2, cb0[108].x
  mov r16.w, -r16.x
  mad r16.xy, r16.wzww, cb0[224].xyxx, r17.xyxx
  sample_b_indexable(texture2d)(float,float,float,float) r16.xyzw, r16.xyxx, t10.xyzw, s2, cb0[108].x
  mul r16.xyzw, r13.wwww, r16.xyzw
  mad r16.xyzw, r18.xyzw, r13.xxxx, r16.xyzw
  mad r13.xw, r16.xxxy, l(2.000000, 0.000000, 0.000000, 2.000000), l(-1.000000, 0.000000, 0.000000, -1.000000)
  mad r9.w, r11.w, l(2.000000), l(-1.000000)
  mad_sat r9.w, r9.w, l(0.800000), r14.w
  mad r14.z, -r16.w, l(0.500000), l(1.000000)
  mad r9.w, r9.w, r14.z, l(-0.700000)
  mul_sat r9.w, r9.w, l(3.33333325)
  mad r14.z, r9.w, l(-2.000000), l(3.000000)
  mul r9.w, r9.w, r9.w
  mul r9.w, r9.w, r14.z
  mul r12.x, r12.x, r16.w
  mad_sat r11.w, r12.x, l(0.500000), r11.w
  mad r11.w, r11.w, l(0.500000), l(0.100000)
  max r9.w, r9.w, r11.w
  add r11.w, -r9.w, l(1.000000)
  max r11.w, r11.w, l(0.000000)
  mul r12.x, r11.w, r11.w
  mul r12.x, r12.x, r12.x
  mul r11.w, r11.w, r12.x
  ge r11.w, r16.z, r11.w
  and r11.w, r11.w, l(0x3f800000)
  mad r9.w, r9.w, l(0.700000), l(0.200000018)
  mad r9.w, r11.w, r9.w, l(0.100000)
  mul r9.w, r16.z, r9.w
  mul r9.w, r9.w, cb0[223].y
  mul r9.w, r9.w, l(0.330000)
  mul r11.w, r11.z, cb0[222].x
  mul r11.w, r13.z, r11.w
  mul r9.w, r9.w, r11.w
  dp2 r11.w, r13.xwxx, r13.xwxx
  min r11.w, r11.w, l(1.000000)
  add r11.w, -r11.w, l(1.000000)
  sqrt r11.w, r11.w
  max r11.w, r11.w, l(0.000488281250)
  mul_sat r12.x, r9.w, l(10.000000)
  mad r14.z, r12.x, l(-2.000000), l(3.000000)
  mul r12.x, r12.x, r12.x
  mul r12.x, r12.x, r14.z
  mul r12.x, r12.x, cb0[223].y
  mul r16.xy, r12.xxxx, r13.xwxx
  add r12.x, l(-1.500000), cb0[223].y
  mul_sat r12.x, r12.x, l(0.666666687)
  mad r13.x, r12.x, l(-2.000000), l(3.000000)
  mul r12.x, r12.x, r12.x
  mul r12.x, r12.x, r13.x
  mul r13.x, r12.x, l(-0.200000)
  mad r11.w, -r12.x, l(-0.200000), r11.w
  mad r16.z, r9.w, r11.w, r13.x
  dp3 r11.w, r16.xyzx, r16.xyzx
  max r11.w, r11.w, l(1.175494351E-38)
  rsq r11.w, r11.w
  mul r16.xyz, r11.wwww, r16.xyzx
  mov r17.x, r14.y
  mov r17.y, r15.x
  mov r17.z, r12.z
  dp3 r17.x, r17.xyzx, r16.xyzx
  mov r15.w, r12.y
  dp2 r17.y, r15.ywyy, r16.yzyy
  mov r12.y, r14.x
  mov r12.z, r15.z
  dp3 r17.z, r12.yzwy, r16.xyzx
  mad r12.xyz, -r3.xyzx, r1.wwww, r17.xyzx
  mad r12.xyz, r9.wwww, r12.xyzx, r2.xywx
  mul r9.w, r9.w, cb0[223].y
  mul r9.w, r9.w, l(0.330000)
else
  mov r12.xyz, r2.xywx
  mov r9.w, l(0)
endif
lt r13.xw, l(0.000488281250, 0.000000, 0.000000, 0.000488281250), cb0[227].yyyw
or r11.w, r13.w, r13.x
lt r13.x, l(0.000488281250), r13.y
and r11.w, r11.w, r13.x
if_nz r11.w
  mul r14.xyz, r2.ywxy, l(1.000000, 0.000000, 0.000000, 0.000000)
  mad r14.xyz, r2.xywx, l(0.000000, 0.000000, 1.000000, 0.000000), -r14.xyzx
  dp2 r11.w, r14.xzxx, r14.xzxx
  rsq r11.w, r11.w
  mul r14.xyz, r11.wwww, r14.xyzx
  mul r15.xyz, r2.ywxy, r14.xyzx
  mad r15.xyz, r14.zxyz, r2.wxyw, -r15.xyzx
  dp3 r11.w, r15.xyzx, r15.xyzx
  rsq r11.w, r11.w
  mul r15.xyz, r11.wwww, r15.xzyx
  mul r13.xw, -r5.xxxz, cb0[228].xxxy
  frc r14.yw, r13.xxxw
  round_ni r13.xw, r13.xxxw
  dp2 r11.w, r13.xwxx, l(12.989800, 78.233002, 0.000000, 0.000000)
  sincos r11.w, null, r11.w
  mul r11.w, r11.w, l(43758.546875)
  frc r11.w, r11.w
  add r13.x, r11.w, cb0[227].x
  frc r13.x, r13.x
  mul r13.w, cb0[228].z, cb0[228].z
  mul r13.x, r13.w, r13.x
  round_ni r13.x, r13.x
  div r13.w, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[228].z
  mad r16.xy, -r5.xzxx, cb0[228].xyxx, cb0[227].zzzz
  sample_b_indexable(texture2d)(float,float,float,float) r16.xy, r16.xyxx, t11.zwxy, s2, cb0[108].x
  mad r17.xy, -r5.xzxx, cb0[228].xyxx, -cb0[227].zzzz
  sample_b_indexable(texture2d)(float,float,float,float) r16.zw, r17.xyxx, t11.xyzw, s2, cb0[108].x
  mul r16.xyzw, r16.xyzw, cb0[227].wwww
  mad r16.xyzw, r16.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), -cb0[227].wwww
  ge r11.w, l(0.500000), r11.w
  and r11.w, r11.w, l(0x3f800000)
  add r17.xy, -r14.ywyy, r14.wyww
  mad r14.yw, r11.wwww, r17.xxxy, r14.yyyw
  div r11.w, r13.x, cb0[228].z
  ge r17.x, r11.w, -r11.w
  frc r11.w, |r11.w|
  movc r11.w, r17.x, r11.w, -r11.w
  mul r11.w, r11.w, cb0[228].z
  mul r17.x, r11.w, r13.w
  add r17.zw, l(0.000000, 0.000000, -0.050000, -1.000000), cb0[228].wwwz
  mul r11.w, r13.w, r13.x
  round_ni r11.w, r11.w
  add r11.w, -r11.w, r17.w
  mul r17.y, r11.w, r13.w
  mad r13.xw, r14.yyyw, r13.wwww, r17.xxxy
  frc r13.xw, r13.xxxw
  sample_b_indexable(texture2d)(float,float,float,float) r13.xw, r13.xwxx, t11.xzwy, s1, cb0[108].x
  mul r13.xw, r13.xxxw, cb0[227].yyyy
  mad r13.xw, r13.xxxw, l(2.000000, 0.000000, 0.000000, 2.000000), -cb0[227].yyyy
  add r14.yw, r16.zzzw, r16.xxxy
  add r16.xy, r13.xwxx, r14.ywyy
  dp2 r11.w, r16.xyxx, r16.xyxx
  min r11.w, r11.w, l(1.000000)
  add r11.w, -r11.w, l(1.000000)
  sqrt r11.w, r11.w
  max r16.z, r11.w, l(0.000488281250)
  dp3 r11.w, r16.xyzx, r16.xyzx
  rsq r11.w, r11.w
  mul r16.xyz, r11.wwww, r16.xyzx
  mov r15.w, r2.x
  dp2 r18.x, r15.xwxx, r16.yzyy
  mov r19.x, r14.z
  mov r19.y, r15.z
  mov r19.z, r2.y
  dp3 r18.y, r19.xyzx, r16.xyzx
  mov r15.x, r14.x
  mov r15.z, r2.w
  dp3 r18.z, r15.xyzx, r16.xyzx
  mul r11.z, r11.z, cb0[222].x
  mul r11.z, r13.y, r11.z
  max r11.w, l(0.000488281250), cb0[228].w
  mov_sat r17.z, r17.z
  add r13.x, -r11.w, r17.z
  add r11.w, r2.z, -r11.w
  div r13.x, l(1.000000, 1.000000, 1.000000, 1.000000), r13.x
  mul_sat r11.w, r11.w, r13.x
  mad r13.x, r11.w, l(-2.000000), l(3.000000)
  mul r11.w, r11.w, r11.w
  mul r11.w, r11.w, r13.x
  mul r11.z, r11.w, r11.z
  mul r11.z, r13.z, r11.z
  mad r3.xyz, -r3.xyzx, r1.wwww, r18.xyzx
  mad r12.xyz, r11.zzzz, r3.xyzx, r2.xywx
endif
min r1.w, r10.y, r10.x
mul r3.x, r11.x, cb0[230].z
mad r3.y, -cb0[230].z, r11.x, l(1.000000)
mad r3.x, r10.w, r3.y, r3.x
mad r3.y, cb0[230].x, cb0[222].w, -cb0[222].w
add r3.z, r11.y, -cb0[222].w
div r3.y, l(1.000000, 1.000000, 1.000000, 1.000000), r3.y
mul_sat r3.y, r3.y, r3.z
mad r3.z, r3.y, l(-2.000000), l(3.000000)
mul r3.y, r3.y, r3.y
mul r3.y, r3.y, r3.z
add r3.z, -r3.x, cb0[230].y
mad r3.x, r3.y, r3.z, r3.x
add r3.x, -r3.x, l(1.000000)
mul r3.y, r3.x, r10.x
add r1.z, r1.z, l(-0.050000)
mul_sat r1.z, r1.z, l(1.052600)
add r3.z, -r2.z, l(1.000000)
mad_sat r10.w, r3.z, cb0[222].z, cb0[222].y
mad_sat r10.w, r9.w, cb0[224].z, r10.w
add r11.x, -r10.w, l(1.000000)
mad r10.w, r1.x, r11.x, r10.w
mul_sat r10.z, r10.z, l(3.33333325)
mad r11.x, r10.z, l(-2.000000), l(3.000000)
mul r10.z, r10.z, r10.z
mad r10.z, -r11.x, r10.z, l(1.000000)
mul r11.x, r10.w, cb0[222].x
add r11.y, -r1.x, l(1.000000)
mul r11.x, r11.y, r11.x
mul r11.x, r10.z, r11.x
mad r11.x, r11.x, l(-0.750000), l(1.000000)
mad r10.w, r10.w, l(-0.299999952), l(0.900000)
sqrt r11.y, r3.z
add r10.w, r10.w, r11.y
add_sat r10.w, r10.w, l(-0.600000)
max r10.w, r3.z, r10.w
min r10.w, r10.w, l(0.990000)
add_sat r11.y, l(2.000000), -cb0[222].x
mul r11.y, r11.y, cb0[222].x
mul r10.z, r10.z, r11.y
mad r3.x, -r10.x, r3.x, l(1.000000)
mul r3.x, r3.x, r10.z
add r10.x, -r3.z, r10.w
mad r3.x, r3.x, r10.x, r3.z
add r3.x, -r3.x, l(1.000000)
mul_sat r3.z, r9.w, l(20.000000)
mad r9.w, r3.z, l(-2.000000), l(3.000000)
mul r3.z, r3.z, r3.z
mul r3.z, r3.z, r9.w
mad r3.z, r3.z, l(-0.900000), l(1.000000)
mul r9.w, r3.z, r3.x
add r10.x, r10.y, l(-1.000000)
mad r10.x, r1.z, r10.x, l(1.000000)
add r10.y, -r1.z, l(1.000000)
movc r10.xy, r8.wwww, r10.xyxx, l(1.000000,1.000000,0,0)
min r1.z, r9.w, r10.x
mad r3.x, r3.x, r3.z, -r1.z
mad r1.z, r1.w, r3.x, r1.z
add r2.z, -r1.z, r2.z
mad r13.z, r3.y, r2.z, r1.z
ld_indexable(texture2d)(float,float,float,float) r10.xzw, r0.xyzz, t26.xwyz
min r1.z, r11.x, r10.y
add r2.z, -r1.z, r11.x
mad r1.z, r1.w, r2.z, r1.z
add r1.w, -r1.z, l(1.000000)
mad r1.z, r3.y, r1.w, r1.z
mul r3.xyz, r1.zzzz, r10.xzwx
mul r11.xyz, r1.xxxx, r3.xyzx
mad r10.xyz, r10.xzwx, r1.zzzz, -r11.xyzx
mad r1.z, -r1.x, l(0.040000), l(0.040000)
mad r1.xzw, r3.xxyz, r1.xxxx, r1.zzzz
dp3 r2.z, r12.xyzx, r9.xyzx
max r11.x, r2.z, l(0.000000)
mul r3.y, r13.z, r13.z
mul r14.x, r11.x, r11.x
mul r14.z, r11.x, r14.x
mul r2.z, r3.y, r3.y
mul r3.z, r3.y, r2.z
mov r11.yzw, l(0,0.0365463011,9.063200,0.990440)
dp2 r15.x, l(3.327070, 1.000000, 0.000000, 0.000000), r11.xyxx
dp2 r15.y, l(-9.047560, 1.000000, 0.000000, 0.000000), r11.xzxx
mov r3.x, l(1.000000)
dp2 r8.w, r15.xyxx, r3.xyxx
mov r14.yw, l(0,9.044010,0,1.000000)
dp3 r15.x, l(3.596850, -1.367720, 1.000000, 0.000000), r14.xzwx
dp3 r15.y, l(-16.317400, 1.000000, 9.229490, 0.000000), r14.xyzx
mov r16.x, l(5.565890)
mov r16.yz, r14.xxzx
dp3 r15.z, l(1.000000, 19.788601, -20.212299, 0.000000), r16.xyzx
dp3 r9.w, r15.xyzx, r3.xyzx
div r8.w, r8.w, r9.w
dp2 r15.x, l(-1.285140, 1.000000, 0.000000, 0.000000), r11.xwxx
mov r14.x, l(1.296780)
mov r14.y, r11.x
dp2 r15.y, l(1.000000, -0.755907, 0.000000, 0.000000), r14.xyxx
dp2 r9.w, r15.xyxx, r3.xyxx
dp3 r15.x, l(2.923380, 59.418800, 1.000000, 0.000000), r14.yzwy
mov r14.xw, l(20.322500,0,0,121.563004)
dp3 r15.y, l(1.000000, -27.030199, 222.591995, 0.000000), r14.xyzx
dp3 r15.z, l(626.130005, 316.627014, 1.000000, 0.000000), r14.yzwy
dp3 r3.x, r15.xyzx, r3.xyzx
div r3.x, r9.w, r3.x
mad r11.yzw, r1.xxzw, r8.wwww, r3.xxxx
add r3.x, r3.x, r8.w
ld_indexable(texture2d)(float,float,float,float) r3.y, r0.xyzz, t6.zxyw
lt r0.z, l(0.001000), r3.y
if_nz r0.z
  dp3 r0.z, -r9.xyzx, r12.xyzx
  add r0.z, r0.z, r0.z
  mad r14.xyz, r12.xyzx, -r0.zzzz, -r9.xyzx
  dp3 r0.z, -cb2[0].xyzx, r14.xyzx
  mad r15.xyz, cb2[0].xyzx, r0.zzzz, r14.xyzx
  lt r0.z, r0.z, cb2[4].z
  dp3 r8.w, r15.xyzx, r15.xyzx
  max r8.w, r8.w, l(0.0000610351562)
  rsq r8.w, r8.w
  mul r15.xyz, r8.wwww, r15.xyzx
  mul r15.xyz, r15.xyzx, cb2[4].yyyy
  mad r15.xyz, -cb2[0].xyzx, cb2[4].zzzz, r15.xyzx
  dp3 r8.w, r15.xyzx, r15.xyzx
  rsq r8.w, r8.w
  mul r15.xyz, r8.wwww, r15.xyzx
  movc r14.xyz, r0.zzzz, r15.xyzx, r14.xyzx
  mad r8.xyz, r8.xyzx, r7.wwww, r14.xyzx
  dp3 r0.z, r8.xyzx, r8.xyzx
  max r0.z, r0.z, l(0.0000610351562)
  rsq r0.z, r0.z
  mul r8.xyz, r0.zzzz, r8.xyzx
  dp3_sat r13.x, r14.xyzx, r12.xyzx
  dp3_sat r0.z, r12.xyzx, r8.xyzx
  min r13.y, r11.x, l(1.000000)
  mad r7.w, r0.z, r2.z, -r0.z
  mad r0.z, r7.w, r0.z, l(1.000000)
  dp3_sat r7.w, r9.xyzx, r8.xyzx
  add r7.w, -r7.w, l(1.000000)
  mul r8.x, r7.w, r7.w
  mul r8.x, r8.x, r8.x
  mul r8.y, r7.w, r8.x
  add r8.z, -r13.z, l(1.000000)
  mad r8.w, -r8.z, l(0.383026), l(-0.0761947036)
  mad r8.w, r8.z, r8.w, l(1.049970)
  mad r8.z, r8.z, r8.w, l(0.409255)
  min r8.z, r8.z, l(0.999000)
  add r8.w, -r8.z, l(1.000000)
  add r15.xyz, -r1.xzwx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mad r15.xyz, r15.xyzx, l(0.0476190485, 0.0476190485, 0.0476190485, 0.000000), r1.xzwx
  mad r7.w, -r8.x, r7.w, l(1.000000)
  mad r16.xyz, r1.xzwx, r7.wwww, r8.yyyy
  mul r0.z, r0.z, r0.z
  div r0.z, r2.z, r0.z
  mad r8.xy, -r13.yxyy, r2.zzzz, r13.yxyy
  mad r8.xy, r8.xyxx, r13.yxyy, r2.zzzz
  sqrt r8.xy, r8.xyxx
  mul r8.xy, r8.xyxx, r13.xyxx
  add r2.z, r8.y, r8.x
  add r2.z, r2.z, l(0.000100)
  div r2.z, l(0.500000), r2.z
  mul r0.z, r0.z, r2.z
  mul r16.xyz, r0.zzzz, r16.xyzx
  min r16.xyz, r16.xyzx, l(2048.000000, 2048.000000, 2048.000000, 0.000000)
  mad r17.xyzw, r13.yzxz, l(0.968750, 0.968750, 0.968750, 0.968750), l(0.015625, 0.015625, 0.015625, 0.015625)
  sample_l_indexable(texture2d)(float,float,float,float) r0.z, r17.xyxx, t12.yzxw, s1, l(0.000000)
  sample_l_indexable(texture2d)(float,float,float,float) r2.z, r17.zwzz, t12.yzxw, s1, l(0.000000)
  mul r0.z, r0.z, r2.z
  mul r0.z, r8.z, r0.z
  div r0.z, r0.z, r8.w
  mul r8.xyz, r15.xyzx, r15.xyzx
  mul r8.xyz, r0.zzzz, r8.xyzx
  mad r15.xyz, -r15.xyzx, r8.wwww, l(1.000000, 1.000000, 1.000000, 0.000000)
  div r8.xyz, r8.xyzx, r15.xyzx
  add r8.xyz, r8.xyzx, r16.xyzx
  mul r8.xyz, r8.xyzx, cb2[4].xxxx
  max r8.xyz, r8.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  min r8.xyz, r8.xyzx, l(1000.000000, 1000.000000, 1000.000000, 0.000000)
  dp3_sat r0.z, r14.xyzx, r2.xywx
  mul r14.xyz, r0.zzzz, r10.xyzx
  mad r8.xyz, r8.xyzx, r13.xxxx, r14.xyzx
  mul r8.xyz, r8.xyzx, cb2[1].xyzx
  mov r3.z, l(0.500000)
  sample_b_indexable(texture2d)(float,float,float,float) r13.xyw, r3.yzyy, t7.xywz, s1, cb0[108].x
  add r0.z, -r3.y, l(1.000000)
  mad r13.xyw, r8.xyxz, r13.xyxw, -r8.xyxz
  mad r8.xyz, r0.zzzz, r13.xywx, r8.xyzx
  sample_l_indexable(texture2d)(float,float,float,float) r0.z, r4.zwzz, t13.yzxw, s1, l(0.000000)
  min r0.z, r0.z, l(1.000000)
  mul r8.xyz, r0.zzzz, r8.xyzx
else
  mov r8.xyz, l(0,0,0,0)
endif
ne r3.yz, l(0.000000, 0.000000, 0.000000, 0.000000), cb0[112].xxyx
if_nz r3.y
  sample_b_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t4.yzxw, s0, cb0[108].x
  min r0.z, r1.y, r0.z
  dp3 r2.z, r2.xywx, r9.xyzx
  max r2.z, r2.z, l(0.000000)
  add r2.z, r0.z, r2.z
  mad r3.y, r13.z, l(-16.000000), l(-1.000000)
  exp r3.y, r3.y
  log r2.z, |r2.z|
  mul r2.z, r2.z, r3.y
  exp r2.z, r2.z
  add r2.z, r0.z, r2.z
  add r2.z, r2.z, l(-1.000000)
  mov_sat r13.xyw, r2.zzzz
  mad r14.xyz, r10.xyzx, l(2.040400, 2.040400, 2.040400, 0.000000), l(-0.332400, -0.332400, -0.332400, 0.000000)
  mul r14.xyz, r0.zzzz, r14.xyzx
  mad r14.xyz, r10.xyzx, l(-4.795100, -4.795100, -4.795100, 0.000000), r14.xyzx
  add r14.xyz, r14.xyzx, l(0.641700, 0.641700, 0.641700, 0.000000)
  mul r14.xyz, r0.zzzz, r14.xyzx
  mad r14.xyz, r10.xyzx, l(2.755200, 2.755200, 2.755200, 0.000000), r14.xyzx
  add r14.xyz, r14.xyzx, l(0.690300, 0.690300, 0.690300, 0.000000)
  mul r14.xyz, r0.zzzz, r14.xyzx
  max r14.xyz, r0.zzzz, r14.xyzx
else
  mov r13.xyw, r1.yyyy
  mov r14.xyz, r1.yyyy
endif
mad r15.xyz, r2.xywx, l(0.250000, 0.250000, 0.250000, 0.000000), r5.xyzx
round_z r0.z, cb0[212].x
mad r16.xy, r0.zzzz, l(2.083000, 4.867000, 0.000000, 0.000000), r4.xyxx
dp2 r0.z, r16.xyxx, l(0.0671105608, 0.00583714992, 0.000000, 0.000000)
frc r0.z, r0.z
mul r0.z, r0.z, l(52.982918)
frc r0.z, r0.z
mad r0.z, r0.z, l(2.000000), l(-1.000000)
mad r15.xyz, r0.zzzz, l(0.200000, 0.200000, 0.200000, 0.000000), r15.xyzx
mad r16.xyz, cb0[6].xzyx, -cb0[212].wwww, cb0[210].xzyx
add r16.xyz, r15.xzyx, -r16.xyzx
max r0.z, |r16.y|, |r16.x|
add r0.z, r0.z, l(-464.000000)
mul_sat r0.z, r0.z, l(0.031250)
add r1.y, |r16.z|, l(-208.000000)
mul_sat r1.y, r1.y, l(0.031250)
max r0.z, r0.z, r1.y
ne r1.y, l(0.000000), cb0[210].w
lt r2.z, r0.z, l(1.000000)
and r1.y, r1.y, r2.z
if_nz r1.y
  mad r16.xyz, cb0[6].xzyx, -cb0[212].yyyy, cb0[210].xzyx
  add r16.xyz, r15.xzyx, -r16.xyzx
  max r1.y, |r16.y|, |r16.x|
  add r1.y, r1.y, l(-29.000000)
  mul_sat r1.y, r1.y, l(0.500000)
  add r2.z, |r16.z|, l(-13.000000)
  mul_sat r2.z, r2.z, l(0.500000)
  max r1.y, r1.y, r2.z
  lt r2.z, r1.y, l(1.000000)
  if_nz r2.z
    mad r16.xyz, r15.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r17.xyz, r16.xyzx, cb0[211].xyzx
    round_ni r17.xyz, r17.xyzx
    mad r16.xyz, r16.xyzx, cb0[211].xyzx, -r17.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r17.xyw, r16.xyzx, t17.yzwx, s2, l(0.000000)
    add r2.z, -r1.y, l(1.000000)
    mul r3.y, l(0.500000), cb0[211].y
    mad r7.w, -cb0[211].y, l(0.500000), l(1.000000)
    max r3.y, r3.y, r16.y
    min r3.y, r7.w, r3.y
    mul r16.w, r3.y, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r18.xyzw, r16.xwzx, t18.xyzw, s1, l(0.000000)
    mad r3.y, r18.w, r2.z, r0.z
    add r19.xyz, r16.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r19.xyz, r19.xyzx, t18.xyzw, s1, l(0.000000)
    mad r19.xyz, r19.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r19.xyz, r17.yyyy, r19.xyzx
    mov r19.w, r17.y
    mul r19.xyzw, r2.zzzz, r19.xyzw
    add r16.xyz, r16.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r16.xyz, r16.xyzx, t18.xyzw, s1, l(0.000000)
    mad r16.xyz, r16.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r16.xyz, r17.xxxx, r16.xyzx
    mov r16.w, r17.x
    mul r16.xyzw, r2.zzzz, r16.xyzw
    mad r18.xyz, r18.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r17.xyz, r17.wwww, r18.xyzx
    mul r17.xyzw, r2.zzzz, r17.xyzw
  else
    mov r19.xyzw, l(0,0,0,0)
    mov r16.xyzw, l(0,0,0,0)
    mov r17.xyzw, l(0,0,0,0)
    mov r3.y, r0.z
  endif
  mad r18.xyz, cb0[6].xzyx, -cb0[212].zzzz, cb0[210].xzyx
  add r18.xyz, r15.xzyx, -r18.xyzx
  max r2.z, |r18.y|, |r18.x|
  add r2.z, r2.z, l(-116.000000)
  mul_sat r2.z, r2.z, l(0.125000)
  add r7.w, |r18.z|, l(-52.000000)
  mul_sat r7.w, r7.w, l(0.125000)
  max r2.z, r2.z, r7.w
  lt r7.w, r2.z, l(1.000000)
  if_nz r7.w
    mad r18.xyz, r15.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r20.xyz, r18.xyzx, cb0[211].xyzx
    round_ni r20.xyz, r20.xyzx
    mad r18.xyz, r18.xyzx, cb0[211].xyzx, -r20.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r20.xyw, r18.xyzx, t19.yzwx, s2, l(0.000000)
    add r7.w, -r2.z, l(1.000000)
    mul r1.y, r1.y, r7.w
    mul r7.w, l(0.500000), cb0[211].y
    mad r8.w, -cb0[211].y, l(0.500000), l(1.000000)
    max r7.w, r7.w, r18.y
    min r7.w, r8.w, r7.w
    mul r18.w, r7.w, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r21.xyzw, r18.xwzx, t20.xyzw, s1, l(0.000000)
    mad r3.y, r21.w, r1.y, r3.y
    add r22.xyz, r18.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r22.xyz, r22.xyzx, t20.xyzw, s1, l(0.000000)
    mad r22.xyz, r22.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r22.xyz, r20.yyyy, r22.xyzx
    mov r22.w, r20.y
    mad r19.xyzw, r22.xyzw, r1.yyyy, r19.xyzw
    add r18.xyz, r18.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r18.xyz, r18.xyzx, t20.xyzw, s1, l(0.000000)
    mad r18.xyz, r18.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r18.xyz, r20.xxxx, r18.xyzx
    mov r18.w, r20.x
    mad r16.xyzw, r18.xyzw, r1.yyyy, r16.xyzw
    mad r18.xyz, r21.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r20.xyz, r20.wwww, r18.xyzx
    mad r17.xyzw, r20.xyzw, r1.yyyy, r17.xyzw
  endif
  lt r1.y, l(0.000000), r2.z
  if_nz r1.y
    mad r15.xyz, r15.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r18.xyz, r15.xyzx, cb0[211].xyzx
    mul r20.xyz, l(0.500000, 0.500000, 0.500000, 0.000000), cb0[211].xyzx
    round_ni r18.xyz, r18.xyzx
    mad r15.xyz, r15.xyzx, cb0[211].xyzx, -r18.xyzx
    mad r18.xyz, -cb0[211].xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(1.000000, 1.000000, 1.000000, 0.000000)
    max r15.xyz, r20.xyzx, r15.xyzx
    min r15.xyz, r18.xyzx, r15.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r21.xyw, r15.xyzx, t21.yzwx, s2, l(0.000000)
    add r1.y, -r0.z, l(1.000000)
    mul r1.y, r1.y, r2.z
    max r2.z, r20.y, r15.y
    min r2.z, r18.y, r2.z
    mul r15.w, r2.z, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r18.xyzw, r15.xwzx, t22.xyzw, s1, l(0.000000)
    add r20.xyz, r15.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r20.xyz, r20.xyzx, t22.xyzw, s1, l(0.000000)
    mad r20.xyz, r20.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r20.xyz, r21.yyyy, r20.xyzx
    mov r20.w, r21.y
    mad r19.xyzw, r20.xyzw, r1.yyyy, r19.xyzw
    add r15.xyz, r15.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r15.xyz, r15.xyzx, t22.xyzw, s1, l(0.000000)
    mad r15.xyz, r15.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r15.xyz, r21.xxxx, r15.xyzx
    mov r15.w, r21.x
    mad r16.xyzw, r15.xyzw, r1.yyyy, r16.xyzw
    mad r15.xyz, r18.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r21.xyz, r21.wwww, r15.xyzx
    mad r17.xyzw, r21.xyzw, r1.yyyy, r17.xyzw
    mad r3.y, r18.w, r1.y, r3.y
  endif
  mad_sat r1.y, r3.y, l(2.000000), l(-1.000000)
  add r15.x, -r0.z, r1.y
  add r0.z, r0.z, r1.y
  mul r15.y, r0.z, l(0.500000)
else
  mov r19.xyzw, l(0,0,0,0)
  mov r16.xyzw, l(0,0,0,0)
  mov r17.xyzw, l(0,0,0,0)
  mov r15.xy, l(0,1.000000,0,0)
endif
mul r18.xyzw, r15.yxyy, cb0[213].ywzx
mad r18.y, r18.y, l(0.500000), r18.x
mul r15.zw, r15.yyyx, cb0[213].wwwy
mad r18.x, r15.w, l(0.375000), r15.z
add r17.xyzw, r17.xyzw, r18.wyzx
mul r18.xyzw, r15.yxyy, cb0[214].ywzx
mad r18.y, r18.y, l(0.500000), r18.x
mul r15.zw, r15.yyyx, cb0[214].wwwy
mad r18.x, r15.w, l(0.375000), r15.z
add r16.xyzw, r16.xyzw, r18.wyzx
mul r18.xyzw, r15.yxyy, cb0[215].ywzx
mad r18.y, r18.y, l(0.500000), r18.x
mul r15.xy, r15.yxyy, cb0[215].wyww
mad r18.x, r15.y, l(0.375000), r15.x
add r15.xyzw, r18.wyzx, r19.xyzw
ge r18.xy, r4.zwzz, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.z, r18.y, r18.x
if_nz r0.z
  sample_l_indexable(texture2d)(float,float,float,float) r18.xyzw, r4.zwzz, t16.xyzw, s1, l(0.000000)
  lt r19.xyzw, l(0.000100, 0.000100, 0.000100, 0.000100), |r18.xyzw|
  or r4.zw, r19.zzzw, r19.xxxy
  or r0.z, r4.w, r4.z
  if_nz r0.z
    dp3 r0.z, r18.yzwy, r18.yzwy
    sqrt r0.z, r0.z
    mov r4.z, l(1.000000)
    mov r4.w, r0.z
    mov r1.y, l(0)
    loop
      ge r2.z, l(4.600000), r4.w
      breakc_nz r2.z
      iadd r2.z, r1.y, l(1)
      mul r19.xy, r4.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
      mov r4.zw, r19.xxxy
      mov r1.y, r2.z
      continue
    endloop
    mul r18.xyzw, r4.zzzz, r18.xyzw
    dp3 r0.z, r18.yzwy, r18.yzwy
    sqrt r0.z, r0.z
    mad r0.z, r0.z, cb4[3].x, cb4[3].y
    mad r0.z, r0.z, l(255.000000), l(0.500000)
    mul r19.x, r0.z, l(0.00390625000)
    mov r19.y, l(0.500000)
    sample_l_indexable(texture2d)(float,float,float,float) r4.zw, r19.xyxx, t15.zwxy, s1, l(0.000000)
    mad r4.zw, r4.zzzw, cb4[2].xxxy, cb4[2].zzzw
    mul r19.x, r4.z, l(3.54490781)
    mul r19.yzw, r4.wwww, r18.yyzw
    mul r0.z, r18.x, l(0.406976730)
    exp r0.z, r0.z
    mul r18.xyzw, r0.zzzz, r19.xyzw
    mov r19.xyzw, r18.xyzw
    mov r0.z, l(0)
    loop
      uge r2.z, r0.z, r1.y
      breakc_nz r2.z
      mul r20.xyzw, r19.xyzw, l(0.282094777, 0.282094777, 0.282094777, 0.282094777)
      dp4 r2.z, r20.xyzw, r19.xyzw
      dp2 r3.y, r20.yxyy, r19.xyxx
      dp2 r4.z, r20.zxzz, r19.xzxx
      dp2 r4.w, r20.wxww, r19.xwxx
      iadd r7.w, r0.z, l(1)
      mov r19.x, r2.z
      mov r19.y, r3.y
      mov r19.zw, r4.zzzw
      mov r0.z, r7.w
      continue
    endloop
    mul r18.xyzw, r19.xyzw, l(0.282094777, 0.282094777, 0.282094777, 0.282094777)
    mul r19.xyzw, r17.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r0.z, r18.xyzw, r19.xyzw
    dp2 r1.y, r18.yxyy, r19.xyxx
    dp2 r2.z, r18.zxzz, r19.xzxx
    dp2 r3.y, r18.wxww, r19.xwxx
    mul r19.xyzw, r16.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r4.z, r18.xyzw, r19.xyzw
    dp2 r4.w, r18.yxyy, r19.xyxx
    dp2 r7.w, r18.zxzz, r19.xzxx
    dp2 r8.w, r18.wxww, r19.xwxx
    mul r19.xyzw, r15.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r9.w, r18.xyzw, r19.xyzw
    dp2 r10.w, r18.yxyy, r19.xyxx
    dp2 r11.x, r18.zxzz, r19.xzxx
    dp2 r14.w, r18.wxww, r19.xwxx
    mul r17.w, r0.z, l(0.886226952)
    mul r17.x, r3.y, l(-1.02332675)
    mul r17.y, r1.y, l(-1.02332675)
    mul r17.z, r2.z, l(1.02332675)
    mul r16.x, r8.w, l(-1.02332675)
    mul r16.yw, r4.wwwz, l(0.000000, -1.02332675, 0.000000, 0.886226952)
    mul r16.z, r7.w, l(1.02332675)
    mul r15.w, r9.w, l(0.886226952)
    mul r15.x, r14.w, l(-1.02332675)
    mul r15.y, r10.w, l(-1.02332675)
    mul r15.z, r11.x, l(1.02332675)
  endif
endif
dp3 r0.z, r17.xyzx, r2.xywx
add r0.z, r17.w, r0.z
max r17.x, r0.z, l(0.000000)
dp3 r0.z, r16.xyzx, r2.xywx
add r0.z, r16.w, r0.z
max r17.y, r0.z, l(0.000000)
dp3 r0.z, r15.xyzx, r2.xywx
add r0.z, r15.w, r0.z
max r17.z, r0.z, l(0.000000)
dp3 r0.z, -r9.xyzx, r12.xyzx
add r0.z, r0.z, r0.z
mad r2.xyz, r12.xyzx, -r0.zzzz, -r9.xyzx
add r0.z, l(-1.000000), cb0[113].x
max r1.y, r13.z, l(0.001000)
log r1.y, r1.y
mad r1.y, -r1.y, l(1.200000), l(1.000000)
add r0.z, r0.z, -r1.y
mul r4.zw, r4.xxxy, cb1[0].wwww
round_ni r4.zw, r4.zzzw
add r1.y, |r3.w|, -cb1[2].y
round_ni r1.y, r1.y
add r2.w, l(-1.000000), cb1[1].x
max r3.y, r1.y, l(0.000000)
min r2.w, r2.w, r3.y
ge r1.y, r2.w, r1.y
mad r3.y, r4.w, cb1[0].x, r4.z
ftoi r3.y, r3.y
iadd r3.y, r3.y, cb0[110].z
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.y, r3.y, l(0), t0.xxxx
ftoi r2.w, r2.w
iadd r2.w, r2.w, cb0[110].w
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.w, r2.w, l(0), t0.xxxx
and r2.w, r2.w, r3.y
and r1.y, r1.y, r2.w
mul r15.xyz, r17.xyzx, cb0[111].xxxx
dp3 r2.w, r15.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
mov r5.w, l(1.000000)
mov r12.w, l(1.000000)
mov r15.xyz, l(0,0,0,0)
mov r3.y, l(1.000000)
mov r4.z, r1.y
mov r4.w, l(0)
loop
  lt r7.w, l(0.010000), r3.y
  ine r8.w, r4.z, l(0)
  and r8.w, r7.w, r8.w
  if_nz r8.w
    firstbit_lo r8.w, r4.z
    ishl r9.w, l(1), r8.w
    xor r4.z, r4.z, r9.w
    ishl r8.w, r8.w, l(3)
    dp4 r16.x, cb1[r8.w + 6].xyzw, r5.xyzw
    dp4 r16.y, cb1[r8.w + 7].xyzw, r5.xyzw
    dp4 r16.z, cb1[r8.w + 8].xyzw, r5.xyzw
    ge r18.xyz, cb1[r8.w + 5].xyzx, |r16.xyzx|
    and r9.w, r18.y, r18.x
    and r9.w, r18.z, r9.w
    if_nz r9.w
      mul r9.w, l(0.100000), cb1[r8.w + 5].x
      mul r18.xyz, |r16.xyzx|, l(0.100000, 0.100000, 0.100000, 0.000000)
      mul r18.xy, r18.xyxx, r18.xyxx
      add r19.xyz, -|r16.xyzx|, cb1[r8.w + 5].xyzx
      mul r19.xyz, r19.xyzx, cb1[r8.w + 9].xyzx
      eq r10.w, l(1.000000), cb1[r8.w + 10].x
      if_nz r10.w
        dp3 r20.x, cb1[r8.w + 6].xyzx, r2.xyzx
        dp3 r20.y, cb1[r8.w + 7].xyzx, r2.xyzx
        dp3 r20.z, cb1[r8.w + 8].xyzx, r2.xyzx
        add r21.xyz, -r16.xyzx, cb1[r8.w + 5].xyzx
        div r21.xyz, r21.xyzx, r20.xyzx
        add r22.xyz, -r16.xyzx, -cb1[r8.w + 5].xyzx
        div r22.xyz, r22.xyzx, r20.xyzx
        lt r23.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r20.xyzx
        movc r21.xyz, r23.xyzx, r21.xyzx, r22.xyzx
        min r10.w, r21.y, r21.x
        min r10.w, r21.z, r10.w
        mad r16.xyz, r20.xyzx, r10.wwww, r16.xyzx
      else
        mov r16.xyz, r2.xyzx
      endif
      dp3 r10.w, r16.xyzx, r16.xyzx
      rsq r10.w, r10.w
      mul r16.xyz, r10.wwww, r16.xyzx
      lt r20.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r16.xyzx
      lt r21.xyz, r16.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
      iadd r20.xyz, -r20.xyzx, r21.xyzx
      itof r20.xyz, r20.xyzx
      dp3 r10.w, r16.xyzx, r20.xyzx
      div r16.xyz, r16.xyzx, r10.wwww
      lt r10.w, r16.z, l(0.000000)
      add r16.zw, -|r16.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
      mul r16.zw, r16.zzzw, r20.xxxy
      movc r16.xy, r10.wwww, r16.zwzz, r16.xyxx
      dp4 r10.w, cb1[r8.w + 4].xyzw, r12.xyzw
      max r10.w, r10.w, l(0.000000)
      max r10.w, r10.w, l(0.000100)
      min r11.x, r19.z, r19.y
      min r11.x, r11.x, r19.x
      add r13.z, r18.y, r18.x
      mad r13.z, r18.z, r18.z, r13.z
      mad r9.w, r9.w, r9.w, -r13.z
      mul r9.w, r9.w, cb1[r8.w + 9].x
      mul r9.w, r9.w, cb1[r8.w + 9].x
      add r13.z, l(1.000000), -cb1[r8.w + 10].y
      mul r9.w, r9.w, r13.z
      mul r9.w, r9.w, l(100.000000)
      mad_sat r9.w, r11.x, cb1[r8.w + 10].y, r9.w
      mul r11.x, r9.w, cb1[r8.w + 10].w
      mad r16.xy, r16.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
      mad r16.xy, r16.xyxx, cb1[1].wwww, cb1[2].wwww
      mov r16.z, cb1[r8.w + 5].w
      sample_l_indexable(texture2darray)(float,float,float,float) r16.xyz, r16.xyzx, t5.xyzw, s3, r0.z
      mul r16.xyz, r16.xyzx, cb1[r8.w + 9].wwww
      div r13.z, r2.w, r10.w
      min r13.z, |r13.z|, l(1.000000)
      mad r13.z, r13.z, l(2.000000), r2.w
      add r10.w, r10.w, l(2.000000)
      div r10.w, r13.z, r10.w
      add r10.w, r10.w, l(-1.000000)
      mad r10.w, r10.w, cb0[112].w, l(1.000000)
      mul r16.xyz, r10.wwww, r16.xyzx
      mul r16.xyz, r11.xxxx, r16.xyzx
      mad r15.xyz, r16.xyzx, r3.yyyy, r15.xyzx
      mad r8.w, -r9.w, cb1[r8.w + 10].w, l(1.000000)
      mul r3.y, r3.y, r8.w
    endif
    mov r4.w, l(-1)
    continue
  else
    mov r4.w, r7.w
    break
  endif
  mov r4.w, r7.w
endloop
if_nz r4.w
  dp3 r1.y, r2.xyzx, r2.xyzx
  rsq r1.y, r1.y
  mul r2.xyz, r1.yyyy, r2.xyzx
  lt r16.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r2.xyzx
  lt r18.xyz, r2.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  iadd r16.xyz, -r16.xyzx, r18.xyzx
  itof r16.xyz, r16.xyzx
  dp3 r1.y, r2.xyzx, r16.xyzx
  div r2.xyz, r2.xyzx, r1.yyyy
  lt r1.y, r2.z, l(0.000000)
  add r4.zw, -|r2.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
  mul r4.zw, r4.zzzw, r16.xxxy
  movc r2.xy, r1.yyyy, r4.zwzz, r2.xyxx
  mov r12.w, l(1.000000)
  dp4 r1.y, cb1[3].xyzw, r12.xyzw
  max r1.y, r1.y, l(0.000000)
  max r1.y, r1.y, l(0.000100)
  mad r2.xy, r2.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
  mad r2.xy, r2.xyxx, cb1[1].wwww, cb1[2].wwww
  mov r2.z, l(0)
  sample_l_indexable(texture2darray)(float,float,float,float) r2.xyz, r2.xyzx, t5.xyzw, s3, r0.z
  div r0.z, r2.w, r1.y
  min r0.z, |r0.z|, l(1.000000)
  mad r0.z, r0.z, l(2.000000), r2.w
  add r1.y, r1.y, l(2.000000)
  div r0.z, r0.z, r1.y
  add r0.z, r0.z, l(-1.000000)
  mad r0.z, r0.z, cb0[112].w, l(1.000000)
  mul r2.xyz, r0.zzzz, r2.xyzx
  mad r15.xyz, r2.xyzx, r3.yyyy, r15.xyzx
endif
mul r2.xyz, r15.xyzx, cb0[112].zzzz
mul r2.xyz, r2.xyzx, cb0[111].yyyy
if_nz r3.z
  sample_b_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t3.yzxw, s1, cb0[108].x
  sample_b_indexable(texture2d)(float,float,float,float) r12.xyz, v1.xyxx, t2.xyzw, s1, cb0[108].x
  add r1.y, -r0.z, l(1.000000)
  mul r15.xyz, r1.yyyy, r2.xyzx
  mad r2.xyz, r12.xyzx, r0.zzzz, r15.xyzx
endif
mul r10.xyz, r10.xyzx, r17.xyzx
mul r10.xyz, r10.xyzx, cb0[111].xxxx
add r0.z, -r3.x, l(1.000000)
div r0.z, r0.z, r3.x
mul r1.xyz, r0.zzzz, r1.xzwx
mad r1.xyz, r1.xyzx, r11.yzwy, r11.yzwy
mul r1.xyz, r1.xyzx, r2.xyzx
mul r1.xyz, r13.xywx, r1.xyzx
mad r1.xyz, r10.xyzx, r14.xyzx, r1.xyzx
add r1.xyz, r1.xyzx, r8.xyzx
max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r1.xyz, r1.xyzx, l(255.000000, 255.000000, 255.000000, 0.000000)
mad r0.z, r5.y, cb0[156].w, cb0[157].w
max r0.z, r0.z, l(0.010000)
mad r1.w, r6.x, cb0[154].w, -cb0[153].w
max r1.w, r1.w, l(0.000000)
mul r2.x, r0.z, l(-1.442695)
exp r2.x, r2.x
add r2.x, -r2.x, l(1.000000)
div r0.z, r2.x, r0.z
mad r2.x, r5.y, cb0[156].w, cb0[158].w
mul r2.x, r2.x, l(1.442695)
exp r2.x, r2.x
mul r0.z, r0.z, r2.x
mul r0.z, r0.z, -r1.w
mul r2.xyz, r0.zzzz, cb0[155].xyzx
mul r2.xyz, r2.xyzx, l(1.442695, 1.442695, 1.442695, 0.000000)
exp r2.xyz, r2.xyzx
dp3 r0.z, -r9.xyzx, cb0[154].xyzx
mad r1.w, cb0[155].w, cb0[155].w, l(1.000000)
dp2 r2.w, r0.zzzz, cb0[155].wwww
add r1.w, r1.w, -r2.w
lt r2.w, l(0.000000), cb0[163].z
if_nz r2.w
  and r0.w, l(7), cb0[108].w
  imad r0.xyw, r0.xyxw, l(0x0019660d, 0x0019660d, 0, 0x0019660d), l(0x3c6ef35f, 0x3c6ef35f, 0, 0x3c6ef35f)
  imad r0.x, r0.y, r0.w, r0.x
  imad r0.y, r0.w, r0.x, r0.y
  imad r0.w, r0.x, r0.y, r0.w
  imad r3.x, r0.y, r0.w, r0.x
  dp3 r0.x, -r9.xyzx, -r7.xyzx
  add r2.w, r5.y, -cb0[44].y
  lt r3.z, l(5.960464478E-08), r0.x
  div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
  and r0.x, r0.x, r3.z
  mul r0.x, r0.x, cb0[163].w
  div r3.z, l(1.000000, 1.000000, 1.000000, 1.000000), r6.x
  mul r4.z, r0.x, r3.z
  mad r4.w, r4.z, r2.w, cb0[44].y
  mad r2.w, -r4.z, r2.w, r2.w
  mul r4.z, r2.w, cb0[159].z
  max r4.z, r4.z, l(-127.000000)
  mul r2.w, r2.w, cb0[162].x
  max r2.w, r2.w, l(-127.000000)
  add r5.w, r4.w, -cb0[159].x
  mul r5.w, r5.w, cb0[159].z
  max r5.w, r5.w, l(-127.000000)
  exp r5.w, -r5.w
  mul r5.w, r5.w, cb0[159].y
  lt r7.x, l(5.960464478E-08), |r4.z|
  exp r7.y, -r4.z
  add r7.y, -r7.y, l(1.000000)
  div r7.y, r7.y, r4.z
  mad r4.z, -r4.z, l(0.240226507), l(0.693147182)
  movc r4.z, r7.x, r7.y, r4.z
  add r4.w, r4.w, -cb0[162].z
  mul r4.w, r4.w, cb0[162].x
  max r4.w, r4.w, l(-127.000000)
  exp r4.w, -r4.w
  mul r4.w, r4.w, cb0[162].y
  lt r7.x, l(5.960464478E-08), |r2.w|
  exp r7.y, -r2.w
  add r7.y, -r7.y, l(1.000000)
  div r7.y, r7.y, r2.w
  mad r2.w, -r2.w, l(0.240226507), l(0.693147182)
  movc r2.w, r7.x, r7.y, r2.w
  mul r2.w, r2.w, r4.w
  mad r2.w, r5.w, r4.z, r2.w
  mad r0.x, -r0.x, r3.z, l(1.000000)
  mul r0.x, r6.x, r0.x
  mul r0.x, r0.x, r2.w
  exp r0.x, -r0.x
  min r0.x, r0.x, l(1.000000)
  max r0.x, r0.x, cb0[161].w
  mad_sat r4.zw, r6.xxxx, cb0[160].yyyw, cb0[160].xxxz
  add r0.x, r0.x, r4.z
  add r0.x, r4.w, r0.x
  min r0.x, r0.x, l(1.000000)
  imad r3.y, r0.w, r3.x, r0.y
  ushr r0.yw, r3.xxxy, l(0, 16, 0, 16)
  utof r0.yw, r0.yyyw
  mad r0.yw, r0.yyyw, l(0.000000, 0.0000305180438, 0.000000, 0.0000305180438), l(0.000000, -1.000000, 0.000000, -1.000000)
  mad r0.yw, r0.yyyw, cb0[167].wwww, r4.xxxy
  mul r3.xy, r0.ywyy, cb0[165].xyxx
  mad r0.y, |r3.w|, cb0[164].x, cb0[164].y
  log r0.y, r0.y
  mul r0.y, r0.y, cb0[164].z
  div r3.z, r0.y, cb0[163].z
  sample_l_indexable(texture3d)(float,float,float,float) r4.xyzw, r3.xyzx, t14.xyzw, s1, l(0.000000)
  add r0.y, |r3.w|, -cb0[166].z
  mul_sat r0.y, r0.y, l(1000000.000000)
  add r3.xyzw, r4.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
  mad r3.xyzw, r0.yyyy, r3.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
  add r0.y, -r0.x, l(1.000000)
  mul r4.xyz, r0.yyyy, cb0[161].xyzx
  mad r3.xyz, r4.xyzx, r3.wwww, r3.xyzx
  mul r0.x, r0.x, r3.w
else
  add r0.y, r5.y, -cb0[44].y
  mul r0.w, r0.y, cb0[159].z
  mul r0.y, r0.y, cb0[162].x
  max r0.yw, r0.yyyw, l(0.000000, -127.000000, 0.000000, -127.000000)
  add r2.w, cb0[44].y, -cb0[159].x
  mul r2.w, r2.w, cb0[159].z
  max r2.w, r2.w, l(-127.000000)
  exp r2.w, -r2.w
  mul r2.w, r2.w, cb0[159].y
  lt r3.w, l(5.960464478E-08), |r0.w|
  exp r4.x, -r0.w
  add r4.x, -r4.x, l(1.000000)
  div r4.x, r4.x, r0.w
  mad r0.w, -r0.w, l(0.240226507), l(0.693147182)
  movc r0.w, r3.w, r4.x, r0.w
  add r3.w, cb0[44].y, -cb0[162].z
  mul r3.w, r3.w, cb0[162].x
  max r3.w, r3.w, l(-127.000000)
  exp r3.w, -r3.w
  mul r3.w, r3.w, cb0[162].y
  lt r4.x, l(5.960464478E-08), |r0.y|
  exp r4.y, -r0.y
  add r4.y, -r4.y, l(1.000000)
  div r4.y, r4.y, r0.y
  mad r0.y, -r0.y, l(0.240226507), l(0.693147182)
  movc r0.y, r4.x, r4.y, r0.y
  mul r0.y, r0.y, r3.w
  mad r0.y, r2.w, r0.w, r0.y
  mul r0.y, r6.x, r0.y
  exp r0.y, -r0.y
  min r0.y, r0.y, l(1.000000)
  max r0.y, r0.y, cb0[161].w
  mad_sat r4.xy, r6.xxxx, cb0[160].ywyy, cb0[160].xzxx
  add r0.y, r0.y, r4.x
  add r0.y, r4.y, r0.y
  min r0.x, r0.y, l(1.000000)
  add r0.y, -r0.x, l(1.000000)
  mul r3.xyz, r0.yyyy, cb0[161].xyzx
endif
mul r4.xyz, r0.xxxx, r2.xyzx
mad r0.y, r0.z, r0.z, l(1.000000)
mul r0.y, r0.y, l(0.0596831031)
mad r0.yzw, cb0[156].xxyz, r0.yyyy, cb0[158].xxyz
mad r2.w, -cb0[155].w, cb0[155].w, l(1.000000)
mul r3.w, r1.w, l(12.566371)
sqrt r1.w, r1.w
mul r1.w, r1.w, r3.w
max r1.w, r1.w, l(0.001000)
div r1.w, r2.w, r1.w
mad_sat r0.yzw, cb0[157].xxyz, r1.wwww, r0.yyzw
mul r0.yzw, r0.yyzw, l(0.000000, 255.000000, 255.000000, 255.000000)
add r2.xyz, -r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r0.yzw, r0.yyzw, r2.xxyz
mad r0.xyz, r0.yzwy, r0.xxxx, r3.xyzx

// === Simplified Fog Modification (Anti-Banding) ===
// Check if fog modification is enabled via cb13[12].y
lt r15.x, l(0.500000), cb13[12].y
if_nz r15.x
  // r1.xyz = scene color, r4.xyz = transmittance, r0.xyz = fog inscatter
  // Boost transmittance: lerp(trans, 1, 0.35) to reduce fog density
  add r15.xyz, -r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mad r15.xyz, r15.xyzx, l(0.350000, 0.350000, 0.350000, 0.000000), r4.xyzx
  
  // Reduce fog inscatter intensity
  mul r16.xyz, r0.xyzx, l(0.650000, 0.650000, 0.650000, 0.000000)
  
  // Modified fog blend: scene * boostedTrans + reducedInscatter
  mad r0.xyz, r1.xyzx, r15.xyzx, r16.xyzx
else
  // Original fog blend
  mad r0.xyz, r1.xyzx, r4.xyzx, r0.xyzx
endif
// === End Fog Modification ===
dp3 r0.w, r4.xyzx, l(0.333333343, 0.333333343, 0.333333343, 0.000000)
dp3 r1.w, r6.yzwy, r6.yzwy
sqrt r1.w, r1.w
mad_sat r1.w, -r1.w, cb0[169].z, l(1.000000)
mul r2.x, r1.w, cb0[169].x
mad r1.w, -cb0[169].x, r1.w, l(1.000000)
mul r2.yzw, cb0[168].xxyz, cb0[183].wwww
mad r2.yzw, r5.xxyz, cb0[169].yyyy, r2.yyzw
sample_l_indexable(texture3d)(float,float,float,float) r2.y, r2.yzwy, t27.xwyz, s2, l(0.000000)
dp2 r2.x, r2.yyyy, r2.xxxx
add r1.w, r1.w, r2.x
add r2.x, r0.w, l(1.000000)
min r1.w, r1.w, r2.x
add r0.xyz, -r1.xyzx, r0.xyzx
mad o0.xyz, r1.wwww, r0.xyzx, r1.xyzx
mov o0.w, r0.w
ret
// Approximately 0 instruction slots used
