//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.4.1 on Sun Feb  1 03:51:02 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy
// TEXCOORD                 0   xy          1     NONE   float   xy
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[235], immediateIndexed
dcl_constantbuffer CB1[259], dynamicIndexed
dcl_constantbuffer CB2[5], immediateIndexed
dcl_constantbuffer CB3[5], immediateIndexed
dcl_constantbuffer CB4[4], immediateIndexed
dcl_constantbuffer CB13[15], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_comparison
dcl_resource_structured t0, 4
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2darray (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture3d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture3d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t14
dcl_resource_texture3d (float,float,float,float) t15
dcl_resource_texture3d (float,float,float,float) t16
dcl_resource_texture3d (float,float,float,float) t17
dcl_resource_texture3d (float,float,float,float) t18
dcl_resource_texture3d (float,float,float,float) t19
dcl_resource_texture3d (float,float,float,float) t20
dcl_resource_texture2d (float,float,float,float) t21
dcl_resource_texture2d (float,float,float,float) t22
dcl_resource_texture2d (float,float,float,float) t23
dcl_resource_texture2d (float,float,float,float) t24
dcl_resource_texture3d (float,float,float,float) t25
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 26
ftou r0.xy, v0.xyxx
mov r0.z, l(0)
ld_indexable(texture2d)(float,float,float,float) r1.xyzw, r0.xyzz, t22.xyzw
ld_indexable(texture2d)(float,float,float,float) r2.xyzw, r0.xyzz, t23.xyzw
ld_indexable(texture2d)(float,float,float,float) r3.xyzw, r0.xyzz, t24.xyzw
mul r1.xyz, r1.xyzx, l(1023.000000, 1023.000000, 1023.000000, 0.000000)
ftou r1.xz, r1.xxzx
ubfe r4.x, l(7), l(3), r1.x
utof r4.x, r4.x
round_ne r1.y, r1.y
ftou r1.y, r1.y
mad r2.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r4.y, l(1.000000, 1.000000, 0.000000, 0.000000), |r2.xyxx|
add r5.y, -r4.y, l(1.000000)
lt r4.y, r5.y, l(0.000000)
ge r4.zw, r2.xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
add r6.xy, -|r2.yxyy|, l(1.000000, 1.000000, 0.000000, 0.000000)
movc r4.zw, r4.zzzw, l(0,0,1.000000,1.000000), l(0,0,-1.000000,-1.000000)
mul r4.zw, r4.zzzw, r6.xxxy
movc r5.xz, r4.yyyy, r4.zzwz, r2.xxyx
dp3 r2.x, r5.xyzx, r5.xyzx
rsq r2.x, r2.x
mul r6.xyz, r2.xxxx, r5.xyzx
and r2.y, r1.y, l(7)
utof r2.y, r2.y
mad r2.y, r2.y, l(0.107142866), l(0.500000)
utof r4.yz, r0.xxyx
mul r5.xz, v0.xxyx, cb0[82].zzwz
mad r7.xy, r5.xzxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
add r7.zw, r4.yyyz, l(0.000000, 0.000000, 0.500000, 0.500000)
mul r7.zw, r7.zzzw, cb0[82].zzzw
sample_l_indexable(texture2d)(float,float,float,float) r4.w, r7.zwzz, t1.yzwx, s0, l(0.000000)
mul r8.xyzw, -r7.yyyy, cb0[25].xyzw
mad r7.xyzw, cb0[24].xyzw, r7.xxxx, r8.xyzw
mad r7.xyzw, cb0[26].xyzw, r4.wwww, r7.xyzw
add r7.xyzw, r7.xyzw, cb0[27].xyzw
div r7.xyz, r7.xyzx, r7.wwww
mul r4.w, r7.y, cb0[1].z
mad r4.w, cb0[0].z, r7.x, r4.w
mad r4.w, cb0[2].z, r7.z, r4.w
add r4.w, r4.w, cb0[3].z
eq r5.w, l(0.000000), cb0[86].w
add r8.xyz, -r7.xyzx, cb0[44].xyzx
mov r9.x, cb0[0].z
mov r9.y, cb0[1].z
mov r9.z, cb0[2].z
movc r10.xyz, r5.wwww, r8.xyzx, r9.xyzx
dp3 r5.w, r10.xyzx, r10.xyzx
max r8.w, r5.w, l(9.999999939E-09)
rsq r8.w, r8.w
mul r11.xyz, r8.wwww, r10.xyzx
mul r5.w, r5.w, r8.w
lt r9.w, l(0.000488281250), cb0[234].x
if_nz r9.w
  sample_b_indexable(texture2d)(float,float,float,float) r9.w, v1.xyxx, t21.yzwx, s1, cb0[108].x
else
  mov r9.w, l(1.000000)
endif
lt r12.xy, l(0.500000, 0.500000, 0.000000, 0.000000), cb0[226].xyxx
if_nz r12.x
  add r10.w, |r6.y|, |r6.x|
  add r10.w, |r6.z|, r10.w
  div r10.w, l(1.000000, 1.000000, 1.000000, 1.000000), r10.w
  mul r12.xzw, |r6.xxyz|, r10.wwww
  mul r13.xyzw, r12.xxzz, l(0.000000, 1.000000, 0.707106, 0.000000)
  add r13.xyz, r13.zwzz, r13.xxyx
  mad r12.xzw, r12.wwww, l(1.000000, 0.000000, 0.000000, 0.000000), r13.xxyz
  mul r13.xyz, r7.xyzx, cb0[229].xxxx
  sample_l_indexable(texture3d)(float,float,float,float) r10.w, r13.xyzx, t9.yzwx, s2, l(0.000000)
  mad r10.w, r10.w, l(2.000000), l(-1.000000)
  mul r12.xzw, r10.wwww, r12.xxzw
  mov r10.w, |r6.y|
  add r10.w, r10.w, l(-0.700000)
  mul_sat r10.w, r10.w, l(4.000000)
  mad r11.w, r10.w, l(-2.000000), l(3.000000)
  mul r10.w, r10.w, r10.w
  mul r10.w, r10.w, r11.w
  add r11.w, -cb0[229].z, cb0[229].y
  mad r10.w, r10.w, r11.w, cb0[229].z
  mul r12.xzw, r10.wwww, r12.xxzw
else
  mov r12.xzw, l(0,0,0,0)
endif
if_nz r12.y
  mul r13.xyz, r6.xyzx, cb0[233].zzzz
  mul r14.xyz, l(0.000000, 1.000000, 0.000000, 0.000000), cb0[225].yyyy
  mad r13.xyz, r13.xyzx, cb0[225].xxxx, r14.xyzx
  max r10.w, -r6.y, l(0.000000)
  min r10.w, r10.w, l(0.900000)
  add r10.w, -r10.w, l(1.000000)
  mad r2.x, -r5.y, r2.x, l(-0.200000)
  mul_sat r2.x, r2.x, l(-10.000000)
  mad r5.y, r2.x, l(-2.000000), l(3.000000)
  mul r2.x, r2.x, r2.x
  mul r2.x, r2.x, r5.y
  max r2.x, r2.x, l(0.100000)
  min r2.x, r2.x, l(1.000000)
  mul r2.x, r2.x, r10.w
  mad r13.xyz, r13.xyzx, r2.xxxx, r7.xyzx
  add r12.xyz, r12.xzwx, r13.xyzx
  mul r13.xyz, r12.yyyy, cb3[1].xyzx
  mad r12.xyw, cb3[0].xyxz, r12.xxxx, r13.xyxz
  mad r12.xyz, cb3[2].xyzx, r12.zzzz, r12.xywx
  add r12.xyz, r12.xyzx, cb3[3].xyzx
  mad r13.x, r12.x, l(0.500000), cb3[4].x
  mad r2.x, r12.y, l(0.500000), l(0.500000)
  add r13.z, -r2.x, cb3[4].y
  add r12.xy, r13.xzxx, l(0.500000, 1.000000, 0.000000, 0.000000)
  max r2.x, r12.z, l(0.000488281250)
  sample_c_lz_indexable(texture2d)(float,float,float,float) r2.x, r12.xyxx, t8.xxxx, s4, r2.x
else
  mov r2.x, l(1.000000)
endif
mov_sat r5.y, r6.y
add r10.w, l(1.000000), -cb0[230].w
mad r5.y, r5.y, r10.w, cb0[230].w
add r12.xy, r7.xzxx, -cb0[44].xzxx
max r10.w, |r12.y|, |r12.x|
mul r11.w, r5.y, cb0[230].z
mul r12.x, r2.x, r5.y
mul r12.y, l(0.0500000119), cb0[222].w
mad r12.z, -cb0[222].w, l(0.700000), r10.w
div r12.y, l(1.000000, 1.000000, 1.000000, 1.000000), r12.y
mul_sat r12.y, r12.y, r12.z
mad r12.z, r12.y, l(-2.000000), l(3.000000)
mul r12.y, r12.y, r12.y
mul r12.y, r12.y, r12.z
mad r2.x, -r5.y, r2.x, l(1.000000)
mad r2.x, r12.y, r2.x, r12.x
mad r5.y, -cb0[230].z, r5.y, l(1.000000)
mad r2.x, r2.x, r5.y, r11.w
mad r5.y, cb0[230].x, cb0[222].w, -cb0[222].w
add r10.w, r10.w, -cb0[222].w
div r5.y, l(1.000000, 1.000000, 1.000000, 1.000000), r5.y
mul_sat r5.y, r5.y, r10.w
mad r10.w, r5.y, l(-2.000000), l(3.000000)
mul r5.y, r5.y, r5.y
mul r5.y, r5.y, r10.w
add r10.w, -r2.x, cb0[230].y
mad r2.x, r5.y, r10.w, r2.x
add r2.x, -r2.x, l(1.000000)
mad r2.x, -r9.w, r2.x, l(1.000000)
mad_sat r5.y, r2.z, l(0.300000), l(0.250000)
mul r5.y, r5.y, cb0[222].x
mul r5.y, r2.x, r5.y
mad r5.y, r5.y, l(-0.750000), l(1.000000)
mul r3.xyz, r3.xyzx, r5.yyyy
min r5.y, r2.z, l(0.300000)
mul r2.x, r2.x, cb0[222].x
mul r2.xw, r2.xxxw, l(0.500000, 0.000000, 0.000000, 3.000000)
add r5.y, -r2.z, r5.y
mad r12.z, r2.x, r5.y, r2.z
mul r2.x, r2.y, l(0.080000)
dp3 r2.z, r6.xyzx, r11.xyzx
max r5.y, r2.z, l(0.000000)
mad r13.xyzw, r12.zzzz, l(-1.000000, -0.027500, -0.572000, 0.022000), l(1.000000, 0.042500, 1.040000, -0.040000)
mul r9.w, r13.x, r13.x
mul r10.w, r5.y, l(-9.280000)
exp r10.w, r10.w
min r9.w, r9.w, r10.w
mad r9.w, r9.w, r13.x, r13.y
mad r13.xy, r9.wwww, l(-1.040000, 1.040000, 0.000000, 0.000000), r13.zwzz
ld_indexable(texture2d)(float,float,float,float) r13.z, r0.xyzz, t6.zwxy
lt r0.z, l(0.001000), r13.z
if_nz r0.z
  bfi r0.z, l(3), l(2), r1.x, l(0)
  mul r1.x, r1.w, l(3.000000)
  ftou r1.x, r1.x
  bfi r0.z, l(2), l(0), r1.x, r0.z
  utof r0.z, r0.z
  mul r1.x, r0.z, l(0.0322580636)
  ubfe r1.y, l(7), l(3), r1.y
  utof r1.y, r1.y
  mul r1.y, r1.y, l(0.00787401572)
  sample_l_indexable(texture2d)(float,float,float,float) r1.w, r5.xzxx, t11.yzwx, s1, l(0.000000)
  dp3 r9.w, -r11.xyzx, r6.xyzx
  add r9.w, r9.w, r9.w
  mad r14.xyz, r6.xyzx, -r9.wwww, -r11.xyzx
  dp3 r9.w, -cb2[0].xyzx, r14.xyzx
  mad r15.xyz, cb2[0].xyzx, r9.wwww, r14.xyzx
  lt r9.w, r9.w, cb2[4].z
  dp3 r10.w, r15.xyzx, r15.xyzx
  max r10.w, r10.w, l(0.0000610351562)
  rsq r10.w, r10.w
  mul r15.xyz, r10.wwww, r15.xyzx
  mul r15.xyz, r15.xyzx, cb2[4].yyyy
  mad r15.xyz, -cb2[0].xyzx, cb2[4].zzzz, r15.xyzx
  dp3 r10.w, r15.xyzx, r15.xyzx
  rsq r10.w, r10.w
  mul r15.xyz, r10.wwww, r15.xyzx
  movc r14.xyz, r9.wwww, r15.xyzx, r14.xyzx
  mad r10.xyz, r10.xyzx, r8.wwww, r14.xyzx
  dp3 r8.w, r10.xyzx, r10.xyzx
  max r8.w, r8.w, l(0.0000610351562)
  rsq r8.w, r8.w
  mul r10.xyz, r8.wwww, r10.xyzx
  dp3 r8.w, r6.xyzx, r14.xyzx
  mov_sat r12.x, r8.w
  dp3_sat r9.w, r6.xyzx, r10.xyzx
  dp3 r10.w, r11.xyzx, r14.xyzx
  min r12.y, r5.y, l(1.000000)
  mul r11.w, r12.z, r12.z
  mul r11.w, r11.w, r11.w
  mad r12.w, r9.w, r11.w, -r9.w
  mad r9.w, r12.w, r9.w, l(1.000000)
  dp3_sat r10.x, r11.xyzx, r10.xyzx
  add r10.x, -r10.x, l(1.000000)
  mul r10.y, r10.x, r10.x
  mul r10.y, r10.y, r10.y
  mul r10.z, r10.x, r10.y
  add r12.w, -r12.z, l(1.000000)
  mad r14.x, -r12.w, l(0.383026), l(-0.0761947036)
  mad r14.x, r12.w, r14.x, l(1.049970)
  mad r12.w, r12.w, r14.x, l(0.409255)
  min r12.w, r12.w, l(0.999000)
  add r14.x, -r12.w, l(1.000000)
  mad r2.y, -r2.y, l(0.080000), l(1.000000)
  mad r2.y, r2.y, l(0.0476190485), r2.x
  mov_sat r14.y, -r10.w
  mul r14.y, r14.y, r14.y
  mad r14.y, r14.y, l(-0.640000), l(1.000000)
  mul r14.y, r14.y, r14.y
  mad r10.x, -r10.y, r10.x, l(1.000000)
  mad r10.x, r2.x, r10.x, r10.z
  mul r9.w, r9.w, r9.w
  div r9.w, r11.w, r9.w
  mad r10.yz, -r12.yyxy, r11.wwww, r12.yyxy
  mad r10.yz, r10.yyzy, r12.yyxy, r11.wwww
  sqrt r10.yz, r10.yyzy
  mul r10.yz, r10.yyzy, r12.xxyx
  add r10.y, r10.z, r10.y
  add r10.y, r10.y, l(0.000100)
  div r10.y, l(0.500000), r10.y
  mul r9.w, r9.w, r10.y
  mul r9.w, r9.w, r10.x
  min r9.w, r9.w, l(2048.000000)
  mad r15.xyzw, r12.yzxz, l(0.968750, 0.968750, 0.968750, 0.968750), l(0.015625, 0.015625, 0.015625, 0.015625)
  sample_l_indexable(texture2d)(float,float,float,float) r10.x, r15.xyxx, t10.xyzw, s1, l(0.000000)
  sample_l_indexable(texture2d)(float,float,float,float) r10.y, r15.zwzz, t10.yxzw, s1, l(0.000000)
  mul r10.x, r10.y, r10.x
  mul r10.x, r12.w, r10.x
  div r10.x, r10.x, r14.x
  mul r10.y, r2.y, r2.y
  mul r10.x, r10.x, r10.y
  mad r2.y, -r2.y, r14.x, l(1.000000)
  div r2.y, r10.x, r2.y
  add r2.y, r2.y, r9.w
  add_sat r2.z, r2.z, l(0.200000)
  mov_sat r9.w, r10.w
  add r9.w, r9.w, l(0.500000)
  min r9.w, r9.w, l(1.000000)
  mul r10.x, r2.z, r9.w
  add_sat r10.y, r10.w, l(1.000000)
  mad r2.z, -r2.z, r9.w, l(1.000000)
  mad r2.z, r10.y, r2.z, r10.x
  mul r2.y, r2.z, r2.y
  mul r2.y, r1.y, r2.y
  mul r10.xyz, r1.yyyy, r3.xyzx
  ubfe r2.z, l(7), l(3), r1.z
  utof r2.z, r2.z
  mul r2.z, r2.z, l(0.00787401572)
  mul r2.y, r2.y, cb2[4].x
  max r2.y, r2.y, l(0.000000)
  min r2.y, r2.y, l(1000.000000)
  mul r2.y, r12.x, r2.y
  mad r10.xyz, r10.xyzx, r2.zzzz, r2.yyyy
  max r2.y, r3.y, r3.x
  max r2.y, r3.z, r2.y
  max r2.y, r2.y, l(0.010000)
  div r14.xzw, r3.xxyz, r2.yyyy
  mul r2.y, r4.x, l(0.00393700786)
  mul r14.xzw, r2.yyyy, r14.xxzw
  add_sat r2.y, -r8.w, l(0.500000)
  ne r2.z, r14.y, l(0.360000)
  div r9.w, l(0.360000), r14.y
  movc r2.z, r2.z, r9.w, l(1.000000)
  mul r2.y, r2.z, r2.y
  mad_sat r0.z, r0.z, l(0.0322580636), r8.w
  add r0.z, -r12.x, r0.z
  mul r12.xyw, r0.zzzz, r3.xyxz
  mad r12.xyw, r14.xzxw, r2.yyyy, r12.xyxw
  mad r10.xyz, r12.xywx, r1.yyyy, r10.xyzx
  mul r10.xyz, r10.xyzx, cb2[1].xyzx
  mov r13.w, l(0.500000)
  sample_b_indexable(texture2d)(float,float,float,float) r12.xyw, r13.zwzz, t7.xywz, s1, cb0[108].x
  add r0.z, -r13.z, l(1.000000)
  mad r12.xyw, r10.xyxz, r12.xyxw, -r10.xyxz
  mad r10.xyz, r0.zzzz, r12.xywx, r10.xyzx
  max r0.z, r1.y, r1.w
  add r0.z, -r1.w, r0.z
  mad r0.z, r1.x, r0.z, r1.w
  mul r1.xyw, r0.zzzz, r10.xyxz
else
  mov r1.xyw, l(0,0,0,0)
endif
ne r2.yz, l(0.000000, 0.000000, 0.000000, 0.000000), cb0[112].xxyx
movc r2.y, cb13[14].z, l(0xFFFFFFFF), r2.y
if_nz r2.y
  sample_b_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t4.yzxw, s0, cb0[108].x
  mad r0.z, r0.z, l(0.750000), l(0.250000)
  min r0.z, r3.w, r0.z
  add r2.y, r0.z, r5.y
  mad r8.w, r12.z, l(-16.000000), l(-1.000000)
  exp r8.w, r8.w
  log r2.y, |r2.y|
  mul r2.y, r2.y, r8.w
  exp r2.y, r2.y
  add r2.y, r0.z, r2.y
  add r2.y, r2.y, l(-1.000000)
  mov_sat r10.xyz, r2.yyyy
  mad r12.xyw, r3.xyxz, l(2.040400, 2.040400, 0.000000, 2.040400), l(-0.332400, -0.332400, 0.000000, -0.332400)
  mul r12.xyw, r0.zzzz, r12.xyxw
  mad r12.xyw, r3.xyxz, l(-4.795100, -4.795100, 0.000000, -4.795100), r12.xyxw
  add r12.xyw, r12.xyxw, l(0.641700, 0.641700, 0.000000, 0.641700)
  mul r12.xyw, r0.zzzz, r12.xyxw
  mad r12.xyw, r3.xyxz, l(2.755200, 2.755200, 0.000000, 2.755200), r12.xyxw
  add r12.xyw, r12.xyxw, l(0.690300, 0.690300, 0.000000, 0.690300)
  mul r12.xyw, r0.zzzz, r12.xyxw
  max r12.xyw, r0.zzzz, r12.xyxw
else
  mov r10.xyz, r3.wwww
  mov r12.xyw, r3.wwww
endif
movc r10.xyz, cb13[14].zzzz, r10.xyzx, l(1.0, 1.0, 1.0, 0)
mul r1.xyw, r1.xyzw, r10.xyxz
mad r14.xyz, cb0[6].xzyx, -cb0[212].wwww, cb0[210].xzyx
add r14.xyz, r7.xzyx, -r14.xyzx
max r0.z, |r14.y|, |r14.x|
add r0.z, r0.z, l(-464.000000)
mul_sat r0.z, r0.z, l(0.031250)
add r2.y, |r14.z|, l(-208.000000)
mul_sat r2.y, r2.y, l(0.031250)
max r0.z, r0.z, r2.y
ne r2.y, l(0.000000), cb0[210].w
lt r3.w, r0.z, l(1.000000)
and r2.y, r2.y, r3.w
if_nz r2.y
  mad r14.xyz, cb0[6].xzyx, -cb0[212].yyyy, cb0[210].xzyx
  add r14.xyz, r7.xzyx, -r14.xyzx
  max r2.y, |r14.y|, |r14.x|
  add r2.y, r2.y, l(-29.000000)
  mul_sat r2.y, r2.y, l(0.500000)
  add r3.w, |r14.z|, l(-13.000000)
  mul_sat r3.w, r3.w, l(0.500000)
  max r2.y, r2.y, r3.w
  lt r3.w, r2.y, l(1.000000)
  if_nz r3.w
    mad r14.xyz, r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r15.xyz, r14.xyzx, cb0[211].xyzx
    round_ni r15.xyz, r15.xyzx
    mad r14.xyz, r14.xyzx, cb0[211].xyzx, -r15.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r15.xyw, r14.xyzx, t15.yzwx, s2, l(0.000000)
    add r3.w, -r2.y, l(1.000000)
    mul r8.w, l(0.500000), cb0[211].y
    mad r9.w, -cb0[211].y, l(0.500000), l(1.000000)
    max r8.w, r8.w, r14.y
    min r8.w, r9.w, r8.w
    mul r14.w, r8.w, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r16.xyzw, r14.xwzx, t16.xyzw, s1, l(0.000000)
    mad r8.w, r16.w, r3.w, r0.z
    add r17.xyz, r14.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r17.xyz, r17.xyzx, t16.xyzw, s1, l(0.000000)
    mad r17.xyz, r17.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r17.xyz, r15.yyyy, r17.xyzx
    mov r17.w, r15.y
    mul r17.xyzw, r3.wwww, r17.xyzw
    add r14.xyz, r14.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r14.xyz, r14.xyzx, t16.xyzw, s1, l(0.000000)
    mad r14.xyz, r14.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r14.xyz, r15.xxxx, r14.xyzx
    mov r14.w, r15.x
    mul r14.xyzw, r3.wwww, r14.xyzw
    mad r16.xyz, r16.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r15.xyz, r15.wwww, r16.xyzx
    mul r15.xyzw, r3.wwww, r15.xyzw
  else
    mov r17.xyzw, l(0,0,0,0)
    mov r14.xyzw, l(0,0,0,0)
    mov r15.xyzw, l(0,0,0,0)
    mov r8.w, r0.z
  endif
  mad r16.xyz, cb0[6].xzyx, -cb0[212].zzzz, cb0[210].xzyx
  add r16.xyz, r7.xzyx, -r16.xyzx
  max r3.w, |r16.y|, |r16.x|
  add r3.w, r3.w, l(-116.000000)
  mul_sat r3.w, r3.w, l(0.125000)
  add r9.w, |r16.z|, l(-52.000000)
  mul_sat r9.w, r9.w, l(0.125000)
  max r3.w, r3.w, r9.w
  lt r9.w, r3.w, l(1.000000)
  if_nz r9.w
    mad r16.xyz, r7.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r18.xyz, r16.xyzx, cb0[211].xyzx
    round_ni r18.xyz, r18.xyzx
    mad r16.xyz, r16.xyzx, cb0[211].xyzx, -r18.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r18.xyw, r16.xyzx, t17.yzwx, s2, l(0.000000)
    add r9.w, -r3.w, l(1.000000)
    mul r2.y, r2.y, r9.w
    mul r9.w, l(0.500000), cb0[211].y
    mad r10.w, -cb0[211].y, l(0.500000), l(1.000000)
    max r9.w, r9.w, r16.y
    min r9.w, r10.w, r9.w
    mul r16.w, r9.w, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r19.xyzw, r16.xwzx, t18.xyzw, s1, l(0.000000)
    mad r8.w, r19.w, r2.y, r8.w
    add r20.xyz, r16.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r20.xyz, r20.xyzx, t18.xyzw, s1, l(0.000000)
    mad r20.xyz, r20.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r20.xyz, r18.yyyy, r20.xyzx
    mov r20.w, r18.y
    mad r17.xyzw, r20.xyzw, r2.yyyy, r17.xyzw
    add r16.xyz, r16.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r16.xyz, r16.xyzx, t18.xyzw, s1, l(0.000000)
    mad r16.xyz, r16.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r16.xyz, r18.xxxx, r16.xyzx
    mov r16.w, r18.x
    mad r14.xyzw, r16.xyzw, r2.yyyy, r14.xyzw
    mad r16.xyz, r19.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r18.xyz, r18.wwww, r16.xyzx
    mad r15.xyzw, r18.xyzw, r2.yyyy, r15.xyzw
  endif
  lt r2.y, l(0.000000), r3.w
  if_nz r2.y
    mad r16.xyz, r7.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r18.xyz, r16.xyzx, cb0[211].xyzx
    mul r19.xyz, l(0.500000, 0.500000, 0.500000, 0.000000), cb0[211].xyzx
    round_ni r18.xyz, r18.xyzx
    mad r16.xyz, r16.xyzx, cb0[211].xyzx, -r18.xyzx
    mad r18.xyz, -cb0[211].xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(1.000000, 1.000000, 1.000000, 0.000000)
    max r16.xyz, r19.xyzx, r16.xyzx
    min r16.xyz, r18.xyzx, r16.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r20.xyw, r16.xyzx, t19.yzwx, s2, l(0.000000)
    add r2.y, -r0.z, l(1.000000)
    mul r2.y, r2.y, r3.w
    max r3.w, r19.y, r16.y
    min r3.w, r18.y, r3.w
    mul r16.w, r3.w, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r18.xyzw, r16.xwzx, t20.xyzw, s1, l(0.000000)
    add r19.xyz, r16.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r19.xyz, r19.xyzx, t20.xyzw, s1, l(0.000000)
    mad r19.xyz, r19.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r19.xyz, r20.yyyy, r19.xyzx
    mov r19.w, r20.y
    mad r17.xyzw, r19.xyzw, r2.yyyy, r17.xyzw
    add r16.xyz, r16.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r16.xyz, r16.xyzx, t20.xyzw, s1, l(0.000000)
    mad r16.xyz, r16.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r16.xyz, r20.xxxx, r16.xyzx
    mov r16.w, r20.x
    mad r14.xyzw, r16.xyzw, r2.yyyy, r14.xyzw
    mad r16.xyz, r18.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r20.xyz, r20.wwww, r16.xyzx
    mad r15.xyzw, r20.xyzw, r2.yyyy, r15.xyzw
    mad r8.w, r18.w, r2.y, r8.w
  endif
  mad_sat r2.y, r8.w, l(2.000000), l(-1.000000)
  add r16.x, -r0.z, r2.y
  add r0.z, r0.z, r2.y
  mul r16.y, r0.z, l(0.500000)
else
  mov r17.xyzw, l(0,0,0,0)
  mov r14.xyzw, l(0,0,0,0)
  mov r15.xyzw, l(0,0,0,0)
  mov r16.xy, l(0,1.000000,0,0)
endif
mul r18.xyzw, r16.yyyx, cb0[213].xyzw
mad r18.y, r18.w, l(0.500000), r18.y
mul r13.zw, r16.yyyx, cb0[213].wwwy
mad r18.w, r13.w, l(0.375000), r13.z
add r15.xyzw, r15.xyzw, r18.xyzw
mul r18.xyzw, r16.yyyx, cb0[214].xyzw
mad r18.y, r18.w, l(0.500000), r18.y
mul r13.zw, r16.yyyx, cb0[214].wwwy
mad r18.w, r13.w, l(0.375000), r13.z
add r14.xyzw, r14.xyzw, r18.xyzw
mul r18.xyzw, r16.yyyx, cb0[215].xyzw
mad r18.y, r18.w, l(0.500000), r18.y
mul r13.zw, r16.yyyx, cb0[215].wwwy
mad r18.w, r13.w, l(0.375000), r13.z
add r16.xyzw, r17.xyzw, r18.xyzw
ge r13.zw, r5.xxxz, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.z, r13.w, r13.z
if_nz r0.z
  sample_l_indexable(texture2d)(float,float,float,float) r17.xyzw, r5.xzxx, t14.xyzw, s1, l(0.000000)
  lt r18.xyzw, l(0.000100, 0.000100, 0.000100, 0.000100), |r17.xyzw|
  or r5.xz, r18.zzwz, r18.xxyx
  or r0.z, r5.z, r5.x
  if_nz r0.z
    dp3 r0.z, r17.yzwy, r17.yzwy
    sqrt r0.z, r0.z
    mov r5.x, l(1.000000)
    mov r5.z, r0.z
    mov r2.y, l(0)
    loop
      ge r3.w, l(4.600000), r5.z
      breakc_nz r3.w
      iadd r3.w, r2.y, l(1)
      mul r13.zw, r5.xxxz, l(0.000000, 0.000000, 0.500000, 0.500000)
      mov r5.xz, r13.zzwz
      mov r2.y, r3.w
      continue
    endloop
    mul r17.xyzw, r5.xxxx, r17.xyzw
    dp3 r0.z, r17.yzwy, r17.yzwy
    sqrt r0.z, r0.z
    mad r0.z, r0.z, cb4[3].x, cb4[3].y
    mad r0.z, r0.z, l(255.000000), l(0.500000)
    mul r18.x, r0.z, l(0.00390625000)
    mov r18.y, l(0.500000)
    sample_l_indexable(texture2d)(float,float,float,float) r5.xz, r18.xyxx, t13.xzyw, s1, l(0.000000)
    mad r5.xz, r5.xxzx, cb4[2].xxyx, cb4[2].zzwz
    mul r18.x, r5.x, l(3.54490781)
    mul r18.yzw, r5.zzzz, r17.yyzw
    mul r0.z, r17.x, l(0.406976730)
    exp r0.z, r0.z
    mul r17.xyzw, r0.zzzz, r18.xyzw
    mov r18.xyzw, r17.xyzw
    mov r0.z, l(0)
    loop
      uge r3.w, r0.z, r2.y
      breakc_nz r3.w
      mul r19.xyzw, r18.xyzw, l(0.282094777, 0.282094777, 0.282094777, 0.282094777)
      dp4 r3.w, r19.xyzw, r18.xyzw
      dp2 r5.x, r19.yxyy, r18.xyxx
      dp2 r5.z, r19.zxzz, r18.xzxx
      dp2 r8.w, r19.wxww, r18.xwxx
      iadd r9.w, r0.z, l(1)
      mov r18.x, r3.w
      mov r18.yz, r5.xxzx
      mov r18.w, r8.w
      mov r0.z, r9.w
      continue
    endloop
    mul r17.xyzw, r18.xyzw, l(0.282094777, 0.282094777, 0.282094777, 0.282094777)
    mul r18.xyzw, r15.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r0.z, r17.xyzw, r18.xyzw
    dp2 r2.y, r17.yxyy, r18.xyxx
    dp2 r3.w, r17.zxzz, r18.xzxx
    dp2 r5.x, r17.wxww, r18.xwxx
    mul r18.xyzw, r14.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r5.z, r17.xyzw, r18.xyzw
    dp2 r8.w, r17.yxyy, r18.xyxx
    dp2 r9.w, r17.zxzz, r18.xzxx
    dp2 r10.w, r17.wxww, r18.xwxx
    mul r18.xyzw, r16.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r11.w, r17.xyzw, r18.xyzw
    dp2 r13.z, r17.yxyy, r18.xyxx
    dp2 r13.w, r17.zxzz, r18.xzxx
    dp2 r17.x, r17.wxww, r18.xwxx
    mul r15.w, r0.z, l(0.886226952)
    mul r15.x, r5.x, l(-1.02332675)
    mul r15.y, r2.y, l(-1.02332675)
    mul r15.z, r3.w, l(1.02332675)
    mul r14.w, r5.z, l(0.886226952)
    mul r14.x, r10.w, l(-1.02332675)
    mul r14.y, r8.w, l(-1.02332675)
    mul r14.z, r9.w, l(1.02332675)
    mul r16.w, r11.w, l(0.886226952)
    mul r16.x, r17.x, l(-1.02332675)
    mul r16.yz, r13.zzwz, l(0.000000, -1.02332675, 1.02332675, 0.000000)
  endif
endif
mov r6.w, l(1.000000)
dp4 r17.x, r15.xyzw, r6.xyzw
dp4 r17.y, r14.xyzw, r6.xyzw
dp4 r17.z, r16.xyzw, r6.xyzw
max r17.xyz, r17.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
dp3 r0.z, -r11.xyzx, r6.xyzx
add r0.z, r0.z, r0.z
mad r18.xyz, r6.xyzx, -r0.zzzz, -r11.xyzx
add r0.z, l(-1.000000), cb0[113].x
max r2.y, r12.z, l(0.001000)
log r2.y, r2.y
mad r2.y, -r2.y, l(1.200000), l(1.000000)
add r0.z, r0.z, -r2.y
mul r5.xz, r4.yyzy, cb1[0].wwww
round_ni r5.xz, r5.xxzx
add r2.y, |r4.w|, -cb1[2].y
round_ni r2.y, r2.y
add r3.w, l(-1.000000), cb1[1].x
max r8.w, r2.y, l(0.000000)
min r3.w, r3.w, r8.w
ge r2.y, r3.w, r2.y
mad r5.x, r5.z, cb1[0].x, r5.x
ftoi r5.x, r5.x
iadd r5.x, r5.x, cb0[110].z
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.x, r5.x, l(0), t0.xxxx
ftoi r3.w, r3.w
iadd r3.w, r3.w, cb0[110].w
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r3.w, l(0), t0.xxxx
and r3.w, r3.w, r5.x
and r2.y, r2.y, r3.w
mul r19.xyz, r17.xyzx, cb0[111].xxxx
dp3 r3.w, r19.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
mov r7.w, l(1.000000)
mov r19.xyz, l(0,0,0,0)
mov r5.x, l(1.000000)
mov r5.z, r2.y
mov r8.w, l(0)
loop
  lt r9.w, l(0.010000), r5.x
  ine r10.w, r5.z, l(0)
  and r10.w, r9.w, r10.w
  if_nz r10.w
    firstbit_lo r10.w, r5.z
    ishl r11.w, l(1), r10.w
    xor r5.z, r5.z, r11.w
    ishl r10.w, r10.w, l(3)
    dp4 r20.x, cb1[r10.w + 6].xyzw, r7.xyzw
    dp4 r20.y, cb1[r10.w + 7].xyzw, r7.xyzw
    dp4 r20.z, cb1[r10.w + 8].xyzw, r7.xyzw
    ge r21.xyz, cb1[r10.w + 5].xyzx, |r20.xyzx|
    and r11.w, r21.y, r21.x
    and r11.w, r21.z, r11.w
    if_nz r11.w
      mul r11.w, l(0.100000), cb1[r10.w + 5].x
      mul r21.xyz, |r20.xyzx|, l(0.100000, 0.100000, 0.100000, 0.000000)
      mul r13.zw, r21.xxxy, r21.xxxy
      add r21.xyw, -|r20.xyxz|, cb1[r10.w + 5].xyxz
      mul r21.xyw, r21.xyxw, cb1[r10.w + 9].xyxz
      eq r12.z, l(1.000000), cb1[r10.w + 10].x
      if_nz r12.z
        dp3 r22.x, cb1[r10.w + 6].xyzx, r18.xyzx
        dp3 r22.y, cb1[r10.w + 7].xyzx, r18.xyzx
        dp3 r22.z, cb1[r10.w + 8].xyzx, r18.xyzx
        add r23.xyz, -r20.xyzx, cb1[r10.w + 5].xyzx
        div r23.xyz, r23.xyzx, r22.xyzx
        add r24.xyz, -r20.xyzx, -cb1[r10.w + 5].xyzx
        div r24.xyz, r24.xyzx, r22.xyzx
        lt r25.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r22.xyzx
        movc r23.xyz, r25.xyzx, r23.xyzx, r24.xyzx
        min r12.z, r23.y, r23.x
        min r12.z, r23.z, r12.z
        mad r20.xyz, r22.xyzx, r12.zzzz, r20.xyzx
      else
        mov r20.xyz, r18.xyzx
      endif
      dp3 r12.z, r20.xyzx, r20.xyzx
      rsq r12.z, r12.z
      mul r20.xyz, r12.zzzz, r20.xyzx
      lt r22.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r20.xyzx
      lt r23.xyz, r20.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
      iadd r22.xyz, -r22.xyzx, r23.xyzx
      itof r22.xyz, r22.xyzx
      dp3 r12.z, r20.xyzx, r22.xyzx
      div r20.xyz, r20.xyzx, r12.zzzz
      lt r12.z, r20.z, l(0.000000)
      add r20.zw, -|r20.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
      mul r20.zw, r20.zzzw, r22.xxxy
      movc r20.xy, r12.zzzz, r20.zwzz, r20.xyxx
      dp4 r12.z, cb1[r10.w + 4].xyzw, r6.xyzw
      max r12.z, r12.z, l(0.000000)
      max r12.z, r12.z, l(0.000100)
      min r17.w, r21.w, r21.y
      min r17.w, r17.w, r21.x
      add r13.z, r13.w, r13.z
      mad r13.z, r21.z, r21.z, r13.z
      mad r11.w, r11.w, r11.w, -r13.z
      mul r11.w, r11.w, cb1[r10.w + 9].x
      mul r11.w, r11.w, cb1[r10.w + 9].x
      add r13.z, l(1.000000), -cb1[r10.w + 10].y
      mul r11.w, r11.w, r13.z
      mul r11.w, r11.w, l(100.000000)
      mad_sat r11.w, r17.w, cb1[r10.w + 10].y, r11.w
      mul r13.z, r11.w, cb1[r10.w + 10].w
      mad r20.xy, r20.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
      mad r20.xy, r20.xyxx, cb1[1].wwww, cb1[2].wwww
      mov r20.z, cb1[r10.w + 5].w
      sample_l_indexable(texture2darray)(float,float,float,float) r20.xyz, r20.xyzx, t5.xyzw, s3, r0.z
      mul r20.xyz, r20.xyzx, cb1[r10.w + 9].wwww
      div r13.w, r3.w, r12.z
      min r13.w, |r13.w|, l(1.000000)
      mad r13.w, r13.w, l(2.000000), r3.w
      add r12.z, r12.z, l(2.000000)
      div r12.z, r13.w, r12.z
      add r12.z, r12.z, l(-1.000000)
      mad r12.z, r12.z, cb0[112].w, l(1.000000)
      mul r20.xyz, r12.zzzz, r20.xyzx
      mul r20.xyz, r13.zzzz, r20.xyzx
      mad r19.xyz, r20.xyzx, r5.xxxx, r19.xyzx
      mad r10.w, -r11.w, cb1[r10.w + 10].w, l(1.000000)
      mul r5.x, r5.x, r10.w
    endif
    mov r8.w, l(-1)
    continue
  else
    mov r8.w, r9.w
    break
  endif
  mov r8.w, r9.w
endloop
if_nz r8.w
  dp3 r2.y, r18.xyzx, r18.xyzx
  rsq r2.y, r2.y
  mul r18.xyz, r2.yyyy, r18.xyzx
  lt r20.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r18.xyzx
  lt r21.xyz, r18.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  iadd r20.xyz, -r20.xyzx, r21.xyzx
  itof r20.xyz, r20.xyzx
  dp3 r2.y, r18.xyzx, r20.xyzx
  div r18.xyz, r18.xyzx, r2.yyyy
  lt r2.y, r18.z, l(0.000000)
  add r13.zw, -|r18.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
  mul r13.zw, r13.zzzw, r20.xxxy
  movc r13.zw, r2.yyyy, r13.zzzw, r18.xxxy
  dp4 r2.y, cb1[3].xyzw, r6.xyzw
  max r2.y, r2.y, l(0.000000)
  max r2.y, r2.y, l(0.000100)
  mad r13.zw, r13.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
  mad r18.xy, r13.zwzz, cb1[1].wwww, cb1[2].wwww
  mov r18.z, l(0)
  sample_l_indexable(texture2darray)(float,float,float,float) r18.xyz, r18.xyzx, t5.xyzw, s3, r0.z
  div r0.z, r3.w, r2.y
  min r0.z, |r0.z|, l(1.000000)
  mad r0.z, r0.z, l(2.000000), r3.w
  add r2.y, r2.y, l(2.000000)
  div r0.z, r0.z, r2.y
  add r0.z, r0.z, l(-1.000000)
  mad r0.z, r0.z, cb0[112].w, l(1.000000)
  mul r18.xyz, r0.zzzz, r18.xyzx
  mad r19.xyz, r18.xyzx, r5.xxxx, r19.xyzx
endif
mul r18.xyz, r19.xyzx, cb0[112].zzzz
mul r18.xyz, r18.xyzx, cb0[111].yyyy
if_nz r2.z
  sample_b_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t3.yzxw, s1, cb0[108].x
  sample_b_indexable(texture2d)(float,float,float,float) r19.xyz, v1.xyxx, t2.xyzw, s1, cb0[108].x
  add r2.y, -r0.z, l(1.000000)
  mul r20.xyz, r2.yyyy, r18.xyzx
  mad r18.xyz, r19.xyzx, r0.zzzz, r20.xyzx
endif
mul r17.xyz, r3.xyzx, r17.xyzx
mul r17.xyz, r17.xyzx, cb0[111].xxxx
mad r0.z, r2.x, r13.x, r13.y
mul r2.xyz, r0.zzzz, r18.xyzx
mul r2.xyz, r10.xyzx, r2.xyzx
mad r2.xyz, r17.xyzx, r12.xywx, r2.xyzx
mul r6.xyzw, r6.xyzw, l(-1.000000, -1.000000, -1.000000, 1.000000)
dp4 r10.x, r15.xyzw, r6.xyzw
dp4 r10.y, r14.xyzw, r6.xyzw
dp4 r10.z, r16.xyzw, r6.xyzw
max r6.xyz, r10.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mul r6.xyz, r6.xyzx, cb0[111].xxxx
mul r6.xyz, r12.xywx, r6.xyzx
max r0.z, r3.y, r3.x
max r0.z, r3.z, r0.z
max r0.z, r0.z, l(0.010000)
div r3.xyz, r3.xyzx, r0.zzzz
mul r3.xyz, r3.xyzx, r6.xyzx
mul r0.z, r4.x, l(0.00787401572)
min r3.w, r5.y, l(1.000000)
bfi r1.z, l(3), l(2), r1.z, l(0)
ftou r2.w, r2.w
bfi r1.z, l(2), l(0), r2.w, r1.z
utof r1.z, r1.z
mul r1.z, r1.z, l(0.0322580636)
mad r0.z, r0.z, r3.w, r1.z
mul r3.xyz, r0.zzzz, r3.xyzx
mad r2.xyz, r3.xyzx, l(0.318309873, 0.318309873, 0.318309873, 0.000000), r2.xyzx
add r1.xyz, r1.xywx, r2.xyzx
max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r1.xyz, r1.xyzx, l(255.000000, 255.000000, 255.000000, 0.000000)
mad r0.z, r7.y, cb0[156].w, cb0[157].w
max r0.z, r0.z, l(0.010000)
mad r1.w, r5.w, cb0[154].w, -cb0[153].w
max r1.w, r1.w, l(0.000000)
mul r2.x, r0.z, l(-1.442695)
exp r2.x, r2.x
add r2.x, -r2.x, l(1.000000)
div r0.z, r2.x, r0.z
mad r2.x, r7.y, cb0[156].w, cb0[158].w
mul r2.x, r2.x, l(1.442695)
exp r2.x, r2.x
mul r0.z, r0.z, r2.x
mul r0.z, r0.z, -r1.w
mul r2.xyz, r0.zzzz, cb0[155].xyzx
mul r2.xyz, r2.xyzx, l(1.442695, 1.442695, 1.442695, 0.000000)
exp r2.xyz, r2.xyzx
dp3 r0.z, -r11.xyzx, cb0[154].xyzx
mad r1.w, cb0[155].w, cb0[155].w, l(1.000000)
dp2 r2.w, r0.zzzz, cb0[155].wwww
add r1.w, r1.w, -r2.w
lt r2.w, l(0.000000), cb0[163].z
if_nz r2.w
  and r0.w, l(7), cb0[108].w
  imad r0.xyw, r0.xyxw, l(0x0019660d, 0x0019660d, 0, 0x0019660d), l(0x3c6ef35f, 0x3c6ef35f, 0, 0x3c6ef35f)
  imad r0.x, r0.y, r0.w, r0.x
  imad r0.y, r0.w, r0.x, r0.y
  imad r0.w, r0.x, r0.y, r0.w
  imad r3.x, r0.y, r0.w, r0.x
  dp3 r0.x, -r11.xyzx, -r9.xyzx
  add r2.w, r7.y, -cb0[44].y
  lt r3.z, l(5.960464478E-08), r0.x
  div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
  and r0.x, r0.x, r3.z
  mul r0.x, r0.x, cb0[163].w
  div r3.z, l(1.000000, 1.000000, 1.000000, 1.000000), r5.w
  mul r3.w, r0.x, r3.z
  mad r4.x, r3.w, r2.w, cb0[44].y
  mad r2.w, -r3.w, r2.w, r2.w
  mul r3.w, r2.w, cb0[159].z
  max r3.w, r3.w, l(-127.000000)
  mul r2.w, r2.w, cb0[162].x
  max r2.w, r2.w, l(-127.000000)
  add r5.x, r4.x, -cb0[159].x
  mul r5.x, r5.x, cb0[159].z
  max r5.x, r5.x, l(-127.000000)
  exp r5.x, -r5.x
  mul r5.x, r5.x, cb0[159].y
  lt r5.y, l(5.960464478E-08), |r3.w|
  exp r5.z, -r3.w
  add r5.z, -r5.z, l(1.000000)
  div r5.z, r5.z, r3.w
  mad r3.w, -r3.w, l(0.240226507), l(0.693147182)
  movc r3.w, r5.y, r5.z, r3.w
  add r4.x, r4.x, -cb0[162].z
  mul r4.x, r4.x, cb0[162].x
  max r4.x, r4.x, l(-127.000000)
  exp r4.x, -r4.x
  mul r4.x, r4.x, cb0[162].y
  lt r5.y, l(5.960464478E-08), |r2.w|
  exp r5.z, -r2.w
  add r5.z, -r5.z, l(1.000000)
  div r5.z, r5.z, r2.w
  mad r2.w, -r2.w, l(0.240226507), l(0.693147182)
  movc r2.w, r5.y, r5.z, r2.w
  mul r2.w, r2.w, r4.x
  mad r2.w, r5.x, r3.w, r2.w
  mad r0.x, -r0.x, r3.z, l(1.000000)
  mul r0.x, r5.w, r0.x
  mul r0.x, r0.x, r2.w
  exp r0.x, -r0.x
  min r0.x, r0.x, l(1.000000)
  max r0.x, r0.x, cb0[161].w
  mad_sat r3.zw, r5.wwww, cb0[160].yyyw, cb0[160].xxxz
  add r0.x, r0.x, r3.z
  add r0.x, r3.w, r0.x
  min r0.x, r0.x, l(1.000000)
  imad r3.y, r0.w, r3.x, r0.y
  ushr r0.yw, r3.xxxy, l(0, 16, 0, 16)
  utof r0.yw, r0.yyyw
  mad r0.yw, r0.yyyw, l(0.000000, 0.0000305180438, 0.000000, 0.0000305180438), l(0.000000, -1.000000, 0.000000, -1.000000)
  mad r0.yw, r0.yyyw, cb0[167].wwww, r4.yyyz
  mul r3.xy, r0.ywyy, cb0[165].xyxx
  mad r0.y, |r4.w|, cb0[164].x, cb0[164].y
  log r0.y, r0.y
  mul r0.y, r0.y, cb0[164].z
  div r3.z, r0.y, cb0[163].z
  sample_l_indexable(texture3d)(float,float,float,float) r3.xyzw, r3.xyzx, t12.xyzw, s1, l(0.000000)
  add r0.y, |r4.w|, -cb0[166].z
  mul_sat r0.y, r0.y, l(1000000.000000)
  add r3.xyzw, r3.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
  mad r3.xyzw, r0.yyyy, r3.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
  add r0.y, -r0.x, l(1.000000)
  mul r4.xyz, r0.yyyy, cb0[161].xyzx
  mad r3.xyz, r4.xyzx, r3.wwww, r3.xyzx
  mul r0.x, r0.x, r3.w
else
  add r0.y, r7.y, -cb0[44].y
  mul r0.w, r0.y, cb0[159].z
  mul r0.y, r0.y, cb0[162].x
  max r0.yw, r0.yyyw, l(0.000000, -127.000000, 0.000000, -127.000000)
  add r2.w, cb0[44].y, -cb0[159].x
  mul r2.w, r2.w, cb0[159].z
  max r2.w, r2.w, l(-127.000000)
  exp r2.w, -r2.w
  mul r2.w, r2.w, cb0[159].y
  lt r3.w, l(5.960464478E-08), |r0.w|
  exp r4.x, -r0.w
  add r4.x, -r4.x, l(1.000000)
  div r4.x, r4.x, r0.w
  mad r0.w, -r0.w, l(0.240226507), l(0.693147182)
  movc r0.w, r3.w, r4.x, r0.w
  add r3.w, cb0[44].y, -cb0[162].z
  mul r3.w, r3.w, cb0[162].x
  max r3.w, r3.w, l(-127.000000)
  exp r3.w, -r3.w
  mul r3.w, r3.w, cb0[162].y
  lt r4.x, l(5.960464478E-08), |r0.y|
  exp r4.y, -r0.y
  add r4.y, -r4.y, l(1.000000)
  div r4.y, r4.y, r0.y
  mad r0.y, -r0.y, l(0.240226507), l(0.693147182)
  movc r0.y, r4.x, r4.y, r0.y
  mul r0.y, r0.y, r3.w
  mad r0.y, r2.w, r0.w, r0.y
  mul r0.y, r5.w, r0.y
  exp r0.y, -r0.y
  min r0.y, r0.y, l(1.000000)
  max r0.y, r0.y, cb0[161].w
  mad_sat r4.xy, r5.wwww, cb0[160].ywyy, cb0[160].xzxx
  add r0.y, r0.y, r4.x
  add r0.y, r4.y, r0.y
  min r0.x, r0.y, l(1.000000)
  add r0.y, -r0.x, l(1.000000)
  mul r3.xyz, r0.yyyy, cb0[161].xyzx
endif
mul r4.xyz, r0.xxxx, r2.xyzx
mad r0.y, r0.z, r0.z, l(1.000000)
mul r0.y, r0.y, l(0.0596831031)
mad r0.yzw, cb0[156].xxyz, r0.yyyy, cb0[158].xxyz
mad r2.w, -cb0[155].w, cb0[155].w, l(1.000000)
mul r3.w, r1.w, l(12.566371)
sqrt r1.w, r1.w
mul r1.w, r1.w, r3.w
max r1.w, r1.w, l(0.001000)
div r1.w, r2.w, r1.w
mad_sat r0.yzw, cb0[157].xxyz, r1.wwww, r0.yyzw
mul r0.yzw, r0.yyzw, l(0.000000, 255.000000, 255.000000, 255.000000)
add r2.xyz, -r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r0.yzw, r0.yyzw, r2.xxyz
mad r0.xyz, r0.yzwy, r0.xxxx, r3.xyzx

// === Simplified Fog Modification (Anti-Banding) ===
// Check if fog modification is enabled via cb13[12].y
lt r15.x, l(0.500000), cb13[12].y
if_nz r15.x
  // r1.xyz = scene color, r4.xyz = transmittance, r0.xyz = fog inscatter
  // Boost transmittance: lerp(trans, 1, 0.35) to reduce fog density
  add r15.xyz, -r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mad r15.xyz, r15.xyzx, l(0.350000, 0.350000, 0.350000, 0.000000), r4.xyzx
  
  // Reduce fog inscatter intensity
  mul r16.xyz, r0.xyzx, l(0.650000, 0.650000, 0.650000, 0.000000)
  
  // Modified fog blend: scene * boostedTrans + reducedInscatter
  mad r0.xyz, r1.xyzx, r15.xyzx, r16.xyzx
else
  // Original fog blend
  mad r0.xyz, r1.xyzx, r4.xyzx, r0.xyzx
endif
// === End Fog Modification ===
dp3 r0.w, r4.xyzx, l(0.333333343, 0.333333343, 0.333333343, 0.000000)
dp3 r1.w, r8.xyzx, r8.xyzx
sqrt r1.w, r1.w
mad_sat r1.w, -r1.w, cb0[169].z, l(1.000000)
mul r2.x, r1.w, cb0[169].x
mad r1.w, -cb0[169].x, r1.w, l(1.000000)
mul r2.yzw, cb0[168].xxyz, cb0[183].wwww
mad r2.yzw, r7.xxyz, cb0[169].yyyy, r2.yyzw
sample_l_indexable(texture3d)(float,float,float,float) r2.y, r2.yzwy, t25.xwyz, s2, l(0.000000)
dp2 r2.x, r2.yyyy, r2.xxxx
add r1.w, r1.w, r2.x
add r2.x, r0.w, l(1.000000)
min r1.w, r1.w, r2.x
add r0.xyz, -r1.xyzx, r0.xyzx
mad o0.xyz, r1.wwww, r0.xyzx, r1.xyzx
mov o0.w, r0.w
ret
// Approximately 0 instruction slots used
