//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.4.1 on Fri Jan 30 20:17:33 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy
// TEXCOORD                 0   xy          1     NONE   float   xy
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                              { 0, 1.000000, 0, 0},
                              { 0, 0, 1.000000, 0},
                              { 0, 0, 0, 1.000000},
                              { 2, 1, -1.000000, 1.000000},
                              { 2, 1, 1.000000, 1.000000},
                              { 0, 2, 1.000000, -1.000000},
                              { 0, 2, 1.000000, 1.000000},
                              { 0, 1, 1.000000, 1.000000},
                              { 0, 1, -1.000000, 1.000000} }
dcl_constantbuffer CB0[235], immediateIndexed
dcl_constantbuffer CB1[259], dynamicIndexed
dcl_constantbuffer CB2[3], immediateIndexed
dcl_constantbuffer CB3[2054], dynamicIndexed
dcl_constantbuffer CB4[401], dynamicIndexed
dcl_constantbuffer CB5[160], dynamicIndexed
dcl_constantbuffer CB6[4], immediateIndexed
dcl_constantbuffer CB13[19], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_comparison
dcl_resource_structured t0, 4
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2darray (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture3d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t14
dcl_resource_texture3d (float,float,float,float) t15
dcl_resource_texture3d (float,float,float,float) t16
dcl_resource_texture3d (float,float,float,float) t17
dcl_resource_texture3d (float,float,float,float) t18
dcl_resource_texture3d (float,float,float,float) t19
dcl_resource_texture3d (float,float,float,float) t20
dcl_resource_texture2d (float,float,float,float) t21
dcl_resource_texture2d (float,float,float,float) t22
dcl_resource_texture2d (float,float,float,float) t23
dcl_resource_texture2d (float,float,float,float) t24
dcl_resource_texture3d (float,float,float,float) t25
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 38
ftou r0.xy, v0.xyxx
mov r0.z, l(0)
ld_indexable(texture2d)(float,float,float,float) r1.xyzw, r0.xyzz, t22.xyzw
ld_indexable(texture2d)(float,float,float,float) r2.xyzw, r0.xyzz, t23.xyzw
ld_indexable(texture2d)(float,float,float,float) r3.xyzw, r0.xyzz, t24.xyzw
mul r1.xyzw, r1.xwyz, l(1023.000000, 3.000000, 1023.000000, 1023.000000)
ftou r1.xyw, r1.xyxw
ubfe r4.x, l(7), l(3), r1.x
bfi r4.yz, l(0, 3, 3, 0), l(0, 2, 2, 0), r1.xxwx, l(0, 0, 0, 0)
bfi r1.x, l(2), l(0), r1.y, r4.y
utof r1.x, r1.x
mul r1.y, r1.x, l(0.0322580636)
round_ne r1.z, r1.z
ftou r1.z, r1.z
ubfe r4.y, l(7), l(3), r1.z
utof r4.xy, r4.xyxx
mul r4.y, r4.y, l(0.00787401572)
mad r2.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r4.w, l(1.000000, 1.000000, 0.000000, 0.000000), |r2.xyxx|
add r5.y, -r4.w, l(1.000000)
lt r4.w, r5.y, l(0.000000)
ge r6.xy, r2.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
add r6.zw, -|r2.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
movc r6.xy, r6.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
mul r6.xy, r6.xyxx, r6.zwzz
movc r5.xz, r4.wwww, r6.xxyx, r2.xxyx
dp3 r2.x, r5.xyzx, r5.xyzx
rsq r2.x, r2.x
mul r5.xyz, r2.xxxx, r5.xyzx
and r1.z, r1.z, l(7)
utof r1.z, r1.z
mad r1.z, r1.z, l(0.107142866), l(0.500000)
utof r2.xy, r0.xyxx
mul r6.xy, v0.xyxx, cb0[82].zwzz
mad r6.zw, r6.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
add r7.xy, r2.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mul r7.xy, r7.xyxx, cb0[82].zwzz
sample_l_indexable(texture2d)(float,float,float,float) r4.w, r7.xyxx, t1.yzwx, s0, l(0.000000)
mul r7.xyzw, -r6.wwww, cb0[25].xyzw
mad r7.xyzw, cb0[24].xyzw, r6.zzzz, r7.xyzw
mad r7.xyzw, cb0[26].xyzw, r4.wwww, r7.xyzw
add r7.xyzw, r7.xyzw, cb0[27].xyzw
div r7.xyz, r7.xyzx, r7.wwww
mul r4.w, r7.y, cb0[1].z
mad r4.w, cb0[0].z, r7.x, r4.w
mad r4.w, cb0[2].z, r7.z, r4.w
add r4.w, r4.w, cb0[3].z
eq r6.z, l(0.000000), cb0[86].w
add r8.xyz, -r7.xyzx, cb0[44].xyzx
mov r9.x, cb0[0].z
mov r9.y, cb0[1].z
mov r9.z, cb0[2].z
movc r10.xyz, r6.zzzz, r8.xyzx, r9.xyzx
dp3 r6.z, r10.xyzx, r10.xyzx
max r6.w, r6.z, l(9.999999939E-09)
rsq r6.w, r6.w
mul r11.xyz, r6.wwww, r10.xyzx
mul r6.z, r6.w, r6.z
lt r8.w, l(0.000488281250), cb0[234].x
if_nz r8.w
  sample_b_indexable(texture2d)(float,float,float,float) r8.w, v1.xyxx, t21.yzwx, s1, cb0[108].x
else
  mov r8.w, l(1.000000)
endif
add r8.w, -r8.w, l(1.000000)
mul r2.w, r2.w, l(3.000000)
mad_sat r9.w, r2.z, l(0.300000), l(0.250000)
mul r9.w, r9.w, cb0[222].x
mul r9.w, r8.w, r9.w
mad r9.w, r9.w, l(-0.750000), l(1.000000)
mul r3.xyz, r3.xyzx, r9.wwww
min r9.w, r2.z, l(0.300000)
mul r8.w, r8.w, cb0[222].x
mul r8.w, r8.w, l(0.500000)
add r9.w, -r2.z, r9.w
mad r12.w, r8.w, r9.w, r2.z
mul r2.z, r1.z, l(0.080000)
dp3 r8.w, r5.xyzx, r11.xyzx
max r9.w, r8.w, l(0.000000)
mad r13.xyzw, r12.wwww, l(-1.000000, -0.027500, -0.572000, 0.022000), l(1.000000, 0.042500, 1.040000, -0.040000)
mul r10.w, r13.x, r13.x
mul r11.w, r9.w, l(-9.280000)
exp r11.w, r11.w
min r10.w, r10.w, r11.w
mad r10.w, r10.w, r13.x, r13.y
mad r13.xy, r10.wwww, l(-1.040000, 1.040000, 0.000000, 0.000000), r13.zwzz
ld_indexable(texture2d)(float,float,float,float) r13.z, r0.xyzz, t7.zwxy
lt r0.z, l(0.001000), r13.z
if_nz r0.z
  sample_l_indexable(texture2d)(float,float,float,float) r0.z, r6.xyxx, t10.yzxw, s1, l(0.000000)
  dp3 r10.w, -r11.xyzx, r5.xyzx
  add r10.w, r10.w, r10.w
  mad r14.xyz, r5.xyzx, -r10.wwww, -r11.xyzx
  dp3 r10.w, -cb3[0].xyzx, r14.xyzx
  mad r15.xyz, cb3[0].xyzx, r10.wwww, r14.xyzx
  lt r10.w, r10.w, cb3[4].z
  dp3 r11.w, r15.xyzx, r15.xyzx
  max r11.w, r11.w, l(0.0000610351562)
  rsq r11.w, r11.w
  mul r15.xyz, r11.wwww, r15.xyzx
  mul r15.xyz, r15.xyzx, cb3[4].yyyy
  mad r15.xyz, -cb3[0].xyzx, cb3[4].zzzz, r15.xyzx
  dp3 r11.w, r15.xyzx, r15.xyzx
  rsq r11.w, r11.w
  mul r15.xyz, r11.wwww, r15.xyzx
  movc r14.xyz, r10.wwww, r15.xyzx, r14.xyzx
  mad r15.xyz, r10.xyzx, r6.wwww, r14.xyzx
  dp3 r10.w, r15.xyzx, r15.xyzx
  max r10.w, r10.w, l(0.0000610351562)
  rsq r10.w, r10.w
  mul r15.xyz, r10.wwww, r15.xyzx
  dp3 r10.w, r5.xyzx, r14.xyzx
  mov_sat r12.y, r10.w
  dp3_sat r11.w, r5.xyzx, r15.xyzx
  dp3 r14.x, r11.xyzx, r14.xyzx
  min r12.z, r9.w, l(1.000000)
  mul r14.y, r12.w, r12.w
  mul r14.y, r14.y, r14.y
  mad r14.z, r11.w, r14.y, -r11.w
  mad r11.w, r14.z, r11.w, l(1.000000)
  dp3_sat r14.z, r11.xyzx, r15.xyzx
  add r14.z, -r14.z, l(1.000000)
  mul r14.w, r14.z, r14.z
  mul r14.w, r14.w, r14.w
  mul r15.x, r14.z, r14.w
  add r15.y, -r12.w, l(1.000000)
  mad r15.z, -r15.y, l(0.383026), l(-0.0761947036)
  mad r15.z, r15.y, r15.z, l(1.049970)
  mad r15.y, r15.y, r15.z, l(0.409255)
  min r15.y, r15.y, l(0.999000)
  add r15.z, -r15.y, l(1.000000)
  mad r15.w, -r1.z, l(0.080000), l(1.000000)
  mad r15.w, r15.w, l(0.0476190485), r2.z
  mov_sat r16.x, -r14.x
  mul r16.x, r16.x, r16.x
  mad r16.x, r16.x, l(-0.640000), l(1.000000)
  mul r16.x, r16.x, r16.x
  mad r14.z, -r14.w, r14.z, l(1.000000)
  mad r14.z, r2.z, r14.z, r15.x
  mul r11.w, r11.w, r11.w
  div r11.w, r14.y, r11.w
  mad r16.yz, -r12.zzyz, r14.yyyy, r12.zzyz
  mad r14.yw, r16.yyyz, r12.zzzy, r14.yyyy
  sqrt r14.yw, r14.yyyw
  mul r14.yw, r12.yyyz, r14.yyyw
  add r14.y, r14.w, r14.y
  add r14.y, r14.y, l(0.000100)
  div r14.y, l(0.500000), r14.y
  mul r11.w, r11.w, r14.y
  mul r11.w, r11.w, r14.z
  min r11.w, r11.w, l(2048.000000)
  mad r17.xyzw, r12.zwyw, l(0.968750, 0.968750, 0.968750, 0.968750), l(0.015625, 0.015625, 0.015625, 0.015625)
  sample_l_indexable(texture2d)(float,float,float,float) r12.z, r17.xyxx, t9.yzxw, s1, l(0.000000)
  sample_l_indexable(texture2d)(float,float,float,float) r14.y, r17.zwzz, t9.yxzw, s1, l(0.000000)
  mul r12.z, r12.z, r14.y
  mul r12.z, r15.y, r12.z
  div r12.z, r12.z, r15.z
  mul r14.y, r15.w, r15.w
  mul r12.z, r12.z, r14.y
  mad r14.y, -r15.w, r15.z, l(1.000000)
  div r12.z, r12.z, r14.y
  add r11.w, r11.w, r12.z
  add_sat r12.z, r8.w, l(0.200000)
  mov_sat r14.y, r14.x
  add r14.y, r14.y, l(0.500000)
  min r14.y, r14.y, l(1.000000)
  mul r14.z, r12.z, r14.y
  add_sat r14.x, r14.x, l(1.000000)
  mad r12.z, -r12.z, r14.y, l(1.000000)
  mad r12.z, r14.x, r12.z, r14.z
  mul r11.w, r11.w, r12.z
  mul r11.w, r4.y, r11.w
  mul r14.xyz, r4.yyyy, r3.xyzx
  ubfe r1.w, l(7), l(3), r1.w
  utof r1.w, r1.w
  mul r1.w, r1.w, l(0.00787401572)
  mul r11.w, r11.w, cb3[4].x
  max r11.w, r11.w, l(0.000000)
  min r11.w, r11.w, l(1000.000000)
  mul r11.w, r12.y, r11.w
  mad r14.xyz, r14.xyzx, r1.wwww, r11.wwww
  max r1.w, r3.y, r3.x
  max r1.w, r3.z, r1.w
  max r1.w, r1.w, l(0.010000)
  div r15.xyz, r3.xyzx, r1.wwww
  mul r1.w, r4.x, l(0.00393700786)
  mul r15.xyz, r1.wwww, r15.xyzx
  add_sat r1.w, -r10.w, l(0.500000)
  ne r11.w, r16.x, l(0.360000)
  div r12.z, l(0.360000), r16.x
  movc r11.w, r11.w, r12.z, l(1.000000)
  mul r1.w, r1.w, r11.w
  mad_sat r10.w, r1.x, l(0.0322580636), r10.w
  add r10.w, -r12.y, r10.w
  mul r16.xyz, r3.xyzx, r10.wwww
  mad r15.xyz, r15.xyzx, r1.wwww, r16.xyzx
  mad r14.xyz, r15.xyzx, r4.yyyy, r14.xyzx
  mul r14.xyz, r14.xyzx, cb3[1].xyzx
  mov r13.w, l(0.500000)
  sample_b_indexable(texture2d)(float,float,float,float) r15.xyz, r13.zwzz, t8.xyzw, s1, cb0[108].x
  add r1.w, -r13.z, l(1.000000)
  mad r15.xyz, r14.xyzx, r15.xyzx, -r14.xyzx
  mad r14.xyz, r1.wwww, r15.xyzx, r14.xyzx
  max r1.w, r4.y, r0.z
  add r1.w, -r0.z, r1.w
  mad r0.z, r1.y, r1.w, r0.z
  mul r14.xyz, r0.zzzz, r14.xyzx
else
  mov r14.xyz, l(0,0,0,0)
endif
mul r1.yw, r2.xxxy, l(0.000000, 0.031250, 0.000000, 0.031250)
round_ni r1.yw, r1.yyyw
mad r0.z, r1.w, cb2[1].y, r1.y
mul r0.z, r0.z, l(8.000000)
ftoi r0.z, r0.z
mad r1.y, -cb0[85].y, cb2[2].w, |r4.w|
round_ni r1.y, r1.y
add r1.w, l(-1.000000), cb2[1].w
max r10.w, r1.y, l(0.000000)
min r1.w, r1.w, r10.w
mul r10.w, r1.w, l(8.000000)
ftoi r10.w, r10.w
ge r1.y, r1.w, r1.y
iadd r1.w, r10.w, cb0[110].y
mul r10.w, r12.w, r12.w
dp3 r11.w, -r11.xyzx, r5.xyzx
add r11.w, r11.w, r11.w
mad r15.xyz, r5.xyzx, -r11.wwww, -r11.xyzx
min r12.x, r9.w, l(1.000000)
add r11.w, -r12.w, l(1.000000)
mad r12.y, -r11.w, l(0.383026), l(-0.0761947036)
mad r12.y, r11.w, r12.y, l(1.049970)
mad r11.w, r11.w, r12.y, l(0.409255)
min r11.w, r11.w, l(0.999000)
add r12.y, -r11.w, l(1.000000)
mad r1.z, -r1.z, l(0.080000), l(1.000000)
mad r1.z, r1.z, l(0.0476190485), r2.z
mad r13.zw, r12.xxxw, l(0.000000, 0.000000, 0.968750, 0.968750), l(0.000000, 0.000000, 0.015625, 0.015625)
sample_l_indexable(texture2d)(float,float,float,float) r12.z, r13.zwzz, t9.yzxw, s1, l(0.000000)
mad r13.z, -r1.z, r12.y, l(1.000000)
add_sat r8.w, r8.w, l(0.200000)
max r13.w, r3.y, r3.x
max r13.w, r3.z, r13.w
max r13.w, r13.w, l(0.010000)
div r16.xyz, r3.xyzx, r13.wwww
mul r13.w, r4.x, l(0.00393700786)
mul r17.xyz, r13.wwww, r16.xyzx
mul r18.xyz, r4.yyyy, r3.xyzx
mul r1.z, r1.z, r1.z
mov r19.w, l(1.000000)
mov r20.y, l(1.000000)
mov r21.z, r12.w
mov r22.xyz, l(0,0,0,0)
mov r13.w, l(1.000000)
mov r14.w, l(0)
loop
  ilt r15.w, l(7), r14.w
  breakc_nz r15.w
  iadd r15.w, r0.z, r14.w
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r15.w, r15.w, l(0), t0.xxxx
  iadd r16.w, r1.w, r14.w
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r16.w, r16.w, l(0), t0.xxxx
  and r15.w, r15.w, r16.w
  and r15.w, r1.y, r15.w
  ishl r16.w, r14.w, l(5)
  mov r23.xyz, l(0,0,0,0)
  mov r17.w, r13.w
  mov r18.w, r15.w
  loop
    breakc_z r18.w
    firstbit_lo r20.z, r18.w
    ishl r20.w, l(1), r20.z
    xor r20.w, r18.w, r20.w
    iadd r20.z, r16.w, r20.z
    bfi r24.xyzw, l(29, 29, 29, 29), l(3, 3, 3, 3), r20.zzzz, l(1, 3, 5, 6)
    bfi r21.w, l(29), l(3), r20.z, l(7)
    ftou r22.w, cb3[r24.z + 6].w
    ieq r22.w, r22.w, l(1)
    if_nz r22.w
      add r19.xyz, r7.xyzx, -cb3[r24.x + 6].xyzx
      and r25.xyz, l(0x0000ffff, 0x0000ffff, 0x0000ffff, 0), cb3[r24.z + 6].xzyx
      and r26.xyz, l(0x0000ffff, 0x0000ffff, 0x0000ffff, 0), cb3[r24.w + 6].yxzy
      ushr r27.xyz, cb3[r24.z + 6].xzyx, l(16, 16, 16, 0)
      ushr r28.xyz, cb3[r24.w + 6].yxzy, l(16, 16, 16, 0)
      f16tof32 r25.xyz, r25.xyzx
      f16tof32 r26.xyz, r26.xyzx
      f16tof32 r27.xyz, r27.xyzx
      f16tof32 r28.xyw, r28.yxyz
      mov r29.xz, r25.xxzx
      mov r29.yw, r27.xxxz
      dp4 r22.w, r19.xyzw, r29.xyzw
      mov r27.x, r25.y
      mov r27.z, r26.y
      mov r27.w, r28.x
      dp4 r23.w, r19.xyzw, r27.xyzw
      mov r28.xz, r26.xxzx
      dp4 r19.x, r19.xyzw, r28.xyzw
      max r19.y, |r22.w|, |r23.w|
      max r19.x, |r19.x|, r19.y
      mad r19.y, cb3[r21.w + 6].x, l(0.500000), l(0.500000)
      add r19.x, -r19.y, r19.x
      mad r19.y, -cb3[r21.w + 6].x, l(0.500000), l(0.500000)
      div_sat r19.x, r19.x, r19.y
      add r19.x, -r19.x, l(1.000000)
      mul r19.x, r19.x, r19.x
    else
      mov r19.x, l(1.000000)
    endif
    lt r19.y, l(0.500000), cb3[r24.y + 6].z
    lt r19.z, r19.x, l(0.001000)
    or r19.z, r19.y, r19.z
    if_nz r19.z
      mov r18.w, r20.w
      continue
    endif
    ishl r19.z, r20.z, l(3)
    bfi r20.z, l(29), l(3), r20.z, l(2)
    lt r22.w, cb3[r19.z + 6].w, l(1.500000)
    if_nz r22.w
      mad r22.w, cb3[r20.z + 6].y, l(0.500000), l(0.500000)
      add r25.x, r22.w, -|cb3[r20.z + 6].x|
      add r25.y, -r25.x, cb3[r20.z + 6].y
      add r22.w, -|r25.x|, l(1.000000)
      add r22.w, -|r25.y|, r22.w
      max r22.w, r22.w, l(0.000488281250)
      ge r23.w, cb3[r20.z + 6].x, l(0.000000)
      movc r25.z, r23.w, r22.w, -r22.w
      dp3 r22.w, r25.xyzx, r25.xyzx
      rsq r22.w, r22.w
      mul r25.xyz, r22.wwww, r25.xyzx
      add r26.xyz, -r7.xyzx, cb3[r24.x + 6].xyzx
      dp3 r22.w, r26.xyzx, r26.xyzx
      rsq r23.w, r22.w
      mul r27.xyz, r23.wwww, r26.xyzx
      ftoi r24.z, cb3[r21.w + 6].w
      mul r28.xyz, r25.xyzx, cb3[r20.z + 6].zzzz
      mad r29.xyz, -r28.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r26.xyzx
      mad r30.xyz, r28.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r26.xyzx
      ftou r25.w, cb3[r19.z + 6].w
      and r25.w, r25.w, l(1)
      ieq r26.w, r25.w, l(0)
      not r26.w, r26.w
      lt r27.w, l(0.000000), cb3[r20.z + 6].z
      and r26.w, r26.w, r27.w
      dp3 r27.w, r29.xyzx, r29.xyzx
      sqrt r27.w, r27.w
      dp3 r28.w, r30.xyzx, r30.xyzx
      sqrt r28.w, r28.w
      dp3 r29.w, r5.xyzx, r29.xyzx
      div r29.w, r29.w, r27.w
      dp3 r30.w, r5.xyzx, r30.xyzx
      div r30.w, r30.w, r28.w
      add r29.w, r29.w, r30.w
      mul_sat r31.x, r29.w, l(0.500000)
      dp3 r29.w, r29.xyzx, r30.xyzx
      mad r27.w, r27.w, r28.w, r29.w
      mad r27.w, r27.w, l(0.500000), l(1.000000)
      div r31.y, l(1.000000, 1.000000, 1.000000, 1.000000), r27.w
      dp3_sat r20.x, r5.xyzx, r27.xyzx
      movc r21.xy, r26.wwww, r31.xyxx, r20.xyxx
      lt r20.x, cb3[r24.w + 6].w, l(0.000000)
      if_nz r20.x
        mul r20.x, cb3[r24.x + 6].w, cb3[r24.x + 6].w
        mul r20.x, r20.x, r22.w
        mad r20.x, -r20.x, r20.x, l(1.000000)
        max r20.x, r20.x, l(0.000000)
        add r22.w, r22.w, l(1.000000)
        div r22.w, l(1.000000, 1.000000, 1.000000, 1.000000), r22.w
        and r27.w, r26.w, l(0x3f800000)
        add r28.w, r21.y, -r22.w
        mad r22.w, r27.w, r28.w, r22.w
        mul r20.x, r20.x, r20.x
        mul r20.x, r20.x, r22.w
      else
        mul r30.xyz, r26.xyzx, cb3[r24.x + 6].wwww
        dp3 r22.w, r30.xyzx, r30.xyzx
        min r22.w, r22.w, l(1.000000)
        add r22.w, -r22.w, l(1.000000)
        log r22.w, r22.w
        mul r22.w, r22.w, cb3[r24.w + 6].w
        exp r22.w, r22.w
        mul r20.x, r21.y, r22.w
      endif
      dp3 r21.y, r27.xyzx, -r25.xyzx
      add r21.y, r21.y, -cb3[r20.z + 6].z
      mul_sat r21.y, r21.y, cb3[r20.z + 6].w
      mul r21.y, r21.y, r21.y
      movc r21.y, r25.w, l(1.000000), r21.y
      mul r20.x, r20.x, r21.y
      not r21.y, r26.w
      ige r22.w, r24.z, l(0)
      and r21.y, r21.y, r22.w
      if_nz r21.y
        if_z r25.w
          ishl r21.y, r24.z, l(2)
          mul r25.xyz, r7.yyyy, cb5[r21.y + 33].xywx
          mad r25.xyz, cb5[r21.y + 32].xywx, r7.xxxx, r25.xyzx
          mad r25.xyz, cb5[r21.y + 34].xywx, r7.zzzz, r25.xyzx
          add r25.xyz, r25.xyzx, cb5[r21.y + 35].xywx
          div_sat r25.xy, r25.xyxx, r25.zzzz
          mad r25.xy, r25.xyxx, cb5[r24.z + 0].zwzz, cb5[r24.z + 0].xyxx
        else
          ishl r21.y, r24.z, l(2)
          dp3 r30.x, -r26.xyzx, cb5[r21.y + 32].xyzx
          dp3 r30.y, -r26.xyzx, cb5[r21.y + 33].xyzx
          dp3 r30.z, -r26.xyzx, cb5[r21.y + 34].xyzx
          lt r21.y, |r30.x|, |r30.y|
          and r21.y, r21.y, l(1)
          dp2 r22.w, |r30.xyxx|, icb[r21.y + 0].xyxx
          lt r22.w, r22.w, |r30.z|
          movc r21.y, r22.w, l(2), r21.y
          dp3 r22.w, r30.xyzx, icb[r21.y + 0].xyzx
          lt r22.w, r22.w, l(0.000000)
          bfi r21.y, l(31), l(1), r21.y, r22.w
          ushr r22.w, r21.y, l(1)
          dp3 r22.w, r30.xyzx, icb[r22.w + 0].xyzx
          div r25.z, l(0.000244140625), cb5[r24.z + 0].w
          add r25.z, -r25.z, l(0.500000)
          utof r26.x, r21.y
          ult r26.y, r21.y, l(2)
          and r26.y, r26.y, l(2)
          dp2 r26.y, r30.xzxx, icb[r26.y + 0].xzxx
          mul r26.y, r26.y, icb[r21.y + 4].z
          div r26.y, r26.y, |r22.w|
          mad r26.x, r26.y, r25.z, r26.x
          add r26.x, r26.x, l(0.500000)
          mul_sat r26.x, r26.x, l(0.166666672)
          iadd r26.z, l(-1), icb[r21.y + 4].y
          dp2 r26.z, r30.yzyy, icb[r26.z + 0].xyxx
          mul r21.y, r26.z, icb[r21.y + 4].w
          div r21.y, r21.y, |r22.w|
          mad_sat r26.y, -r21.y, r25.z, l(0.500000)
          mad r25.xy, r26.xyxx, cb5[r24.z + 0].zwzz, cb5[r24.z + 0].xyxx
        endif
        sample_l_indexable(texture2d)(float,float,float,float) r21.y, r25.xyxx, t11.yxzw, s1, l(0.000000)
        mul r20.x, r20.x, r21.y
      endif
      lt r21.y, l(0.000000), r20.x
      if_nz r21.y
        if_z r25.w
          ftoi r22.w, cb3[r24.y + 6].x
        else
          add r25.xyz, r7.xyzx, -cb3[r24.x + 6].xyzx
          lt r26.xyz, |r25.yzzy|, |r25.xxyx|
          and r24.z, r26.y, r26.x
          lt r25.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r25.xyzx
          ushr r25.w, cb3[r20.z + 6].w, l(24)
          ubfe r26.xy, l(8, 8, 0, 0), l(16, 8, 0, 0), cb3[r20.z + 6].wwww
          movc r25.x, r25.x, r25.w, r26.x
          and r25.w, l(255), cb3[r20.z + 6].w
          movc r25.y, r25.y, r26.y, r25.w
          ubfe r25.w, l(8), l(8), cb3[r24.y + 6].x
          and r26.x, l(255), cb3[r24.y + 6].x
          movc r25.z, r25.z, r25.w, r26.x
          movc r25.y, r26.z, r25.y, r25.z
          movc r24.z, r24.z, r25.x, r25.y
          ilt r25.x, r24.z, l(80)
          movc r22.w, r25.x, r24.z, l(-1)
        endif
        ishl r24.z, r22.w, l(2)
        mad r25.xyz, r27.xyzx, cb4[r22.w + 288].xxxx, r7.xyzx
        mul r25.w, l(5.000000), cb4[r22.w + 288].y
        mad r25.xyz, r5.xyzx, r25.wwww, r25.xyzx
        mul r30.xyzw, r25.yyyy, cb4[r24.z + 65].xyzw
        mad r30.xyzw, cb4[r24.z + 64].xyzw, r25.xxxx, r30.xyzw
        mad r25.xyzw, cb4[r24.z + 66].xyzw, r25.zzzz, r30.xyzw
        add r25.xyzw, r25.xyzw, cb4[r24.z + 67].xyzw
        div r25.xyz, r25.xyzx, r25.wwww
        ge r26.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r25.xyzx
        ge r30.xyz, r25.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
        add r31.xy, -cb4[r22.w + 344].xyxx, cb4[r22.w + 344].zwzz
        mad r25.xy, r25.xyxx, r31.xyxx, cb4[r22.w + 344].xyxx
        mad r31.xy, r25.xyxx, cb4[400].zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
        round_ni r31.xy, r31.xyxx
        mad r25.xy, r25.xyxx, cb4[400].zwzz, -r31.xyxx
        add r32.xyzw, r25.xxyy, l(0.500000, 1.000000, 0.500000, 1.000000)
        mul r33.xyzw, r32.xxzz, r32.xxzz
        add r31.zw, -r25.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
        min r32.xz, r25.xxyx, l(0.000000, 0.000000, 0.000000, 0.000000)
        max r34.xy, r25.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
        mul r35.xy, r31.zwzz, l(0.160000, 0.160000, 0.000000, 0.000000)
        mad r34.xy, -r34.xyxx, r34.xyxx, r32.ywyy
        add r34.xy, r34.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
        mul r34.xy, r34.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
        mul r33.xz, r33.xxzx, l(0.080000, 0.000000, 0.080000, 0.000000)
        mad r25.xy, r33.ywyy, l(0.500000, 0.500000, 0.000000, 0.000000), -r25.xyxx
        mul r36.xy, r25.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
        mad r25.xy, -r32.xzxx, r32.xzxx, r31.zwzz
        add r25.xy, r25.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
        mul r37.xy, r25.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
        mul r25.xy, r32.ywyy, l(0.160000, 0.160000, 0.000000, 0.000000)
        mov r36.z, r37.x
        mov r36.w, r25.x
        mov r35.z, r34.x
        mov r35.w, r33.x
        add r32.xyzw, r35.zwxz, r36.zwxz
        mov r37.z, r36.y
        mov r37.w, r25.y
        mov r34.z, r35.y
        mov r34.w, r33.z
        add r25.xyw, r34.zyzw, r37.zyzw
        div r33.xyz, r35.xzwx, r32.zwyz
        add r33.xyz, r33.xyzx, l(-2.500000, -0.500000, 1.500000, 0.000000)
        mul r33.xyz, r33.yxzy, cb4[400].xxxx
        div r34.xyz, r34.zywz, r25.xywx
        add r34.xyz, r34.xyzx, l(-2.500000, -0.500000, 1.500000, 0.000000)
        mul r34.xyz, r34.xyzx, cb4[400].yyyy
        mov r33.w, r34.x
        mad r35.xyzw, r31.xyxy, cb4[400].xyxy, r33.ywxw
        mad r31.zw, r31.xxxy, cb4[400].xxxy, r33.zzzw
        mov r34.w, r33.y
        mov r33.yw, r34.yyyz
        mad r36.xyzw, r31.xyxy, cb4[400].xyxy, r33.xyzy
        mad r34.xyzw, r31.xyxy, cb4[400].xyxy, r34.wywz
        mad r33.xyzw, r31.xyxy, cb4[400].xyxy, r33.xwzw
        mul r37.xyzw, r25.xxxy, r32.zwyz
        sample_c_lz_indexable(texture2d)(float,float,float,float) r24.z, r35.xyxx, t6.xxxx, s4, r25.z
        sample_c_lz_indexable(texture2d)(float,float,float,float) r25.x, r35.zwzz, t6.xxxx, s4, r25.z
        mul r25.x, r25.x, r37.y
        mad r24.z, r37.x, r24.z, r25.x
        sample_c_lz_indexable(texture2d)(float,float,float,float) r25.x, r31.zwzz, t6.xxxx, s4, r25.z
        mad r24.z, r37.z, r25.x, r24.z
        sample_c_lz_indexable(texture2d)(float,float,float,float) r25.x, r34.xyxx, t6.xxxx, s4, r25.z
        mad r24.z, r37.w, r25.x, r24.z
        mul r31.xyzw, r25.yyww, r32.xyzw
        sample_c_lz_indexable(texture2d)(float,float,float,float) r25.x, r36.xyxx, t6.xxxx, s4, r25.z
        mad r24.z, r31.x, r25.x, r24.z
        sample_c_lz_indexable(texture2d)(float,float,float,float) r25.x, r36.zwzz, t6.xxxx, s4, r25.z
        mad r24.z, r31.y, r25.x, r24.z
        sample_c_lz_indexable(texture2d)(float,float,float,float) r25.x, r34.zwzz, t6.xxxx, s4, r25.z
        mad r24.z, r31.z, r25.x, r24.z
        sample_c_lz_indexable(texture2d)(float,float,float,float) r25.x, r33.xyxx, t6.xxxx, s4, r25.z
        mad r24.z, r31.w, r25.x, r24.z
        ige r25.x, r22.w, l(0)
        or r26.xyz, r26.xyzx, r30.xyzx
        or r25.y, r26.y, r26.x
        or r25.y, r26.z, r25.y
        and r26.x, r25.z, l(0x7fffffff)
        ult r26.x, l(0x7f800000), r26.x
        or r25.y, r25.y, r26.x
        mul r25.w, r25.w, r32.y
        sample_c_lz_indexable(texture2d)(float,float,float,float) r25.z, r33.zwzz, t6.xxxx, s4, r25.z
        mad r24.z, r25.w, r25.z, r24.z
        add r24.z, r24.z, l(-1.000000)
        mad r22.w, cb4[r22.w + 288].w, r24.z, l(1.000000)
        movc r22.w, r25.y, l(1.000000), r22.w
        movc r22.w, r25.x, r22.w, l(1.000000)
      else
        mov r22.w, l(1.000000)
      endif
      if_nz r26.w
        dp3 r24.z, r15.xyzx, r28.xyzx
        mul_sat r25.x, r23.w, cb3[r20.z + 6].z
        mad r25.x, r25.x, l(0.500000), r10.w
        min r25.x, r25.x, l(1.000000)
        div r25.x, r10.w, r25.x
        mad r25.yzw, r15.xxyz, r24.zzzz, -r28.xxyz
        dp3 r25.y, r29.xyzx, r25.yzwy
        mul r24.z, r24.z, r24.z
        mad r24.z, cb3[r20.z + 6].z, cb3[r20.z + 6].z, -r24.z
        div_sat r24.z, r25.y, r24.z
        mad r25.yzw, r28.xxyz, r24.zzzz, r29.xxyz
        dp3 r24.z, r25.yzwy, r25.yzwy
        rsq r24.z, r24.z
        mul r27.xyz, r24.zzzz, r25.yzwy
      else
        mov r25.x, l(1.000000)
      endif
      if_nz r21.y
        mul_sat r21.y, r23.w, cb3[r21.w + 6].y
        mad r25.yzw, r10.xxyz, r6.wwww, r27.xxyz
        dp3 r23.w, r25.yzwy, r25.yzwy
        max r23.w, r23.w, l(0.0000610351562)
        rsq r23.w, r23.w
        mul r25.yzw, r23.wwww, r25.yyzw
        dp3 r23.w, r5.xyzx, r27.xyzx
        dp3_sat r24.z, r5.xyzx, r25.yzwy
        dp3_sat r25.y, r11.xyzx, r25.yzwy
        dp3 r25.z, r11.xyzx, r27.xyzx
        lt r25.w, l(0.000000), r21.y
        mul r21.y, r21.y, r21.y
        mad r26.x, r25.y, l(3.600000), l(0.400000)
        div r21.y, r21.y, r26.x
        mad r21.y, r12.w, r12.w, r21.y
        min r21.y, r21.y, l(1.000000)
        movc r21.y, r25.w, r21.y, r10.w
        mul r21.y, r21.y, r21.y
        mad r25.w, r24.z, r21.y, -r24.z
        mad r24.z, r25.w, r24.z, l(1.000000)
        add r25.y, -r25.y, l(1.000000)
        mul r25.w, r25.y, r25.y
        mul r25.w, r25.w, r25.w
        mul r26.x, r25.y, r25.w
        mov_sat r26.y, -r25.z
        mul r26.y, r26.y, r26.y
        mad r26.y, r26.y, l(-0.640000), l(1.000000)
        mul r26.y, r26.y, r26.y
        mad r25.y, -r25.w, r25.y, l(1.000000)
        mad r25.y, r2.z, r25.y, r26.x
        mul r24.z, r24.z, r24.z
        div r24.z, r21.y, r24.z
        mul r24.z, r25.x, r24.z
        mad r25.x, -r12.x, r21.y, r12.x
        mad r25.x, r25.x, r12.x, r21.y
        sqrt r25.x, r25.x
        mad r25.w, -r21.x, r21.y, r21.x
        mad r21.y, r25.w, r21.x, r21.y
        sqrt r21.y, r21.y
        mul r21.y, r12.x, r21.y
        mad r21.y, r21.x, r25.x, r21.y
        add r21.y, r21.y, l(0.000100)
        div r21.y, l(0.500000), r21.y
        mul r21.y, r21.y, r24.z
        mul r21.y, r21.y, r25.y
        min r21.y, r21.y, l(2048.000000)
        mad r25.xy, r21.xzxx, l(0.968750, 0.968750, 0.000000, 0.000000), l(0.015625, 0.015625, 0.000000, 0.000000)
        sample_l_indexable(texture2d)(float,float,float,float) r24.z, r25.xyxx, t9.yzxw, s1, l(0.000000)
        mul r24.z, r12.z, r24.z
        mul r24.z, r11.w, r24.z
        div r24.z, r24.z, r12.y
        mul r24.z, r1.z, r24.z
        div r24.z, r24.z, r13.z
        add r21.y, r21.y, r24.z
        mov_sat r24.z, r25.z
        add r24.z, r24.z, l(0.500000)
        min r24.z, r24.z, l(1.000000)
        mul r25.x, r8.w, r24.z
        add_sat r25.y, r25.z, l(1.000000)
        mad r24.z, -r8.w, r24.z, l(1.000000)
        mad r24.z, r25.y, r24.z, r25.x
        mul r21.y, r21.y, r24.z
        mul r21.y, r4.y, r21.y
        mul r21.y, r21.y, cb3[r21.w + 6].z
        max r21.y, r21.y, l(0.000000)
        min r21.y, r21.y, l(1000.000000)
        add_sat r24.z, -r23.w, l(0.500000)
        ne r25.x, r26.y, l(0.360000)
        div r25.y, l(0.360000), r26.y
        movc r25.x, r25.x, r25.y, l(1.000000)
        mul r24.z, r24.z, r25.x
        mad_sat r23.w, r1.x, l(0.0322580636), r23.w
        add r23.w, -r21.x, r23.w
        mul r25.xyz, r3.xyzx, r23.wwww
        mad r25.xyz, r17.xyzx, r24.zzzz, r25.xyzx
        mul r25.xyz, r4.yyyy, r25.xyzx
        mad r25.xyz, r21.yyyy, r21.xxxx, r25.xyzx
        mad r25.xyz, r18.xyzx, r21.xxxx, r25.xyzx
        mul r26.xyz, r20.xxxx, cb3[r19.z + 6].xyzx
        mul r26.xyz, r22.wwww, r26.xyzx
        mul r26.xyz, r19.xxxx, r26.xyzx
        mul r25.xyz, r25.xyzx, r26.xyzx
      else
        mov r25.xyz, l(0,0,0,0)
      endif
    else
      if_z r19.y
        mad r19.x, cb3[r20.z + 6].y, l(0.500000), l(0.500000)
        add r26.x, r19.x, -|cb3[r20.z + 6].x|
        add r26.y, -r26.x, cb3[r20.z + 6].y
        add r19.x, -|r26.x|, l(1.000000)
        add r19.x, -|r26.y|, r19.x
        max r19.x, r19.x, l(0.000488281250)
        ge r19.y, cb3[r20.z + 6].x, l(0.000000)
        movc r26.z, r19.y, r19.x, -r19.x
        dp3 r19.x, r26.xyzx, r26.xyzx
        rsq r19.x, r19.x
        mul r26.xyz, r19.xxxx, r26.xyzx
        add r27.xyz, -r7.xyzx, cb3[r24.x + 6].xyzx
        dp3 r19.x, r27.xyzx, r27.xyzx
        rsq r19.y, r19.x
        mul r28.xyz, r19.yyyy, r27.xyzx
        ftoi r19.y, cb3[r21.w + 6].w
        mul r21.xyw, r26.xyxz, cb3[r20.z + 6].zzzz
        mad r29.xyz, -r21.xywx, l(0.500000, 0.500000, 0.500000, 0.000000), r27.xyzx
        mad r21.xyw, r21.xyxw, l(0.500000, 0.500000, 0.000000, 0.500000), r27.xyxz
        ftou r19.z, cb3[r19.z + 6].w
        and r19.z, r19.z, l(1)
        ieq r20.x, r19.z, l(0)
        not r20.x, r20.x
        lt r22.w, l(0.000000), cb3[r20.z + 6].z
        and r20.x, r20.x, r22.w
        dp3 r22.w, r29.xyzx, r29.xyzx
        sqrt r22.w, r22.w
        dp3 r23.w, r21.xywx, r21.xywx
        sqrt r23.w, r23.w
        dp3 r21.x, r29.xyzx, r21.xywx
        mad r21.x, r22.w, r23.w, r21.x
        mad r21.x, r21.x, l(0.500000), l(1.000000)
        div r21.x, l(1.000000, 1.000000, 1.000000, 1.000000), r21.x
        movc r21.x, r20.x, r21.x, l(1.000000)
        lt r21.y, cb3[r24.w + 6].w, l(0.000000)
        if_nz r21.y
          mul r21.y, cb3[r24.x + 6].w, cb3[r24.x + 6].w
          mul r21.y, r19.x, r21.y
          mad r21.y, -r21.y, r21.y, l(1.000000)
          max r21.y, r21.y, l(0.000000)
          add r19.x, r19.x, l(1.000000)
          div r19.x, l(1.000000, 1.000000, 1.000000, 1.000000), r19.x
          and r21.w, r20.x, l(0x3f800000)
          add r22.w, -r19.x, r21.x
          mad r19.x, r21.w, r22.w, r19.x
          mul r21.y, r21.y, r21.y
          mul r19.x, r19.x, r21.y
        else
          mul r29.xyz, r27.xyzx, cb3[r24.x + 6].wwww
          dp3 r21.y, r29.xyzx, r29.xyzx
          min r21.y, r21.y, l(1.000000)
          add r21.y, -r21.y, l(1.000000)
          log r21.y, r21.y
          mul r21.y, r21.y, cb3[r24.w + 6].w
          exp r21.y, r21.y
          mul r19.x, r21.y, r21.x
        endif
        dp3 r21.x, r28.xyzx, -r26.xyzx
        add r21.x, r21.x, -cb3[r20.z + 6].z
        mul_sat r21.x, r21.x, cb3[r20.z + 6].w
        mul r21.x, r21.x, r21.x
        movc r21.x, r19.z, l(1.000000), r21.x
        mul r19.x, r19.x, r21.x
        not r20.x, r20.x
        ige r21.x, r19.y, l(0)
        and r20.x, r20.x, r21.x
        if_nz r20.x
          if_z r19.z
            ishl r20.x, r19.y, l(2)
            mul r21.xyw, r7.yyyy, cb5[r20.x + 33].xyxw
            mad r21.xyw, cb5[r20.x + 32].xyxw, r7.xxxx, r21.xyxw
            mad r21.xyw, cb5[r20.x + 34].xyxw, r7.zzzz, r21.xyxw
            add r21.xyw, r21.xyxw, cb5[r20.x + 35].xyxw
            div_sat r21.xy, r21.xyxx, r21.wwww
            mad r21.xy, r21.xyxx, cb5[r19.y + 0].zwzz, cb5[r19.y + 0].xyxx
          else
            ishl r20.x, r19.y, l(2)
            dp3 r26.x, -r27.xyzx, cb5[r20.x + 32].xyzx
            dp3 r26.y, -r27.xyzx, cb5[r20.x + 33].xyzx
            dp3 r26.z, -r27.xyzx, cb5[r20.x + 34].xyzx
            lt r20.x, |r26.x|, |r26.y|
            and r20.x, r20.x, l(1)
            dp2 r21.w, |r26.xyxx|, icb[r20.x + 0].xyxx
            lt r21.w, r21.w, |r26.z|
            movc r20.x, r21.w, l(2), r20.x
            dp3 r21.w, r26.xyzx, icb[r20.x + 0].xyzx
            lt r21.w, r21.w, l(0.000000)
            bfi r20.x, l(31), l(1), r20.x, r21.w
            ushr r21.w, r20.x, l(1)
            dp3 r21.w, r26.xyzx, icb[r21.w + 0].xyzx
            div r22.w, l(0.000244140625), cb5[r19.y + 0].w
            add r22.w, -r22.w, l(0.500000)
            utof r23.w, r20.x
            ult r24.z, r20.x, l(2)
            and r24.z, r24.z, l(2)
            dp2 r24.z, r26.xzxx, icb[r24.z + 0].xzxx
            mul r24.z, r24.z, icb[r20.x + 4].z
            div r24.z, r24.z, |r21.w|
            mad r23.w, r24.z, r22.w, r23.w
            add r23.w, r23.w, l(0.500000)
            mul_sat r27.x, r23.w, l(0.166666672)
            iadd r23.w, l(-1), icb[r20.x + 4].y
            dp2 r23.w, r26.yzyy, icb[r23.w + 0].xyxx
            mul r20.x, r23.w, icb[r20.x + 4].w
            div r20.x, r20.x, |r21.w|
            mad_sat r27.y, -r20.x, r22.w, l(0.500000)
            mad r21.xy, r27.xyxx, cb5[r19.y + 0].zwzz, cb5[r19.y + 0].xyxx
          endif
          sample_l_indexable(texture2d)(float,float,float,float) r19.y, r21.xyxx, t11.yxzw, s1, l(0.000000)
          mul r19.x, r19.y, r19.x
        endif
        lt r19.x, l(0.000000), r19.x
        if_nz r19.x
          if_z r19.z
            ftoi r19.x, cb3[r24.y + 6].x
          else
            add r21.xyw, r7.xyxz, -cb3[r24.x + 6].xyxz
            lt r24.xzw, |r21.yyww|, |r21.xxxy|
            and r19.y, r24.z, r24.x
            lt r21.xyw, l(0.000000, 0.000000, 0.000000, 0.000000), r21.xyxw
            ushr r19.z, cb3[r20.z + 6].w, l(24)
            ubfe r24.xz, l(8, 0, 8, 0), l(16, 0, 8, 0), cb3[r20.z + 6].wwww
            movc r19.z, r21.x, r19.z, r24.x
            and r20.x, l(255), cb3[r20.z + 6].w
            movc r20.x, r21.y, r24.z, r20.x
            ubfe r20.z, l(8), l(8), cb3[r24.y + 6].x
            and r21.x, l(255), cb3[r24.y + 6].x
            movc r20.z, r21.w, r20.z, r21.x
            movc r20.x, r24.w, r20.x, r20.z
            movc r19.y, r19.y, r19.z, r20.x
            ilt r19.z, r19.y, l(80)
            movc r19.x, r19.z, r19.y, l(-1)
          endif
          ishl r19.y, r19.x, l(2)
          mad r21.xyw, r28.xyxz, cb4[r19.x + 288].xxxx, r7.xyxz
          mul r19.z, l(5.000000), cb4[r19.x + 288].y
          mad r21.xyw, r5.xyxz, r19.zzzz, r21.xyxw
          mul r24.xyzw, r21.yyyy, cb4[r19.y + 65].xyzw
          mad r24.xyzw, cb4[r19.y + 64].xyzw, r21.xxxx, r24.xyzw
          mad r24.xyzw, cb4[r19.y + 66].xyzw, r21.wwww, r24.xyzw
          add r24.xyzw, r24.xyzw, cb4[r19.y + 67].xyzw
          div r21.xyw, r24.xyxz, r24.wwww
          ge r24.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r21.xywx
          ge r26.xyz, r21.xywx, l(1.000000, 1.000000, 1.000000, 0.000000)
          add r19.yz, -cb4[r19.x + 344].xxyx, cb4[r19.x + 344].zzwz
          mad r19.yz, r21.xxyx, r19.yyzy, cb4[r19.x + 344].xxyx
          mad r20.xz, r19.yyzy, cb4[400].zzwz, l(0.500000, 0.000000, 0.500000, 0.000000)
          round_ni r20.xz, r20.xxzx
          mad r19.yz, r19.yyzy, cb4[400].zzwz, -r20.xxzx
          add r27.xyzw, r19.yyzz, l(0.500000, 1.000000, 0.500000, 1.000000)
          mul r28.xyzw, r27.xxzz, r27.xxzz
          add r21.xy, -r19.yzyy, l(1.000000, 1.000000, 0.000000, 0.000000)
          min r27.xz, r19.yyzy, l(0.000000, 0.000000, 0.000000, 0.000000)
          max r29.xy, r19.yzyy, l(0.000000, 0.000000, 0.000000, 0.000000)
          mul r30.xy, r21.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
          mad r29.xy, -r29.xyxx, r29.xyxx, r27.ywyy
          add r29.xy, r29.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
          mul r29.xy, r29.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
          mul r28.xz, r28.xxzx, l(0.080000, 0.000000, 0.080000, 0.000000)
          mad r19.yz, r28.yywy, l(0.000000, 0.500000, 0.500000, 0.000000), -r19.yyzy
          mul r31.xy, r19.yzyy, l(0.160000, 0.160000, 0.000000, 0.000000)
          mad r19.yz, -r27.xxzx, r27.xxzx, r21.xxyx
          add r19.yz, r19.yyzy, l(0.000000, 1.000000, 1.000000, 0.000000)
          mul r32.xy, r19.yzyy, l(0.160000, 0.160000, 0.000000, 0.000000)
          mul r19.yz, r27.yywy, l(0.000000, 0.160000, 0.160000, 0.000000)
          mov r31.z, r32.x
          mov r31.w, r19.y
          mov r30.z, r29.x
          mov r30.w, r28.x
          add r27.xyzw, r30.zwxz, r31.zwxz
          mov r32.z, r31.y
          mov r32.w, r19.z
          mov r29.z, r30.y
          mov r29.w, r28.z
          add r28.xyz, r29.zywz, r32.zywz
          div r30.xyz, r30.xzwx, r27.zwyz
          add r30.xyz, r30.xyzx, l(-2.500000, -0.500000, 1.500000, 0.000000)
          mul r30.xyz, r30.yxzy, cb4[400].xxxx
          div r29.xyz, r29.zywz, r28.xyzx
          add r29.xyz, r29.xyzx, l(-2.500000, -0.500000, 1.500000, 0.000000)
          mul r29.xyz, r29.xyzx, cb4[400].yyyy
          mov r30.w, r29.x
          mad r31.xyzw, r20.xzxz, cb4[400].xyxy, r30.ywxw
          mad r19.yz, r20.xxzx, cb4[400].xxyx, r30.zzwz
          mov r29.w, r30.y
          mov r30.yw, r29.yyyz
          mad r32.xyzw, r20.xzxz, cb4[400].xyxy, r30.xyzy
          mad r29.xyzw, r20.xzxz, cb4[400].xyxy, r29.wywz
          mad r30.xyzw, r20.xzxz, cb4[400].xyxy, r30.xwzw
          mul r33.xyzw, r27.zwyz, r28.xxxy
          sample_c_lz_indexable(texture2d)(float,float,float,float) r20.x, r31.xyxx, t6.xxxx, s4, r21.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r20.z, r31.zwzz, t6.xxxx, s4, r21.w
          mul r20.z, r20.z, r33.y
          mad r20.x, r33.x, r20.x, r20.z
          sample_c_lz_indexable(texture2d)(float,float,float,float) r19.y, r19.yzyy, t6.xxxx, s4, r21.w
          mad r19.y, r33.z, r19.y, r20.x
          sample_c_lz_indexable(texture2d)(float,float,float,float) r19.z, r29.xyxx, t6.xxxx, s4, r21.w
          mad r19.y, r33.w, r19.z, r19.y
          mul r31.xyzw, r27.xyzw, r28.yyzz
          sample_c_lz_indexable(texture2d)(float,float,float,float) r19.z, r32.xyxx, t6.xxxx, s4, r21.w
          mad r19.y, r31.x, r19.z, r19.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r19.z, r32.zwzz, t6.xxxx, s4, r21.w
          mad r19.y, r31.y, r19.z, r19.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r19.z, r29.zwzz, t6.xxxx, s4, r21.w
          mad r19.y, r31.z, r19.z, r19.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r19.z, r30.xyxx, t6.xxxx, s4, r21.w
          mad r19.y, r31.w, r19.z, r19.y
          ige r19.z, r19.x, l(0)
          or r24.xyz, r24.xyzx, r26.xyzx
          or r20.x, r24.y, r24.x
          or r20.x, r24.z, r20.x
          and r20.z, r21.w, l(0x7fffffff)
          ult r20.z, l(0x7f800000), r20.z
          or r20.x, r20.z, r20.x
          mul r20.z, r27.y, r28.z
          sample_c_lz_indexable(texture2d)(float,float,float,float) r21.x, r30.zwzz, t6.xxxx, s4, r21.w
          mad r19.y, r20.z, r21.x, r19.y
          add r19.y, r19.y, l(-1.000000)
          mad r19.x, cb4[r19.x + 288].w, r19.y, l(1.000000)
          movc r19.x, r20.x, l(1.000000), r19.x
          movc r19.x, r19.z, r19.x, l(1.000000)
        else
          mov r19.x, l(1.000000)
        endif
      else
        mov r19.x, l(1.000000)
      endif
      mul r17.w, r17.w, r19.x
      mov r25.xyz, l(0,0,0,0)
    endif
    add r23.xyz, r23.xyzx, r25.xyzx
    mov r18.w, r20.w
  endloop
  mov r13.w, r17.w
  add r22.xyz, r22.xyzx, r23.xyzx
  iadd r14.w, r14.w, l(1)
endloop
mad r1.xyz, r22.xyzx, r13.wwww, r14.xyzx
ne r10.xy, l(0.000000, 0.000000, 0.000000, 0.000000), cb0[112].xyxx
movc r10.x, cb13[18].w, l(0xFFFFFFFF), r10.x
if_nz r10.x
  sample_b_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t4.yzxw, s0, cb0[108].x
  mad r0.z, r0.z, l(0.750000), l(0.250000)
  min r0.z, r3.w, r0.z
  add r1.w, r0.z, r9.w
  mad r4.y, r12.w, l(-16.000000), l(-1.000000)
  exp r4.y, r4.y
  log r1.w, |r1.w|
  mul r1.w, r1.w, r4.y
  exp r1.w, r1.w
  add r1.w, r0.z, r1.w
  add r1.w, r1.w, l(-1.000000)
  mov_sat r10.xzw, r1.wwww
  mad r14.xyz, r3.xyzx, l(2.040400, 2.040400, 2.040400, 0.000000), l(-0.332400, -0.332400, -0.332400, 0.000000)
  mul r14.xyz, r0.zzzz, r14.xyzx
  mad r14.xyz, r3.xyzx, l(-4.795100, -4.795100, -4.795100, 0.000000), r14.xyzx
  add r14.xyz, r14.xyzx, l(0.641700, 0.641700, 0.641700, 0.000000)
  mul r14.xyz, r0.zzzz, r14.xyzx
  mad r14.xyz, r3.xyzx, l(2.755200, 2.755200, 2.755200, 0.000000), r14.xyzx
  add r14.xyz, r14.xyzx, l(0.690300, 0.690300, 0.690300, 0.000000)
  mul r14.xyz, r0.zzzz, r14.xyzx
  max r14.xyz, r0.zzzz, r14.xyzx
else
  mov r10.xzw, r3.wwww
  mov r14.xyz, r3.wwww
endif
movc r10.xzw, cb13[18].wwww, r10.xyzw, l(1.0, 0, 1.0, 1.0)
mul r1.xyz, r1.xyzx, r10.xzwx
mad r17.xyz, cb0[6].xzyx, -cb0[212].wwww, cb0[210].xzyx
add r17.xyz, r7.xzyx, -r17.xyzx
max r0.z, |r17.y|, |r17.x|
add r0.z, r0.z, l(-464.000000)
mul_sat r0.z, r0.z, l(0.031250)
add r1.w, |r17.z|, l(-208.000000)
mul_sat r1.w, r1.w, l(0.031250)
max r0.z, r0.z, r1.w
ne r1.w, l(0.000000), cb0[210].w
lt r3.w, r0.z, l(1.000000)
and r1.w, r1.w, r3.w
if_nz r1.w
  mad r17.xyz, cb0[6].xzyx, -cb0[212].yyyy, cb0[210].xzyx
  add r17.xyz, r7.xzyx, -r17.xyzx
  max r1.w, |r17.y|, |r17.x|
  add r1.w, r1.w, l(-29.000000)
  mul_sat r1.w, r1.w, l(0.500000)
  add r3.w, |r17.z|, l(-13.000000)
  mul_sat r3.w, r3.w, l(0.500000)
  max r1.w, r1.w, r3.w
  lt r3.w, r1.w, l(1.000000)
  if_nz r3.w
    mad r17.xyz, r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r18.xyz, r17.xyzx, cb0[211].xyzx
    round_ni r18.xyz, r18.xyzx
    mad r17.xyz, r17.xyzx, cb0[211].xyzx, -r18.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r18.xyw, r17.xyzx, t15.yzwx, s2, l(0.000000)
    add r3.w, -r1.w, l(1.000000)
    mul r4.y, l(0.500000), cb0[211].y
    mad r6.w, -cb0[211].y, l(0.500000), l(1.000000)
    max r4.y, r4.y, r17.y
    min r4.y, r6.w, r4.y
    mul r17.w, r4.y, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r19.xyzw, r17.xwzx, t16.xyzw, s1, l(0.000000)
    mad r4.y, r19.w, r3.w, r0.z
    add r20.xyz, r17.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r20.xyz, r20.xyzx, t16.xyzw, s1, l(0.000000)
    mad r20.xyz, r20.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r20.xyz, r18.yyyy, r20.xyzx
    mov r20.w, r18.y
    mul r20.xyzw, r3.wwww, r20.xyzw
    add r17.xyz, r17.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r17.xyz, r17.xyzx, t16.xyzw, s1, l(0.000000)
    mad r17.xyz, r17.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r17.xyz, r18.xxxx, r17.xyzx
    mov r17.w, r18.x
    mul r17.xyzw, r3.wwww, r17.xyzw
    mad r19.xyz, r19.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r18.xyz, r18.wwww, r19.xyzx
    mul r18.xyzw, r3.wwww, r18.xyzw
  else
    mov r20.xyzw, l(0,0,0,0)
    mov r17.xyzw, l(0,0,0,0)
    mov r18.xyzw, l(0,0,0,0)
    mov r4.y, r0.z
  endif
  mad r19.xyz, cb0[6].xzyx, -cb0[212].zzzz, cb0[210].xzyx
  add r19.xyz, r7.xzyx, -r19.xyzx
  max r3.w, |r19.y|, |r19.x|
  add r3.w, r3.w, l(-116.000000)
  mul_sat r3.w, r3.w, l(0.125000)
  add r6.w, |r19.z|, l(-52.000000)
  mul_sat r6.w, r6.w, l(0.125000)
  max r3.w, r3.w, r6.w
  lt r6.w, r3.w, l(1.000000)
  if_nz r6.w
    mad r19.xyz, r7.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r21.xyz, r19.xyzx, cb0[211].xyzx
    round_ni r21.xyz, r21.xyzx
    mad r19.xyz, r19.xyzx, cb0[211].xyzx, -r21.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r21.xyw, r19.xyzx, t17.yzwx, s2, l(0.000000)
    add r6.w, -r3.w, l(1.000000)
    mul r1.w, r1.w, r6.w
    mul r6.w, l(0.500000), cb0[211].y
    mad r8.w, -cb0[211].y, l(0.500000), l(1.000000)
    max r6.w, r6.w, r19.y
    min r6.w, r8.w, r6.w
    mul r19.w, r6.w, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r22.xyzw, r19.xwzx, t18.xyzw, s1, l(0.000000)
    mad r4.y, r22.w, r1.w, r4.y
    add r23.xyz, r19.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r23.xyz, r23.xyzx, t18.xyzw, s1, l(0.000000)
    mad r23.xyz, r23.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r23.xyz, r21.yyyy, r23.xyzx
    mov r23.w, r21.y
    mad r20.xyzw, r23.xyzw, r1.wwww, r20.xyzw
    add r19.xyz, r19.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r19.xyz, r19.xyzx, t18.xyzw, s1, l(0.000000)
    mad r19.xyz, r19.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r19.xyz, r21.xxxx, r19.xyzx
    mov r19.w, r21.x
    mad r17.xyzw, r19.xyzw, r1.wwww, r17.xyzw
    mad r19.xyz, r22.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r21.xyz, r21.wwww, r19.xyzx
    mad r18.xyzw, r21.xyzw, r1.wwww, r18.xyzw
  endif
  lt r1.w, l(0.000000), r3.w
  if_nz r1.w
    mad r19.xyz, r7.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r21.xyz, r19.xyzx, cb0[211].xyzx
    mul r22.xyz, l(0.500000, 0.500000, 0.500000, 0.000000), cb0[211].xyzx
    round_ni r21.xyz, r21.xyzx
    mad r19.xyz, r19.xyzx, cb0[211].xyzx, -r21.xyzx
    mad r21.xyz, -cb0[211].xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(1.000000, 1.000000, 1.000000, 0.000000)
    max r19.xyz, r22.xyzx, r19.xyzx
    min r19.xyz, r21.xyzx, r19.xyzx
    sample_l_indexable(texture3d)(float,float,float,float) r23.xyw, r19.xyzx, t19.yzwx, s2, l(0.000000)
    add r1.w, -r0.z, l(1.000000)
    mul r1.w, r1.w, r3.w
    max r3.w, r22.y, r19.y
    min r3.w, r21.y, r3.w
    mul r19.w, r3.w, l(0.333333343)
    sample_l_indexable(texture3d)(float,float,float,float) r21.xyzw, r19.xwzx, t20.xyzw, s1, l(0.000000)
    add r22.xyz, r19.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r22.xyz, r22.xyzx, t20.xyzw, s1, l(0.000000)
    mad r22.xyz, r22.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r22.xyz, r23.yyyy, r22.xyzx
    mov r22.w, r23.y
    mad r20.xyzw, r22.xyzw, r1.wwww, r20.xyzw
    add r19.xyz, r19.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
    sample_l_indexable(texture3d)(float,float,float,float) r19.xyz, r19.xyzx, t20.xyzw, s1, l(0.000000)
    mad r19.xyz, r19.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r19.xyz, r23.xxxx, r19.xyzx
    mov r19.w, r23.x
    mad r17.xyzw, r19.xyzw, r1.wwww, r17.xyzw
    mad r19.xyz, r21.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
    mul r23.xyz, r23.wwww, r19.xyzx
    mad r18.xyzw, r23.xyzw, r1.wwww, r18.xyzw
    mad r4.y, r21.w, r1.w, r4.y
  endif
  mad_sat r1.w, r4.y, l(2.000000), l(-1.000000)
  add r19.x, -r0.z, r1.w
  add r0.z, r0.z, r1.w
  mul r19.y, r0.z, l(0.500000)
else
  mov r20.xyzw, l(0,0,0,0)
  mov r17.xyzw, l(0,0,0,0)
  mov r18.xyzw, l(0,0,0,0)
  mov r19.xy, l(0,1.000000,0,0)
endif
mul r21.xyzw, r19.yyyx, cb0[213].xyzw
mad r21.y, r21.w, l(0.500000), r21.y
mul r12.yz, r19.yyxy, cb0[213].wwyw
mad r21.w, r12.z, l(0.375000), r12.y
add r18.xyzw, r18.xyzw, r21.xyzw
mul r21.xyzw, r19.yyyx, cb0[214].xyzw
mad r21.y, r21.w, l(0.500000), r21.y
mul r12.yz, r19.yyxy, cb0[214].wwyw
mad r21.w, r12.z, l(0.375000), r12.y
add r17.xyzw, r17.xyzw, r21.xyzw
mul r21.xyzw, r19.yyyx, cb0[215].xyzw
mad r21.y, r21.w, l(0.500000), r21.y
mul r12.yz, r19.yyxy, cb0[215].wwyw
mad r21.w, r12.z, l(0.375000), r12.y
add r19.xyzw, r20.xyzw, r21.xyzw
ge r12.yz, r6.xxyx, l(0.000000, 0.000000, 0.000000, 0.000000)
and r0.z, r12.z, r12.y
if_nz r0.z
  sample_l_indexable(texture2d)(float,float,float,float) r20.xyzw, r6.xyxx, t14.xyzw, s1, l(0.000000)
  lt r21.xyzw, l(0.000100, 0.000100, 0.000100, 0.000100), |r20.xyzw|
  or r6.xy, r21.zwzz, r21.xyxx
  or r0.z, r6.y, r6.x
  if_nz r0.z
    dp3 r0.z, r20.yzwy, r20.yzwy
    sqrt r0.z, r0.z
    mov r6.x, l(1.000000)
    mov r6.y, r0.z
    mov r1.w, l(0)
    loop
      ge r3.w, l(4.600000), r6.y
      breakc_nz r3.w
      iadd r3.w, r1.w, l(1)
      mul r12.yz, r6.xxyx, l(0.000000, 0.500000, 0.500000, 0.000000)
      mov r6.xy, r12.yzyy
      mov r1.w, r3.w
      continue
    endloop
    mul r20.xyzw, r6.xxxx, r20.xyzw
    dp3 r0.z, r20.yzwy, r20.yzwy
    sqrt r0.z, r0.z
    mad r0.z, r0.z, cb6[3].x, cb6[3].y
    mad r0.z, r0.z, l(255.000000), l(0.500000)
    mul r6.x, r0.z, l(0.00390625000)
    mov r6.y, l(0.500000)
    sample_l_indexable(texture2d)(float,float,float,float) r6.xy, r6.xyxx, t13.xyzw, s1, l(0.000000)
    mad r6.xy, r6.xyxx, cb6[2].xyxx, cb6[2].zwzz
    mul r21.x, r6.x, l(3.54490781)
    mul r21.yzw, r6.yyyy, r20.yyzw
    mul r0.z, r20.x, l(0.406976730)
    exp r0.z, r0.z
    mul r20.xyzw, r0.zzzz, r21.xyzw
    mov r21.xyzw, r20.xyzw
    mov r0.z, l(0)
    loop
      uge r3.w, r0.z, r1.w
      breakc_nz r3.w
      mul r22.xyzw, r21.xyzw, l(0.282094777, 0.282094777, 0.282094777, 0.282094777)
      dp4 r3.w, r22.xyzw, r21.xyzw
      dp2 r4.y, r22.yxyy, r21.xyxx
      dp2 r6.x, r22.zxzz, r21.xzxx
      dp2 r6.y, r22.wxww, r21.xwxx
      iadd r6.w, r0.z, l(1)
      mov r21.x, r3.w
      mov r21.y, r4.y
      mov r21.zw, r6.xxxy
      mov r0.z, r6.w
      continue
    endloop
    mul r20.xyzw, r21.xyzw, l(0.282094777, 0.282094777, 0.282094777, 0.282094777)
    mul r21.xyzw, r18.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r0.z, r20.xyzw, r21.xyzw
    dp2 r1.w, r20.yxyy, r21.xyxx
    dp2 r3.w, r20.zxzz, r21.xzxx
    dp2 r4.y, r20.wxww, r21.xwxx
    mul r21.xyzw, r17.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r6.x, r20.xyzw, r21.xyzw
    dp2 r6.y, r20.yxyy, r21.xyxx
    dp2 r6.w, r20.zxzz, r21.xzxx
    dp2 r8.w, r20.wxww, r21.xwxx
    mul r21.xyzw, r19.wyzx, l(1.12837911, -0.977205, 0.977205, -0.977205)
    dp4 r9.w, r20.xyzw, r21.xyzw
    dp2 r11.w, r20.yxyy, r21.xyxx
    dp2 r12.y, r20.zxzz, r21.xzxx
    dp2 r12.z, r20.wxww, r21.xwxx
    mul r18.w, r0.z, l(0.886226952)
    mul r18.x, r4.y, l(-1.02332675)
    mul r18.y, r1.w, l(-1.02332675)
    mul r18.z, r3.w, l(1.02332675)
    mul r17.x, r8.w, l(-1.02332675)
    mul r17.yzw, r6.yywx, l(0.000000, -1.02332675, 1.02332675, 0.886226952)
    mul r19.w, r9.w, l(0.886226952)
    mul r19.y, r11.w, l(-1.02332675)
    mul r19.xz, r12.zzyz, l(-1.02332675, 0.000000, 1.02332675, 0.000000)
  endif
endif
mov r5.w, l(1.000000)
dp4 r20.x, r18.xyzw, r5.xyzw
dp4 r20.y, r17.xyzw, r5.xyzw
dp4 r20.z, r19.xyzw, r5.xyzw
max r6.xyw, r20.xyxz, l(0.000000, 0.000000, 0.000000, 0.000000)
add r0.z, l(-1.000000), cb0[113].x
max r1.w, r12.w, l(0.001000)
log r1.w, r1.w
mad r1.w, -r1.w, l(1.200000), l(1.000000)
add r0.z, r0.z, -r1.w
mul r12.yz, r2.xxyx, cb1[0].wwww
round_ni r12.yz, r12.yyzy
add r1.w, |r4.w|, -cb1[2].y
round_ni r1.w, r1.w
add r3.w, l(-1.000000), cb1[1].x
max r4.y, r1.w, l(0.000000)
min r3.w, r3.w, r4.y
ge r1.w, r3.w, r1.w
mad r4.y, r12.z, cb1[0].x, r12.y
ftoi r4.y, r4.y
iadd r4.y, r4.y, cb0[110].z
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r4.y, r4.y, l(0), t0.xxxx
ftoi r3.w, r3.w
iadd r3.w, r3.w, cb0[110].w
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r3.w, l(0), t0.xxxx
and r3.w, r3.w, r4.y
and r1.w, r1.w, r3.w
mul r12.yzw, r6.xxyw, cb0[111].xxxx
dp3 r3.w, r12.yzwy, l(0.212672904, 0.715152204, 0.072175, 0.000000)
mov r7.w, l(1.000000)
mov r12.yzw, l(0,0,0,0)
mov r4.y, l(1.000000)
mov r8.w, r1.w
mov r9.w, l(0)
loop
  lt r11.w, l(0.010000), r4.y
  ine r13.z, r8.w, l(0)
  and r13.z, r11.w, r13.z
  if_nz r13.z
    firstbit_lo r13.z, r8.w
    ishl r13.w, l(1), r13.z
    xor r8.w, r8.w, r13.w
    ishl r13.z, r13.z, l(3)
    dp4 r20.x, cb1[r13.z + 6].xyzw, r7.xyzw
    dp4 r20.y, cb1[r13.z + 7].xyzw, r7.xyzw
    dp4 r20.z, cb1[r13.z + 8].xyzw, r7.xyzw
    ge r21.xyz, cb1[r13.z + 5].xyzx, |r20.xyzx|
    and r13.w, r21.y, r21.x
    and r13.w, r21.z, r13.w
    if_nz r13.w
      mul r13.w, l(0.100000), cb1[r13.z + 5].x
      mul r21.xyz, |r20.xyzx|, l(0.100000, 0.100000, 0.100000, 0.000000)
      mul r21.xy, r21.xyxx, r21.xyxx
      add r22.xyz, -|r20.xyzx|, cb1[r13.z + 5].xyzx
      mul r22.xyz, r22.xyzx, cb1[r13.z + 9].xyzx
      eq r14.w, l(1.000000), cb1[r13.z + 10].x
      if_nz r14.w
        dp3 r23.x, cb1[r13.z + 6].xyzx, r15.xyzx
        dp3 r23.y, cb1[r13.z + 7].xyzx, r15.xyzx
        dp3 r23.z, cb1[r13.z + 8].xyzx, r15.xyzx
        add r24.xyz, -r20.xyzx, cb1[r13.z + 5].xyzx
        div r24.xyz, r24.xyzx, r23.xyzx
        add r25.xyz, -r20.xyzx, -cb1[r13.z + 5].xyzx
        div r25.xyz, r25.xyzx, r23.xyzx
        lt r26.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r23.xyzx
        movc r24.xyz, r26.xyzx, r24.xyzx, r25.xyzx
        min r14.w, r24.y, r24.x
        min r14.w, r24.z, r14.w
        mad r20.xyz, r23.xyzx, r14.wwww, r20.xyzx
      else
        mov r20.xyz, r15.xyzx
      endif
      dp3 r14.w, r20.xyzx, r20.xyzx
      rsq r14.w, r14.w
      mul r20.xyz, r14.wwww, r20.xyzx
      lt r23.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r20.xyzx
      lt r24.xyz, r20.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
      iadd r23.xyz, -r23.xyzx, r24.xyzx
      itof r23.xyz, r23.xyzx
      dp3 r14.w, r20.xyzx, r23.xyzx
      div r20.xyz, r20.xyzx, r14.wwww
      lt r14.w, r20.z, l(0.000000)
      add r20.zw, -|r20.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
      mul r20.zw, r20.zzzw, r23.xxxy
      movc r20.xy, r14.wwww, r20.zwzz, r20.xyxx
      dp4 r14.w, cb1[r13.z + 4].xyzw, r5.xyzw
      max r14.w, r14.w, l(0.000000)
      max r14.w, r14.w, l(0.000100)
      min r15.w, r22.z, r22.y
      min r15.w, r15.w, r22.x
      add r16.w, r21.y, r21.x
      mad r16.w, r21.z, r21.z, r16.w
      mad r13.w, r13.w, r13.w, -r16.w
      mul r13.w, r13.w, cb1[r13.z + 9].x
      mul r13.w, r13.w, cb1[r13.z + 9].x
      add r16.w, l(1.000000), -cb1[r13.z + 10].y
      mul r13.w, r13.w, r16.w
      mul r13.w, r13.w, l(100.000000)
      mad_sat r13.w, r15.w, cb1[r13.z + 10].y, r13.w
      mul r15.w, r13.w, cb1[r13.z + 10].w
      mad r20.xy, r20.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
      mad r20.xy, r20.xyxx, cb1[1].wwww, cb1[2].wwww
      mov r20.z, cb1[r13.z + 5].w
      sample_l_indexable(texture2darray)(float,float,float,float) r20.xyz, r20.xyzx, t5.xyzw, s3, r0.z
      mul r20.xyz, r20.xyzx, cb1[r13.z + 9].wwww
      div r16.w, r3.w, r14.w
      min r16.w, |r16.w|, l(1.000000)
      mad r16.w, r16.w, l(2.000000), r3.w
      add r14.w, r14.w, l(2.000000)
      div r14.w, r16.w, r14.w
      add r14.w, r14.w, l(-1.000000)
      mad r14.w, r14.w, cb0[112].w, l(1.000000)
      mul r20.xyz, r14.wwww, r20.xyzx
      mul r20.xyz, r15.wwww, r20.xyzx
      mad r12.yzw, r20.xxyz, r4.yyyy, r12.yyzw
      mad r13.z, -r13.w, cb1[r13.z + 10].w, l(1.000000)
      mul r4.y, r4.y, r13.z
    endif
    mov r9.w, l(-1)
    continue
  else
    mov r9.w, r11.w
    break
  endif
  mov r9.w, r11.w
endloop
if_nz r9.w
  dp3 r1.w, r15.xyzx, r15.xyzx
  rsq r1.w, r1.w
  mul r15.xyz, r1.wwww, r15.xyzx
  lt r20.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r15.xyzx
  lt r21.xyz, r15.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  iadd r20.xyz, -r20.xyzx, r21.xyzx
  itof r20.xyz, r20.xyzx
  dp3 r1.w, r15.xyzx, r20.xyzx
  div r15.xyz, r15.xyzx, r1.wwww
  lt r1.w, r15.z, l(0.000000)
  add r13.zw, -|r15.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
  mul r13.zw, r13.zzzw, r20.xxxy
  movc r13.zw, r1.wwww, r13.zzzw, r15.xxxy
  dp4 r1.w, cb1[3].xyzw, r5.xyzw
  max r1.w, r1.w, l(0.000000)
  max r1.w, r1.w, l(0.000100)
  mad r13.zw, r13.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
  mad r15.xy, r13.zwzz, cb1[1].wwww, cb1[2].wwww
  mov r15.z, l(0)
  sample_l_indexable(texture2darray)(float,float,float,float) r15.xyz, r15.xyzx, t5.xyzw, s3, r0.z
  div r0.z, r3.w, r1.w
  min r0.z, |r0.z|, l(1.000000)
  mad r0.z, r0.z, l(2.000000), r3.w
  add r1.w, r1.w, l(2.000000)
  div r0.z, r0.z, r1.w
  add r0.z, r0.z, l(-1.000000)
  mad r0.z, r0.z, cb0[112].w, l(1.000000)
  mul r15.xyz, r0.zzzz, r15.xyzx
  mad r12.yzw, r15.xxyz, r4.yyyy, r12.yyzw
endif
mul r12.yzw, r12.yyzw, cb0[112].zzzz
mul r12.yzw, r12.yyzw, cb0[111].yyyy
if_nz r10.y
  sample_b_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t3.yzxw, s1, cb0[108].x
  sample_b_indexable(texture2d)(float,float,float,float) r15.xyz, v1.xyxx, t2.xyzw, s1, cb0[108].x
  add r1.w, -r0.z, l(1.000000)
  mul r20.xyz, r1.wwww, r12.yzwy
  mad r12.yzw, r15.xxyz, r0.zzzz, r20.xxyz
endif
mul r3.xyz, r3.xyzx, r6.xywx
mul r3.xyz, r3.xyzx, cb0[111].xxxx
mad r0.z, r2.z, r13.x, r13.y
mul r6.xyw, r0.zzzz, r12.yzyw
mul r6.xyw, r10.xzxw, r6.xyxw
mad r3.xyz, r3.xyzx, r14.xyzx, r6.xywx
mul r5.xyzw, r5.xyzw, l(-1.000000, -1.000000, -1.000000, 1.000000)
dp4 r10.x, r18.xyzw, r5.xyzw
dp4 r10.y, r17.xyzw, r5.xyzw
dp4 r10.z, r19.xyzw, r5.xyzw
max r5.xyz, r10.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mul r5.xyz, r5.xyzx, cb0[111].xxxx
mul r5.xyz, r14.xyzx, r5.xyzx
mul r5.xyz, r16.xyzx, r5.xyzx
mul r0.z, r4.x, r12.x
ftou r1.w, r2.w
bfi r1.w, l(2), l(0), r1.w, r4.z
utof r1.w, r1.w
mul r1.w, r1.w, l(0.0322580636)
mad r0.z, r0.z, l(0.00787401572), r1.w
mul r4.xyz, r0.zzzz, r5.xyzx
mad r3.xyz, r4.xyzx, l(0.318309873, 0.318309873, 0.318309873, 0.000000), r3.xyzx
add r1.xyz, r1.xyzx, r3.xyzx
max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r1.xyz, r1.xyzx, l(255.000000, 255.000000, 255.000000, 0.000000)
mad r0.z, r7.y, cb0[156].w, cb0[157].w
max r0.z, r0.z, l(0.010000)
mad r1.w, r6.z, cb0[154].w, -cb0[153].w
max r1.w, r1.w, l(0.000000)
mul r2.z, r0.z, l(-1.442695)
exp r2.z, r2.z
add r2.z, -r2.z, l(1.000000)
div r0.z, r2.z, r0.z
mad r2.z, r7.y, cb0[156].w, cb0[158].w
mul r2.z, r2.z, l(1.442695)
exp r2.z, r2.z
mul r0.z, r0.z, r2.z
mul r0.z, r0.z, -r1.w
mul r3.xyz, r0.zzzz, cb0[155].xyzx
mul r3.xyz, r3.xyzx, l(1.442695, 1.442695, 1.442695, 0.000000)
exp r3.xyz, r3.xyzx
dp3 r0.z, -r11.xyzx, cb0[154].xyzx
mad r1.w, cb0[155].w, cb0[155].w, l(1.000000)
dp2 r2.z, r0.zzzz, cb0[155].wwww
add r1.w, r1.w, -r2.z
lt r2.z, l(0.000000), cb0[163].z
if_nz r2.z
  and r0.w, l(7), cb0[108].w
  imad r0.xyw, r0.xyxw, l(0x0019660d, 0x0019660d, 0, 0x0019660d), l(0x3c6ef35f, 0x3c6ef35f, 0, 0x3c6ef35f)
  imad r0.x, r0.y, r0.w, r0.x
  imad r0.y, r0.w, r0.x, r0.y
  imad r0.w, r0.x, r0.y, r0.w
  imad r4.x, r0.y, r0.w, r0.x
  dp3 r0.x, -r11.xyzx, -r9.xyzx
  add r2.z, r7.y, -cb0[44].y
  lt r2.w, l(5.960464478E-08), r0.x
  div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
  and r0.x, r0.x, r2.w
  mul r0.x, r0.x, cb0[163].w
  div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.z
  mul r3.w, r0.x, r2.w
  mad r4.z, r3.w, r2.z, cb0[44].y
  mad r2.z, -r3.w, r2.z, r2.z
  mul r3.w, r2.z, cb0[159].z
  max r3.w, r3.w, l(-127.000000)
  mul r2.z, r2.z, cb0[162].x
  max r2.z, r2.z, l(-127.000000)
  add r5.x, r4.z, -cb0[159].x
  mul r5.x, r5.x, cb0[159].z
  max r5.x, r5.x, l(-127.000000)
  exp r5.x, -r5.x
  mul r5.x, r5.x, cb0[159].y
  lt r5.y, l(5.960464478E-08), |r3.w|
  exp r5.z, -r3.w
  add r5.z, -r5.z, l(1.000000)
  div r5.z, r5.z, r3.w
  mad r3.w, -r3.w, l(0.240226507), l(0.693147182)
  movc r3.w, r5.y, r5.z, r3.w
  add r4.z, r4.z, -cb0[162].z
  mul r4.z, r4.z, cb0[162].x
  max r4.z, r4.z, l(-127.000000)
  exp r4.z, -r4.z
  mul r4.z, r4.z, cb0[162].y
  lt r5.y, l(5.960464478E-08), |r2.z|
  exp r5.z, -r2.z
  add r5.z, -r5.z, l(1.000000)
  div r5.z, r5.z, r2.z
  mad r2.z, -r2.z, l(0.240226507), l(0.693147182)
  movc r2.z, r5.y, r5.z, r2.z
  mul r2.z, r2.z, r4.z
  mad r2.z, r5.x, r3.w, r2.z
  mad r0.x, -r0.x, r2.w, l(1.000000)
  mul r0.x, r6.z, r0.x
  mul r0.x, r0.x, r2.z
  exp r0.x, -r0.x
  min r0.x, r0.x, l(1.000000)
  max r0.x, r0.x, cb0[161].w
  mad_sat r2.zw, r6.zzzz, cb0[160].yyyw, cb0[160].xxxz
  add r0.x, r0.x, r2.z
  add r0.x, r2.w, r0.x
  min r0.x, r0.x, l(1.000000)
  imad r4.y, r0.w, r4.x, r0.y
  ushr r0.yw, r4.xxxy, l(0, 16, 0, 16)
  utof r0.yw, r0.yyyw
  mad r0.yw, r0.yyyw, l(0.000000, 0.0000305180438, 0.000000, 0.0000305180438), l(0.000000, -1.000000, 0.000000, -1.000000)
  mad r0.yw, r0.yyyw, cb0[167].wwww, r2.xxxy
  mul r2.xy, r0.ywyy, cb0[165].xyxx
  mad r0.y, |r4.w|, cb0[164].x, cb0[164].y
  log r0.y, r0.y
  mul r0.y, r0.y, cb0[164].z
  div r2.z, r0.y, cb0[163].z
  sample_l_indexable(texture3d)(float,float,float,float) r2.xyzw, r2.xyzx, t12.xyzw, s1, l(0.000000)
  add r0.y, |r4.w|, -cb0[166].z
  mul_sat r0.y, r0.y, l(1000000.000000)
  add r2.xyzw, r2.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
  mad r2.xyzw, r0.yyyy, r2.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
  add r0.y, -r0.x, l(1.000000)
  mul r4.xyz, r0.yyyy, cb0[161].xyzx
  mad r2.xyz, r4.xyzx, r2.wwww, r2.xyzx
  mul r0.x, r0.x, r2.w
else
  add r0.y, r7.y, -cb0[44].y
  mul r0.w, r0.y, cb0[159].z
  mul r0.y, r0.y, cb0[162].x
  max r0.yw, r0.yyyw, l(0.000000, -127.000000, 0.000000, -127.000000)
  add r2.w, cb0[44].y, -cb0[159].x
  mul r2.w, r2.w, cb0[159].z
  max r2.w, r2.w, l(-127.000000)
  exp r2.w, -r2.w
  mul r2.w, r2.w, cb0[159].y
  lt r3.w, l(5.960464478E-08), |r0.w|
  exp r4.x, -r0.w
  add r4.x, -r4.x, l(1.000000)
  div r4.x, r4.x, r0.w
  mad r0.w, -r0.w, l(0.240226507), l(0.693147182)
  movc r0.w, r3.w, r4.x, r0.w
  add r3.w, cb0[44].y, -cb0[162].z
  mul r3.w, r3.w, cb0[162].x
  max r3.w, r3.w, l(-127.000000)
  exp r3.w, -r3.w
  mul r3.w, r3.w, cb0[162].y
  lt r4.x, l(5.960464478E-08), |r0.y|
  exp r4.y, -r0.y
  add r4.y, -r4.y, l(1.000000)
  div r4.y, r4.y, r0.y
  mad r0.y, -r0.y, l(0.240226507), l(0.693147182)
  movc r0.y, r4.x, r4.y, r0.y
  mul r0.y, r0.y, r3.w
  mad r0.y, r2.w, r0.w, r0.y
  mul r0.y, r6.z, r0.y
  exp r0.y, -r0.y
  min r0.y, r0.y, l(1.000000)
  max r0.y, r0.y, cb0[161].w
  mad_sat r4.xy, r6.zzzz, cb0[160].ywyy, cb0[160].xzxx
  add r0.y, r0.y, r4.x
  add r0.y, r4.y, r0.y
  min r0.x, r0.y, l(1.000000)
  add r0.y, -r0.x, l(1.000000)
  mul r2.xyz, r0.yyyy, cb0[161].xyzx
endif
mul r4.xyz, r0.xxxx, r3.xyzx
mad r0.y, r0.z, r0.z, l(1.000000)
mul r0.y, r0.y, l(0.0596831031)
mad r0.yzw, cb0[156].xxyz, r0.yyyy, cb0[158].xxyz
mad r2.w, -cb0[155].w, cb0[155].w, l(1.000000)
mul r3.w, r1.w, l(12.566371)
sqrt r1.w, r1.w
mul r1.w, r1.w, r3.w
max r1.w, r1.w, l(0.001000)
div r1.w, r2.w, r1.w
mad_sat r0.yzw, cb0[157].xxyz, r1.wwww, r0.yyzw
mul r0.yzw, r0.yyzw, l(0.000000, 255.000000, 255.000000, 255.000000)
add r3.xyz, -r3.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r0.yzw, r0.yyzw, r3.xxyz
mad r0.xyz, r0.yzwy, r0.xxxx, r2.xyzx
// Check fog modification toggle (cb13[12].y)
// If 0 (Original), skip fog modification and output original
if_z cb13[12].y
  mad r0.xyz, r1.xyzx, r4.xyzx, r0.xyzx
  dp3 r0.w, r4.xyzx, l(0.333333343, 0.333333343, 0.333333343, 0.000000)
  dp3 r1.w, r8.xyzx, r8.xyzx
  sqrt r1.w, r1.w
  mad_sat r1.w, -r1.w, cb0[169].z, l(1.000000)
  mul r2.x, r1.w, cb0[169].x
  mad r1.w, -cb0[169].x, r1.w, l(1.000000)
  mul r2.yzw, cb0[168].xxyz, cb0[183].wwww
  mad r2.yzw, r7.xxyz, cb0[169].yyyy, r2.yyzw
  sample_l_indexable(texture3d)(float,float,float,float) r2.y, r2.yzwy, t25.xwyz, s2, l(0.000000)
  dp2 r2.x, r2.yyyy, r2.xxxx
  add r1.w, r1.w, r2.x
  add r2.x, r0.w, l(1.000000)
  min r1.w, r1.w, r2.x
  add r0.xyz, -r1.xyzx, r0.xyzx
  mad o0.xyz, r1.wwww, r0.xyzx, r1.xyzx
  mov o0.w, r0.w
  ret
endif

// === Simplified Fog Modification (Anti-Banding) ===
// r1.xyz = scene color (0-255), r4.xyz = transmittance, r0.xyz = fog inscatter (0-255)

// Normalize colors to 0-1 range
mul r9.xyz, r1.xyzx, l(0.003921569, 0.003921569, 0.003921569, 0.000000)  // sceneColor = r1/255
mul r10.xyz, r0.xyzx, l(0.003921569, 0.003921569, 0.003921569, 0.000000)  // fogColor = r0/255

// Boost transmittance: transmittance = lerp(transmittance, 1, 0.35) to reduce fog density
add r11.xyz, -r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mad r11.xyz, r11.xyzx, l(0.350000, 0.350000, 0.350000, 0.000000), r4.xyzx

// Reduce fog inscatter intensity
mul r10.xyz, r10.xyzx, l(0.650000, 0.650000, 0.650000, 0.000000)

// Standard fog blend with reduced intensity
mad r12.xyz, r9.xyzx, r11.xyzx, r10.xyzx

// Scale back to 0-255
mul r0.xyz, r12.xyzx, l(255.000000, 255.000000, 255.000000, 0.000000)

// Continue with original post-fog processing
dp3 r0.w, r4.xyzx, l(0.333333343, 0.333333343, 0.333333343, 0.000000)
dp3 r1.w, r8.xyzx, r8.xyzx
sqrt r1.w, r1.w
mad_sat r1.w, -r1.w, cb0[169].z, l(1.000000)
mul r2.x, r1.w, cb0[169].x
mad r1.w, -cb0[169].x, r1.w, l(1.000000)
mul r2.yzw, cb0[168].xxyz, cb0[183].wwww
mad r2.yzw, r7.xxyz, cb0[169].yyyy, r2.yyzw
sample_l_indexable(texture3d)(float,float,float,float) r2.y, r2.yzwy, t25.xwyz, s2, l(0.000000)
dp2 r2.x, r2.yyyy, r2.xxxx
add r1.w, r1.w, r2.x
add r2.x, r0.w, l(1.000000)
min r1.w, r1.w, r2.x
add r0.xyz, -r1.xyzx, r0.xyzx
mad o0.xyz, r1.wwww, r0.xyzx, r1.xyzx
mov o0.w, r0.w
ret
// Approximately 0 instruction slots used
