//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.4.1 on Sat Jan 31 16:59:16 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy w
// TEXCOORD                 0   xy          1     NONE   float   xy
// TEXCOORD                 1   xyz         2     NONE   float   xyz
// TEXCOORD                 2   xyz         3     NONE   float   xyz
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyz         5     NONE   float   xyz
// TEXCOORD                 5   xyz         6     NONE   float   xyz
// TEXCOORD                 6   xyz         7     NONE   float   xyz
// TEXCOORD                 7   xyz         8     NONE   float   xyz
// TEXCOORD                 8   x           9     NONE    uint   x
// SV_IsFrontFace           0   x          10    FFACE    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                              { 0, 1.000000, 0, 0},
                              { 0, 0, 1.000000, 0},
                              { 0, 0, 0, 1.000000},
                              { 2, 1, -1.000000, 1.000000},
                              { 2, 1, 1.000000, 1.000000},
                              { 0, 2, 1.000000, -1.000000},
                              { 0, 2, 1.000000, 1.000000},
                              { 0, 1, 1.000000, 1.000000},
                              { 0, 1, -1.000000, 1.000000} }
dcl_constantbuffer CB0[216], immediateIndexed
dcl_constantbuffer CB1[4093], dynamicIndexed
dcl_constantbuffer CB2[3], immediateIndexed
dcl_constantbuffer CB3[2054], dynamicIndexed
dcl_constantbuffer CB4[401], dynamicIndexed
dcl_constantbuffer CB5[9], immediateIndexed
dcl_constantbuffer CB6[160], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_comparison
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_resource_structured t0, 4
dcl_resource_structured t1, 16
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture3d (float,float,float,float) t4
dcl_resource_texture3d (float,float,float,float) t5
dcl_resource_texture3d (float,float,float,float) t6
dcl_resource_texture3d (float,float,float,float) t7
dcl_resource_texture3d (float,float,float,float) t8
dcl_resource_texture3d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t14
dcl_resource_texture2d (float,float,float,float) t15
dcl_resource_texturecube (float,float,float,float) t16
dcl_resource_texture2d (float,float,float,float) t17
dcl_resource_texture3d (float,float,float,float) t18
dcl_input_ps_siv linear noperspective v0.xyw, position
dcl_input_ps linear v1.xy
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.xyz
dcl_input_ps linear v7.xyz
dcl_input_ps linear v8.xyz
dcl_input_ps constant v9.x
dcl_input_ps_sgv constant v10.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 32
add r0.xyz, -v2.xyzx, cb0[44].xyzx
mov r1.x, cb0[0].z
mov r1.y, cb0[1].z
mov r1.z, cb0[2].z
add r2.xyz, -r0.xyzx, r1.xyzx
mad r0.xyz, cb0[86].wwww, r2.xyzx, r0.xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
max r1.w, r0.w, l(9.999999939E-09)
rsq r1.w, r1.w
mul r2.xyz, r0.xyzx, r1.wwww
ishl r2.w, v9.x, l(4)
and r3.x, l(16), cb1[r2.w + 4].w
if_nz r3.x
  iadd r3.x, l(2), cb1[r2.w + 5].x
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.x, r3.x, l(12), t1.xxxx
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.y, cb1[r2.w + 5].x, l(12), t1.xxxx
else
  mov r3.xy, cb1[r2.w + 3].zxzz
endif
sample_b_indexable(texture2d)(float,float,float,float) r4.xyzw, v1.xyxx, t12.xyzw, s3, cb0[108].x
sample_b_indexable(texture2d)(float,float,float,float) r5.xyzw, v1.xyxx, t13.xyzw, s4, cb0[108].x
add r3.z, -r5.w, l(1.000000)
mul r4.xyzw, r4.xyzw, cb5[5].xyzw
mul r6.xyz, r4.xyzx, cb5[4].zzzz
dp3 r3.w, r6.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
mad r6.xyz, r4.xyzx, cb5[4].zzzz, -r3.wwww
mad r6.xyz, cb5[4].wwww, r6.xyzx, r3.wwww
sample_b_indexable(texture2d)(float,float,float,float) r7.xyz, v1.xyxx, t14.xywz, s5, cb0[108].x
mul r7.x, r7.x, r7.z
mad r7.xy, r7.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r3.w, r7.xyxx, r7.xyxx
min r3.w, r3.w, l(1.000000)
add r3.w, -r3.w, l(1.000000)
sqrt r3.w, r3.w
max r3.w, r3.w, l(1.000000017E-16)
mul r7.xy, r7.xyxx, cb5[0].wwww
sample_b_indexable(texture2d)(float,float,float,float) r8.xyz, v1.xyxx, t15.xyzw, s6, cb0[108].x
add r9.xz, -r3.yyxy, v2.xxzx
mov r9.y, l(0.0000610351562)
dp3 r3.x, r9.xyzx, r9.xyzx
rsq r3.x, r3.x
mul r9.xyz, r3.xxxx, r9.xyzx
mul r10.xyz, v3.zxyz, v4.yzxy
mad r10.xyz, v3.yzxy, v4.zxyz, -r10.xyzx
mul r10.xyz, r10.xyzx, v4.wwww
mul r7.yzw, r7.yyyy, r10.xxyz
mad r7.xyz, r7.xxxx, v4.xyzx, r7.yzwy
mad r3.xyw, r3.wwww, v3.xyxz, r7.xyxz
mad r6.w, cb5[1].y, l(2.000000), l(-1.000000)
movc r6.w, v10.x, l(1.000000), r6.w
dp3 r7.x, r3.xywx, r3.xywx
max r7.x, r7.x, l(1.175494351E-38)
rsq r7.x, r7.x
mul r3.xyw, r3.xyxw, r7.xxxx
mul r7.xyz, r6.wwww, r3.xywx
dp3 r8.w, v3.xyzx, v3.xyzx
rsq r8.w, r8.w
mul r10.xyz, r8.wwww, v3.xyzx
mul r10.xyz, r6.wwww, r10.xyzx
ftou r11.xy, v0.xyxx
add r8.w, l(1.000000), -cb0[111].x
mad r8.w, cb0[198].w, r8.w, cb0[111].x
mul r8.w, r8.w, cb0[109].x
lt r9.w, cb0[187].y, l(0.500000)
if_nz r9.w
  mad r12.xyz, cb0[6].xzyx, -cb0[212].wwww, cb0[210].xzyx
  add r12.xyz, -r12.xyzx, v2.xzyx
  max r9.w, |r12.y|, |r12.x|
  add r9.w, r9.w, l(-464.000000)
  mul_sat r9.w, r9.w, l(0.031250)
  add r10.w, |r12.z|, l(-208.000000)
  mul_sat r10.w, r10.w, l(0.031250)
  max r9.w, r9.w, r10.w
  ne r10.w, l(0.000000), cb0[210].w
  lt r12.x, r9.w, l(1.000000)
  and r10.w, r10.w, r12.x
  if_nz r10.w
    mad r12.xyz, cb0[6].xzyx, -cb0[212].yyyy, cb0[210].xzyx
    add r12.xyz, -r12.xyzx, v2.xzyx
    max r10.w, |r12.y|, |r12.x|
    add r10.w, r10.w, l(-29.000000)
    mul_sat r10.w, r10.w, l(0.500000)
    add r12.x, |r12.z|, l(-13.000000)
    mul_sat r12.x, r12.x, l(0.500000)
    max r10.w, r10.w, r12.x
    lt r12.x, r10.w, l(1.000000)
    if_nz r12.x
      mad r12.xyz, v2.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
      mul r13.xyz, r12.xyzx, cb0[211].xyzx
      round_ni r13.xyz, r13.xyzx
      mad r12.xyz, r12.xyzx, cb0[211].xyzx, -r13.xyzx
      sample_l_indexable(texture3d)(float,float,float,float) r13.xyw, r12.xyzx, t4.yzwx, s1, l(0.000000)
      add r14.x, -r10.w, l(1.000000)
      mul r14.y, l(0.500000), cb0[211].y
      mad r14.z, -cb0[211].y, l(0.500000), l(1.000000)
      max r12.y, r12.y, r14.y
      min r12.y, r14.z, r12.y
      mul r12.w, r12.y, l(0.333333343)
      sample_l_indexable(texture3d)(float,float,float,float) r15.xyzw, r12.xwzx, t5.xyzw, s0, l(0.000000)
      mad r12.y, r15.w, r14.x, r9.w
      add r14.yzw, r12.xxwz, l(0.000000, 0.000000, 0.666666687, 0.000000)
      sample_l_indexable(texture3d)(float,float,float,float) r14.yzw, r14.yzwy, t5.wxyz, s0, l(0.000000)
      mad r14.yzw, r14.yyzw, l(0.000000, 4.000000, 4.000000, 4.000000), l(0.000000, -2.000000, -2.000000, -2.000000)
      mul r16.xyz, r13.yyyy, r14.yzwy
      mov r16.w, r13.y
      mul r16.xyzw, r14.xxxx, r16.xyzw
      add r12.xzw, r12.xxwz, l(0.000000, 0.000000, 0.333333343, 0.000000)
      sample_l_indexable(texture3d)(float,float,float,float) r12.xzw, r12.xzwx, t5.xwyz, s0, l(0.000000)
      mad r12.xzw, r12.xxzw, l(4.000000, 0.000000, 4.000000, 4.000000), l(-2.000000, 0.000000, -2.000000, -2.000000)
      mul r17.xyz, r13.xxxx, r12.xzwx
      mov r17.w, r13.x
      mul r17.xyzw, r14.xxxx, r17.xyzw
      mad r12.xzw, r15.xxyz, l(4.000000, 0.000000, 4.000000, 4.000000), l(-2.000000, 0.000000, -2.000000, -2.000000)
      mul r13.xyz, r13.wwww, r12.xzwx
      mul r13.xyzw, r14.xxxx, r13.xyzw
    else
      mov r16.xyzw, l(0,0,0,0)
      mov r17.xyzw, l(0,0,0,0)
      mov r13.xyzw, l(0,0,0,0)
      mov r12.y, r9.w
    endif
    mad r12.xzw, cb0[6].xxzy, -cb0[212].zzzz, cb0[210].xxzy
    add r12.xzw, -r12.xxzw, v2.xxzy
    max r12.x, |r12.z|, |r12.x|
    add r12.x, r12.x, l(-116.000000)
    add r12.z, |r12.w|, l(-52.000000)
    mul_sat r12.xz, r12.xxzx, l(0.125000, 0.000000, 0.125000, 0.000000)
    max r12.x, r12.z, r12.x
    lt r12.z, r12.x, l(1.000000)
    if_nz r12.z
      mad r14.xyz, v2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
      mul r15.xyz, r14.xyzx, cb0[211].xyzx
      round_ni r15.xyz, r15.xyzx
      mad r14.xyz, r14.xyzx, cb0[211].xyzx, -r15.xyzx
      sample_l_indexable(texture3d)(float,float,float,float) r15.xyw, r14.xyzx, t6.yzwx, s1, l(0.000000)
      add r12.z, -r12.x, l(1.000000)
      mul r10.w, r10.w, r12.z
      mul r12.z, l(0.500000), cb0[211].y
      mad r12.w, -cb0[211].y, l(0.500000), l(1.000000)
      max r12.z, r12.z, r14.y
      min r12.z, r12.w, r12.z
      mul r14.w, r12.z, l(0.333333343)
      sample_l_indexable(texture3d)(float,float,float,float) r18.xyzw, r14.xwzx, t7.xyzw, s0, l(0.000000)
      mad r12.y, r18.w, r10.w, r12.y
      add r19.xyz, r14.xwzx, l(0.000000, 0.666666687, 0.000000, 0.000000)
      sample_l_indexable(texture3d)(float,float,float,float) r19.xyz, r19.xyzx, t7.xyzw, s0, l(0.000000)
      mad r19.xyz, r19.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
      mul r19.xyz, r15.yyyy, r19.xyzx
      mov r19.w, r15.y
      mad r16.xyzw, r19.xyzw, r10.wwww, r16.xyzw
      add r14.xyz, r14.xwzx, l(0.000000, 0.333333343, 0.000000, 0.000000)
      sample_l_indexable(texture3d)(float,float,float,float) r14.xyz, r14.xyzx, t7.xyzw, s0, l(0.000000)
      mad r14.xyz, r14.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
      mul r14.xyz, r15.xxxx, r14.xyzx
      mov r14.w, r15.x
      mad r17.xyzw, r14.xyzw, r10.wwww, r17.xyzw
      mad r14.xyz, r18.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000), l(-2.000000, -2.000000, -2.000000, 0.000000)
      mul r15.xyz, r15.wwww, r14.xyzx
      mad r13.xyzw, r15.xyzw, r10.wwww, r13.xyzw
    endif
    lt r10.w, l(0.000000), r12.x
    if_nz r10.w
      mad r14.xyz, v2.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
      mul r15.xyz, r14.xyzx, cb0[211].xyzx
      mul r18.xyz, l(0.500000, 0.500000, 0.500000, 0.000000), cb0[211].xyzx
      round_ni r15.xyz, r15.xyzx
      mad r14.xyz, r14.xyzx, cb0[211].xyzx, -r15.xyzx
      mad r15.xyz, -cb0[211].xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(1.000000, 1.000000, 1.000000, 0.000000)
      max r14.xyz, r18.xyzx, r14.xyzx
      min r14.xyz, r15.xyzx, r14.xyzx
      sample_l_indexable(texture3d)(float,float,float,float) r19.xyw, r14.xyzx, t8.yzwx, s1, l(0.000000)
      add r10.w, -r9.w, l(1.000000)
      mul r10.w, r10.w, r12.x
      max r12.x, r18.y, r14.y
      min r12.x, r15.y, r12.x
      mul r14.w, r12.x, l(0.333333343)
      sample_l_indexable(texture3d)(float,float,float,float) r15.xyzw, r14.xwzx, t9.xyzw, s0, l(0.000000)
      add r12.xzw, r14.xxwz, l(0.000000, 0.000000, 0.666666687, 0.000000)
      sample_l_indexable(texture3d)(float,float,float,float) r12.xzw, r12.xzwx, t9.xwyz, s0, l(0.000000)
      mad r12.xzw, r12.xxzw, l(4.000000, 0.000000, 4.000000, 4.000000), l(-2.000000, 0.000000, -2.000000, -2.000000)
      mul r18.xyz, r19.yyyy, r12.xzwx
      mov r18.w, r19.y
      mad r16.xyzw, r18.xyzw, r10.wwww, r16.xyzw
      add r12.xzw, r14.xxwz, l(0.000000, 0.000000, 0.333333343, 0.000000)
      sample_l_indexable(texture3d)(float,float,float,float) r12.xzw, r12.xzwx, t9.xwyz, s0, l(0.000000)
      mad r12.xzw, r12.xxzw, l(4.000000, 0.000000, 4.000000, 4.000000), l(-2.000000, 0.000000, -2.000000, -2.000000)
      mul r14.xyz, r19.xxxx, r12.xzwx
      mov r14.w, r19.x
      mad r17.xyzw, r14.xyzw, r10.wwww, r17.xyzw
      mad r12.xzw, r15.xxyz, l(4.000000, 0.000000, 4.000000, 4.000000), l(-2.000000, 0.000000, -2.000000, -2.000000)
      mul r19.xyz, r19.wwww, r12.xzwx
      mad r13.xyzw, r19.xyzw, r10.wwww, r13.xyzw
      mad r12.y, r15.w, r10.w, r12.y
    endif
    mad_sat r10.w, r12.y, l(2.000000), l(-1.000000)
    add r12.x, -r9.w, r10.w
    add r9.w, r9.w, r10.w
    mul r12.y, r9.w, l(0.500000)
  else
    mov r16.xyzw, l(0,0,0,0)
    mov r17.xyzw, l(0,0,0,0)
    mov r13.xyzw, l(0,0,0,0)
    mov r12.xy, l(0,1.000000,0,0)
  endif
  mul r14.xyzw, r12.yyyx, cb0[213].xyzw
  mad r14.y, r14.w, l(0.500000), r14.y
  mul r12.zw, r12.yyyx, cb0[213].wwwy
  mad r14.w, r12.w, l(0.375000), r12.z
  add r13.xyzw, r13.xyzw, r14.xyzw
  mul r14.xyzw, r12.yyyx, cb0[214].xyzw
  mad r14.y, r14.w, l(0.500000), r14.y
  mul r12.zw, r12.yyyx, cb0[214].wwwy
  mad r14.w, r12.w, l(0.375000), r12.z
  add r14.xyzw, r14.xyzw, r17.xyzw
  mul r15.xyzw, r12.yyyx, cb0[215].xyzw
  mad r15.y, r15.w, l(0.500000), r15.y
  mul r12.xy, r12.yxyy, cb0[215].wyww
  mad r15.w, r12.y, l(0.375000), r12.x
  add r12.xyzw, r15.xyzw, r16.xyzw
  mov r7.w, l(1.000000)
  dp4 r15.x, r13.xyzw, r7.xyzw
  dp4 r15.y, r14.xyzw, r7.xyzw
  dp4 r15.z, r12.xyzw, r7.xyzw
  max r15.xyz, r15.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  mul r16.xyz, r8.wwww, r15.xyzx
  mul r17.xyz, r14.xyzx, l(0.715200, 0.715200, 0.715200, 0.000000)
  mad r17.xyz, r13.xyzx, l(0.212600, 0.212600, 0.212600, 0.000000), r17.xyzx
  mad r17.xyz, r12.xyzx, l(0.072200, 0.072200, 0.072200, 0.000000), r17.xyzx
  dp3 r7.w, r17.xyzx, r17.xyzx
  max r7.w, r7.w, l(1.175494351E-38)
  rsq r7.w, r7.w
  mul r17.xyz, r7.wwww, r17.xyzx
  mov r17.y, |r17.y|
  mov r17.w, l(1.000000)
  dp4 r13.x, r13.xyzw, r17.xyzw
  dp4 r13.y, r14.xyzw, r17.xyzw
  dp4 r13.z, r12.xyzw, r17.xyzw
  max r12.xyz, r13.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  ge r7.w, r16.y, r16.z
  and r7.w, r7.w, l(0x3f800000)
  mov r13.xy, r16.zyzz
  mov r13.zw, l(0,0,-1.000000,0.666666687)
  mad r14.xy, r15.yzyy, r8.wwww, -r13.xyxx
  mov r14.zw, l(0,0,1.000000,-1.000000)
  mad r13.xyzw, r7.wwww, r14.xyzw, r13.xyzw
  ge r7.w, r16.x, r13.x
  and r7.w, r7.w, l(0x3f800000)
  mov r14.xyz, r13.xywx
  mov r14.w, r16.x
  mov r13.xyw, r14.wywx
  add r13.xyzw, -r14.xyzw, r13.xyzw
  mad r13.xyzw, r7.wwww, r13.xyzw, r14.xyzw
  min r7.w, r13.y, r13.w
  add r7.w, -r7.w, r13.x
  add r9.w, -r13.y, r13.w
  mad r10.w, r7.w, l(6.000000), l(0.000100)
  div r9.w, r9.w, r10.w
  add r9.w, r9.w, r13.z
  frc r9.w, |r9.w|
  add r10.w, r13.x, l(0.000100)
  div r7.w, r7.w, r10.w
  add r14.xyzw, r9.wwww, l(-0.500000, 1.000000, 0.666666687, 0.333333343)
  add r9.w, |r14.x|, l(-0.450000)
  mul_sat r9.w, r9.w, l(-10.000001)
  mad r10.w, r9.w, l(-2.000000), l(3.000000)
  mul r9.w, r9.w, r9.w
  mul r9.w, r9.w, r10.w
  mad r9.w, r9.w, l(-0.350000), l(0.700000)
  mov_sat r13.x, r13.x
  mul r9.w, r9.w, r13.x
  min r7.w, r7.w, r9.w
  add r9.w, -r7.w, l(2.000000)
  div r9.w, l(2.000000), r9.w
  frc r13.xyz, r14.yzwy
  mad r13.xyz, r13.xyzx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-3.000000, -3.000000, -3.000000, 0.000000)
  add_sat r13.xyz, |r13.xyzx|, l(-1.000000, -1.000000, -1.000000, 0.000000)
  add r13.xyz, r13.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
  mad r13.xyz, r7.wwww, r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mul r13.xyz, r9.wwww, r13.xyzx
  max r7.w, r12.y, r12.x
  max r7.w, r12.z, r7.w
  mul r8.w, r8.w, r7.w
  mov r7.w, l(1.000000)
else
  mov r17.xyz, l(0,0,0,0)
  mov r16.xyz, l(1.000000,1.000000,1.000000,0)
  mov r13.xyz, cb0[188].xyzx
  mov r7.w, l(0)
endif
add r9.w, -v2.y, cb1[r2.w + 12].z
add r9.w, r9.w, l(0.200000)
mul_sat r9.w, r9.w, l(2.85714269)
mad r10.w, r9.w, l(-2.000000), l(3.000000)
mul r9.w, r9.w, r9.w
mul r9.w, r9.w, r10.w
mul r9.w, r9.w, cb1[r2.w + 12].y
max r9.w, r9.w, cb1[r2.w + 12].w
add r10.w, r9.w, cb1[r2.w + 12].x
lt r10.w, l(0.010000), r10.w
if_nz r10.w
  add r10.w, -r5.x, l(1.000000)
  mul r12.xyz, r4.xyzx, r10.wwww
  dp3 r12.x, r12.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
  add r12.x, r12.x, l(-0.350000)
  mul_sat r12.x, r12.x, l(-4.000000)
  mad r12.y, r12.x, l(-2.000000), l(3.000000)
  mul r12.x, r12.x, r12.x
  mul r12.z, r12.x, r12.y
  mul r14.xyzw, v8.xyxz, l(1.000000, -1.000000, 1.000000, 1.000000)
  movc r14.xyzw, cb1[r2.w + 4].wwww, r14.xyzw, v8.xzxy
  mul r15.xyzw, r14.xyzw, cb0[196].zzzz
  movc r18.yz, cb1[r2.w + 4].wwww, v7.zzyz, v7.yyzy
  mov r18.x, v7.x
  add r19.xyz, |r18.xyzx|, l(-0.200000, -0.200000, -0.200000, 0.000000)
  mul r20.xyz, r19.xyzx, r19.xyzx
  mul r19.xyz, r19.xyzx, r20.xyzx
  max r19.xyz, r19.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  dp3 r12.w, r19.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  div r19.xyz, r19.xyzx, r12.wwww
  sample_b_indexable(texture2d)(float,float,float,float) r21.xyzw, r15.zyzz, t10.xyzw, s3, cb0[108].x
  sample_b_indexable(texture2d)(float,float,float,float) r22.xyzw, r15.zwzz, t10.xyzw, s3, cb0[108].x
  mul r22.xyzw, r19.zzzz, r22.xyzw
  mad r21.xyzw, r21.xyzw, r19.yyyy, r22.xyzw
  sample_b_indexable(texture2d)(float,float,float,float) r22.xyzw, r15.ywyy, t10.xyzw, s3, cb0[108].x
  mad r19.xyzw, r22.xyzw, r19.xxxx, r21.xyzw
  add r18.yw, -r19.wwww, l(0.000000, 0.800000, 0.000000, 0.450000)
  mul r21.xyz, r7.yyxy, l(0.200000, 0.000000, 1.000000, 0.000000)
  mad_sat r12.w, cb1[r2.w + 12].x, r10.w, r21.x
  add r12.w, -r18.y, r12.w
  mul_sat r12.w, r12.w, l(3.33333325)
  mad r13.w, r12.w, l(-2.000000), l(3.000000)
  mul r12.w, r12.w, r12.w
  mul r12.w, r12.w, r13.w
  mul_sat r10.w, r9.w, r10.w
  add r10.w, -r18.w, r10.w
  mul_sat r10.w, r10.w, l(1.53846145)
  mad r13.w, r10.w, l(-2.000000), l(3.000000)
  mul r10.w, r10.w, r10.w
  mul r10.w, r10.w, r13.w
  max r10.w, r10.w, r12.w
  add r12.w, r5.x, l(-0.500000)
  mul_sat r12.w, r12.w, l(4.000000)
  mad r13.w, r12.w, l(-2.000000), l(3.000000)
  mul r12.w, r12.w, r12.w
  mul r12.w, r12.w, r13.w
  add r5.w, -r5.w, l(0.199999988)
  mul_sat r5.w, r5.w, l(-5.00000048)
  mad r13.w, r5.w, l(-2.000000), l(3.000000)
  mul r5.w, r5.w, r5.w
  mul r5.w, r5.w, r13.w
  mad r13.w, r5.w, r12.z, r12.w
  min r13.w, r13.w, l(1.000000)
  max r9.w, r9.w, cb1[r2.w + 12].x
  mad r18.yw, r19.xxxy, l(0.000000, 2.000000, 0.000000, 2.000000), l(0.000000, -1.000000, 0.000000, -1.000000)
  mul r19.xyw, r15.yzyw, l(20.000000, 20.000000, 0.000000, 20.000000)
  mul r22.xyz, r15.yzwy, l(34.345600, 34.345600, 34.345600, 0.000000)
  mul r23.xyz, r20.xyzx, r20.xyzx
  mul r23.xyz, r23.xyzx, r23.xyzx
  mul r20.xyz, r20.xyzx, r23.xyzx
  dp3 r14.x, r20.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  div r20.xyz, r20.xyzx, r14.xxxx
  round_ni r23.xyzw, r19.yxyw
  mul r24.xyzw, r23.xyzw, l(123.339996, 456.209991, 123.339996, 456.209991)
  frc r24.xyzw, r24.xyzw
  add r25.xyzw, r24.xyzw, l(34.345001, 34.345001, 34.345001, 34.345001)
  dp2 r14.x, r24.xyxx, r25.xyxx
  add r21.xw, r14.xxxx, r24.xxxy
  mul r14.x, r21.w, r21.x
  add r16.w, r21.w, r21.x
  frc r14.x, r14.x
  frc r26.w, r16.w
  add r27.xyzw, r23.xyzw, l(114.514000, 114.514000, 114.514000, 114.514000)
  mul r27.xyzw, r27.xyzw, l(123.339996, 456.209991, 123.339996, 456.209991)
  frc r27.xyzw, r27.xyzw
  add r28.xyzw, r27.xyzw, l(34.345001, 34.345001, 34.345001, 34.345001)
  dp2 r16.w, r27.xyxx, r28.xyxx
  add r21.xw, r16.wwww, r27.xxxy
  mul r16.w, r21.w, r21.x
  add r17.w, r21.w, r21.x
  frc r24.x, r16.w
  frc r24.y, r17.w
  mad r16.w, r14.x, l(0.399999976), l(0.600000)
  mul r17.w, r16.w, l(0.250000)
  mad r23.xyzw, r15.zyzw, l(20.000000, 20.000000, 20.000000, 20.000000), -r23.xyzw
  mad r21.xw, r24.xxxy, l(2.000000, 0.000000, 0.000000, 2.000000), l(-1.000000, 0.000000, 0.000000, -1.000000)
  mad r21.xw, r21.xxxw, l(0.250000, 0.000000, 0.000000, 0.250000), r23.xxxy
  add r21.xw, r21.xxxw, l(-0.500000, 0.000000, 0.000000, -0.500000)
  mul r23.x, r21.x, l(1.250000)
  lt r19.y, r21.w, l(0.000000)
  movc r19.y, r19.y, l(1.250000), l(0.750000)
  mul r23.y, r19.y, r21.w
  mad r14.x, cb0[102].x, l(3.000000), r14.x
  frc r14.x, r14.x
  add r21.xw, r14.xxxx, l(-0.200000, 0.000000, 0.000000, -0.850000)
  mul_sat r21.xw, r21.xxxw, l(50.000011, 0.000000, 0.000000, -3.33333325)
  mad r25.xy, r21.xwxx, l(-2.000000, -2.000000, 0.000000, 0.000000), l(3.000000, 3.000000, 0.000000, 0.000000)
  mul r21.xw, r21.xxxw, r21.xxxw
  mul r21.xw, r21.xxxw, r25.xxxy
  mul r14.x, r21.w, r21.x
  dp2 r19.y, r23.xyxx, r23.xyxx
  sqrt r19.y, r19.y
  mad r16.w, -r16.w, l(0.250000), r19.y
  div r19.y, l(1.000000, 1.000000, 1.000000, 1.000000), -r17.w
  mul_sat r16.w, r16.w, r19.y
  mad r19.y, r16.w, l(-2.000000), l(3.000000)
  mul r16.w, r16.w, r16.w
  mul r16.w, r16.w, r19.y
  ge r16.w, r16.w, l(0.001000)
  and r16.w, r16.w, l(0x3f800000)
  mul r26.z, r14.x, r16.w
  div r21.xw, r23.xxxy, r17.wwww
  max r21.xw, r21.xxxw, l(-1.000000, 0.000000, 0.000000, -1.000000)
  min r21.xw, r21.xxxw, l(1.000000, 0.000000, 0.000000, 1.000000)
  ge r14.x, r26.z, l(0.001000)
  and r14.x, r14.x, l(0x3f800000)
  mul r21.xw, r14.xxxx, r21.xxxw
  mad r14.x, r24.x, l(0.250000), l(0.250000)
  mul r26.xy, r14.xxxx, r21.xwxx
  dp2 r14.x, r24.zwzz, r25.zwzz
  add r21.xw, r14.xxxx, r24.zzzw
  mul r14.x, r21.w, r21.x
  add r16.w, r21.w, r21.x
  frc r14.x, r14.x
  frc r24.w, r16.w
  dp2 r16.w, r27.zwzz, r28.zwzz
  add r21.xw, r16.wwww, r27.zzzw
  mul r16.w, r21.w, r21.x
  add r17.w, r21.w, r21.x
  frc r23.x, r16.w
  frc r23.y, r17.w
  mad r16.w, r14.x, l(0.399999976), l(0.600000)
  mul r17.w, r16.w, l(0.250000)
  mad r21.xw, r23.xxxy, l(2.000000, 0.000000, 0.000000, 2.000000), l(-1.000000, 0.000000, 0.000000, -1.000000)
  mad r21.xw, r21.xxxw, l(0.250000, 0.000000, 0.000000, 0.250000), r23.zzzw
  add r21.xw, r21.xxxw, l(-0.500000, 0.000000, 0.000000, -0.500000)
  mul r25.x, r21.x, l(1.250000)
  lt r19.y, r21.w, l(0.000000)
  movc r19.y, r19.y, l(1.250000), l(0.750000)
  mul r25.y, r19.y, r21.w
  mad r14.x, cb0[102].x, l(3.000000), r14.x
  frc r14.x, r14.x
  add r21.xw, r14.xxxx, l(-0.200000, 0.000000, 0.000000, -0.850000)
  mul_sat r21.xw, r21.xxxw, l(50.000011, 0.000000, 0.000000, -3.33333325)
  mad r23.yz, r21.xxwx, l(0.000000, -2.000000, -2.000000, 0.000000), l(0.000000, 3.000000, 3.000000, 0.000000)
  mul r21.xw, r21.xxxw, r21.xxxw
  mul r21.xw, r21.xxxw, r23.yyyz
  mul r14.x, r21.w, r21.x
  dp2 r19.y, r25.xyxx, r25.xyxx
  sqrt r19.y, r19.y
  mad r16.w, -r16.w, l(0.250000), r19.y
  div r19.y, l(1.000000, 1.000000, 1.000000, 1.000000), -r17.w
  mul_sat r16.w, r16.w, r19.y
  mad r19.y, r16.w, l(-2.000000), l(3.000000)
  mul r16.w, r16.w, r16.w
  mul r16.w, r16.w, r19.y
  ge r16.w, r16.w, l(0.001000)
  and r16.w, r16.w, l(0x3f800000)
  mul r24.z, r14.x, r16.w
  div r21.xw, r25.xxxy, r17.wwww
  max r21.xw, r21.xxxw, l(-1.000000, 0.000000, 0.000000, -1.000000)
  min r21.xw, r21.xxxw, l(1.000000, 0.000000, 0.000000, 1.000000)
  ge r14.x, r24.z, l(0.001000)
  and r14.x, r14.x, l(0x3f800000)
  mul r21.xw, r14.xxxx, r21.xxxw
  mad r14.x, r23.x, l(0.250000), l(0.250000)
  mul r24.xy, r14.xxxx, r21.xwxx
  round_ni r19.xy, r19.xwxx
  mul r21.xw, r19.xxxy, l(123.339996, 0.000000, 0.000000, 456.209991)
  frc r21.xw, r21.xxxw
  add r23.xy, r21.xwxx, l(34.345001, 34.345001, 0.000000, 0.000000)
  dp2 r14.x, r21.xwxx, r23.xyxx
  add r21.xw, r14.xxxx, r21.xxxw
  mul r14.x, r21.w, r21.x
  add r16.w, r21.w, r21.x
  frc r14.x, r14.x
  frc r23.w, r16.w
  add r21.xw, r19.xxxy, l(114.514000, 0.000000, 0.000000, 114.514000)
  mul r21.xw, r21.xxxw, l(123.339996, 0.000000, 0.000000, 456.209991)
  frc r21.xw, r21.xxxw
  add r25.xy, r21.xwxx, l(34.345001, 34.345001, 0.000000, 0.000000)
  dp2 r16.w, r21.xwxx, r25.xyxx
  add r21.xw, r16.wwww, r21.xxxw
  mul r16.w, r21.w, r21.x
  add r17.w, r21.w, r21.x
  frc r25.x, r16.w
  frc r25.y, r17.w
  mad r16.w, r14.x, l(0.399999976), l(0.600000)
  mul r17.w, r16.w, l(0.250000)
  mad r19.xy, r15.ywyy, l(20.000000, 20.000000, 0.000000, 0.000000), -r19.xyxx
  mad r21.xw, r25.xxxy, l(2.000000, 0.000000, 0.000000, 2.000000), l(-1.000000, 0.000000, 0.000000, -1.000000)
  mad r19.xy, r21.xwxx, l(0.250000, 0.250000, 0.000000, 0.000000), r19.xyxx
  add r19.xy, r19.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
  mul r27.x, r19.x, l(1.250000)
  lt r19.x, r19.y, l(0.000000)
  movc r19.x, r19.x, l(1.250000), l(0.750000)
  mul r27.y, r19.x, r19.y
  mad r14.x, cb0[102].x, l(3.000000), r14.x
  frc r14.x, r14.x
  add r19.xy, r14.xxxx, l(-0.200000, -0.850000, 0.000000, 0.000000)
  mul_sat r19.xy, r19.xyxx, l(50.000011, -3.33333325, 0.000000, 0.000000)
  mad r21.xw, r19.xxxy, l(-2.000000, 0.000000, 0.000000, -2.000000), l(3.000000, 0.000000, 0.000000, 3.000000)
  mul r19.xy, r19.xyxx, r19.xyxx
  mul r19.xy, r19.xyxx, r21.xwxx
  mul r14.x, r19.y, r19.x
  dp2 r19.x, r27.xyxx, r27.xyxx
  sqrt r19.x, r19.x
  mad r16.w, -r16.w, l(0.250000), r19.x
  div r19.x, l(1.000000, 1.000000, 1.000000, 1.000000), -r17.w
  mul_sat r16.w, r16.w, r19.x
  mad r19.x, r16.w, l(-2.000000), l(3.000000)
  mul r16.w, r16.w, r16.w
  mul r16.w, r16.w, r19.x
  ge r16.w, r16.w, l(0.001000)
  and r16.w, r16.w, l(0x3f800000)
  mul r23.z, r14.x, r16.w
  div r19.xy, r27.xyxx, r17.wwww
  max r19.xy, r19.xyxx, l(-1.000000, -1.000000, 0.000000, 0.000000)
  min r19.xy, r19.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
  ge r14.x, r23.z, l(0.001000)
  and r14.x, r14.x, l(0x3f800000)
  mul r19.xy, r14.xxxx, r19.xyxx
  mad r14.x, r25.x, l(0.250000), l(0.250000)
  mul r23.xy, r14.xxxx, r19.xyxx
  mul r24.xyzw, r20.zzzz, r24.xyzw
  mad r24.xyzw, r26.xyzw, r20.yyyy, r24.xyzw
  mad r23.xyzw, r23.xyzw, r20.xxxx, r24.xyzw
  round_ni r24.xyzw, r22.yxyz
  mul r25.xyzw, r24.xyzw, l(123.339996, 456.209991, 123.339996, 456.209991)
  frc r25.xyzw, r25.xyzw
  add r26.xyzw, r25.xyzw, l(34.345001, 34.345001, 34.345001, 34.345001)
  dp2 r14.x, r25.xyxx, r26.xyxx
  add r19.xy, r14.xxxx, r25.xyxx
  mul r14.x, r19.y, r19.x
  add r16.w, r19.y, r19.x
  frc r14.x, r14.x
  frc r27.w, r16.w
  add r28.xyzw, r24.xyzw, l(114.514000, 114.514000, 114.514000, 114.514000)
  mul r28.xyzw, r28.xyzw, l(123.339996, 456.209991, 123.339996, 456.209991)
  frc r28.xyzw, r28.xyzw
  add r29.xyzw, r28.xyzw, l(34.345001, 34.345001, 34.345001, 34.345001)
  dp2 r16.w, r28.xyxx, r29.xyxx
  add r19.xy, r16.wwww, r28.xyxx
  mul r16.w, r19.y, r19.x
  add r17.w, r19.y, r19.x
  frc r19.x, r16.w
  frc r19.y, r17.w
  mad r16.w, r14.x, l(0.399999976), l(0.600000)
  mul r17.w, r16.w, l(0.250000)
  mad r24.xyzw, r15.xyzw, l(34.345600, 34.345600, 34.345600, 34.345600), -r24.xyzw
  mad r19.yw, r19.xxxy, l(0.000000, 2.000000, 0.000000, 2.000000), l(0.000000, -1.000000, 0.000000, -1.000000)
  mad r19.yw, r19.yyyw, l(0.000000, 0.250000, 0.000000, 0.250000), r24.xxxy
  add r19.yw, r19.yyyw, l(0.000000, -0.500000, 0.000000, -0.500000)
  mul r24.x, r19.y, l(1.250000)
  lt r15.x, r19.w, l(0.000000)
  movc r15.x, r15.x, l(1.250000), l(0.750000)
  mul r24.y, r15.x, r19.w
  mad r14.x, cb0[102].x, l(4.345600), r14.x
  frc r14.x, r14.x
  add r19.yw, r14.xxxx, l(0.000000, -0.200000, 0.000000, -0.850000)
  mul_sat r19.yw, r19.yyyw, l(0.000000, 50.000011, 0.000000, -3.33333325)
  mad r21.xw, r19.yyyw, l(-2.000000, 0.000000, 0.000000, -2.000000), l(3.000000, 0.000000, 0.000000, 3.000000)
  mul r19.yw, r19.yyyw, r19.yyyw
  mul r19.yw, r19.yyyw, r21.xxxw
  mul r14.x, r19.w, r19.y
  dp2 r15.x, r24.xyxx, r24.xyxx
  sqrt r15.x, r15.x
  mad r15.x, -r16.w, l(0.250000), r15.x
  div r16.w, l(1.000000, 1.000000, 1.000000, 1.000000), -r17.w
  mul_sat r15.x, r15.x, r16.w
  mad r16.w, r15.x, l(-2.000000), l(3.000000)
  mul r15.x, r15.x, r15.x
  mul r15.x, r15.x, r16.w
  ge r15.x, r15.x, l(0.001000)
  and r15.x, r15.x, l(0x3f800000)
  mul r27.z, r14.x, r15.x
  div r19.yw, r24.xxxy, r17.wwww
  max r19.yw, r19.yyyw, l(0.000000, -1.000000, 0.000000, -1.000000)
  min r19.yw, r19.yyyw, l(0.000000, 1.000000, 0.000000, 1.000000)
  ge r14.x, r27.z, l(0.001000)
  and r14.x, r14.x, l(0x3f800000)
  mul r19.yw, r14.xxxx, r19.yyyw
  mad r14.x, r19.x, l(0.250000), l(0.250000)
  mul r27.xy, r14.xxxx, r19.ywyy
  dp2 r14.x, r25.zwzz, r26.zwzz
  add r19.xy, r14.xxxx, r25.zwzz
  mul r14.x, r19.y, r19.x
  add r15.x, r19.y, r19.x
  frc r14.x, r14.x
  frc r25.w, r15.x
  dp2 r15.x, r28.zwzz, r29.zwzz
  add r19.xy, r15.xxxx, r28.zwzz
  mul r15.x, r19.y, r19.x
  add r16.w, r19.y, r19.x
  frc r19.x, r15.x
  frc r19.y, r16.w
  mad r15.x, r14.x, l(0.399999976), l(0.600000)
  mul r16.w, r15.x, l(0.250000)
  mad r19.yw, r19.xxxy, l(0.000000, 2.000000, 0.000000, 2.000000), l(0.000000, -1.000000, 0.000000, -1.000000)
  mad r19.yw, r19.yyyw, l(0.000000, 0.250000, 0.000000, 0.250000), r24.zzzw
  add r19.yw, r19.yyyw, l(0.000000, -0.500000, 0.000000, -0.500000)
  mul r24.x, r19.y, l(1.250000)
  lt r17.w, r19.w, l(0.000000)
  movc r17.w, r17.w, l(1.250000), l(0.750000)
  mul r24.y, r17.w, r19.w
  mad r14.x, cb0[102].x, l(4.345600), r14.x
  frc r14.x, r14.x
  add r19.yw, r14.xxxx, l(0.000000, -0.200000, 0.000000, -0.850000)
  mul_sat r19.yw, r19.yyyw, l(0.000000, 50.000011, 0.000000, -3.33333325)
  mad r21.xw, r19.yyyw, l(-2.000000, 0.000000, 0.000000, -2.000000), l(3.000000, 0.000000, 0.000000, 3.000000)
  mul r19.yw, r19.yyyw, r19.yyyw
  mul r19.yw, r19.yyyw, r21.xxxw
  mul r14.x, r19.w, r19.y
  dp2 r17.w, r24.xyxx, r24.xyxx
  sqrt r17.w, r17.w
  mad r15.x, -r15.x, l(0.250000), r17.w
  div r17.w, l(1.000000, 1.000000, 1.000000, 1.000000), -r16.w
  mul_sat r15.x, r15.x, r17.w
  mad r17.w, r15.x, l(-2.000000), l(3.000000)
  mul r15.x, r15.x, r15.x
  mul r15.x, r15.x, r17.w
  ge r15.x, r15.x, l(0.001000)
  and r15.x, r15.x, l(0x3f800000)
  mul r25.z, r14.x, r15.x
  div r19.yw, r24.xxxy, r16.wwww
  max r19.yw, r19.yyyw, l(0.000000, -1.000000, 0.000000, -1.000000)
  min r19.yw, r19.yyyw, l(0.000000, 1.000000, 0.000000, 1.000000)
  ge r14.x, r25.z, l(0.001000)
  and r14.x, r14.x, l(0x3f800000)
  mul r19.yw, r14.xxxx, r19.yyyw
  mad r14.x, r19.x, l(0.250000), l(0.250000)
  mul r25.xy, r14.xxxx, r19.ywyy
  round_ni r19.xy, r22.xzxx
  mul r21.xw, r19.xxxy, l(123.339996, 0.000000, 0.000000, 456.209991)
  frc r21.xw, r21.xxxw
  add r22.xy, r21.xwxx, l(34.345001, 34.345001, 0.000000, 0.000000)
  dp2 r14.x, r21.xwxx, r22.xyxx
  add r21.xw, r14.xxxx, r21.xxxw
  mul r14.x, r21.w, r21.x
  add r15.x, r21.w, r21.x
  frc r14.x, r14.x
  frc r22.w, r15.x
  add r21.xw, r19.xxxy, l(114.514000, 0.000000, 0.000000, 114.514000)
  mul r21.xw, r21.xxxw, l(123.339996, 0.000000, 0.000000, 456.209991)
  frc r21.xw, r21.xxxw
  add r24.xy, r21.xwxx, l(34.345001, 34.345001, 0.000000, 0.000000)
  dp2 r15.x, r21.xwxx, r24.xyxx
  add r21.xw, r15.xxxx, r21.xxxw
  mul r15.x, r21.w, r21.x
  add r16.w, r21.w, r21.x
  frc r24.x, r15.x
  frc r24.y, r16.w
  mad r15.x, r14.x, l(0.399999976), l(0.600000)
  mul r16.w, r15.x, l(0.250000)
  mad r19.xy, r15.ywyy, l(34.345600, 34.345600, 0.000000, 0.000000), -r19.xyxx
  mad r21.xw, r24.xxxy, l(2.000000, 0.000000, 0.000000, 2.000000), l(-1.000000, 0.000000, 0.000000, -1.000000)
  mad r19.xy, r21.xwxx, l(0.250000, 0.250000, 0.000000, 0.000000), r19.xyxx
  add r19.xy, r19.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
  mul r26.x, r19.x, l(1.250000)
  lt r17.w, r19.y, l(0.000000)
  movc r17.w, r17.w, l(1.250000), l(0.750000)
  mul r26.y, r17.w, r19.y
  mad r14.x, cb0[102].x, l(4.345600), r14.x
  frc r14.x, r14.x
  add r19.xy, r14.xxxx, l(-0.200000, -0.850000, 0.000000, 0.000000)
  mul_sat r19.xy, r19.xyxx, l(50.000011, -3.33333325, 0.000000, 0.000000)
  mad r21.xw, r19.xxxy, l(-2.000000, 0.000000, 0.000000, -2.000000), l(3.000000, 0.000000, 0.000000, 3.000000)
  mul r19.xy, r19.xyxx, r19.xyxx
  mul r19.xy, r19.xyxx, r21.xwxx
  mul r14.x, r19.y, r19.x
  dp2 r17.w, r26.xyxx, r26.xyxx
  sqrt r17.w, r17.w
  mad r15.x, -r15.x, l(0.250000), r17.w
  div r17.w, l(1.000000, 1.000000, 1.000000, 1.000000), -r16.w
  mul_sat r15.x, r15.x, r17.w
  mad r17.w, r15.x, l(-2.000000), l(3.000000)
  mul r15.x, r15.x, r15.x
  mul r15.x, r15.x, r17.w
  ge r15.x, r15.x, l(0.001000)
  and r15.x, r15.x, l(0x3f800000)
  mul r22.z, r14.x, r15.x
  div r19.xy, r26.xyxx, r16.wwww
  max r19.xy, r19.xyxx, l(-1.000000, -1.000000, 0.000000, 0.000000)
  min r19.xy, r19.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
  ge r14.x, r22.z, l(0.001000)
  and r14.x, r14.x, l(0x3f800000)
  mul r19.xy, r14.xxxx, r19.xyxx
  mad r14.x, r24.x, l(0.250000), l(0.250000)
  mul r22.xy, r14.xxxx, r19.xyxx
  mul r24.xyzw, r20.zzzz, r25.xyzw
  mad r24.xyzw, r27.xyzw, r20.yyyy, r24.xyzw
  mad r20.xyzw, r22.xyzw, r20.xxxx, r24.xyzw
  max r19.xy, r20.zwzz, r23.zwzz
  mad r20.zw, -r13.wwww, r9.wwww, l(0.000000, 0.000000, 1.000000, 1.010000)
  add r14.x, r19.y, l(-0.100000)
  ge r14.x, r14.x, r20.z
  and r14.x, r14.x, l(0x3f800000)
  mul r14.x, r14.x, r19.x
  ge r2.w, cb1[r2.w + 12].x, l(0.010000)
  and r2.w, r2.w, l(0x3f800000)
  mul r2.w, r2.w, r14.x
  lt r14.x, l(0.001000), r2.w
  add r19.xy, r20.xyxx, r23.xyxx
  mul r15.x, cb0[102].x, cb0[196].z
  mul r20.y, r15.x, l(0.750000)
  dp2 r15.x, r18.xzxx, r18.xzxx
  max r15.x, r15.x, l(1.175494351E-38)
  rsq r15.x, r15.x
  mul r18.xz, r15.xxxx, r18.xxzx
  add r18.xz, |r18.xxzx|, l(-0.200000, 0.000000, -0.200000, 0.000000)
  mul r21.xw, r18.xxxz, r18.xxxz
  mul r18.xz, r18.xxzx, r21.xxwx
  max r18.xz, r18.xxzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  dp2 r15.x, r18.xzxx, l(1.000000, 1.000000, 0.000000, 0.000000)
  div r18.xz, r18.xxzx, r15.xxxx
  sample_b_indexable(texture2d)(float,float,float,float) r22.xyz, r15.zwzz, t11.xyzw, s3, cb0[108].x
  sample_b_indexable(texture2d)(float,float,float,float) r15.xyz, r15.ywyy, t11.xyzw, s3, cb0[108].x
  mul r15.xyz, r18.xxxx, r15.xyzx
  mad r15.xyz, r22.xyzx, r18.zzzz, r15.xyzx
  movc r18.yw, r14.xxxx, r19.xxxy, r18.yyyw
  mad r15.xy, r15.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  mov r20.x, l(0)
  mad r14.xyzw, r14.zwyw, cb0[196].zzzz, r20.xyxy
  sample_b_indexable(texture2d)(float,float,float,float) r14.x, r14.xyxx, t11.wxyz, s3, cb0[108].x
  sample_b_indexable(texture2d)(float,float,float,float) r14.y, r14.zwzz, t11.xwyz, s3, cb0[108].x
  mul r14.y, r18.x, r14.y
  mad r14.x, r14.x, r18.z, r14.y
  mad r14.xy, r15.xyxx, r14.xxxx, r18.ywyy
  ge r14.z, r19.z, r20.w
  and r14.z, r14.z, l(0x3f800000)
  max r2.w, r2.w, r14.z
  add r14.z, -r15.z, l(1.000000)
  mad r9.w, r13.w, r9.w, -r14.z
  mul_sat r9.w, r9.w, l(9.999998)
  mad r13.w, r9.w, l(-2.000000), l(3.000000)
  mul r9.w, r9.w, r9.w
  mul r9.w, r9.w, r13.w
  max r2.w, r2.w, r9.w
  mad r14.zw, -r7.zzzy, l(0.000000, 0.000000, 1.000000, 0.000000), r21.yyyz
  dp2 r9.w, r14.zwzz, r14.zwzz
  lt r13.w, l(0.0000610351562), r9.w
  rsq r9.w, r9.w
  mul r14.zw, r9.wwww, r14.zzzw
  mov r14.zw, -r14.zzzw
  movc r15.z, r13.w, r14.z, l(-1.000000)
  and r15.y, r13.w, r14.w
  min r9.w, r3.z, l(0.050000)
  add r13.w, -r3.z, r9.w
  mad r13.w, r2.w, r13.w, r3.z
  mad r12.x, -r12.y, r12.x, l(1.000000)
  mul r12.x, r10.w, r12.x
  mad r5.w, -r5.w, r12.z, l(1.000000)
  mul r5.w, r5.w, r12.x
  mad r5.w, r5.w, l(-0.500000), l(1.000000)
  mov r15.x, l(0)
  mad r3.xyw, -r3.xyxw, r6.wwww, r15.zxzy
  mad r3.xyw, r14.xxxx, r3.xyxw, r7.xyxz
  mul r14.xzw, r7.zzxy, r15.xxyz
  mad r14.xzw, r7.yyzx, r15.yyzx, -r14.xxzw
  add r14.xzw, -r3.xxyw, r14.xxzw
  mad r3.xyw, r14.yyyy, r14.xzxw, r3.xyxw
  dp3 r6.w, r3.xywx, r3.xywx
  rsq r6.w, r6.w
  mad r3.xyw, r3.xyxw, r6.wwww, -r7.xyxz
  mad r3.xyw, r2.wwww, r3.xyxw, r7.xyxz
  dp3 r6.w, r3.xywx, r3.xywx
  rsq r6.w, r6.w
  mul r3.xyw, r3.xyxw, r6.wwww
  mul r6.w, r12.z, r10.w
  mad r6.w, -r6.w, l(0.200000), r13.w
  min r10.w, r13.w, l(0.200000)
  max r3.z, r6.w, r10.w
  mul r6.xyz, r5.wwww, r6.xyzx
  dp3 r6.w, r4.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
  add r6.w, r6.w, l(-0.700000)
  mul_sat r6.w, r6.w, l(-2.50000024)
  mad r10.w, r6.w, l(-2.000000), l(3.000000)
  mul r6.w, r6.w, r6.w
  mul r6.w, r6.w, r10.w
  mad r6.w, r6.w, l(0.500000), l(1.000000)
  mul r10.w, r12.w, r2.w
  mad r12.xyz, r4.xyzx, r6.wwww, -r4.xyzx
  mad r12.xyz, r10.wwww, r12.xyzx, r4.xyzx
  mul r4.xyz, r5.wwww, r12.xyzx
else
  mov r3.xyw, r7.xyxz
  mov r9.w, l(0.010000)
  mov r2.w, l(0)
endif
mul r5.w, r5.y, l(0.040000)
mad r6.w, -r5.x, l(0.960000), l(0.960000)
mul r12.xyz, r4.xyzx, r6.wwww
mad r14.xyz, -r5.yyyy, l(0.040000, 0.040000, 0.040000, 0.000000), r4.xyzx
mad r14.xyz, r5.xxxx, r14.xyzx, r5.wwww
mul r6.xyz, r6.wwww, r6.xyzx
mul r5.y, r3.z, r3.z
max r5.y, r5.y, l(0.00781250000)
max r5.w, v5.z, l(9.999999939E-09)
div r15.xy, v5.xyxx, r5.wwww
max r5.w, v6.z, l(9.999999939E-09)
div r15.zw, v6.xxxy, r5.wwww
add r15.xy, -r15.zwzz, r15.xyxx
mul r18.xy, r15.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000)
sqrt r18.xy, |r18.xyxx|
sqrt r18.xy, r18.xyxx
mov r15.z, -r15.y
lt r15.yw, l(0.000000, 0.000000, 0.000000, 0.000000), r15.xxxz
lt r15.xz, r15.xxzx, l(0.000000, 0.000000, 0.000000, 0.000000)
iadd r15.xy, -r15.ywyy, r15.xzxx
itof r15.xy, r15.xyxx
mul r15.xy, r15.xyxx, r18.xyxx
mad o1.xy, r15.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
lt r5.w, l(0.500000), r2.w
movc o1.w, r5.w, l(0.700000), l(0.400000)
add r15.xyz, cb0[197].xyzx, cb3[0].xyzx
mad r15.xyz, cb0[187].wwww, r15.xyzx, -cb3[0].xyzx
mov r15.w, l(0.0000610351562)
dp3 r5.w, r15.xzwx, r15.xzwx
rsq r5.w, r5.w
mul r18.xyz, r5.wwww, r15.xwzx
add r19.xyz, cb0[191].xyzx, -cb3[3].xyzx
mad r19.xyz, cb0[198].yyyy, r19.xyzx, cb3[3].xyzx
add r5.w, l(1.000000), -cb3[3].w
mad r5.w, cb0[198].w, r5.w, cb3[3].w
mul r20.xyz, r5.wwww, r19.xyzx
mov r11.z, l(0)
ld_indexable(texture2d)(float,float,float,float) r21.xy, r11.xyzz, t3.xyzw
add r10.w, r21.x, l(-1.000000)
mad r10.w, cb4[34].x, r10.w, l(1.000000)
add r11.z, -r10.w, l(1.000000)
mad r10.w, cb0[187].z, r11.z, r10.w
dp3 r11.z, r7.xyzx, r15.xyzx
mul r21.xzw, r6.xxyz, cb0[186].zzzz
mul r22.xyz, r21.xzwx, l(0.650000, 0.650000, 0.650000, 0.000000)
dp3 r12.w, r12.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
dp2 r13.w, cb0[6].xzxx, cb0[6].xzxx
rsq r13.w, r13.w
mul r23.xy, r13.wwww, cb0[6].xzxx
dp2 r13.w, r18.xzxx, r23.xyxx
mov_sat r13.w, -r13.w
add r23.xy, l(1.000000, 1.000000, 0.000000, 0.000000), -cb0[198].xyxx
mad r14.w, r11.z, l(0.500000), l(-1.000000)
mad r14.w, -r11.z, r14.w, -r11.z
add r15.w, l(0.750000), -|cb0[6].y|
add_sat r15.w, r15.w, r15.w
mad r16.w, r15.w, l(-2.000000), l(3.000000)
mul r15.w, r15.w, r15.w
mul r15.w, r15.w, r16.w
mul r15.w, r13.w, r15.w
mul r15.w, r23.x, r15.w
add r14.w, r14.w, l(0.500000)
mad r11.z, r15.w, r14.w, r11.z
mad r11.z, cb0[197].w, cb0[198].x, r11.z
max r11.z, r11.z, l(-1.000000)
min r11.z, r11.z, l(1.000000)
add r11.z, r11.z, l(-0.250000)
mul r11.z, r11.z, l(1.33333337)
max r11.z, r11.z, l(0.000000)
mad r14.w, r11.z, l(-2.000000), l(3.000000)
mul r11.z, r11.z, r11.z
mul r11.z, r11.z, r14.w
dp3 r14.w, r7.xyzx, cb0[6].xyzx
add r14.w, r14.w, l(-0.250000)
mul_sat r14.w, r14.w, l(1.33333337)
mad r15.w, r14.w, l(-2.000000), l(3.000000)
mul r14.w, r14.w, r14.w
mul r14.w, r14.w, r15.w
mul r15.w, r5.z, r21.y
min r16.w, r5.z, r21.y
min r17.w, r11.z, r16.w
mul r18.w, r14.w, r15.w
dp3 r19.w, r7.xyzx, cb0[192].xyzx
add_sat r19.w, r19.w, cb0[193].x
mad r19.w, r19.w, cb0[193].y, cb0[193].z
mul r20.w, r17.w, cb0[187].y
add r24.xyz, -r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mad r24.xyz, r20.wwww, r24.xyzx, r13.xyzx
mul r24.xyz, r19.wwww, r24.xyzx
mad r19.w, r8.w, l(0.350000024), l(0.650000)
min r19.w, r19.w, l(1.500000)
max r25.xyz, r8.wwww, l(1.250000, 0.000000, 0.500000, 0.000000)
min r25.xyz, r25.xyzx, l(1.750000, 1.500000, 1.500000, 0.000000)
add r8.w, -r19.w, r25.x
mad r8.w, cb0[187].x, r8.w, r19.w
mul r26.xyz, r8.wwww, r24.xyzx
mul r26.xyz, r26.xyzx, cb0[186].wwww
dp3 r8.w, r20.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
mad r20.xyz, r19.xyzx, r5.wwww, -r8.wwww
mad r20.xyz, r17.wwww, r20.xyzx, r8.wwww
mul r24.xyz, r24.xyzx, r25.yyyy
mad r23.yzw, r19.xxyz, cb0[198].yyyy, r23.yyyy
mad r20.xyz, r24.xyzx, r23.yzwy, r20.xyzx
mad r20.xyz, r20.xyzx, cb0[186].yyyy, -r26.xyzx
mad r20.xyz, r10.wwww, r20.xyzx, r26.xyzx
dp3 r8.w, r22.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
mad r22.xyz, r21.xzwx, l(0.650000, 0.650000, 0.650000, 0.000000), -r8.wwww
mad r22.xyz, r22.xyzx, l(1.200000, 1.200000, 1.200000, 0.000000), r8.wwww
mad_sat r8.w, r14.w, r15.w, r11.z
mad r23.yzw, r6.xxyz, cb0[186].zzzz, -r22.xxyz
mad r22.xyz, r8.wwww, r23.yzwy, r22.xyzx
mad r23.yzw, r4.xxyz, r6.wwww, -r22.xxyz
mad r22.xyz, r17.wwww, r23.yzwy, r22.xyzx
mad r23.yzw, r4.xxyz, r6.wwww, -r12.wwww
mad r23.yzw, r23.yyzw, l(0.000000, 1.200000, 1.200000, 1.200000), r12.wwww
mad r23.yzw, -r6.xxyz, cb0[186].zzzz, r23.yyzw
mad r21.xzw, r18.wwww, r23.yyzw, r21.xxzw
dp3 r8.w, r22.xyzx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
max r11.z, r8.w, l(0.001000)
div r11.z, l(1.000000, 1.000000, 1.000000, 1.000000), r11.z
mul r8.w, r8.w, r11.z
max r8.w, r8.w, l(0.000000)
min r8.w, r8.w, l(1.500000)
mad r22.xyz, r22.xyzx, r8.wwww, -r21.xzwx
mad r21.xzw, r10.wwww, r22.xxyz, r21.xxzw
mad r8.w, -r14.w, r15.w, r17.w
mad r8.w, r10.w, r8.w, r18.w
add r11.z, l(1.000000), -cb0[186].z
mad r11.z, r8.w, r11.z, cb0[186].z
add r14.w, r15.y, l(-0.500000)
mad r22.y, r10.w, r14.w, l(0.500000)
dp3_sat r24.x, r3.xywx, r2.xyzx
mov r22.xz, cb0[6].xxzx
dp3 r14.w, r22.xyzx, r22.xyzx
max r14.w, r14.w, l(1.175494351E-38)
rsq r14.w, r14.w
mul r22.xyz, r14.wwww, r22.xyzx
add r22.xyz, r22.xyzx, r22.xyzx
mad r15.xyz, r15.xyzx, r10.wwww, r22.xyzx
add r14.w, r10.w, l(2.000000)
mad r15.xyz, r2.xyzx, r14.wwww, r15.xyzx
dp3 r14.w, r15.xyzx, r15.xyzx
rsq r14.w, r14.w
mul r15.xyz, r14.wwww, r15.xyzx
dp3 r14.w, r3.xywx, r15.xyzx
mul r15.x, r5.y, r5.y
mad r15.y, r14.w, r15.x, -r14.w
mad r14.w, r15.y, r14.w, l(1.000000)
mul r14.w, r14.w, r14.w
add r15.y, l(1.000000), -cb5[1].z
mad r15.y, r4.w, cb5[1].z, r15.y
mul r22.xyz, r20.xyzx, r21.xzwx
ne r15.z, r14.w, r15.x
div r14.w, r15.x, r14.w
movc r14.w, r15.z, r14.w, l(1.000000)
mad r15.x, r24.x, l(2.000000), r5.y
add r15.x, r15.x, l(0.000100)
div r15.x, l(0.500000), r15.x
mad r14.w, r14.w, r15.x, l(-0.0000610351562)
max r14.w, r14.w, l(0.000000)
min r14.w, r14.w, l(20.000000)
mul r15.xzw, r14.wwww, r14.xxyz
mad r8.w, r8.w, l(0.500000), l(0.500000)
mul r8.w, r11.z, r8.w
mul r20.xyz, r8.wwww, r20.xyzx
mul r15.xzw, r15.xxzw, r20.xxyz
mul r15.xzw, r15.xxzw, cb0[199].wwww
mad r15.xzw, r22.xxyz, r15.yyyy, r15.xxzw
dp3 r8.w, r15.xzwx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
add r14.w, r8.w, l(-0.500000)
max r14.w, r14.w, l(0.000000)
min r14.w, r14.w, l(0.500000)
mov r20.y, l(0)
mov r20.xz, cb0[195].yyxy
mul r22.xyz, r20.xyzx, cb0[6].zxyz
mad r20.xyz, cb0[6].yzxy, r20.yzxy, -r22.xyzx
dp3 r17.w, r20.xyzx, r20.xyzx
rsq r17.w, r17.w
mul r20.xyz, r17.wwww, r20.xyzx
dp3 r17.w, r2.xyzx, r7.xyzx
add r22.xy, -|r17.wwww|, l(1.000000, 0.399999976, 0.000000, 0.000000)
dp3 r18.x, r18.xyzx, r7.xyzx
add r18.y, -r10.w, l(1.000000)
add r9.w, -r3.z, r9.w
mad r2.w, r2.w, r9.w, r3.z
mul r26.y, r2.w, r2.w
mul r27.x, r24.x, r24.x
mul r27.z, r24.x, r27.x
mul r9.w, r26.y, r26.y
mul r26.z, r26.y, r9.w
mov r24.yzw, l(0,0.0365463011,9.063200,0.990440)
dp2 r25.x, l(3.327070, 1.000000, 0.000000, 0.000000), r24.xyxx
dp2 r25.y, l(-9.047560, 1.000000, 0.000000, 0.000000), r24.xzxx
mov r26.x, l(1.000000)
dp2 r9.w, r25.xyxx, r26.xyxx
mov r27.yw, l(0,9.044010,0,1.000000)
dp3 r28.x, l(3.596850, -1.367720, 1.000000, 0.000000), r27.xzwx
dp3 r28.y, l(-16.317400, 1.000000, 9.229490, 0.000000), r27.xyzx
mov r29.x, l(5.565890)
mov r29.yz, r27.xxzx
dp3 r28.z, l(1.000000, 19.788601, -20.212299, 0.000000), r29.xyzx
dp3 r18.z, r28.xyzx, r26.xyzx
div r9.w, r9.w, r18.z
dp2 r25.x, l(-1.285140, 1.000000, 0.000000, 0.000000), r24.xwxx
mov r27.x, l(1.296780)
mov r27.y, r24.x
dp2 r25.y, l(1.000000, -0.755907, 0.000000, 0.000000), r27.xyxx
dp2 r18.z, r25.xyxx, r26.xyxx
dp3 r28.x, l(2.923380, 59.418800, 1.000000, 0.000000), r27.yzwy
mov r27.xw, l(20.322500,0,0,121.563004)
dp3 r28.y, l(1.000000, -27.030199, 222.591995, 0.000000), r27.xyzx
dp3 r28.z, l(626.130005, 316.627014, 1.000000, 0.000000), r27.yzwy
dp3 r18.w, r28.xyzx, r26.xyzx
div r18.z, r18.z, r18.w
mad r23.yzw, r14.xxyz, r9.wwww, r18.zzzz
add r9.w, r9.w, r18.z
mad r14.w, r14.w, r14.w, l(1.000000)
add r15.xzw, -r8.wwww, r15.xxzw
mad r15.xzw, r14.wwww, r15.xxzw, r8.wwww
mad r18.zw, cb0[195].wwww, l(0.000000, 0.000000, -0.600000, -0.399999976), l(0.000000, 0.000000, 0.800000, 0.900000)
add r8.w, -r18.z, r18.w
add r14.w, -r18.z, r22.x
div r8.w, l(1.000000, 1.000000, 1.000000, 1.000000), r8.w
mul_sat r8.w, r8.w, r14.w
mad r14.w, r8.w, l(-2.000000), l(3.000000)
mul r8.w, r8.w, r8.w
mul r8.w, r8.w, r14.w
mul r24.yzw, r8.wwww, cb0[194].xxyz
mul r24.yzw, r24.yyzw, cb0[194].wwww
dp3 r8.w, r9.xyzx, r20.xyzx
add_sat r8.w, r8.w, l(1.000000)
min r5.z, r5.z, r8.w
min r5.z, r21.y, r5.z
mul r24.yzw, r5.zzzz, r24.yyzw
mad r25.xyw, r4.xyxz, r6.wwww, l(-0.250000, -0.250000, 0.000000, -0.250000)
mad r25.xyw, cb0[195].zzzz, r25.xyxw, l(0.250000, 0.250000, 0.000000, 0.250000)
dp3_sat r5.z, r20.xyzx, r7.xyzx
mul r20.xyz, r5.zzzz, r25.xywx
max r5.z, r16.y, r16.x
max r5.z, r16.z, r5.z
mul r5.z, r5.z, l(0.500000)
max r5.z, r5.z, l(1.000000)
div r5.z, l(1.000000, 1.000000, 1.000000, 1.000000), r5.z
mul r16.xyz, r5.zzzz, r16.xyzx
mad r19.xyz, r19.xyzx, r5.wwww, -r16.xyzx
mad r16.xyz, r10.wwww, r19.xyzx, r16.xyzx
dp3 r5.z, r17.xyzx, r7.xyzx
mul r5.w, r7.w, r5.z
mad r8.w, r18.x, l(0.500000), l(-1.000000)
mad r8.w, -r18.x, r8.w, l(0.500000)
mad r5.z, -r5.z, r7.w, r8.w
mad_sat r5.z, r10.w, r5.z, r5.w
mul r16.xyz, r5.zzzz, r16.xyzx
mad r5.z, r13.w, r10.w, r18.y
mul r5.z, r23.x, r5.z
mul r16.xyz, r5.zzzz, r16.xyzx
mul_sat r5.z, r22.y, l(5.00000048)
mad r5.w, r5.z, l(-2.000000), l(3.000000)
mul r5.z, r5.z, r5.z
mul r5.z, r5.z, r5.w
mul r16.xyz, r5.zzzz, r16.xyzx
mul r16.xyz, r16.wwww, r16.xyzx
add r5.z, r12.w, l(-0.100000)
mul_sat r5.z, r5.z, l(-16.666666)
mad r5.w, r5.z, l(-2.000000), l(3.000000)
mul r5.z, r5.z, r5.z
mul r5.z, r5.z, r5.w
mad r5.z, r5.z, r10.w, r18.y
mul r16.xyz, r5.zzzz, r16.xyzx
max r17.xyz, r12.xyzx, l(0.150000, 0.150000, 0.150000, 0.000000)
mul r16.xyz, r16.xyzx, r17.xyzx
mad r16.xyz, r24.yzwy, r20.xyzx, r16.xyzx
add r15.xzw, r15.xxzw, r16.xxyz
utof r5.zw, r11.xxxy
mul r16.xy, r5.zwzz, l(0.031250, 0.031250, 0.000000, 0.000000)
round_ni r16.xy, r16.xyxx
mad r7.w, r16.y, cb2[1].y, r16.x
mul r7.w, r7.w, l(8.000000)
ftoi r7.w, r7.w
mad r8.w, -cb0[85].y, cb2[2].w, v0.w
round_ni r8.w, r8.w
add r10.w, l(-1.000000), cb2[1].w
max r12.w, r8.w, l(0.000000)
min r10.w, r10.w, r12.w
mul r12.w, r10.w, l(8.000000)
ftoi r12.w, r12.w
mul r8.xyz, r8.xyzx, cb5[6].xyzx
mul r8.xyz, r8.xyzx, cb5[1].wwww
mad r8.xyz, r8.xyzx, r15.yyyy, r15.xzwx
dp3 r13.w, -r2.xyzx, r3.xywx
add r13.w, r13.w, r13.w
mad r15.xzw, r3.xxyw, -r13.wwww, -r2.xxyz
max r2.w, r2.w, l(0.001000)
log r2.w, r2.w
mad r2.w, r2.w, l(1.200000), l(5.000000)
sample_l_indexable(texturecube)(float,float,float,float) r15.xzw, r15.xzwx, t16.xwyz, s0, r2.w
add r2.w, -r9.w, l(1.000000)
div r2.w, r2.w, r9.w
mul r16.xyz, r2.wwww, r14.xyzx
mad r16.xyz, r16.xyzx, r23.yzwy, r23.yzwy
mul r15.xzw, r15.xxzw, r16.xxyz
mul r2.w, r25.z, cb0[186].w
mul r2.w, r11.z, r2.w
mul r15.xzw, r2.wwww, r15.xxzw
mad r8.xyz, r15.xzwx, r13.xyzx, r8.xyzx
ge r2.w, r10.w, r8.w
iadd r8.w, r12.w, cb0[110].y
mad r9.w, r18.y, l(-0.250000), l(0.750000)
mad r4.xyz, r4.xyzx, r6.wwww, l(-0.500000, -0.500000, -0.500000, 0.000000)
add r6.w, -r5.y, l(0.010000)
ge r5.x, r5.x, l(0.500000)
and r5.x, r5.x, l(0x3f800000)
mov r13.w, l(1.000000)
mov r15.xzw, r8.xxyz
mov r10.w, l(0)
loop
  ilt r11.z, l(7), r10.w
  breakc_nz r11.z
  iadd r11.z, r7.w, r10.w
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r11.z, r11.z, l(0), t0.xxxx
  iadd r12.w, r8.w, r10.w
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r12.w, r12.w, l(0), t0.xxxx
  and r11.z, r11.z, r12.w
  and r11.z, r2.w, r11.z
  ishl r12.w, r10.w, l(5)
  mov r16.xyz, r15.xzwx
  mov r14.w, r11.z
  loop
    breakc_z r14.w
    firstbit_lo r16.w, r14.w
    ishl r17.x, l(1), r16.w
    xor r17.x, r14.w, r17.x
    iadd r16.w, r12.w, r16.w
    bfi r18.xyzw, l(29, 29, 29, 29), l(3, 3, 3, 3), r16.wwww, l(1, 5, 6, 7)
    ftou r17.y, cb3[r18.y + 6].w
    ieq r17.y, r17.y, l(1)
    if_nz r17.y
      add r13.xyz, v2.xyzx, -cb3[r18.x + 6].xyzx
      and r19.xyz, l(0x0000ffff, 0x0000ffff, 0x0000ffff, 0), cb3[r18.y + 6].xzyx
      and r20.xyz, l(0x0000ffff, 0x0000ffff, 0x0000ffff, 0), cb3[r18.z + 6].yxzy
      ushr r22.yzw, cb3[r18.y + 6].xxzy, l(0, 16, 16, 16)
      ushr r23.xyz, cb3[r18.z + 6].yxzy, l(16, 16, 16, 0)
      f16tof32 r19.xyz, r19.xyzx
      f16tof32 r20.xyz, r20.xyzx
      f16tof32 r25.xyz, r22.yzwy
      f16tof32 r23.xyw, r23.yxyz
      mov r26.xz, r19.xxzx
      mov r26.yw, r25.xxxz
      dp4 r17.y, r13.xyzw, r26.xyzw
      mov r25.x, r19.y
      mov r25.z, r20.y
      mov r25.w, r23.x
      dp4 r17.z, r13.xyzw, r25.xyzw
      mov r23.xz, r20.xxzx
      dp4 r13.x, r13.xyzw, r23.xyzw
      max r13.y, |r17.z|, |r17.y|
      max r13.x, |r13.x|, r13.y
      mad r13.y, cb3[r18.w + 6].x, l(0.500000), l(0.500000)
      add r13.x, -r13.y, r13.x
      mad r13.y, -cb3[r18.w + 6].x, l(0.500000), l(0.500000)
      div_sat r13.x, r13.x, r13.y
      add r13.x, -r13.x, l(1.000000)
      mul r13.x, r13.x, r13.x
    else
      mov r13.x, l(1.000000)
    endif
    lt r13.y, r13.x, l(0.001000)
    if_nz r13.y
      mov r14.w, r17.x
      continue
    endif
    ishl r13.y, r16.w, l(3)
    lt r13.z, cb3[r13.y + 6].w, l(1.500000)
    if_nz r13.z
      bfi r13.z, l(29), l(3), r16.w, l(3)
      ieq r17.y, l(16), cb3[r13.z + 6].w
      add r17.z, cb0[198].z, cb3[r13.z + 6].z
      lt r17.z, r17.z, l(0.500000)
      or r17.y, r17.z, r17.y
      if_z r17.y
        bfi r17.yz, l(0, 29, 29, 0), l(0, 3, 3, 0), r16.wwww, l(0, 2, 4, 0)
        ftou r16.w, cb3[r13.y + 6].w
        and r16.w, r16.w, l(1)
        ieq r18.y, r16.w, l(0)
        not r18.y, r18.y
        lt r19.x, l(0.000000), cb3[r17.y + 6].z
        and r18.y, r18.y, r19.x
        ieq r19.x, l(4), cb3[r13.z + 6].w
        movc r19.y, r16.w, l(0), l(1.000000)
        mad r19.z, cb3[r17.y + 6].y, l(0.500000), l(0.500000)
        add r20.z, r19.z, -|cb3[r17.y + 6].x|
        add r20.x, -r20.z, cb3[r17.y + 6].y
        add r19.z, -|r20.z|, l(1.000000)
        add r19.z, -|r20.x|, r19.z
        max r19.z, r19.z, l(0.000488281250)
        ge r19.w, cb3[r17.y + 6].x, l(0.000000)
        movc r20.y, r19.w, r19.z, -r19.z
        dp3 r19.z, r20.xyzx, r20.xyzx
        rsq r19.z, r19.z
        mul r20.xyz, r19.zzzz, r20.xyzx
        add r19.z, cb3[r17.z + 6].y, cb3[r17.z + 6].y
        max r19.z, r19.z, l(0.100000)
        and r19.w, r19.x, l(0x3f800000)
        add r19.z, r19.z, -cb3[r18.z + 6].w
        mad r18.z, r19.w, r19.z, cb3[r18.z + 6].w
        add r22.yzw, -v2.xxyz, cb3[r18.x + 6].xxyz
        dp3 r19.z, r22.zwyz, -r20.xyzx
        lt r19.w, l(0.500000), cb3[r17.z + 6].z
        and r19.w, r19.w, r19.x
        and r19.w, r19.w, l(0x3f800000)
        mul r19.w, r19.y, r19.w
        mad r23.xyz, -r20.zxyz, r19.zzzz, -r22.yzwy
        mad r22.yzw, r19.wwww, r23.xxyz, r22.yyzw
        dp3 r19.z, r22.yzwy, r22.yzwy
        rsq r19.w, r19.z
        mul r23.xyz, r19.wwww, r22.yzwy
        if_nz r18.y
          mul r24.yzw, r20.zzxy, cb3[r17.y + 6].zzzz
          mad r25.xyz, -r24.yzwy, l(0.500000, 0.500000, 0.500000, 0.000000), r22.yzwy
          mad r24.yzw, r24.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000), r22.yyzw
          dp3 r19.w, r25.xyzx, r25.xyzx
          sqrt r19.w, r19.w
          dp3 r20.w, r24.yzwy, r24.yzwy
          sqrt r20.w, r20.w
          mul r26.xyz, r20.xyzx, r23.xyzx
          mad r26.xyz, r20.zxyz, r23.yzxy, -r26.xyzx
          mul r27.xyz, r20.xyzx, r26.xyzx
          mad r26.xyz, r26.zxyz, r20.yzxy, -r27.xyzx
          dp3 r21.y, r26.xyzx, r26.xyzx
          rsq r21.y, r21.y
          mul r23.xyz, r21.yyyy, r26.xyzx
          dp3 r21.y, r25.xyzx, r24.yzwy
          mad r21.y, r19.w, r20.w, r21.y
          mad r21.y, r21.y, l(0.500000), l(1.000000)
          div r21.y, l(1.000000, 1.000000, 1.000000, 1.000000), r21.y
          dp3 r23.w, r23.xyzx, r25.xyzx
          div r19.w, r23.w, r19.w
          dp3 r23.w, r23.xyzx, r24.yzwy
          div r20.w, r23.w, r20.w
          add r19.w, r19.w, r20.w
          mul_sat r19.w, r19.w, l(0.500000)
          mul r19.w, r19.w, r21.y
        else
          mov r19.w, l(1.000000)
        endif
        lt r20.w, r18.z, l(0.000000)
        if_nz r20.w
          mul r20.w, cb3[r18.x + 6].w, cb3[r18.x + 6].w
          mul r20.w, r19.z, r20.w
          mad r20.w, -r20.w, r20.w, l(1.000000)
          max r20.w, r20.w, l(0.000000)
          add r19.z, r19.z, l(1.000000)
          div r19.z, l(1.000000, 1.000000, 1.000000, 1.000000), r19.z
          and r21.y, r18.y, l(0x3f800000)
          add r23.w, -r19.z, r19.w
          mad r19.z, r21.y, r23.w, r19.z
          mul r20.w, r20.w, r20.w
          mul r19.z, r19.z, r20.w
        else
          mul r24.yzw, r22.yyzw, cb3[r18.x + 6].wwww
          dp3 r20.w, r24.yzwy, r24.yzwy
          min r20.w, r20.w, l(1.000000)
          add r20.w, -r20.w, l(1.000000)
          log r20.w, r20.w
          mul r18.z, r18.z, r20.w
          exp r18.z, r18.z
          mul r19.z, r18.z, r19.w
        endif
        dp3 r18.z, r23.yzxy, -r20.xyzx
        add r18.z, r18.z, -cb3[r17.y + 6].z
        mul_sat r18.z, r18.z, cb3[r17.y + 6].w
        mad r18.z, r18.z, r18.z, l(-1.000000)
        mad r18.z, r19.y, r18.z, l(1.000000)
        mul r18.z, r18.z, r19.z
        ftoi r19.y, cb3[r18.w + 6].w
        not r18.y, r18.y
        ige r19.z, r19.y, l(0)
        and r18.y, r18.y, r19.z
        if_nz r18.y
          if_z r16.w
            ishl r18.y, r19.y, l(2)
            mul r20.xyz, v2.yyyy, cb6[r18.y + 33].xywx
            mad r20.xyz, cb6[r18.y + 32].xywx, v2.xxxx, r20.xyzx
            mad r20.xyz, cb6[r18.y + 34].xywx, v2.zzzz, r20.xyzx
            add r20.xyz, r20.xyzx, cb6[r18.y + 35].xywx
            div_sat r19.zw, r20.xxxy, r20.zzzz
            mad r19.zw, r19.zzzw, cb6[r19.y + 0].zzzw, cb6[r19.y + 0].xxxy
          else
            ishl r18.y, r19.y, l(2)
            dp3 r20.x, -r22.yzwy, cb6[r18.y + 32].xyzx
            dp3 r20.y, -r22.yzwy, cb6[r18.y + 33].xyzx
            dp3 r20.z, -r22.yzwy, cb6[r18.y + 34].xyzx
            lt r18.y, |r20.x|, |r20.y|
            and r18.y, r18.y, l(1)
            dp2 r20.w, |r20.xyxx|, icb[r18.y + 0].xyxx
            lt r20.w, r20.w, |r20.z|
            movc r18.y, r20.w, l(2), r18.y
            dp3 r20.w, r20.xyzx, icb[r18.y + 0].xyzx
            lt r20.w, r20.w, l(0.000000)
            bfi r18.y, l(31), l(1), r18.y, r20.w
            ushr r20.w, r18.y, l(1)
            dp3 r20.w, r20.xyzx, icb[r20.w + 0].xyzx
            div r21.y, l(0.000244140625), cb6[r19.y + 0].w
            add r21.y, -r21.y, l(0.500000)
            utof r22.y, r18.y
            ult r22.z, r18.y, l(2)
            and r22.z, r22.z, l(2)
            dp2 r20.x, r20.xzxx, icb[r22.z + 0].xzxx
            mul r20.x, r20.x, icb[r18.y + 4].z
            div r20.x, r20.x, |r20.w|
            mad r20.x, r20.x, r21.y, r22.y
            add r20.x, r20.x, l(0.500000)
            mul_sat r25.x, r20.x, l(0.166666672)
            iadd r20.x, l(-1), icb[r18.y + 4].y
            dp2 r20.x, r20.yzyy, icb[r20.x + 0].xyxx
            mul r18.y, r20.x, icb[r18.y + 4].w
            div r18.y, r18.y, |r20.w|
            mad_sat r25.y, -r18.y, r21.y, l(0.500000)
            mad r19.zw, r25.xxxy, cb6[r19.y + 0].zzzw, cb6[r19.y + 0].xxxy
          endif
          sample_l_indexable(texture2d)(float,float,float,float) r18.y, r19.zwzz, t17.yxzw, s0, l(0.000000)
          mul r18.z, r18.y, r18.z
        endif
        mul r13.x, r13.x, r18.z
        lt r18.y, l(0.000100), r13.x
        if_nz r18.y
          if_nz r19.x
            add r18.y, l(1.000000), -cb3[r17.z + 6].w
            dp3 r18.z, r10.xyzx, r23.xyzx
            add_sat r18.z, r18.z, l(0.500000)
            mad r19.y, r18.z, l(-2.000000), l(3.000000)
            mul r18.z, r18.z, r18.z
            mul r18.z, r18.z, r19.y
            mad r18.y, r18.z, cb3[r17.z + 6].w, r18.y
            mul r18.y, r18.y, cb3[r17.z + 6].x
            mul r18.y, r13.x, r18.y
            add r19.yzw, -r16.xxyz, cb3[r13.y + 6].xxyz
            mad r19.yzw, r18.yyyy, r19.yyzw, r16.xxyz
          endif
          if_z r19.x
            dp3 r18.y, r7.xyzx, r23.xyzx
            mov_sat r18.z, r18.y
            if_nz cb3[r13.z + 6].w
              if_z r16.w
                ftoi r16.w, cb3[r13.z + 6].x
              else
                add r20.xyz, v2.xyzx, -cb3[r18.x + 6].xyzx
                lt r22.yzw, |r20.yyzz|, |r20.xxxy|
                and r20.w, r22.z, r22.y
                lt r20.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r20.xyzx
                ushr r21.y, cb3[r17.y + 6].w, l(24)
                ubfe r22.yz, l(0, 8, 8, 0), l(0, 16, 8, 0), cb3[r17.y + 6].wwww
                movc r20.x, r20.x, r21.y, r22.y
                and r17.y, l(255), cb3[r17.y + 6].w
                movc r17.y, r20.y, r22.z, r17.y
                ubfe r20.y, l(8), l(8), cb3[r13.z + 6].x
                and r21.y, l(255), cb3[r13.z + 6].x
                movc r20.y, r20.z, r20.y, r21.y
                movc r17.y, r22.w, r17.y, r20.y
                movc r17.y, r20.w, r20.x, r17.y
                ilt r20.x, r17.y, l(80)
                movc r16.w, r20.x, r17.y, l(-1)
              endif
              ige r17.y, r16.w, l(0)
              if_nz r17.y
                add r20.xyz, v2.xyzx, -cb3[r18.x + 6].xyzx
                ishl r17.y, r16.w, l(2)
                dp3 r18.x, r20.xyzx, r20.xyzx
                max r18.x, r18.x, l(1.175494351E-38)
                rsq r18.x, r18.x
                mul r20.xyz, r18.xxxx, r20.xyzx
                mad r20.xyz, -r20.xyzx, cb4[r16.w + 288].xxxx, v2.xyzx
                mul r18.x, l(5.000000), cb4[r16.w + 288].y
                mad r20.xyz, r10.xyzx, r18.xxxx, r20.xyzx
                mul r25.xyzw, r20.yyyy, cb4[r17.y + 65].xyzw
                mad r25.xyzw, cb4[r17.y + 64].xyzw, r20.xxxx, r25.xyzw
                mad r20.xyzw, cb4[r17.y + 66].xyzw, r20.zzzz, r25.xyzw
                add r20.xyzw, r20.xyzw, cb4[r17.y + 67].xyzw
                div r20.xyz, r20.xyzx, r20.wwww
                ge r22.yzw, l(0.000000, 0.000000, 0.000000, 0.000000), r20.xxyz
                ge r24.yzw, r20.xxyz, l(0.000000, 1.000000, 1.000000, 1.000000)
                add r25.xy, -cb4[r16.w + 344].xyxx, cb4[r16.w + 344].zwzz
                mad r20.xy, r20.xyxx, r25.xyxx, cb4[r16.w + 344].xyxx
                mad r25.xy, r20.xyxx, cb4[400].zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
                round_ni r25.xy, r25.xyxx
                mad r20.xy, r20.xyxx, cb4[400].zwzz, -r25.xyxx
                add r26.xyzw, r20.xxyy, l(0.500000, 1.000000, 0.500000, 1.000000)
                mul r27.xyzw, r26.xxzz, r26.xxzz
                add r25.zw, -r20.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
                min r26.xz, r20.xxyx, l(0.000000, 0.000000, 0.000000, 0.000000)
                max r28.xy, r20.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
                mul r29.xy, r25.zwzz, l(0.160000, 0.160000, 0.000000, 0.000000)
                mad r28.xy, -r28.xyxx, r28.xyxx, r26.ywyy
                add r28.xy, r28.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
                mul r28.xy, r28.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
                mul r27.xz, r27.xxzx, l(0.080000, 0.000000, 0.080000, 0.000000)
                mad r20.xy, r27.ywyy, l(0.500000, 0.500000, 0.000000, 0.000000), -r20.xyxx
                mul r30.xy, r20.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
                mad r20.xy, -r26.xzxx, r26.xzxx, r25.zwzz
                add r20.xy, r20.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
                mul r31.xy, r20.xyxx, l(0.160000, 0.160000, 0.000000, 0.000000)
                mul r20.xy, r26.ywyy, l(0.160000, 0.160000, 0.000000, 0.000000)
                mov r30.z, r31.x
                mov r30.w, r20.x
                mov r29.z, r28.x
                mov r29.w, r27.x
                add r26.xyzw, r29.zwxz, r30.zwxz
                mov r31.z, r30.y
                mov r31.w, r20.y
                mov r28.z, r29.y
                mov r28.w, r27.z
                add r20.xyw, r28.zyzw, r31.zyzw
                div r27.xyz, r29.xzwx, r26.zwyz
                add r27.xyz, r27.xyzx, l(-2.500000, -0.500000, 1.500000, 0.000000)
                mul r27.xyz, r27.yxzy, cb4[400].xxxx
                div r28.xyz, r28.zywz, r20.xywx
                add r28.xyz, r28.xyzx, l(-2.500000, -0.500000, 1.500000, 0.000000)
                mul r28.xyz, r28.xyzx, cb4[400].yyyy
                mov r27.w, r28.x
                mad r29.xyzw, r25.xyxy, cb4[400].xyxy, r27.ywxw
                mad r25.zw, r25.xxxy, cb4[400].xxxy, r27.zzzw
                mov r28.w, r27.y
                mov r27.yw, r28.yyyz
                mad r30.xyzw, r25.xyxy, cb4[400].xyxy, r27.xyzy
                mad r28.xyzw, r25.xyxy, cb4[400].xyxy, r28.wywz
                mad r27.xyzw, r25.xyxy, cb4[400].xyxy, r27.xwzw
                mul r31.xyzw, r20.xxxy, r26.zwyz
                sample_c_lz_indexable(texture2d)(float,float,float,float) r17.y, r29.xyxx, t2.xxxx, s2, r20.z
                sample_c_lz_indexable(texture2d)(float,float,float,float) r18.x, r29.zwzz, t2.xxxx, s2, r20.z
                mul r18.x, r18.x, r31.y
                mad r17.y, r31.x, r17.y, r18.x
                sample_c_lz_indexable(texture2d)(float,float,float,float) r18.x, r25.zwzz, t2.xxxx, s2, r20.z
                mad r17.y, r31.z, r18.x, r17.y
                sample_c_lz_indexable(texture2d)(float,float,float,float) r18.x, r28.xyxx, t2.xxxx, s2, r20.z
                mad r17.y, r31.w, r18.x, r17.y
                mul r25.xyzw, r20.yyww, r26.xyzw
                sample_c_lz_indexable(texture2d)(float,float,float,float) r18.x, r30.xyxx, t2.xxxx, s2, r20.z
                mad r17.y, r25.x, r18.x, r17.y
                sample_c_lz_indexable(texture2d)(float,float,float,float) r18.x, r30.zwzz, t2.xxxx, s2, r20.z
                mad r17.y, r25.y, r18.x, r17.y
                sample_c_lz_indexable(texture2d)(float,float,float,float) r18.x, r28.zwzz, t2.xxxx, s2, r20.z
                mad r17.y, r25.z, r18.x, r17.y
                sample_c_lz_indexable(texture2d)(float,float,float,float) r18.x, r27.xyxx, t2.xxxx, s2, r20.z
                mad r17.y, r25.w, r18.x, r17.y
                or r22.yzw, r22.yyzw, r24.yyzw
                or r18.x, r22.z, r22.y
                or r18.x, r22.w, r18.x
                and r20.x, r20.z, l(0x7fffffff)
                ult r20.x, l(0x7f800000), r20.x
                or r18.x, r18.x, r20.x
                mul r20.x, r20.w, r26.y
                sample_c_lz_indexable(texture2d)(float,float,float,float) r20.y, r27.zwzz, t2.xxxx, s2, r20.z
                mad r17.y, r20.x, r20.y, r17.y
                add r17.y, r17.y, l(-1.000000)
                mad r16.w, cb4[r16.w + 288].w, r17.y, l(1.000000)
                movc r16.w, r18.x, l(1.000000), r16.w
              else
                dp3 r17.y, r9.xyzx, r23.xyzx
                add_sat r16.w, r17.y, l(1.000000)
              endif
            else
              mov r16.w, l(1.000000)
            endif
            if_z cb3[r13.z + 6].w
              mul r20.xyz, r13.xxxx, cb3[r13.y + 6].xyzx
              add r17.y, l(1.000000), -cb3[r17.z + 6].y
              max r18.x, r20.y, r20.x
              max r18.x, r20.z, r18.x
              mul r18.x, r9.w, r18.x
              max r18.x, r18.x, l(1.000000)
              div r18.x, l(1.000000, 1.000000, 1.000000, 1.000000), r18.x
              mad r17.y, r18.x, cb3[r17.z + 6].y, r17.y
              mul r20.xyz, r17.yyyy, cb3[r13.y + 6].xyzx
              mul r17.y, l(0.250000), cb3[r17.z + 6].x
              add_sat r18.x, r18.y, l(0.500000)
              mad r20.w, -cb3[r17.z + 6].x, l(0.250000), l(1.000000)
              mad r17.y, r18.x, r20.w, r17.y
              mul r20.xyz, r17.yyyy, r20.xyzx
              mov r22.yzw, r21.xxzw
              mov r24.yzw, r21.xxzw
              mov r17.y, l(1.000000)
              mov r18.x, l(0)
            else
              ieq r20.w, l(3), cb3[r13.z + 6].w
              if_nz r20.w
                mad r25.xy, cb3[r17.z + 6].xxxx, l(-0.600000, -0.399999976, 0.000000, 0.000000), l(0.800000, 0.900000, 0.000000, 0.000000)
                add r20.w, -r25.x, r25.y
                add r21.y, r22.x, -r25.x
                div r20.w, l(1.000000, 1.000000, 1.000000, 1.000000), r20.w
                mul_sat r20.w, r20.w, r21.y
                mad r21.y, r20.w, l(-2.000000), l(3.000000)
                mul r20.w, r20.w, r20.w
                mul r20.w, r20.w, r21.y
                mul r20.w, r16.w, r20.w
                mul r13.x, r13.x, r20.w
                mul r25.xyz, r23.zxyz, cb0[6].xyzx
                mad r25.xyz, cb0[6].zxyz, r23.xyzx, -r25.xyzx
                mul r26.xyz, r25.xyzx, cb0[6].zxyz
                mad r25.xyz, cb0[6].yzxy, r25.yzxy, -r26.xyzx
                dp3 r20.w, r25.xyzx, r25.xyzx
                rsq r20.w, r20.w
                mul r25.xyz, r20.wwww, r25.xyzx
                dp3_sat r18.z, r7.xyzx, -r25.xyzx
                mad r22.yzw, cb3[r17.z + 6].yyyy, r4.xxyz, l(0.000000, 0.500000, 0.500000, 0.500000)
                mov r24.yzw, l(0,0,0,0)
                mov r17.y, l(1.000000)
                mov r18.x, l(0)
              else
                ieq r20.w, l(1), cb3[r13.z + 6].w
                if_nz r20.w
                  add r18.y, r18.y, cb3[r17.z + 6].x
                  max_sat r18.y, r18.y, l(-1.000000)
                  mul r18.z, r16.w, r18.y
                  mul r24.yzw, r6.xxyz, cb3[r17.z + 6].yyyy
                  mov r17.y, l(1.000000)
                  mov r18.x, l(0)
                else
                  ieq r16.w, l(2), cb3[r13.z + 6].w
                  if_nz r16.w
                    add r18.y, l(0.050000), cb3[r17.z + 6].x
                    add r18.y, r3.z, -r18.y
                    mul_sat r18.y, r18.y, l(-10.000000)
                    mad r21.y, r18.y, l(-2.000000), l(3.000000)
                    mul r18.y, r18.y, r18.y
                    mul r18.y, r18.y, r21.y
                    add r21.y, l(1.000000), -cb3[r17.z + 6].z
                    mad r21.y, r5.x, cb3[r17.z + 6].z, r21.y
                    mul r17.y, r18.y, r21.y
                  else
                    mov r17.y, l(1.000000)
                  endif
                  and r18.x, r16.w, cb3[r17.z + 6].y
                  mov r24.yzw, l(0,0,0,0)
                endif
                and r22.yzw, r12.xxyz, r20.wwww
              endif
              mov r20.xyz, cb3[r13.y + 6].xyzx
            endif
            ine r13.y, l(3), cb3[r13.z + 6].w
            if_nz r13.y
              mad r13.y, r18.x, r6.w, r5.y
              mad r23.xyz, r0.xyzx, r1.wwww, r23.xyzx
              dp3 r13.z, r23.xyzx, r23.xyzx
              rsq r13.z, r13.z
              mul r23.xyz, r13.zzzz, r23.xyzx
              dp3 r13.z, r3.xywx, r23.xyzx
              mul r16.w, r13.y, r13.y
              mad r17.z, r13.z, r16.w, -r13.z
              mad r13.z, r17.z, r13.z, l(1.000000)
              mul r13.z, r13.z, r13.z
              ne r17.z, r13.z, r16.w
              div r13.z, r16.w, r13.z
              movc r13.z, r17.z, r13.z, l(1.000000)
              mad r13.y, r24.x, l(2.000000), r13.y
              add r13.y, r13.y, l(0.000100)
              div r13.y, l(0.500000), r13.y
              mad r13.y, r13.z, r13.y, l(-0.0000610351562)
              max r13.y, r13.y, l(0.000000)
              min r13.y, r13.y, l(20.000000)
              mul r23.xyz, r13.yyyy, r14.xyzx
              mul r23.xyz, r17.yyyy, r23.xyzx
              mul r18.xyw, r23.xyxz, cb3[r18.w + 6].zzzz
            else
              mov r18.xyw, l(0,0,0,0)
            endif
            mul r13.xyz, r13.xxxx, r20.xyzx
            add r20.xyz, r22.yzwy, -r24.yzwy
            mad r20.xyz, r18.zzzz, r20.xyzx, r24.yzwy
            mul r20.xyz, r13.xyzx, r20.xyzx
            mul r13.xyz, r18.xywx, r13.xyzx
            mul r13.xyz, r18.zzzz, r13.xyzx
            mad r13.xyz, r20.xyzx, r15.yyyy, r13.xyzx
            add r16.xyz, r13.xyzx, r16.xyzx
          endif
        else
          mov r19.x, l(0)
        endif
        movc r16.xyz, r19.xxxx, r19.yzwy, r16.xyzx
      endif
    endif
    mov r14.w, r17.x
  endloop
  mov r15.xzw, r16.xxyz
  iadd r10.w, r10.w, l(1)
endloop
lt r0.x, l(0.500000), cb5[3].x
if_nz r0.x
  dp3 r0.x, r15.xzwx, l(0.212672904, 0.715152204, 0.072175, 0.000000)
  add r3.xyz, -r0.xxxx, r15.xzwx
  mad r0.xyz, cb5[3].zzzz, r3.xyzx, r0.xxxx
  add r0.xyz, r0.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)
  mad r0.xyz, cb5[3].wwww, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  mul r3.xyz, r0.xyzx, cb5[3].yyyy
  mad r0.xyz, -r0.xyzx, cb5[3].yyyy, cb5[7].xyzx
  mad r0.xyz, cb5[7].wwww, r0.xyzx, r3.xyzx
  add r2.w, l(1.000000), -cb5[4].x
  mov_sat r17.w, r17.w
  add r3.x, -r17.w, l(1.000000)
  add r3.y, -r2.w, l(1.000000)
  add r2.w, -r2.w, r3.x
  div r3.x, l(1.000000, 1.000000, 1.000000, 1.000000), r3.y
  mul_sat r2.w, r2.w, r3.x
  mad r3.x, r2.w, l(-2.000000), l(3.000000)
  mul r2.w, r2.w, r2.w
  mul r2.w, r2.w, r3.x
  mul r3.xyz, r2.wwww, cb5[8].xyzx
  mad r15.xzw, r3.xxyz, cb5[4].yyyy, r0.xxyz
endif
div r0.xyz, r15.xzwx, cb0[109].xxxx
eq r2.w, l(1.000000), cb5[2].x
movc o0.w, r2.w, r4.w, l(1.000000)
lt r2.w, cb0[198].w, l(0.500000)
if_nz r2.w
  mul r0.w, r0.w, r1.w
  mad r1.w, v2.y, cb0[156].w, cb0[157].w
  max r1.w, r1.w, l(0.010000)
  mad r2.w, r0.w, cb0[154].w, -cb0[153].w
  max r2.w, r2.w, l(0.000000)
  mul r3.x, r1.w, l(-1.442695)
  exp r3.x, r3.x
  add r3.x, -r3.x, l(1.000000)
  div r1.w, r3.x, r1.w
  mad r3.x, v2.y, cb0[156].w, cb0[158].w
  mul r3.x, r3.x, l(1.442695)
  exp r3.x, r3.x
  mul r1.w, r1.w, r3.x
  mul r1.w, r1.w, -r2.w
  mul r3.xyz, r1.wwww, cb0[155].xyzx
  mul r3.xyz, r3.xyzx, l(1.442695, 1.442695, 1.442695, 0.000000)
  exp r3.xyz, r3.xyzx
  dp3 r1.w, -r2.xyzx, cb0[154].xyzx
  mad r2.w, cb0[155].w, cb0[155].w, l(1.000000)
  dp2 r3.w, r1.wwww, cb0[155].wwww
  add r2.w, r2.w, -r3.w
  lt r3.w, l(0.000000), cb0[163].z
  if_nz r3.w
    and r11.w, l(7), cb0[108].w
    imad r4.xyz, r11.xywx, l(0x0019660d, 0x0019660d, 0x0019660d, 0), l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)
    imad r3.w, r4.y, r4.z, r4.x
    imad r4.x, r4.z, r3.w, r4.y
    imad r4.y, r3.w, r4.x, r4.z
    imad r5.x, r4.x, r4.y, r3.w
    dp3 r1.x, -r2.xyzx, -r1.xyzx
    add r1.y, v2.y, -cb0[44].y
    lt r1.z, l(5.960464478E-08), r1.x
    div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
    and r1.x, r1.x, r1.z
    mul r1.x, r1.x, cb0[163].w
    div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
    mul r2.x, r1.z, r1.x
    mad r2.y, r2.x, r1.y, cb0[44].y
    mad r1.y, -r2.x, r1.y, r1.y
    mul r2.x, r1.y, cb0[159].z
    mul r1.y, r1.y, cb0[162].x
    max r1.y, r1.y, l(-127.000000)
    add r2.z, r2.y, -cb0[159].x
    mul r2.z, r2.z, cb0[159].z
    max r2.xz, r2.xxzx, l(-127.000000, 0.000000, -127.000000, 0.000000)
    exp r2.z, -r2.z
    mul r2.z, r2.z, cb0[159].y
    lt r3.w, l(5.960464478E-08), |r2.x|
    exp r4.z, -r2.x
    add r4.z, -r4.z, l(1.000000)
    div r4.z, r4.z, r2.x
    mad r2.x, -r2.x, l(0.240226507), l(0.693147182)
    movc r2.x, r3.w, r4.z, r2.x
    add r2.y, r2.y, -cb0[162].z
    mul r2.y, r2.y, cb0[162].x
    max r2.y, r2.y, l(-127.000000)
    exp r2.y, -r2.y
    mul r2.y, r2.y, cb0[162].y
    lt r3.w, l(5.960464478E-08), |r1.y|
    exp r4.z, -r1.y
    add r4.z, -r4.z, l(1.000000)
    div r4.z, r4.z, r1.y
    mad r1.y, -r1.y, l(0.240226507), l(0.693147182)
    movc r1.y, r3.w, r4.z, r1.y
    mul r1.y, r1.y, r2.y
    mad r1.y, r2.z, r2.x, r1.y
    mad r1.x, -r1.x, r1.z, l(1.000000)
    mul r1.x, r0.w, r1.x
    mul r1.x, r1.x, r1.y
    exp r1.x, -r1.x
    min r1.x, r1.x, l(1.000000)
    max r1.x, r1.x, cb0[161].w
    mad_sat r1.yz, r0.wwww, cb0[160].yywy, cb0[160].xxzx
    add r1.x, r1.y, r1.x
    add r1.x, r1.z, r1.x
    min r1.x, r1.x, l(1.000000)
    imad r5.y, r4.y, r5.x, r4.x
    ushr r1.yz, r5.xxyx, l(0, 16, 16, 0)
    utof r1.yz, r1.yyzy
    mad r1.yz, r1.yyzy, l(0.000000, 0.0000305180438, 0.0000305180438, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
    mad r1.yz, r1.yyzy, cb0[167].wwww, r5.zzwz
    mul r2.xy, r1.yzyy, cb0[165].xyxx
    mad r1.y, v0.w, cb0[164].x, cb0[164].y
    log r1.y, r1.y
    mul r1.y, r1.y, cb0[164].z
    div r2.z, r1.y, cb0[163].z
    sample_l_indexable(texture3d)(float,float,float,float) r4.xyzw, r2.xyzx, t18.xyzw, s0, l(0.000000)
    add r1.y, v0.w, -cb0[166].z
    mul_sat r1.y, r1.y, l(1000000.000000)
    add r4.xyzw, r4.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
    mad r4.xyzw, r1.yyyy, r4.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)
    add r1.y, -r1.x, l(1.000000)
    mul r2.xyz, r1.yyyy, cb0[161].xyzx
    mad r2.xyz, r2.xyzx, r4.wwww, r4.xyzx
    mul r1.x, r1.x, r4.w
  else
    add r1.y, v2.y, -cb0[44].y
    mul r1.z, r1.y, cb0[159].z
    mul r1.y, r1.y, cb0[162].x
    max r1.yz, r1.yyzy, l(0.000000, -127.000000, -127.000000, 0.000000)
    add r3.w, cb0[44].y, -cb0[159].x
    mul r3.w, r3.w, cb0[159].z
    max r3.w, r3.w, l(-127.000000)
    exp r3.w, -r3.w
    mul r3.w, r3.w, cb0[159].y
    lt r4.x, l(5.960464478E-08), |r1.z|
    exp r4.y, -r1.z
    add r4.y, -r4.y, l(1.000000)
    div r4.y, r4.y, r1.z
    mad r1.z, -r1.z, l(0.240226507), l(0.693147182)
    movc r1.z, r4.x, r4.y, r1.z
    add r4.x, cb0[44].y, -cb0[162].z
    mul r4.x, r4.x, cb0[162].x
    max r4.x, r4.x, l(-127.000000)
    exp r4.x, -r4.x
    mul r4.x, r4.x, cb0[162].y
    lt r4.y, l(5.960464478E-08), |r1.y|
    exp r4.z, -r1.y
    add r4.z, -r4.z, l(1.000000)
    div r4.z, r4.z, r1.y
    mad r1.y, -r1.y, l(0.240226507), l(0.693147182)
    movc r1.y, r4.y, r4.z, r1.y
    mul r1.y, r1.y, r4.x
    mad r1.y, r3.w, r1.z, r1.y
    mul r1.y, r0.w, r1.y
    exp r1.y, -r1.y
    min r1.y, r1.y, l(1.000000)
    max r1.y, r1.y, cb0[161].w
    mad_sat r4.xy, r0.wwww, cb0[160].ywyy, cb0[160].xzxx
    add r0.w, r1.y, r4.x
    add r0.w, r4.y, r0.w
    min r1.x, r0.w, l(1.000000)
    add r0.w, -r1.x, l(1.000000)
    mul r2.xyz, r0.wwww, cb0[161].xyzx
  endif
  mul r4.xyz, r1.xxxx, r3.xyzx
  mad r0.w, r1.w, r1.w, l(1.000000)
  mul r0.w, r0.w, l(0.0596831031)
  mad r1.yzw, cb0[156].xxyz, r0.wwww, cb0[158].xxyz
  mad r0.w, -cb0[155].w, cb0[155].w, l(1.000000)
  mul r3.w, r2.w, l(12.566371)
  sqrt r2.w, r2.w
  mul r2.w, r2.w, r3.w
  max r2.w, r2.w, l(0.001000)
  div r0.w, r0.w, r2.w
  mad_sat r1.yzw, cb0[157].xxyz, r0.wwww, r1.yyzw
  mul r1.yzw, r1.yyzw, l(0.000000, 255.000000, 255.000000, 255.000000)
  add r3.xyz, -r3.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mul r1.yzw, r1.yyzw, r3.xxyz
  mad r1.xyz, r1.yzwy, r1.xxxx, r2.xyzx
  mad o0.xyz, r0.xyzx, r4.xyzx, r1.xyzx
else
  mov o0.xyz, r0.xyzx
endif
mov o1.z, l(1.000000)
ret
// Approximately 0 instruction slots used
